### ISSUE TITLE
Test deleting assets

### ISSUE THREAD

**Issue by patrickmj** [omeka/omeka-s#1011]
Now on develop, when editing theme options (at least the ones that  for a site admins should have the ability to delete assets that have already been uploaded by clicking on the trashcan next to assets, then confirming.

This should get a look across browsers, and make sure that people without permission to add an asset also cannot delete an asset.

@kimisgold might also want to look to see if I should change the UI & CSS stuff.

**Comment by mebrett** [comment]
Researchers, Editors, Admin, and Author users (installation role) can only access site settings when given site role of Admin; in these instances they can view and change the logo/asset for a specific site but cannot delete or add assets. 

Global and Site Admins can add, edit, and delete assets from any site, regardless of their permissions on that specific site.

**Comment by mebrett** [comment]
On Safari, Chrome, and Firefox, long image titles overlap the delete button when there's not a clear break in the title: 
![screen shot 2017-08-04 at 11 00 06 am](https://user-images.githubusercontent.com/2314070/28974348-17b7b92a-7904-11e7-8a95-aff68ce4920b.png)

**Comment by patrickmj** [comment]
For the lack of a clear break, that looks like a more general issue with the sidebar (it's also there in the latest beta release). I'm not sure anything can be done about it, but @kimisgold will know better what's possible.

**Comment by kimisgold** [comment]
The titles should now wrap, but could others confirm that the titles in no way run into the delete buttons?

**Comment by patrickmj** [comment]
Looks good to me on FF and Chromium

**Comment by mebrett** [comment]
And Safari.

**Comment by patrickmj** [comment]
Is this ready to close, then?

**Comment by mebrett** [comment]
Just checked it on Internet Explorer, so yes.
