### ISSUE TITLE
[Question]OAuth Implementation Roadmap

### ISSUE THREAD

**Issue by flotho** [omeka/omeka-s#1015]
Hy,

I would like to know if there is any roadmap for an Oauth implementation ?
I saw this Proposal PR : https://github.com/omeka/omeka-s/pull/872 Does that mean that once this PR will be merged Oauth will be available?

regards

**Comment by elrossco22** [comment]
Hi @flotho , We (https://github.com/digirati-co-uk) are currently working on an OAuth module which is near completion and will be released as Open Source.

You are correct though a solution to https://github.com/omeka/omeka-s/pull/872 is required to make it possible though

**Comment by flotho** [comment]
Hi @elrossco22 ,

Thanks for your answer. To be sure, would the Oauth workflow be implemented in the API as in the GUI? 
I'm discovering this amazing project and I'm not sure of the architecture, I meant is the UI a client of the Webservice API or is the API and the UI closely tight?

regards

**Comment by elrossco22** [comment]
Hi @flotho, 

I'm not entirely sure what you mean could you provide further clarity ?

Cheers,
Ross

**Comment by jimsafley** [comment]
We don't currently plan on addressing this issue. Feel free to reopen and elaborate should you want further discussion.
