### ISSUE TITLE
"thumbnail_type" in API output for Resources seems odd

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#1019]
"thumbnail_type" is actually the media type of the primary media for the resource. This is a little bit confusing at best because the thumbnail_url, as you'd expect, is to an actual thumbnail, not to the original media. So if the media is a TIFF or PDF or whatever, the thumbnail_url is to a jpeg, but thumbnail_type is "image/tiff" or "application/pdf" or whatever.

Do we really need thumbnail_type at all?

**Comment by jimsafley** [comment]
We don't use "thumbnail_type" or "thumbnail_title" anywhere in our codebase. I have no problem removing them.

**Comment by pols12** [comment]
Don’t you think some theme pages may want to know `primaryMedia_type` in order to choose how a link targetting an item should be display?
Maybe there is a more usable workaround?

**Comment by zerocrates** [comment]
For theme pages the presence or absence of these doesn't really change much: they'd still access this as `$resource->primaryMedia()->type()` regardless.

The effect would be on external API consumers.

**Comment by pols12** [comment]
Indeed, an easy workaround, thanks. :) 

What do you call “external API consumers”? Does the JSON of RESTful interface contain `thumbnail_type`?
I have not achieved to get a sample.

Anyway, I don’t find this key useful too.

**Comment by zerocrates** [comment]
I've become less certain that this should be removed.
