### ISSUE TITLE
Initial Installation - Default Locale Selection Error

### ISSUE THREAD

**Issue by cudevmaxwell** [omeka/omeka-s#1027]
Hello All. 

Apologies if this is a known issue, but during initial installation, the value 'en_US' cannot be chosen as the locale.

![image](https://user-images.githubusercontent.com/1489722/29371062-4946aef4-8275-11e7-8ea5-1602211dac2b.png)

results in

![image](https://user-images.githubusercontent.com/1489722/29371069-56d0b0ec-8275-11e7-921d-ec77339bf126.png)

**Comment by zerocrates** [comment]
Thanks. This is pretty much brand new so it hasn't been looked at much yet.

**Comment by zerocrates** [comment]
There's a little bit of a distinction between "blank" here and "en_US" so we don't want to just fill that in, at least not at the moment. Instead I just applied a small fix that makes it accept the blank value (as it does in the "real" settings form).
