### ISSUE TITLE
"Select a template" and "Select a class" not translatable on item add

### ISSUE THREAD

**Issue by patrickmj** [omeka/omeka-s#1032]

**Comment by zerocrates** [comment]
The trouble here is that the property is data-placeholder, which the Zend form code doesn't know needs to be translated when output. Not sure if we can easily convince it that's the case.

**Comment by zerocrates** [comment]
There's an `addTranslatableAttribute` that looks like it should work... possibly in a service manager delegator for the Select view helper.
