### ISSUE TITLE
Site Settings page not loading

### ISSUE THREAD

**Issue by mebrett** [omeka/omeka-s#1037]
Trying to access the Settings page for any site on the shared install (up to date on develop) results in a page with just "Sites: [Site Title]", a Save button and the following message 'Attachment link type
Fatal error: Call to undefined method Zend\Form\View\Helper\FormSelect::addTranslatableAttribute() in /websites/omekadev/home/www/omeka-s/application/src/Service/Delegator/FormSelectDelegatorFactory.php on line 15'

I tried working backwards through commits and the last commit on which I can access site settings is [2846f60](https://github.com/omeka/omeka-s/commit/2846f606b8c7f8ef3a345af2a603cc43018fa810). When I step up to [cd53cfc](https://github.com/omeka/omeka-s/commit/cd53cfc76cc40e5be2b1b5229acab39f72040c33), things break.

**Comment by zerocrates** [comment]
Try running `gulp deps` after updating.

**Comment by mebrett** [comment]
on dev.omeka.org,  `gulp: command not found` and I don't have permissions to install such things on dev. Is there another update command I can run?

**Comment by patrickmj** [comment]
Had a similar thing a while ago. Here's what Roberto sent me:


> Running npm install from the root folder should install gulp and all of it's deps. Once it's complete all node modules will be installed in the folder called node_modules so from the root of the project you will need to call ./node_modules/gulp/bin/gulp.js deps to satisfy all the dependencies . Don't forget to specify the path to the correct php version, in this case, it's /opt/php5.6/bin/php. Let me know if you encounter any other problems.

I'll see if I can recreate the whole thing in the sandbox

**Comment by mebrett** [comment]
John walked me through an alternative which updated the necessary deps and things are working now - but thanks. Having gulp on dev would be helpful.

**Comment by zerocrates** [comment]
I'll poke around on dev to see what's what, if something can be or needs to be done there.
