### ISSUE TITLE
Add modules to Transifex

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#1039]
As we get through @patrickmj's passes through the modules for i18n, we should be putting them on Transifex. This means deciding on a pattern of where they'll go and then just the little mechanical bits of pushing them up.

I'm leaning toward publishing them as "resources" of the S project on transifex, in the same way they are for Classic.

**Comment by patrickmj** [comment]
That sounds quite reasonable to me.

**Comment by Daniel-KM** [comment]
Will it be available for third parties?

**Comment by zerocrates** [comment]
Initial pattern for Transifex config is in MetadataBrowse.

As far as third parties, I don't see a way in Transifex to enable that, but I could be missing something. Obviously anybody can just use Transifex themselves independently.
