### ISSUE TITLE
Organize javascript shared between admin and public views

### ISSUE THREAD

**Issue by kimisgold** [omeka/omeka-s#1043]
The current `globals.js` file has some functionality that's used in both admin and public views. It's primarily behaviors that are used in the advanced searches (i.e. adding and removing form values), but I'd moved it from `advanced-search .js` to `globals.js` because they're also used in other admin forms. I'm thinking we should probably create a shared js, though if we do, where should it live and what should we call it?

**Comment by zerocrates** [comment]
Really globals.js is probably the best name for stuff that's truly shared.

We could pull out the admin-only stuff, which must of course be the vast bulk of the file, into admin.js or something like that.
