### ISSUE TITLE
Expanding field description pushes form element down

### ISSUE THREAD

**Issue by jimsafley** [omeka/omeka-s#1044]
It appears to happen only when the description exceeds a given length. See "Property label information" and "Default site" below:
![global settings whoameka](https://user-images.githubusercontent.com/141955/29944863-069f2cda-8e6d-11e7-9681-db2e9d02f7c1.png)

**Comment by zerocrates** [comment]
Seems to just be a case of the info div having a min-width but nothing else constraining its size.

**Comment by zerocrates** [comment]
This is a pretty recent regression that doesn't necessarily seem to be specifically related to the min-width... odd.
