### ISSUE TITLE
Possible oddity with string/\Zend\Uri\Http

### ISSUE THREAD

**Issue by patrickmj** [omeka/omeka-s#1045]
Running ApiGen to generate documentation barfs with

```
  [InvalidArgumentException]                      
  "\string/\Zend\Uri\Http" is not a valid Fqsen.
```

Looks like it is in https://github.com/omeka/omeka-s/blob/develop/application/src/File/Downloader.php#L46

It looks odd to me, but not really sure what it should be instead.

**Comment by jimsafley** [comment]
There should be a pipe separating "string" and "\Zend\Uri\Http", not a forward slash.
