### ISSUE TITLE
Should/do we include a PHP Code Style config file?

### ISSUE THREAD

**Issue by patrickmj** [omeka/omeka-s#1046]
In the interests of style consistency, it'd be nice to run php-cs on the code, including modules. We currently say we aim to adhere to PSR-2. When running that check, is there a configuration file we include for the check, especially for quirks that we might come up against? 

I'd like to document where that config is for others to run against modules, a question implicitly raised by @Daniel-KM in https://github.com/omeka-s-modules/CSVImport/pull/88

**Comment by zerocrates** [comment]
We already have a .php_cs file for the core, which is automatically used for code style checks as part of the automated CI tests.

Modules would need a slightly different configuration as the core one includes things like excludes for module and theme paths. I've had a local one floating around for a while but never checked in. We could probably stick one somewhere and make a task for it akin to the translation ones if we wanted to go that route.

**Comment by Daniel-KM** [comment]
@patrickmj 
At least you could config your editors to remove automatically all the trailing spaces.
