### ISSUE TITLE
In Pages, access to the modifying bar in HTML block disappeared in 1.0.0-beta4

### ISSUE THREAD

**Issue by hajoki** [omeka/omeka-s#1050]
In beta 3 I used to have access to such a modifying bar when clicking in an HTML block
![screenshot from 2017-09-06 19 09 34](https://user-images.githubusercontent.com/8191742/30122632-c3a8e220-9337-11e7-8967-b545d24eeed4.png)
but I do not get this bar any more in beta 4

**Comment by zerocrates** [comment]
Hmmm, that bar should still be there.. and it's there in the current version.

For starters try clearing cache/hard refreshing, that sort of thing. Stylesheet changes don't always get picked up right away by your browser when you've updated versions.

**Comment by hajoki** [comment]
I tried it and it did not work out for me but thanks

**Comment by hajoki** [comment]
Got solved by @jimsafley's advice: open application/asset/ckeditor_config.js, comment out the line that sets config.skin = 'flat'; and hard refresh the page. Thanks for the help!
