### ISSUE TITLE
Resource Templates edit action buttons seem off

### ISSUE THREAD

**Issue by patrickmj** [omeka/omeka-s#1051]
Both FF and Chromium, I see something like this

![resourcetemplates](https://user-images.githubusercontent.com/153262/30123044-ad4c5de2-92fe-11e7-9156-4b6599fd414b.png)

Seems like they should be in line

**Comment by zerocrates** [comment]
Gosh it feels like we _just_ fixed this...

Like every other time, it's that the styles are expecting the "row" here to be `display: flex`
