### ISSUE TITLE
Final call on accessibility of Media browse

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#1053]
We often forget about the Media browse, partially because it's so hard to get to (or at least doesn't make itself visible). This extends to media show as well, and of course search. Edit is slightly more accessible since it's linked to from item edit.

I don't love that we have this full browse interface but it's so hidden away.

**Comment by kimisgold** [comment]
I agree that I find media/browse's hiddenness pretty odd. I'm trying to recall the argument against its inclusion in the left sidebar, something along the lines of not wanting to make Omeka too CMS/site-oriented.

**Comment by zerocrates** [comment]
There's still disagreement over this, and for the sake of stability in the leadup to 1.0, I think leaving it out is still the best course of action.
