### ISSUE TITLE
Maybe a site details action/sidebar?

### ISSUE THREAD

**Issue by patrickmj** [omeka/omeka-s#1057]
We're in the mode of not adding features, I think, but as I've bopped around to different sites this seemed like a useful one.

From the sites browse page, it'd be nice to have a details button/sidebar that'd quickly show basic info like theme choice, maybe item pool info?, settings info (including from modules).

The idea is to give an overview of the state of the sites. This could be useful for admins to know what's being used and how, and for bug reporting to us.

**Comment by zerocrates** [comment]
Don't think it's a priority for 1.0
