### ISSUE TITLE
Best practice for default user and module settings

### ISSUE THREAD

**Issue by Daniel-KM** [omeka/omeka-s#1058]
What are the best practices to save user settings for a module (see omeka-s-modules/CSVImport#96)?

There seems to be at least six possibilities (for the position of the settings and its name):

- Internally in the module
- in the module config of the module, somewhere
- in the module config, as [csv_import][user_settings]
- in the module config, as [user_settings][csv_import]
- in the module config, without subarray, as [user_settings]['csv_import_multivalue_separator]
- in the module config, without subarray, as [user_settings]['multivalue_separator]

The question is the same for module settings and site settings.

(copied from https://github.com/omeka/omeka-s/issues/973#issuecomment-327781804)

**Comment by jimsafley** [comment]
There's no best practice as far as I'm aware.

**Comment by zerocrates** [comment]
I'm not aware of the 'user_settings' patterns existing outside of CsvImport (but correct me if I'm wrong), so I wouldn't really consider those "in the running." I'm not even really sure what the concept of "user settings" in the module config would mean.

**Comment by zerocrates** [comment]
Ah I see you mean defaults (it's in the title but not really in the issue body).

I'd say to that the current practice (we can argue about "best") is to do it internally: i.e. it's handled by each module that defines a setting in the form config and/or the default arg it passes when it tries to get the setting.

**Comment by Daniel-KM** [comment]
Yes, this is for the default. I think it's important that all params should go in the same place (more config, less code), so I'm going to choose the option 3, for modules I manage (for module settings too).
