### ISSUE TITLE
Language codes for URI reference labels?

### ISSUE THREAD

**Issue by patrickmj** [omeka/omeka-s#1060]
Per https://forum.omeka.org/t/internationalized-omeka-s/3154/19, it might be nice to allow i18n on the labels for URI references in metadata, similar to what we have for literals.

**Comment by jimsafley** [comment]
This is possible from a data model perspective. We can store the language in the value's `lang` field, since it's not being used for the URI data type. We can assume `lang` is the label's language because `@language` is ignored when placed in non-`@value` nodes.

**Comment by zerocrates** [comment]
Yes, there's nothing in the data model preventing this. In terms of our presentation there'd be a little difference between if we try to say it's just the label that's got the language or if it really applies to the whole value (like, would we try to match labels where the URI is the same?).

Just the label makes the most sense to me, and as Jim says that aligns better with what JSON-LD allows, but I do believe that we've already recieved a suggestion to do it on the whole value.

**Comment by zerocrates** [comment]
Again cramming it into the interface is another matter.

**Comment by jimsafley** [comment]
Note that we do not have the capability of providing multiple labels for one URI value, so the definition of "multilingual" is important here.

**Comment by martimpassos** [comment]
Hi, are there any updates on this? I'm working on a bilingual project and would like to display URI labels in more than one language

**Comment by mdavismcd** [comment]
I'm also interested in this. I might be missing something but all URI labels are missing a language, which is flagged on a simple WAVE test.

**Comment by amileta** [comment]
Hello, is there an update on this? Is it possible to somehow enable this feature ? We also work on a bilingual project and this would simplify the implementation of the request to show the URI label in the language the user has selected

**Comment by jimsafley** [comment]
@kimisgold The [uri-data-type-lang](https://github.com/omeka/omeka-s/tree/uri-data-type-lang) branch adds the language control to URI values. The styling needs your attention, preferably without changing the markup. Notify me if a markup change is needed.

**Comment by kimisgold** [comment]
@jimsafley I've styled the language toggle button to the right. I would like to add a `<label>` reading "Language" to that input, and a wrapping span to the effect of `<span class="value-label-text">` around the label strings. This will help me improve the label styles and give the language input a little more clarity and markup consistency.

Example markup I'm looking for:

```
<a class="value-language o-icon-language active" title="Set language" href="#" aria-label="Set language"></a>
<label>
    <span class="value-label-text"><?php echo $translate('Language'); ?></span>
    <input class="value-language active touched" type="text" list="value-languages" data-value-key="@language" aria-label="Language">
</label>
```

We would apply the same markup pattern to the labels in the URI input.

**Comment by jimsafley** [comment]
I don't think changing that markup will affect the behavior, so go ahead and make those changes.
