### ISSUE TITLE
Error with attached media loses item metadata

### ISSUE THREAD

**Issue by patrickmj** [omeka/omeka-s#1065]
If I fill in a bunch of metadata for an item, then try to upload a file that doesn't validate (e.g., disallowed extension and type), all the metadata that I had entered is lost when the page reloads.

(The double-error of both file type and extension is also a little odd, but I think there's not much to do about that)

**Comment by zerocrates** [comment]
Yeah the double error is expected.

There's an existing issue floating around for this but we may have closed it (as we slightly improved things at that time but didn't cover every possible error).

Just to clarify, this is about losing other stuff you were going to save into the form at the same time, not about losing any already saved data, correct?

**Comment by patrickmj** [comment]
Yes, already saved data is still there. Just the new stuff disappears

**Comment by jimsafley** [comment]
We acknowledge this as a problem, but there are significant barriers to fixing it. Given this and the lack of users engaged with this issue, we're closing it.
