### ISSUE TITLE
Can't reorder blocks in FF

### ISSUE THREAD

**Issue by patrickmj** [omeka/omeka-s#1067]
Trying to reorder blocks in FF has no effect. Attachments, e.g. on item showcase block can be reordered, but the blocks themselves don't move. Works fine in Chromium.

**Comment by kimisgold** [comment]
Confirmed. Looking at the inspector, I see sortable's attributes applied when attempting to drag (`<div class="block value sortable-chosen" data-block-layout="pageTitle" style="will-change: transform" draggable="true">`), but it doesn't seem to successfully create and insert a `.sortable-ghost` element into the DOM.

**Comment by zerocrates** [comment]
I believe #1049 is on Firefox as well

**Comment by zerocrates** [comment]
I'm able to drag the blocks from the very very bottom of the handle on Firefox, probably only a pixel or a handful of space where it works.

This applies even if you take off the handle setting or set it to the whole header, the handle is still unclickable. This is some kind of clue probably.

**Comment by zerocrates** [comment]
Removing `overflow: hidden` from the style for `.block` seems to make Firefox happy.

@kimisgold can you confirm?

**Comment by kimisgold** [comment]
Confirmed.

**Comment by zerocrates** [comment]
makes perfect sense

**Comment by kimisgold** [comment]
ugh

**Comment by zerocrates** [comment]
The style's been there forever: https://github.com/omeka/omeka-s/commit/c6cbc82f4cc0906cf70fe450289ff16a090dd30a

so I'm going to point the finger at Firefox changing.
