### ISSUE TITLE
Visibility tab does nothing

### ISSUE THREAD

**Issue by kalbers** [omeka/omeka-s#107]
Should allow users to set items to public or private.

Additionally, if that is all this does, should it have its own tab?

**Comment by kimisgold** [comment]
Similarly, I'm wondering if item sets needs its own tab based on the way it works with all selected item sets being defined in one field. Should we consolidate the two tabs somehow, and if so, what is a good summary label for the fieldset?

**Comment by kalbers** [comment]
I guess a consideration here is where does the stuff modules add go as well? It's not hard to imagine running out of real estate at the top if there are 4-5 plugins that add panels. (On the other hand, that hasn't become a problem on Omeka as of yet, with a similar layout). But would it make sense to have something like an Administrative panel, with baked in things like visibility and item sets, and then a Modules panel, that throws up anything a module adds?

I also think that no matter how those questions are answered, it's worth considering that the public status could probably live outside of the panel pretty easily, next to the Save Changes button, and that might make the most sense for that particular feature.

**Comment by jimsafley** [comment]
Since #133 you can submit a checkbox element with `name="o:is_public"` to set the resource visibility.

**Comment by kimisgold** [comment]
Fixed in c6c4c0f6d68d1709ae6fcc7da8bc147dd3864252.
