### ISSUE TITLE
"Show attachment title" returns nothing for HTML media's "file name" setting

### ISSUE THREAD

**Issue by kimisgold** [omeka/omeka-s#1075]
In my use case, I am using the media block to display a music player via an embed code as HTML media. HTML media doesn't come with a file name, so I provided a title for it. There doesn't seem to be a non-manual way to display the media title as part of the page media block.

**Comment by zerocrates** [comment]
So, specifying a Title does or doesn't work? I'm not totally getting which combination of things works and doesn't.

**Comment by kimisgold** [comment]
Yeah, it's hard to talk about. Let's see if screenshots help.

1. The HTML media attachment, titled "Memphis Blues, 1914, Victor Military Band": 

![screen shot 2017-10-04 at 3 08 21 pm](https://user-images.githubusercontent.com/606764/31194699-fd9e6646-a915-11e7-9982-51a617400d26.png)

2. The media block on a page, attaching the above media. The 'file name' is selected option for 'Show attachment title'. (The item name is simply "Memphis Blues".)

![screen shot 2017-10-04 at 3 26 33 pm](https://user-images.githubusercontent.com/606764/31195493-84a481d2-a918-11e7-9169-b5f9567fd8e9.png)

3. The page view with the media block visible. Nothing appears under the media player.

![screen shot 2017-10-04 at 3 29 15 pm](https://user-images.githubusercontent.com/606764/31195612-dfc7c2d6-a918-11e7-8ddd-4cb430a92603.png)

**Comment by jimsafley** [comment]
See #1113
