### ISSUE TITLE
Module version info reflects the files, not what's installed

### ISSUE THREAD

**Issue by patrickmj** [omeka/omeka-s#1081]
A quirk came up with updating Collecting. Going from beta3 to rc.1, there was an error in the upgrade. The result was that the modules screen reported the version as v1.0.0-rc.1, and had the Upgrade button. However, that's not the version that was in place according to the database, since the upgrade failed. 

The only way to dig up the difference was to look directly at the database, which won't be an option for many people.

**Comment by zerocrates** [comment]
Pretty sure this is in line with Classic's behavior: we report the version of the installed files (the INI version), not the database version. In the case of a mismatch the upgrade UI serves as a marker.
