### ISSUE TITLE
Schedule 1.0 Official Release Date / time during Sprint Planning Oct 16

### ISSUE THREAD

**Issue by sheilabrennan** [omeka/omeka-s#1083]
- [ ] Schedule an actual date and relative time (that cannot be late on a Friday) that everyone agrees upon

- [ ] Entire team agrees to be in the office on both the day before and day of official release day

**Comment by patrickmj** [comment]
Practically speaking, this looks like official release Oct 31, as we've said elsewhere.

**Comment by sheilabrennan** [comment]
It's a little more complicated than that, because we're also relaunching omeka.org and moving everything to Ziti. So there are many moving pieces to discuss on Monday.
