### ISSUE TITLE
Outreach plan for devs and end users

### ISSUE THREAD

**Issue by sheilabrennan** [omeka/omeka-s#1084]
For 1.0 and new Omeka.org

**Comment by mebrett** [comment]
General user outreach is up as a GoogleDoc.

**Comment by sheilabrennan** [comment]
Thanks, @mebrett. 
@patrickmj do you have anything to share? 
Megan has an idea for you to write a post that addresses changes to Classic add-ons registry. I think this is a good opp to encourage developers and designers to submit addons for both Classic and S.

**Comment by patrickmj** [comment]
@mebrett could you put the link to the Google doc here? I'm not seeing it among the things that I'm part of, though I'm pretty sure you invited me to edit it.

**Comment by mebrett** [comment]
@patrickmj I'll invite you via the doc

**Comment by sheilabrennan** [comment]
@patrickmj is there anything for us to look at regarding dev outreach?

**Comment by patrickmj** [comment]
Not yet

**Comment by Daniel-KM** [comment]
Is there a roadmap somewhere for the next version of Omeka S (already a very good product anyway)?

**Comment by patrickmj** [comment]
Not really yet. We know of some things people would like, and are watching the feedback we get. But those aren't formalized into a roadmap yet.

**Comment by patrickmj** [comment]
Internal doc is updated
