### ISSUE TITLE
CKEditor style dropdowns are inconsistently usable

### ISSUE THREAD

**Issue by kimisgold** [omeka/omeka-s#1085]
While working on a page, I was able to use CKEditor to change strings to different block or different styles in one block, but in another block the headings and styles dropdowns don't expand to show options.

First block on the page with working dropdown: 

![screen shot 2017-10-10 at 4 13 27 pm](https://user-images.githubusercontent.com/606764/31408804-bce5a77e-add7-11e7-84b9-72b08007e741.png)

Same page, later block with nonworking dropdowns:

![screen shot 2017-10-10 at 4 14 02 pm](https://user-images.githubusercontent.com/606764/31408830-d29294e2-add7-11e7-9b41-df8063e196bc.png)

Message me for a site login if you'd like to reproduce this bug.

**Comment by patrickmj** [comment]
Confirmed on my local install in FF. Order of trying to edit the block doesn't matter -- after reloading the page, trying to use the dropdowns on the 2nd or 3rd block first doesn't work, but on the 1st block they do.

**Comment by mebrett** [comment]
Still an issue: https://forum.omeka.org/t/html-blocks-in-page-edit/5153
