### ISSUE TITLE
Private icon for items a little offset from other icons

### ISSUE THREAD

**Issue by patrickmj** [omeka/omeka-s#1093]
In both Chromium and FF, the icon signaling an item is private is a little offset vertically from the other icons.
![privateicon](https://user-images.githubusercontent.com/153262/31620182-97d3cd9e-b264-11e7-8b7c-d16fb624a16d.png)

**Comment by zerocrates** [comment]
The alignment of the action links looks like it's yet another Metadata Browse-related styling side effect.

**Comment by patrickmj** [comment]
Yep. Adding this to https://github.com/omeka-s-modules/MetadataBrowse/issues/39
