### ISSUE TITLE
CSRF error when importing a resource template

### ISSUE THREAD

**Issue by patrickmj** [omeka/omeka-s#1095]
As the global admin, when I review a resource template to import then try to complete the import, I get an error of `CSRF: Value is required and can't be empty`

**Comment by patrickmj** [comment]
More info:

The first page (uploading the file for review), sends `resourcetemplateimportform_csrf`

The complete import form appears to send a parameter named `resourcetemplatereviewimportform_csrf`

Their values are different.

**Comment by zerocrates** [comment]
Hmmm. It's expected that those would be different like that (at least, now it is), but that action is just doing some wacky stuff where it sometimes checks the validity of a different form than it actually rendered.
