### ISSUE TITLE
Redundancy between Resource Pool Item Set search and Item Set tab?

### ISSUE THREAD

**Issue by patrickmj** [omeka/omeka-s#1102]
Just noticed that both the Resource Pool search by Item Set and the Item Set tab look like they do the same thing. I can imagine that the search basically takes a snapshot of the Item Set Items, while the tab is continuously updated. If that's the case, that should be more clear. Otherwise, it looks redundant.

**Comment by zerocrates** [comment]
The Resource Pool item search tab just limits what items show, so choosing an Item Set there limits what _items_ are visible. It's not a snapshot, but continuously updated.

The Item Set tab limits which _sets_ are visible. So, if you have one overarching set everything you're working with is in, you can choose it on the search. If you've got several "sub" sets you want to expose, you'd choose them under Item Sets. The set that limits the items need not be one of the sets you actually expose, either.

**Comment by patrickmj** [comment]
Ah! So is it fair to say "Use the pool search for fine-grained selection with criteria in addition to item set."

**Comment by zerocrates** [comment]
The key distinction is that the selections on the Item Set tab don't affect at all which *Items* are visible.

**Comment by patrickmj** [comment]
Ah. Got it. Difficulty of the different manifestations of what a Resource might be (Item vs Item Set)? Thanks.

**Comment by zerocrates** [comment]
Yeah. The situation is that the Item Pool search-based system was first and only affected Items. The Item Set filtering was added later based on the idea that the same items might be categorized into different sets, some of which you might not want to show on a particular site (or any site), even if you want the item itself.

**Comment by patrickmj** [comment]
Makes sense, though the terminology gets nonintuitive until you really grok what a Resource is in Omeka S in practice and interface.
