### ISSUE TITLE
Multiple hasPart relations don't stack correctly

### ISSUE THREAD

**Issue by patrickmj** [omeka/omeka-s#1104]
An Item Set that uses multiple hasPart relations doesn't quite get them to line up on the admin side. It's probably worth checking if the same is true on Item pages. 

This is on the sandbox, which is only at RC1, so it's also possible that this has been fixed.

![itemsethaspart](https://user-images.githubusercontent.com/153262/31966605-2fae24e6-b8d9-11e7-9e3a-4e2814932e1f.png)

**Comment by patrickmj** [comment]
Looks fixed on develop. yay!

**Comment by zerocrates** [comment]
That's strange, because I don't believe there have been any post-RC1 styling changes in this area (or any really).

It looks like it may just be a problem caused by the MetadataBrowse module rather than the core styling.

**Comment by patrickmj** [comment]
Doesn't seem so. MetadataBrowse isn't enabled in the sandbox, and I get same working results on develop with it on and with it off. Possibly a side effect of some other change?

**Comment by zerocrates** [comment]
MetadataBrowse is enabled on the sandbox, though. Unless I'm looking at the wrong sandbox.

The offending styles are in metadata-browse.css so it seems pretty cut and dried to me.

**Comment by patrickmj** [comment]
I should've said that it isn't enabled for that property. Still confusing that I can't reproduce it locally.

**Comment by patrickmj** [comment]
ah, just found how to reproduce it, at least in part
