### ISSUE TITLE
Allow global or site administrator to turn off API?

### ISSUE THREAD

**Issue by patrickmj** [omeka/omeka-s#1109]
Right now, the public API is open. Should we add the ability to turn it off like we have in Classic?

**Comment by zerocrates** [comment]
I'd have to double check but it's possible/likely that all the linked data accoutrements of S assume the existence of the API, and I'm not sure what having it not exist would entail.

As for site-by-site, the API being almost entirely global in its scope, there won't be a way to disable the API just for one site.

**Comment by patrickmj** [comment]
Okay. I'm good with the answer to the original question being "no". 

[Editorial: It's a good, textbook, example of code design, decisions, and technology not being politically or ethically neutral.]
