### ISSUE TITLE
Undefined variable 'message' when URL media fails

### ISSUE THREAD

**Issue by patrickmj** [omeka/omeka-s#1111]
Trying to use the URL Media type, but failing because it isn't found, gives

```
Undefined variable message in
/var/www/html/omekas/application/src/File/Downloader.php on line 86

```

peeking out at the top of the page

**Comment by zerocrates** [comment]
Looks to have been a regression introduced when consolidating the very similar error printing code used just above: both places used basically the same code, but this lower one actually used the `$message` variable previously there to log the error. (The one above results from an exception and so simply logs that directly).

**Comment by patrickmj** [comment]
Yeah, I just started looking at it now. Should I just do

```php
$message = sprintf(
                    'Error downloading %s: %s %s', // @translate
                    (string) $uri, $response->getStatusCode(), $response->getReasonPhrase()
                );
```
and use it both places?

**Comment by zerocrates** [comment]
That's basically what the previous code did, yes, so that would be fine.
