### ISSUE TITLE
Look over linked resource markup/styling/copy

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#1112]
Now that the linked resources tab only shows "in" links, there's some decisions we made we should probably revisit:

- The name "linked resources": too generic now? Since it's now "what links to this"
- The three-column table structure: the "This" will always be in the same column now so should we just omit it? Or even not use the table structure?
- The pagination here is a little different than everywhere else, but so is the pagination _markup_, which seems less useful
- I added thumbnails to the resource links here just recently, I don't think it will be controversial, just a note.

**Comment by jimsafley** [comment]
* Technically they are "subject values," but that's not helpful to most users. "What links to this?" is descriptive but clunky. SEO uses the term "inbound links," but ew.
* I'm all for getting rid of the "Object" column. Whatever our decision, I think we should indicate that the resource is the "Subject" and the property is the "Predicate," explicitly or visually.
* I remember having a reason for not using our current pagination helper. Maybe that reason doesn't apply anymore. I'll look into it.

**Comment by patrickmj** [comment]
On naming: I'm not sure we'll come up with much better. Maybe "Incoming links" or "Incoming relations"? but I think that only makes sense when people already understand the directionality. I'm not worried about "Linked resources" sounding too generic.

On the structure: Yeah, that is awkward. I don't know if we do -- or can -- group the relations by predicate, but if that's there we could get rid of the table structure and do something like

```
dcterms:isPartOf
     {other Item 1}
     {other Item 2}
dcterms:creator
     {other Item 3, with class foaf:Person}
```

if possible, I think that'd give a nice overview of the relations involved.

**Comment by sharonmleon** [comment]
My sample universe of one would like to ditch the printing of the notion of "subject" "predicate" "object" column labels on the public side. Instead, they would l a two column table called "Relationships" that consists both the vocab property or edited label, object resource title construction-- with no labels for those columns. 

Even in this set-up, the grouping of predicates would be nice.

**Comment by zerocrates** [comment]
Grouping like that could be tough with Jim's new pagination of this view, but we could probably make that work too.

**Comment by sharonmleon** [comment]
Not essential, certainly. Historians will want everything sorted by data, which is not possible.

**Comment by jimsafley** [comment]
John is right that pagination complicates grouping by predicate, but I recognize the usefulness in it. 

We're closing in on an interface that may be best suited on a separate page, perhaps a "Linked resources" link on the details sidebar, alongside "Visibility," "Item sets," etc. The new page would list all the predicates in alphabetical order, with a link back to the object resource. The individual predicates would link to a paginated list of subject resources, with a link back to the predicates page.

**Comment by jimsafley** [comment]
I've implemented pagination, property grouping, and filtering by property, all on the resource show pages as before. Once we settle on nomenclature for "linked resources" and have @kimisgold style the admin and public pages, i think that resolves this issue.

Kim, the templates that need styling are `common/linked-resources` and `omeka/site/item/show`.

**Comment by patrickmj** [comment]
Timely feedback from the DCMI workshop is that one group expected it to include external resources, not just internal ones. We'd probably have to signal the difference somehow. The existing icons from the edit page seems fine.
