### ISSUE TITLE
Check use of "file name" in Sites/block layouts

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#1113]
Some of the layouts or their options refer to and/or use "file name" as an option for the display of captions, etc.

For one, we don't usually want to refer to "file" at all, rather Media, and for another there are some functional problems with Media that don't have a backing file like HTML, etc.

**Comment by zerocrates** [comment]
@kimisgold please check this to ensure it addresses the problem(s) you had identified

**Comment by kimisgold** [comment]
Tested with both HTML and non-image media. Works for me.
