### ISSUE TITLE
Suggestions for site resource page item pool

### ISSUE THREAD

**Issue by patrickmj** [omeka/omeka-s#1116]
These would ultimately be separate issues, but since they're all so closely related I'm listing them here and we can break apart the ones we want.

Generally, this was the most confusing part of the site creation process for the DCMI workshop. Here's some things people came up with that might make it easier.

* Have a list of recently added items to select from. That'd let people go quickly from creating their content to adding to the pool.

* Search or list by owner (maybe with shortcut to show your recent additions). Selecting multiple users as the owner might also be helpful, but would be unwieldy when there are lots of users in the installation.

* A preview of what items would come in based on the selections made on the screen would be super helpful to check what will happen before committing to the additions. An item count would also be helpful, either in the preview or as a separate thing.

The current workaround for some of these is to do similar things via creating an item set and putting items into it, but these would provide a much more direct path.

**Comment by zerocrates** [comment]
We already have an item count on that screen, I believe. Clicking the count should show you the actual items your pool includes, too (just on a browse page).

Search by owner should be addable without too much fuss.

Listing recent items on the other hand, would require a whole new paradigm of one-by-one selection that the pool is very different from.

**Comment by patrickmj** [comment]
There's the item count of what currently exists, but not an item count of how many would be added. I think that's what they are thinking of.

Search  by owner(s) sounds like it'd be very helpful, from what I heard.

Yeah, I suspected that the recent items (and preview) would be a new complicated thing. Sounds like that might not be something for 1.0.

**Comment by zerocrates** [comment]
We need to replace this issue with one saying what we actually want to do.

**Comment by zerocrates** [comment]
This really isn't applicable anymore in the current/new system (though we're still considering things that are basically the same as some of these suggestions, like the "preview.")
