### ISSUE TITLE
Make media orderable

### ISSUE THREAD

**Issue by jimsafley** [omeka/omeka-s#113]
Following up on #109, existing media should be orderable via the item edit form. The media model will need a `position` field and the interface should look similar to the resource template form.

**Comment by zerocrates** [comment]
@kimisgold This should just need javascript/CSS for dragging/dropping the media divs to reorder them.

The WIP is on the media-position branch, so work on there.

**Comment by zerocrates** [comment]
On second thought let's just make the second UI pass on this a separate issue.
