### ISSUE TITLE
Put mail config example in local config file

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#1131]
We had an analogous commented-out example section for SMTP mail in Classic's config file.

**Comment by jimsafley** [comment]
Something like this in local.config.php.dist?
```
    'mail' => [
        'transport' => [
            'type' => 'sendmail',
            'options' => [
                'host' => null,
                'port' => null,
            ],
        ],
        'default_message_options' => [
            'encoding' => 'UTF-8',
            'from' => null,
        ],
    ],
```

**Comment by zerocrates** [comment]
The only useful example would be for SMTP, not Sendmail where the defaults are almost always fine if it's going to work at all.

**Comment by jimsafley** [comment]
Added to enduser docs https://github.com/omeka/omeka-s-enduser/commit/b66a2446ba94eec4349034c14d015769833584c8
