### ISSUE TITLE
Apigen doesn't like interfaces being referred to as classes

### ISSUE THREAD

**Issue by patrickmj** [omeka/omeka-s#1136]
Running Apigen on latest develop, a fairly ambiguous complaint comes out:

```
  [Roave\BetterReflection\Reflection\Exception\NotAClassReflection]                    
  Provided node "Omeka\Db\Migration\MigrationInterface" is not class, but "interface"
```

My best guess is that it's complaining when it hits this, but not sure:

https://github.com/omeka/omeka-s/blob/develop/application/src/Db/Migration/Manager.php#L109

```
        if (!class_exists($class, false)
            || !is_subclass_of($class, 'Omeka\Db\Migration\MigrationInterface')
        ) {
            throw new Exception\ClassNotFoundException(
                $this->getTranslator()->translate('Migration file did not contain the expected class')
            );
        }
```

Note that apigen demands PHP 7.1 or higher, so it might not necessarily be an issue with our current PHP requirements. But it does make the generated documentation fail.

**Comment by patrickmj** [comment]
Following things in https://github.com/omeka/omeka-s/blob/develop/application/src/Db/Migration/Manager.php#L116 look like the same thing

```php
        if (is_subclass_of($class, 'Omeka\Db\Migration\ConstructedMigrationInterface')) {
            $migration = $class::create($this->serviceLocator);
        } else {
            $migration = new $class;
        }
```

**Comment by zerocrates** [comment]
I don't think it's going to be those pieces, as they're not part of the documentation it would read, they're just (valid) code.

My guess would be a docblock somewhere or another.

If it's feasible you could skip the whole migrations folder.

**Comment by patrickmj** [comment]
Sadly, the options in apigen make it hard to select out a folder. So, I'm going to try some fairly sketchy tries in the docblocks and see what happens.

**Comment by patrickmj** [comment]
Aaaand apigen turns out to be problematic. I went to report issues, and discovered the latest.

They're looking for a maintainer, so might not be a solution for our needs.
