### ISSUE TITLE
Searching to link a resource produces properties selector rather than results

### ISSUE THREAD

**Issue by sharonmleon** [omeka/omeka-s#1137]
When searching in the sidebar to link an existing resources as a value in an item description, the search output doesn't list matching resources, but rather produces the property selector sidebar.
![screenshot-2017-11-10 edit 1744-07-12 phebe mingo church record items new england people of color 1](https://user-images.githubusercontent.com/741480/32665103-3856adc2-c601-11e7-8aee-72d916da9c18.png)
![screenshot-2017-11-10 edit 1744-07-12 phebe mingo church record items new england people of color](https://user-images.githubusercontent.com/741480/32665104-38770c84-c601-11e7-9681-71d165e32012.png)

**Comment by zerocrates** [comment]
Not seeing that behavior. Maybe somehow the "X" button is getting focus?

**Comment by sharonmleon** [comment]
It's not getting cancelled, because the site works for a while before the turnover to the properties. Might just be this install.

**Comment by zerocrates** [comment]
I think we determined this was a caching issue.
