### ISSUE TITLE
Move add media input to the sidebar

### ISSUE THREAD

**Issue by jimsafley** [omeka/omeka-s#114]
From #109

> It's also possible that we don't need so much horizontal space for the "add new media" control since it's very simple, or that we could use the huge empty space where the sidebar should be for this or some other purpose on this tab.

> It'd be fixed, always available, and we could always scroll down to the new file if it's being added to a long list of existing media.

**Comment by kimisgold** [comment]
Fixed in fa7a550f13013823d904294d57cc23afc239e871.
