### ISSUE TITLE
Clarify that the results on the 'front' page is the list of sites

### ISSUE THREAD

**Issue by patrickmj** [omeka/omeka-s#1143]
Going to the front page of an S installation, you get a list of the public sites (or is it just the sites you have access to?). Without knowing that, though, it's unclear that that's what's being listed.

It's especially confusing when there are no sites. You just get "0 results".

![zerosites](https://user-images.githubusercontent.com/153262/32813762-bd97e778-c979-11e7-98d2-1df8bffeebcb.png)

**Comment by zerocrates** [comment]
I think it's fairly clear that the default front page isn't going to survive as-is, but we've just yet to come up with anything better (or frankly, to care about it all that much).

It is only the sites you have access to view that you can see.
