### ISSUE TITLE
New version notification

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#1144]
A la Classic.

We could probably either hook it to Github's "latest release" API, or use the same system Classic uses where we host an exceedingly simple API just declaring the latest released version.

**Comment by Daniel-KM** [comment]
For modules too?

**Comment by zerocrates** [comment]
Good point...

That's actually part of the reasoning behind the new website add-ons directory: it finally outputs machine readable info on available addons and versions.

We could definitely be reading that for both modules and themes.

**Comment by zerocrates** [comment]
Leaning toward asking omeka.org, just as Classic does. It's just barely more release workflow, and keeps us from being even more tightly tied to github.
