### ISSUE TITLE
Default values for resource templates?

### ISSUE THREAD

**Issue by patrickmj** [omeka/omeka-s#1150]
Via https://forum.omeka.org/t/default-values-for-resource-templates/4966

Can resource templates be used to fill in a default value for a property? Seems like it's a good way to get around the feature request we hear about cloning an item. This might also be a module adding a datatype. One complication is that the forum poster is thinking of text values, but we'd need to sort out internal references and URIs, too.

**Comment by jimsafley** [comment]
We don't currently plan on addressing this issue. If you want default values, you can provide your own data types that set a default. Feel free to reopen and elaborate should you want further discussion.
