### ISSUE TITLE
In linked resources, use alternate property label if available.

### ISSUE THREAD

**Issue by kimisgold** [omeka/omeka-s#1152]
Currently, a resource's list of linked resources does not display alternate property labels if any of its linked resources uses a resource template. It instead shows the original property label.

**Comment by zerocrates** [comment]
One "cheap" option could be to include in each property heading _all_ the different labels for that property represented in the results (i.e.: `Creator (Composer, Author, Director)`), so you're basically taking the same result set we already have and just addding a little extra lookup to the headings.

A similar alternative would be to print the template-derived name inline alongside the link (like `Item X (as Author)`. It's a different presentation but still the same basic idea of just tacking on a little extra information to what's essentially the same output.

Re-jiggering the output so it's actually reordered/grouped based on the alternative property labels is a much bigger pain, though probably doable with some gnarly set of joins.
