### ISSUE TITLE
Tagged release not correct

### ISSUE THREAD

**Issue by timmmmyboy** [omeka/omeka-s#1153]
Download https://github.com/omeka/omeka-s/releases/download/v1.0.1/omeka-s.zip and open application/Module.php and it reports version 1.0.0. Haven't done a diff to see if there are other differences between Github and the release that got tagged but seems something is up.

**Comment by patrickmj** [comment]
Whoops! Thanks. We'll make corrections.

**Comment by zerocrates** [comment]
Yes, there appears to have been a problem uploading the zipped release.

It should now be correct.

**Comment by timmmmyboy** [comment]
Awesome, thanks for the quick work on that!

**Comment by zerocrates** [comment]
It appears that the problem was more or less _just_ the number being wrong.
