### ISSUE TITLE
Don't use phar

### ISSUE THREAD

**Issue by jhdulaney** [omeka/omeka-s#1158]
Hello!

So, it seems that we want to use phar.  However, phar has not seen any activity in nearly a decade.  Plus, I am on a shared hosting environment and would rather not have to carry dependencies if I don't have to.

**Comment by zerocrates** [comment]
I'm not quite sure to what you're referring.

**Comment by jhdulaney** [comment]
If I do gulp init, it eventually gets to wanting to use phar.  I can provide more detail when I'm on my other box.

**Comment by zerocrates** [comment]
Likely it's trying to run Composer, which ships itself as a .phar.

Every version of PHP that Omeka S supports (plus several older ones) has phar support built in and enabled by default. If you're dealing with a shared host and they won't enable it or offer some option for you to do so, I'd switch hosts.
