### ISSUE TITLE
Opening forms in multiple tabs results in CSRF Error

### ISSUE THREAD

**Issue by brian-maher** [omeka/omeka-s#1180]
Having looked at this issue, it appears to be an issue with the way in which Zend handles sessions and CSRF tokens. Take this usage scenario:

 - User opens item set
 - User then opens multiple items in new tabs, and clicks edit in each

This action will cause all but the last-opened forms to fail upon submission due to an invalid CSRF token. It appears that Zend is refreshing the CSRF token upon every request and keeping only 1 valid CSRF token per session, rather than using per-session or per-form tokens which would enhance usability.

**Comment by jimsafley** [comment]
We can't reproduce this issue. Feel free to reopen and elaborate should you want further discussion.

**Comment by brian-maher** [comment]
It was over 4 years ago, I think we just worked around it but honestly cannot remember.

**Comment by zerocrates** [comment]
Sure. We're just cleaning up our backlog of issues.
