### ISSUE TITLE
Linked resources table wonkiness on public item show

### ISSUE THREAD

**Issue by sharonmleon** [omeka/omeka-s#1181]
I'm having this odd breaking on both firefox and chrome, regardless of theme. Also, the alternate labels for the properties aren't carrying through to the linked resources. See: http://jesuitplantationproject.org/s/jpp/item/1145

![screenshot-2018-1-3 dina jesuit plantation project 1](https://user-images.githubusercontent.com/741480/34548371-c10fe36a-f0cf-11e7-979e-9997c757d535.png)

**Comment by kimisgold** [comment]
We just made some big markup changes to the linked resources, so all the themes should be getting updates soon.

**Comment by kimisgold** [comment]
@sharonmleon All the themes should be updated to reflect the new markup. Could you update your Omeka S installation and your theme to confirm?

**Comment by sharonmleon** [comment]
@kimisgold I updated and cleared my cache in both firefox and chrome and I've got the same row issues going on. Exactly the same, in fact. I tested Cozy and Center Row.

**Comment by kimisgold** [comment]
I suspect that the S installation isn't up-to-date. I'm on Omeka S v.1.1.0-alpha, and the main difference I see on your installation is that the linked resources aren't in a table that includes the "Alternate Label" column that we introduced in https://github.com/omeka/omeka-s/commit/0005126445d2552b5db0db17d1a9dd1b9006f6e9. This is what the current linked resources section should look like in Center Row:

![latest-linked-resources](https://user-images.githubusercontent.com/606764/35102078-d6bcf2fa-fc2f-11e7-852e-827daf7dff81.png)

**Comment by sharonmleon** [comment]
True. I am on the latest released version.

**Comment by kimisgold** [comment]
@sharonmleon Did updating to v1.1 resolve this issue for you?

**Comment by sharonmleon** [comment]
Yes, it did.
