### ISSUE TITLE
Advanced search for properties linking Omeka S resources yields no results

### ISSUE THREAD

**Issue by sharonmleon** [omeka/omeka-s#1184]
Searching for a property containing the title text of a linked Omeka S resource returns no results:

http://jesuitplantationproject.org/s/jpp/item?resource_class_id=&property%5B0%5D%5Bjoiner%5D=and&property%5B0%5D%5Bproperty%5D=818&property%5B0%5D%5Btype%5D=in&property%5B0%5D%5Btext%5D=Newtown&site_id=&item_set_id%5B%5D=&submit=Search

Newtown is the title of a linked location for the property "homeLocation" and there should be 197 items return: http://jesuitplantationproject.org/s/jpp/item/2

I've tested this with a range of linked resources and neither the title text nor the item id return any results.

**Comment by zerocrates** [comment]
The trick with linked resource search is that it's a different search "type". Where the type is "eq" in the search you've got there, you instead want "res" to search by ID. We do need to work that into the actual search interface.

Finding linked resources with the normal text search is a little more involved and we don't support it currently.

**Comment by pols12** [comment]
#939 have been closed, however I also really think the search tool should consider title of resource values as literal values.

**Comment by sharonmleon** [comment]
I do wonder if it would be possible to include a set of pre-selected multi-selects for the types. I can't imagine that visiting users would know whether they were looking for text or a resource value.
