### ISSUE TITLE
Let choose what property use as title

### ISSUE THREAD

**Issue by pols12** [omeka/omeka-s#1188]
Currently, `dcterms:title` is used as item title. However, depending on the context, we would use an other property. `dcterms:title` has a defined semantic and we are obliged to follow its semantic to write it.

For example, if each item represent a book edition (1880 first edition, 1901 second edition, 1924 third edition...), it is not relevant to use `dcterms:title` as item titles: we would prefer `bibo:edition` or a combination of property.

Maybe it is too complicated to let personalize title as a combination of user-chosen properties, but we can imagine a `o:title` property with no other semantic value than item’s designation.

(asked two times on the forum: [[1]](https://forum.omeka.org/t/is-dcterms-title-required-for-item-names/4767) [[2]](https://forum.omeka.org/t/repeatable-group-of-fields/3971/5))

**Comment by zerocrates** [comment]
There's a limited form of this feature already there in the form of the "browse heading property" site setting. Were you envisioning this as something that would be set for a whole site (or installation) or vary from item to item?

**Comment by pols12** [comment]
> There's a limited form of this feature already there in the form of the "browse heading property" site setting.

I didn’t know that feature which is indeed useful in this case.

However, I think we would want to choose a different property at least for each item type (for each resource template).

**Each item** would have a required `o:title` property to fill. Its value could be picked from another property (`dcterms:title` by default) or be manually typed.

**Comment by Daniel-KM** [comment]
I just have a case where I need this feature for some items. In my case, it is related to the class, so it is "simple" to fix: just check the class in https://github.com/omeka/omeka-s/blob/develop/application/src/Api/Representation/AbstractResourceEntityRepresentation.php#L470. It should be done for the description too. We have to specify what property to attach to each class (in the vocabulary of classes).

**Comment by Daniel-KM** [comment]
So we have to decide if we base this feature on resource template or resource class.

**Comment by sharonmleon** [comment]
Taken up in #1377
