### ISSUE TITLE
File behavior in item/show sidebar

### ISSUE THREAD

**Issue by kalbers** [omeka/omeka-s#119]
We get thumbnails for images, but a url media type, for example, produces a placeholder thumbnail. Would something more meaningful (like the url in the example) be more useful for linking to the media/show page?

**Comment by zerocrates** [comment]
I think the thumbnail is best here (any media type can have a thumbnail, including URL ones and ones without an original file at all)

The question to me is whether there should/could be the "title" for the media included in there somewhere, even just as the HTML `title` attribute. (the media display title will use the dcterms:title if it exists but will fall back to the "source" filename or URL if no title is set, it's what's used currently in the Media panel of the item edit page)

**Comment by zerocrates** [comment]
we could also combine the two and have a non-linked "header" thumbnail like we currently do, just to illustrate what the item is and how it will appear on browses, and then have all the media listed out in basically a list format, with much smaller thumbnails and title text for each. Actually visible titles vs. tooltips could be a space issue in the sidebar, though.

(this needs to involve @kimisgold i'm sure)

**Comment by kimisgold** [comment]
I like the main image up top and then media list with thumbnails and titles further down on the sidebar. I'd like to try having visible titles alongside thumbnails first, mainly because fallback images for non-image file types wouldn't be particularly useful by themselves. I don't think people would necessarily think to hover for the title.

**Comment by kalbers** [comment]
I think the title needs to be involved somehow. You could easily have multiple placeholder thumbs in the sidebar, not giving you information about any of them...
