### ISSUE TITLE
Asset cachebusting breaks openseadragon UI images

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#1191]
We have to give openseadragon the location to its images folder, which we use the regular asset helper for. With the cachebusting change, the cachebust parameter gets appended to what should just be a folder name and openseadragon generates invalid urls.

**Comment by Daniel-KM** [comment]
Fixed in #1179.

**Comment by zerocrates** [comment]
Ah yes, thanks for the reminder
