### ISSUE TITLE
Use Value for something else than item sets, items and media

### ISSUE THREAD

**Issue by Daniel-KM** [omeka/omeka-s#1198]
I'd like to use the table Value to store values that are not for item sets, items and media. For example store user data with properties from the foaf vocabulary, or tags with a specific vocabulary, etc. 

The main interest of such a thing is that the searches, etc. will be done in one table only, so modules that add metadata will be a lot easier to maintain. The second main interest is that the tags, for example, will have a language and this language will be managed like anywhere in Omeka. And they will be fully normalized as rdf too. 

The issue is that the Value refers to a resource id, but the resource type is managed outside, in the Resource table, and there is no parent entity for resources that may allow to manage it.

So if this is not a good solution, have you some idea on how to bypass this issue?

**Comment by zerocrates** [comment]
You _should_ be able to create new Resource subtypes (that can therefore take Values and classes and so on) by extending from the Resource abstract entity and adding module config for the [[entity_manager][resource_discriminator_map]](https://github.com/omeka/omeka-s/blob/develop/application/config/module.config.php#L52) config key.

Or are you wanting to do something different?

**Comment by Daniel-KM** [comment]
I'm going to give it a try, but it seems to be the good solution. I was looking for parent, but if child works, it's ok.
