### ISSUE TITLE
Server dies with 500 error on file upload if ImageMagick not installed

### ISSUE THREAD

**Issue by crism** [omeka/omeka-s#1206]
Running Omeka S on a server without ImageMagick installed… all media additions (file upload, IIIF, URL, etc.) fail with a 500 Internal Server Error. I finally traced this to the fact that ImageMagick wasn’t installed. The call to `$thumbnailer->setOptions()` crashes in `TempFile::storeThumbnails()`. I haven’t tracked it further than that, but this should be more robust.

**Comment by zerocrates** [comment]
It fails on setOptions?

That's weird, because for the default ImageMagick thumbnailer, setOptions really doesn't do much of anything. Did you get an error message? (Switching APPLICATION_ENV from `production` to `development` in .htaccess should get you one if you're not getting one now.)

**Comment by crism** [comment]
@zerocrates, there was no error message logged nor any diagnostics returned to the browser. I tracked it down via divide-and-conquer error-log messages… Naturally, this was only on our production server, while everything worked fine in staging, so I don’t want to go back and recreate it.

Before [the call to `setOptions()`](https://github.com/omeka/omeka-s/blob/develop/application/src/File/TempFile.php#L249) it was fine; it never made it to the next line. I added an explicit call to `getThumbnailerOptions()` to verify that it wasn’t crashing there. That gave me the clue I needed to fix it; sorry I didn’t probe deeper.

**Comment by zerocrates** [comment]
So, this wasn't an "Omeka has encountered an error" page, but just a white screen? In my own testing it's the "encountered an error" page that I get if we can't find ImageMagick.

**Comment by crism** [comment]
When uploading a file, the POST request gets a 500 response, and the page gives “Omeka has encountered an error.” When using IIIF import, the entire page is blank.

**Comment by zerocrates** [comment]
OK, thanks.

**Comment by jimsafley** [comment]
We can't reproduce the issue. There have been some changes in the meantime that may have resolved this. Feel free to reopen and elaborate should you want further discussion.
