### ISSUE TITLE
Module Import: not found

### ISSUE THREAD

**Issue by persianphilosopher** [omeka/omeka-s#1212]
Since this is not mentioned in the previous issues, it must be on my end and I would appreciate any direction to figuring out what's going on.

* Clean install of Omeka-s, latest release
* Admin dashboard works as expected
* The module tab is working until I click install and then I get 
```admin/module/install?id=ZoteroImport```

I tried the CSVImport module and have the same results. And I tried all of the above on two different servers as well.

I have set the Zend log to debug but the logs remain empty. Where can I look for the culprit? 

Thanks in advance.

**Comment by zerocrates** [comment]
What result are you getting?

**Comment by persianphilosopher** [comment]
Unfortunately, I have neither results nor logs to report: all I get is: "not found". Here is a screenshot

[screenshot](https://www.dropbox.com/s/iahq66koltsocqb/Screenshot%202018-02-14%2013.38.56.png?dl=0)

**Comment by zerocrates** [comment]
We let this lie fallow long enough that it's probably no longer valid, so I'm closing it.

Feel free to reopen or re-file if this is still an issue.
