### ISSUE TITLE
Provide direct access to private sites

### ISSUE THREAD

**Issue by ManOnDaMoon** [omeka/omeka-s#1213]
Hi,

Private sites can't be accessed directly, URLs throws a "Not found" error for non logged-in users .
Is there a plan to enable access to private sites without paying a visit to admin panel first?

Thanks and have a nice day,

Laurent

**Comment by Daniel-KM** [comment]
Just make them public? And give the url only to some people (who don't have gmail or similar mail providers of course)?

**Comment by patrickmj** [comment]
We plan to do _something_ with the login page, which is currently spartan at best. Exactly what, we haven't nailed down, but this gives us helpful feedback.

**Comment by zerocrates** [comment]
To clarify, are you asking about allowing access to non-logged in users to these sites (in which case I'd be in alignment with Daniel's answer), or are you just looking for us to prompt you to log in?

Typically we've had a pattern of making private things "invisible" when not logged in, i.e. they appear to not exist at all, and I'm a little hesitant to move from that default.

**Comment by ManOnDaMoon** [comment]
Hi and thanks for the feedback.

Here is the use case I'm looking to achieve:
I would like my sites "Restricted", meaning only accessible to a list of users defined in the site authorizations. I can't have them public for confidentiality purposes.
If I were to define the "Private" option currently used in Omeka S as I understand it, it would be closer to "Hidden".

Although I understand the original idea. I find having the sites totally invisible being a bit counterintuitive in a web standards point of view. There are some users that only require viewing permissions to the sites, and they currently are granted access to the admin panel for this purpose.
Indeed, if "Restricted" access was to exist, the logic would be that they get a login prompt on the site URL. :)

In the meantime, I have another way to achieve what I want: I set up htaccess passwords for the Omeka S install, and set my sites as "Public". There are two downsides:
- "real" admins need to login twice - meh but not so bad
- it is not possible to manage different user grants from one site to another (or not so easily)

Again thanks, and have a nice day.

Laurent

**Comment by Daniel-KM** [comment]
You can use the module [GuestUser](https://github.com/Daniel-KM/Omeka-S-module-GuestUser), that gives access only to public board.

**Comment by ManOnDaMoon** [comment]
Hi,

Based on your recommendations and my limited knowledge of omeka-s and zend framework, I've started my own module to implement the restricted sites:
https://github.com/ManOnDaMoon/omeka-s-module-RestrictedSites

**Comment by ldearly** [comment]
Hello, is there any change on this issue? I would like users to log in to see an otherwise private public site, rather than log in to the admin panel. I have tried both Guest User and Restricted Sites modules but neither seem to work. Please advise, and thank you so much for your time - I would really love to make Omeka S work for my project here.
