### ISSUE TITLE
In the Select Item sidebar on the item/edit page items appear oldest first

### ISSUE THREAD

**Issue by kalbers** [omeka/omeka-s#122]
Should appear newest first, as with items/browse.

**Comment by kimisgold** [comment]
Looking through the browse views, I'm noticing that we're inconsistent in default sorting order. Should we default to most recently created at the top, or are there exceptions to consider?

**Comment by jimsafley** [comment]
You're correct, the sort order is inconsistent at the moment. We will be fixing this once #128 is settled.
