### ISSUE TITLE
Page block that allows for iframe embeds

### ISSUE THREAD

**Issue by sharonmleon** [omeka/omeka-s#1220]
I've been thinking about how to share my work in doing my social network analysis, and one useful way would be to actually embed the incident and adjacency matrix. In the end, this is just csv data, which I image it might be nice to have a viewer for. But, I can also see that other people might want to frame a whole bunch of things the way that slides.com allows in their set-up (e.g. [my slides for my talk at Bates](https://slides.com/sharonmleon/bates/)).

**Comment by zerocrates** [comment]
You mean to embed stuff into a page? What would you want this to do that you can't currently do with just the HTML block? Or just a way to avoid having to write out the tag?

**Comment by sharonmleon** [comment]
I did mix two things together there. Sorry about that.

1) An Iframe-tag builder, because I can't be the only one who always screws it up when doing it by hand. And, I assume that there are some security concerns that could be headed off by building the tag? Maybe that's wrong. 

2) Is there a way to embed a csv file that renders it readable in the way that the github does? I guess I've been too trained by RStudio and Jupyter notebooks to want to be able to see everything in one place, rather than grabbing the files and opening them with a different application.
