### ISSUE TITLE
Browse Preview block ignores sorting

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#1224]
We mandate "descending by created" sorting when displaying browse preview results, so when a user gives us a query that includes a sort order, we don't respect that sorting in the preview.

**Comment by sharonmleon** [comment]
This fix seems like it messes the browse all link. Or the adding of the sort parameters to the browse preview carries through to that link in a way that it shouldn't.

**Comment by zerocrates** [comment]
Can you explain further?

**Comment by sharonmleon** [comment]
I built a browse preview that used the sort by title ascending, which worked great. A click on the browse all link produced no results. But, now that I look, it doesn't work with the unsorted browse preview either. So, the browse all link isn't working at all, producing the following URL: http://chnmdev.gmu.edu/RI/s/nehistoricpeopleofcolor/item?item_set_id=132
