### ISSUE TITLE
VPAT for Omeka S (1.1)

### ISSUE THREAD

**Issue by mebrett** [omeka/omeka-s#1225]
Complete VPAT for Omeka S v1.1, post to website

**Comment by mebrett** [comment]
@zerocrates @kimisgold I could use help determining whether the dashboard meets the following: 

- [3.1.1 Language of Page](https://www.w3.org/TR/WCAG20/#meaning-doc-lang-id)
- [3.2.1 and 3.2.2 On Focus and On Input](https://www.w3.org/TR/WCAG20/#consistent-behavior-receive-focus)
- [1.4.5 Images of Text](https://www.w3.org/TR/WCAG20/#visual-audio-contrast-text-presentation)
- [4.1.2 Name, Role, Value](https://www.w3.org/TR/WCAG20/#ensure-compat-rsv)
- [3.3.3 Error Suggestion](https://www.w3.org/TR/WCAG20/#minimize-error-suggestions)

Thanks!

**Comment by mebrett** [comment]
Thank you!

**Comment by mebrett** [comment]
Thoughts on "502.3.13 Modification of Focus Cursor: Focus, text insertion point, and selection attributes that can be set by the user shall be capable of being set programmatically, including through the use of assistive technology." ?

**Comment by kimisgold** [comment]
✅ 4.1.2 Name, Role, Value
* This has been addressed in #1238.

I believe "3.2.1 and 3.2.2 On Focus and On Input", "3.3.3 Error Suggestion", and "502.3.13 Modification of Focus Cursor: Focus, text insertion point, and selection attributes that can be set by the user shall be capable of being set programmatically, including through the use of assistive technology" are all handled by the browser, so we'd be covered. I think that's the case anyway, but might need @zerocrates to look through to confirm.
