### ISSUE TITLE
local server error 500

### ISSUE THREAD

**Issue by WenNg** [omeka/omeka-s#1229]
Tried my two laptops and my desktop as local server for Omeka S and Omeka Classic. All Omeka S instances installed on three machines were working before installing the Archive Repertory plugins, after installing Archive Repertory, it will show server error 500. Not sure if it's actually Archive Repertory or Omeka S issue. Meanwhile, all other Omeka classics running well on the local servers without any problem. Anyone had the same issue?

**Comment by Daniel-KM** [comment]
Which version do you use? For me, Omeka S and Archive Repertory work fine;
