### ISSUE TITLE
Testing: Batch edit media

### ISSUE THREAD

**Issue by jimsafley** [omeka/omeka-s#1230]
[This pull request](https://github.com/omeka/omeka-s/pull/1101) adds batch editing to media browse, which is currently only available by going directly to /admin/media. The PR also makes some big changes behind-the-scenes that will require testing of all batch-edit forms: item, item set, and media.

**Comment by mebrett** [comment]
Is there a branch with the changes, or do I need to check out the pull request?

**Comment by jimsafley** [comment]
Check out the PR using the instructions near the bottom of the page

**Comment by mebrett** [comment]
Anything in particular you want testing to look for? Or just general "it does not break" and UI checks?

**Comment by jimsafley** [comment]
Nothing in particular, just every possible combination. A big task, to be sure.

**Comment by zerocrates** [comment]
We might need to take the opportunity to (yet again) broach the subject of making the media browse reachable by link from somewhere. This isn't strictly testing related but just in the ballpark
