### ISSUE TITLE
Move methods to more accessible classes

### ISSUE THREAD

**Issue by jimsafley** [omeka/omeka-s#1232]
I see no reason why the following methods need to be in `AbstractResourceEntityAdapter` when they could be more accessible in the parent `AbstractEntityAdapter`:

- `getPropertyByTerm()`
- `getSubjectValues()`
- `getSubjectValueTotalCount()`
- `getSubjectValueProperties()`

**Comment by zerocrates** [comment]
As these are all related to the property or value system, they don't really apply at the level of generality of "Entity," do they? Resource Entity would seem to be their proper location.

**Comment by jimsafley** [comment]
My use case is moot now, so this issue isn't as important to me as it once was. I have an adapter that needed to get a property by term, but `getPropertyByTerm()` is only available to adapters that extend `AbstractResourceEntityAdapter`.

The methods I listed above are the only ones in `AbstractResourceEntityAdapter` that have no dependency on their containing class, so we _could_ move them to `AbstractEntityAdapter`. Whether we _should_ is another matter.

**Comment by zerocrates** [comment]
They don't really have any connection to the API adapter or the API in general other than that it's a convenient place that has access to the necessary services, which is why the location seems (and is) somewhere arbitrary.
