### ISSUE TITLE
FontAwesome should be provided to browsers

### ISSUE THREAD

**Issue by crism** [omeka/omeka-s#1236]
The search interface is nearly invisible to end-users, and several aspects of the administrative dashboard are very confusing (especially editing and deleting navigation elements) when FontAwesome and Font Awesome 5 Free are not present on a user’s system. Omeka S should use BootstrapCDN or redistribute the fonts for best results.

**Comment by zerocrates** [comment]
Omeka S already redistributes Font Awesome, it does not require users to have it installed.

The specific problem of missing icons on the navigation edit interface has been previously reported and Omeka S 1.1.1, just released today, fixes that issue. Are you seeing missing icons anywhere else, or other icon problems? We haven't had any other reports besides the one just mentioned.

**Comment by zerocrates** [comment]
You mentioned the search interface also, which could just be a problem with needing to update the theme you're using. [All our themes](http://omeka.org/s/themes/) got 1.1.0 releases that update their usage of icons to align with Omeka S 1.1.0's move to Font Awesome 5.

**Comment by crism** [comment]
Thanks, @zerocrates. That does seem to fix the problem!
