### ISSUE TITLE
Add links to documentation, forums in admin footer?

### ISSUE THREAD

**Issue by mebrett** [omeka/omeka-s#1239]
In Classic, we have the links to the forums and docs in the footer of every page, but we don't do this in S. Adding those in would help us meet [WCAG 3.3.5 "Help"](https://www.w3.org/TR/UNDERSTANDING-WCAG20/minimize-error-context-help.html)

**Comment by kimisgold** [comment]
@zerocrates @mebrett How are the footer links looking? Is there anything else that needs to be done to close this?

**Comment by zerocrates** [comment]
lgtm
