### ISSUE TITLE
"Search Items" is a little confusing with regard to simple search on the left

### ISSUE THREAD

**Issue by kalbers** [omeka/omeka-s#124]
I think in part because of placement, in part because of terms. Maybe changing to Advanced Search would help?

**Comment by jimsafley** [comment]
I think that, instead of "Search..." links on the right, we somehow integrate advanced search links within the simple search control. These links should not be hidden, though, so I'm not sure the best way to design it.

**Comment by kimisgold** [comment]
I'm also drafting a version that incorporates @jimsafley's suggestion, but until then, can everyone take a look at the current presentation of the advanced searches?

(@kalbers, @zerocrates, @patrickmj)

**Comment by jimsafley** [comment]
I like the placement of the advanced search links, but I'd prefer that they appear like a normal link rather than a button since they aren't actions. I also question whether we need to specify the resource (item, item set, media) in the link text since the links are squarely within context.

**Comment by kalbers** [comment]
I second the notion of changing it to a text link rather than a button. Otherwise I like the placement.

Couple of small things that are probably on your radar, but in case they aren't:
1) The link sits on the same line as the pagination, which makes sense. However, if there is no pagination (eg a results page with one result), then it looks awkward, as the results header (eg; Property contains value(s) "test") adds a line, and there is a large empty space below it, with the Advanced Search to the right. Maybe we need a pagination placeholder, even when there's only one page?
2) If an advanced search produces no results, the link does not appear on the results page.

**Comment by zerocrates** [comment]
There's no reason we can't have a "page 1 of 1" control if we want to do that

**Comment by patrickmj** [comment]
I agree about the text link thing. Wondering about the match-up of the wording between the link and the page. Struck me as odd that a link "Advanced Item Search" went to a page "Item Search". If, as Jim suggests, we get rid of the resource name, those would still be not exactly the same, since on the advanced search page the resource name should still be there. Either way, 'Advanced' on the advanced search page makes more sense to me.

**Comment by kalbers** [comment]
Page 1 of 1 was along the lines of what I was thinking. Probably makes the most sense.

**Comment by kimisgold** [comment]
I think I applied most of the suggestions. If there's anything I missed, let me know.

**Comment by kalbers** [comment]
I think I mostly like this. My only suggestion is I did like the link on the right side, across from the pagination. Right now it's positioned above the pagination on mine, which, especially with the results header, feels a little busy.

**Comment by kimisgold** [comment]
Try hard refreshing your css? On my installation it's still to the right.
