### ISSUE TITLE
Missing icons for mapping/refresh in solr and search modules

### ISSUE THREAD

**Issue by pprw** [omeka/omeka-s#1247]
After updating Omeka S to 1.1.1, I don't have a icon for "mapping" in the solr module. 

![image](https://user-images.githubusercontent.com/5262986/39297727-8af6c596-4944-11e8-896f-175d84c7f091.png)

This is also the case for the indexes refresh in the search module. 

Both icons are missing (but I can click in the empty and it works).

**Comment by pols12** [comment]
It’s due to Font Awesome update. I’ve noticed the owner of those modules through pull request.

**Comment by Daniel-KM** [comment]
Yes, it is integrated in my upgrade-fork that is not yet merged upstream.
