### ISSUE TITLE
JSON-LD validation errors

### ISSUE THREAD

**Issue by Falteri** [omeka/omeka-s#1249]
Seems to be some validation errors in JSON-LD data exoposed by item show.
Please check: https://search.google.com/structured-data/testing-tool?hl=en#url=http%3A%2F%2Fengb.bmlonline.it%2Fs%2Fcasa-boccaccio%2Fitem%2F370
Most of the errors are related with @type declarations and values but i get also an unspecified "There was an invalid type in your JSON-LD." error related with @context.

**Comment by akuckartz** [comment]
The tool reports a "URL was not found" error.

**Comment by Falteri** [comment]
You are right: the structured-data testing tool provided by google doesn't work anymore. I do not why ...
I'll try later or with another similar validator and I'll give you a feedback asap. Thanks!

**Comment by zerocrates** [comment]
I don't have any issue getting the tool to work, but at least most of the errors seem spurious... Google's tool is understandably very focused on showing you what Google is looking for, and it doesn't understand or care about Omeka's types or even the Dublin Core ones (it's looking for schema.org stuff, mostly).

**Comment by Falteri** [comment]
Hi John,
yes that is what I also think, but I thought it was good to share with someone more skilled than me.
I think that all “semantic” possibile issues need to be addressed soon because of the “semantic mission” of Omeka that is the most relevant characteristic of this platform.
Thank for replying!

Inviato da iPhone

**Comment by Daniel-KM** [comment]
When we copy-paste a json-ld item from the `/api/items/#` on https://json-ld.org/playground/, it doesn't validate: 

```
jsonld.InvalidUrl: Dereferencing a URL did not result in a valid JSON-LD object. Possible causes are an inaccessible URL perhaps due to a same-origin policy (ensure the server uses CORS if you are using client-side JavaScript), too many redirects, a non-JSON response, or more than one HTTP Link Header was provided for a remote context.
```
Of course, all the urls are accessibles and there is no cors issue.

**Comment by zerocrates** [comment]
You could still get that error (based on CORS) if the playground can't load the `@context`, which would be a URL even if the content is pasted.

**Comment by Daniel-KM** [comment]
Ok, it should be related to my server. Nevertheless, when I try the sandbox, there are issue too : http://tinyurl.com/yaxvupzy.
```
jsonld.SyntaxError: Invalid JSON-LD syntax; a term definition must not contain vocabulary_id
```

**Comment by zerocrates** [comment]
Hmm, that's interesting, that's definitely a newer restriction on their end.

**Comment by zerocrates** [comment]
That turns out to be a SHOULD NOT in the spec, so its somewhat dubious that they're now considering it a syntax error when they didn't before... but that data also isn't really crucial for us to include there.
