### ISSUE TITLE
Changing Item or Item set template

### ISSUE THREAD

**Issue by Falteri** [omeka/omeka-s#1256]
Changing resource template while creating or modifying an item or a set do not change the properties displayed but only their order.

**Comment by Daniel-KM** [comment]
Yes, the resource template is only a base for the user, but the user can always add other properties.

**Comment by jimsafley** [comment]
If I understand you correctly, this behavior is by design. We don't currently plan on addressing this. Feel free to reopen and elaborate should you want further discussion.
