### ISSUE TITLE
Search results different with/without spaces

### ISSUE THREAD

**Issue by Daniel-KM** [omeka/omeka-s#1258]
Search results are not the same for "keyword" and "keyword " : in the second case, a resource with the word "keyword," is not found). 

This is true technically, but false ergonomically, because users are used to google etc. where the results are the same, except when the double quotes are added. 

So the values should be trimmed when they come from the web front end, and eventually from the api front-end.

**Comment by zerocrates** [comment]
I don't see a problem with trimming the query.

If we trim it in the API it should affect the API and the frontend search simultaneously.

**Comment by Daniel-KM** [comment]
So how to manage the case where the user wants a space?

**Comment by zerocrates** [comment]
I guess that's a possible issue... Classic has always trimmed and I don't think it's come up so I'm tempted to say that capability wouldn't be missed.
