### ISSUE TITLE
Non-text UI for browse preview query

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#1264]
Ideally this looks something like the search in a sidebar (with sorting controls tacked on possibly...)

Big issue is we don't have a sidebar-friendly search UI at the moment.

**Comment by hxsllc** [comment]
Do you mean a primarily image-based browse/preview results?

**Comment by zerocrates** [comment]
This is an issue about the "Query" input in the Browse Preview block which currently asks you to input the text of a query string, and possibly replacing that with an interface where you just select the search/browse filters you want like in the advanced search.

**Comment by sharonmleon** [comment]
@jimsafley is this closed by the merge of your query builder?

**Comment by jimsafley** [comment]
Feature added in c5ae9b286b45a3629fa01e8c184955e1a402ac8f
