### ISSUE TITLE
Prev/Next text should not be displayed when the page is unique

### ISSUE THREAD

**Issue by pols12** [omeka/omeka-s#1266]
See [“Page navigation” on the forum](https://forum.omeka.org/t/page-navigation/6186): when there is a unique page on a site, a end user does not understand what “Prev | Next” text means.

These “disabled links” should probably be hidden in this case.

**Comment by kimisgold** [comment]
Here are the expected behaviors:

* Site page pagination is on by default. However, the pagination links will only appear if a "previous page" or "next page" exist—there are no longer inactive placeholders.
* Users can toggle the site page pagination off entirely. It is now a checkbox in site settings.

@mebrett Can you take a look at this?

**Comment by mebrett** [comment]
Functionality works as expected on all themes except The Daily - even with "show page pagination" unchecked, the Prev/Next still displays.

**Comment by kimisgold** [comment]
@mebrett Did you pull omeka s core as well?

**Comment by mebrett** [comment]
I did - on branch develop, everything is up to date
