### ISSUE TITLE
Upgrade zend-session to 2.8.5 in next release?

### ISSUE THREAD

**Issue by ManOnDaMoon** [omeka/omeka-s#1269]
Hi

Recent Omeka S releases were both packaged with zendframework/zend-session v2.8.3

There are some bug fixes that were introduced recently to zend-session, relative to compatibility with php 7.2 (e.g. https://github.com/zendframework/zend-session/pull/107).
Would you be able to upgrade the packaged zend-session to v2.8.5 in future Omeka S releases?

Thanks and have a nice day

Laurent

**Comment by zerocrates** [comment]
Updating that is no problem (and we would normally do so as a matter of course in a "minor" release).

Are you actually experiencing the ini_set problem mentioned in that issue? That should only really occur when changes are being made _after_ the session has started, which I don't think Omeka should be doing. I've been running Omeka S on PHP 7.2 myself and haven't encountered any session issues...

**Comment by ManOnDaMoon** [comment]
Thanks for the feedback. No, I'm experiencing issues only within a module I'm developing.
More precisely, using `SessionManager::rememberMe()` is buggy with zend-session v2.8.3 and php 7.2.
