### ISSUE TITLE
Add the ability to set different "results per page" setting according to the page

### ISSUE THREAD

**Issue by pprw** [omeka/omeka-s#1270]
There is only one global setting for "results per page".

This is a request to add the ability to change this parameter only for one page or item-set.

I have a collection of names for which I want 200 results per page and another collection of articles for which I want 50 results per page. I can display the names in a very compact way, not the articles.

**Comment by jimsafley** [comment]
We don't currently plan on addressing this issue. This feels like something better suited for a custom module. Feel free to reopen and elaborate should you want further discussion.
