### ISSUE TITLE
Pagination of admin/site/s/my-site/users

### ISSUE THREAD

**Issue by Daniel-KM** [omeka/omeka-s#1288]
When there are too many users for a site, the page `admin/site/s/my-site/users` doesn't display, so a pagination is needed. The same for the `api/sites`, where a solution like for the item sets of items can be used (a link to the separated and paginated list of users).

**Comment by jimsafley** [comment]
We don't currently plan on addressing this issue. Feel free to reopen and elaborate on how many users it takes to reproduce this, etc. should you want further discussion.
