### ISSUE TITLE
Terminology of show user bar

### ISSUE THREAD

**Issue by mebrett** [omeka/omeka-s#1289]
On Site Settings, the three options for "show user bar on public views" are "never," "always" and "when identified."  

I'm guessing that "when identified" means "when logged in" or "for logged in users only" but it doesn't parse well in English. Is there another phrasing we could use which would translate well and still be parsed by our (many) English-speaking users of non-technical backgrounds?

**Comment by zerocrates** [comment]
@kimisgold opinion?

We wanted to hold this so as to not have to redo the translations... if we're going to change, now would be a good time to do it.

**Comment by kimisgold** [comment]
I agree, "when identified" is awkward. Maybe "after login"? I'm also okay with "when logged in".

**Comment by zerocrates** [comment]
Don't like "after login." "When logged in" is fine.
