### ISSUE TITLE
Site pages and languages

### ISSUE THREAD

**Issue by Daniel-KM** [omeka/omeka-s#1293]
About multilanguage, I need to add a language to pages, so maybe a new field should be added in table site_page or site_page_block, but I don't know yet which one is better. Do you have plan about this point and about the global pages (like the about page)?

This issue may be related to the multilanguage site issue (https://github.com/omeka/omeka-s/issues/898), and there is no clear way to manage such a site with Omeka S, and there may be multiple cases (the two main are one site by language and multiple languages by site).

**Comment by Daniel-KM** [comment]
On this important question, I wonder if a language setting can be attached to two things: 
- the site : a simple site setting to set the default language of a site, for anonymous users, so it will be possible to resolve many questions of the forum (https://forum.omeka.org/t/bilingual-content-internationalisation/2116, https://forum.omeka.org/t/internationalized-omeka-s/3154/22, etc. and here (#898), and in, particular to make each site multilingual, not only a site by language.
- the page: a new column in site_page, so the pages will have a language, so it will be possible to make a multilanguage module like in Omeka Classic, either at site level in the case of a multilanguage site, or in the whole in the case of a site by language).

I can push a request on  that, but I need a confirmation that it is a good structural choice.

**Comment by zerocrates** [comment]
We did some discussion of this topic in the the attached PR, closing by reference to that.
