### ISSUE TITLE
Applying resource templates to advanced search

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#1296]
There's a sliding scale here where this feature could include some or all of:

- Simple filtering on the resource template
- Applying the resource template settings to change labels of properties
- Applying the resource template settings to change which properties are available to be chosen
- Applying the resource template settings to change the search input (i.e., use the same controlled vocab or auto-suggester that is used for input to drive search input)

There's an additional dimension of whether this should be site or user-controlled, if exposed on the public side: having a site setting to select a template to apply to the search could be a powerful and relatively simple method to allow users to customize the search, particularly if the site is basically composed of items using just one template. Of course, for sites using a diverse mix of templates this wouldn't work so well, and having an option for a user to choose the template for searching (or multiple different search pages with different applied templates?) would be more appropriate.

**Comment by jimsafley** [comment]
WIP in [template-search branch](https://github.com/omeka/omeka-s/tree/template-search)

**Comment by jimsafley** [comment]
Some tangential questions on advanced search as I work on this issue:
- Should we convert the resource class filter to accept more than one class for a union of results, like item sets and resource templates? (E.g. `?resource_class_id=[1]&resource_class_id=[2]`)
- Should we convert the resource class and resource template search interfaces to allow multiple selections, like item sets?
- User names and emails are visible on the public item set search interface. They provide disambiguation of identically named item sets, but doesn't it seem undesirable to expose user data publicly?

**Comment by jimsafley** [comment]
Fixed in https://github.com/omeka/omeka-s/pull/1303, 7b5b79fa6f174f51caae395d1093d5b9285a6936, be9f76580dd34b5dcc2cabfd02f450e7dc87d28b, 4d044265cf9b513b880ef45cf3868b621c9d0e10, and 709957faf1cc1692c5c9645f553c133a5a3d6f1a
