### ISSUE TITLE
Add Resource label overflow shows when Mapping active

### ISSUE THREAD

**Issue by mebrett** [omeka/omeka-s#1300]
On the Item edit view, the very top of "Add value" for properties shows up - but only if Mapping is active (develop branch of everything).

Normal view:
![screen shot 2018-09-07 at 10 50 50 am](https://user-images.githubusercontent.com/2314070/45226046-e95a2f00-b28b-11e8-87e6-42a913867966.png)

When Mapping activated:
![screen shot 2018-09-07 at 10 40 43 am](https://user-images.githubusercontent.com/2314070/45226065-f2e39700-b28b-11e8-9362-9eb59fb9a617.png)

And if I use the inspector to deselect `.add-values label` overflow-hidden
![screen shot 2018-09-07 at 10 40 50 am](https://user-images.githubusercontent.com/2314070/45226114-11e22900-b28c-11e8-8e17-9e34e1a62b3f.png)

**Comment by jimsafley** [comment]
You'll notice that the font is different in the "normal" and "Mapping activated" screenshots, which probably accounts for the overflow bug. I suspect that Mapping is loading scripts or tiles that somehow interfere with Omeka's font loading.

**Comment by jimsafley** [comment]
Fixed in https://github.com/omeka-s-modules/Mapping/commit/509dd7b38ab50a1191ec656f89879c666a98f081
