### ISSUE TITLE
Documentation translation

### ISSUE THREAD

**Issue by Daniel-KM** [omeka/omeka-s#1302]
There are now direct links from the admin interface of Omeka into the help. This help is very complete and useful. 

Nevertheless, there is an issue: the help is in English, and it doesn't help non-English speaking end users. And in some months, nobody will speak English in Europe. In particular, I need to translate the documentation into French. 

For example, the help for the browse preview is https://omeka.org/s/docs/user-manual/sites/site_pages/#browse-preview, but what if the user has a French user interface and wants help in French, of course. 

In fact, there are two questions: how to manage such a link inside Omeka? And where to store it on the web? In Omeka.org on a new separate project on https://readthedocs.io? 

In fact, the answer may depend on the solution that will be adopted to make Omeka a fully multilanguage tool (see #1293, some architectural changes or new columns in some tables are required for that).

**Comment by zerocrates** [comment]
Hmm, an interesting question.

I could see us providing this capability in configuration (like a list of `lang-code => docs-url` pairings we'd look up). I've also seen this kind of thing done as a "translation" of the URL just using the regular translation system... I'm kind of wary of pushing stuff that's not really translation that way, though.

As for the translation itself, the Omeka documentation is just being built by us ourselves, with the source available at https://github.com/omeka/omeka-s-enduser . We're using mkdocs, which I'm not sure has internationalization support itself, though we haven't investigated that much. Certainly just a complete branch/fork of the documentation into another language would be possible. Discussion about what to do on that end of things might make more sense on the omeka-s-enduser repository than here.

**Comment by jimsafley** [comment]
See [omeka-s-enduser#98](https://github.com/omeka/omeka-s-enduser/pull/98)
