### ISSUE TITLE
Setting target for navigation links with custom URL

### ISSUE THREAD

**Issue by Boca13** [omeka/omeka-s#1309]
Hi all,
I think it would be useful to have the option to set the target for navigation links to external websites. This way we could make these links go to a new tab.

What do you think about this **feature**?

**Comment by zerocrates** [comment]
So you're thinking of being able to set `target="_blank"` basically?

**Comment by Boca13** [comment]
Exactly

**Comment by jimsafley** [comment]
We don't currently plan on addressing this issue. Feel free to reopen and elaborate should you want further discussion.
