### ISSUE TITLE
Testing: Private Values

### ISSUE THREAD

**Issue by jimsafley** [omeka/omeka-s#1311]
The [private-values](https://github.com/omeka/omeka-s/tree/private-values) branch adds configurable visibility to values. Values are set as public by default, but now users can set them as private. A private value is an individual value that can only be seen by the owner of the parent resource or users with the "view-all" privilege (global admin, site admin, editor, and reviewer).

Considerable testing will need to be done before we can merge the branch into develop.

Log in as a global admin, site admin, editor, or author. When adding or editing a resource (item, item set, media), you should see a new visibility icon next to every value. You should be able to toggle between public and private by clicking on this icon. After saving the values, you should be able to see every value you entered, public and private, and values you marked as private should have a private icon next to them.

Log in as a researcher or another author. When viewing the same resource you should be able to see all public values, but you shouldn't be able to see any private values. These same rules should apply for anonymous users viewing the resource on a public site.

Another aspect to this feature is the addition of default value visibility, set via a resource template.

Log in as global admin, site admin, editor, or author. When adding or editing a resource template you should see a new "Private" checkbox in the edit property sidebar. You should be able to set the default visibility of the property's values to private by checking this checkbox and saving the changes.

As the same user, add or edit a resource and set the template that you edited above. Every new value that was set as private by default should show a private icon, and, as usual, values that are saved as private should only be visible to users with permission.

**Comment by jimsafley** [comment]
> while on this branch, the batch edit/delete options were not visible for items. I'm assuming that's a quirk of the branch.

The batch edit/delete options should only render when the current user has the `batch_update` privilege, which only global and site administrators have. What is strange is that there's no check against `batch_update` when rendering the batch checkboxes, which render simply when the current user has `update` or `delete` privileges on the respective resource. This is a bug, but not related to this branch.

> Will there be a "batch set values" functionality available?

Yes, that's a good idea. I'll look into it.

**Comment by mebrett** [comment]
> The batch edit/delete options should only render when the current user has the batch_update privilege

Thank you for the reminder to go through and add this ability in to the description of user roles.

**Comment by mebrett** [comment]
Is there anywhere I should be looking for this other than the admin browse and view? Private titles come up as [untitled] and private properties other than title just don't display at all. 

Global admin: 
<img width="460" alt="screen shot 2018-10-05 at 2 19 00 pm" src="https://user-images.githubusercontent.com/2314070/46552748-ab135800-c8a9-11e8-968e-59313ac024e4.png">

researcher user
<img width="387" alt="screen shot 2018-10-05 at 2 19 08 pm" src="https://user-images.githubusercontent.com/2314070/46552753-afd80c00-c8a9-11e8-8f7b-481e18a223fe.png">

**Comment by jimsafley** [comment]
I think you covered the obvious places, and I can't think of any non-obvious places. Omeka funnels all values through one method, and that method definitely filters out private values, so I think it's safe to assume everything is covered.
