### ISSUE TITLE
Metadata fields not disappearing after template change in item creation

### ISSUE THREAD

**Issue by hydrosIII** [omeka/omeka-s#1312]
Hi, I have an issue when creating a new item after selecting the  template in omeka-s.
The template fields are appearing but at the end of the template preselected categories, they appear new random dublin core terms.  He have a team of historians and this have happened twice. We currently are investigating the issue. Here are some screenshoots. 

![photo_2018-09-28_15-32-16](https://user-images.githubusercontent.com/7807363/46232633-59ad1b00-c335-11e8-98a3-e3db9fd6c0ec.jpg)
![photo_2018-09-28_15-32-15](https://user-images.githubusercontent.com/7807363/46232635-5a45b180-c335-11e8-898e-ef02593adf88.jpg)
![photo_2018-09-28_15-32-14](https://user-images.githubusercontent.com/7807363/46232636-5a45b180-c335-11e8-9dda-7faa6d412adb.jpg)
![photo_2018-09-28_15-31-51](https://user-images.githubusercontent.com/7807363/46232638-5a45b180-c335-11e8-9db4-6f9525617859.jpg)

In the screenshot you can see the extra generated categories.

Server:  Omeka-S v. 1.2.0, php  7.0.30-0+deb9u1, debian 9

  

 Client: Firefox Versión 62.0.2 (64-bit) Mozilla Firefox for Acer, Windows 10.

**Comment by zerocrates** [comment]
And those properties aren't part of the template you're selecting? We can't really tell that from these photos.

**Comment by hydrosIII** [comment]
No, they are not.

**Comment by zerocrates** [comment]
So, which ones are in your template and which are not?

Also, you say this happened twice, is it reliable or does it only happen sometimes?

**Comment by hydrosIII** [comment]
It only happens sometime. my template has:
 
bibo:numPages | dcterms:created | dcterms:available | dcterms:replaces | bibo:locator | dcterms:medium | dcterms:type | dcterms:title | dcterms:description | bibo:authorList | bibo:editorList | dcterms:creator , dcterms:identifier,bibo:interviewee,dcterms:spatial


It happened three times, now, today happened again.

**Comment by zerocrates** [comment]
Hmmmm....

Do you have any other templates that _do_ use those "extra" properties you showed.

**Comment by hydrosIII** [comment]
No.

**Comment by hydrosIII** [comment]
Hello I double checked, i had a template called "Base resource" that defined the above values. The error was produced when someone accidentally selected that template, and then changed over to the template we are using. Lest call it template A. So the error only ocurred when you changed from "base template" to template A. The solution was to delete "base template" to avoid confusion. I am not sure if this is a bug or expected behaviour. It may not be a bug.

**Comment by zerocrates** [comment]
It's expected: we don't have the templates remove fields.

**Comment by hydrosIII** [comment]
So it is not a bug?

**Comment by zerocrates** [comment]
Yeah.

It's something that could be changed, but I wouldn't call it a bug.
