### ISSUE TITLE
Attaching media to an Item set

### ISSUE THREAD

**Issue by stephenwf** [omeka/omeka-s#1317]
It would be useful to be able to attach media to Item sets. Item sets do have a method `primaryMedia` which will go through its own items. It would be really useful to be able to attach new media on item sets, to enrich pages on the website representing the item sets.

Our current relevant use-case: IIIF resources, manifests as ItemSets. We want to be able to add editorial content associated with the manifest and display it on the page along side the manifest

**Comment by zerocrates** [comment]
Are you looking to directly attach media (i.e., a media that would belong directly to the set and only to the set), or would simply being able to select the "correct" media from among those belonging to the items? It sounds like you want the former, but I think we'd be more likely to do the latter.

Items as the sole parents of media is an assumption baked in at several places and it would be a fairly significant change.

We're also currently looking at and about to land an ability to use the "asset" system to provide custom thumbnails, ignoring the primary media, but that doesn't sound like it squarely addresses what you're talking about either.

**Comment by jimsafley** [comment]
We don't currently plan on addressing this issue. You now have the ability to add a custom thumbnail to an item set. Feel free to reopen and elaborate should you want further discussion.
