### ISSUE TITLE
Mails of the users being shown when using advanced search.

### ISSUE THREAD

**Issue by hydrosIII** [omeka/omeka-s#1320]
Hi. In the main page, if you use the option for the advanced search, the mails of the users are shown. This is a security issue. Since the emails, should be private.

**Comment by zerocrates** [comment]
Do you mean the emails that show in the item set selector? We have some changes pending release that will provide the option to not show the emails there (and remove them by default from the public search interface).

**Comment by hydrosIII** [comment]
Yes i mean the emails in the item set selector. Thank you, looking forward to see the changes.
