### ISSUE TITLE
Site user table has odd spacing

### ISSUE THREAD

**Issue by mebrett** [omeka/omeka-s#1323]
First, there's a very large gap between the Role dropdown option and the delete button. This becomes very obvious when the window is narrow because the Role dropdown overlaps the user emails with a fair amount of empty space on the other side.

![siteuserissue](https://user-images.githubusercontent.com/2314070/47106470-9c676200-d214-11e8-8b8d-0ae4c86c4e4a.png)

**Comment by sharonmleon** [comment]
@mebrett @kimisgold Is this still a problem?
