### ISSUE TITLE
Use a job when a big media is uploaded manually in order to avoid a fail in the creation of the thumbnails

### ISSUE THREAD

**Issue by Daniel-KM** [omeka/omeka-s#1325]
When an item is created manually and when there are many media or a heavy media, the creation of the thumbnails may fail. It would be interesting to have an internal check of the total size of the files (eventually with a param for the max size processable in the front-end), and in the case that the size is bigger than the limit, fork the process into a job automatically, and warn the user to wait some time.

**Comment by jimsafley** [comment]
We don't currently plan on addressing this issue. Feel free to reopen and elaborate should you want further discussion.
