### ISSUE TITLE
Possibility to import the ontology Time

### ISSUE THREAD

**Issue by Daniel-KM** [omeka/omeka-s#1336]
For one project, we need the time ontology (https://www.w3.org/TR/owl-time/), with the recommended prefix `time`. But it is forbidden by Omeka : https://github.com/omeka/omeka-s/blob/develop/application/src/Api/Adapter/VocabularyAdapter.php#L23 Is this limit still required? If yes, is it possible to keep the restriction, except for this ontology?

**Comment by zerocrates** [comment]
So, the reason it's reserved is that it's used internally and therefore there's already a "time" entry in the JSON-LD context.

**Comment by Daniel-KM** [comment]
So how can I use a property such `time:hasDuration` to describe a resource? Just another prefix to import the vocabulary? So two prefixes for the same ontology?

**Comment by zerocrates** [comment]
Fixed in #1340

**Comment by Daniel-KM** [comment]
Thanks!
