### ISSUE TITLE
Present top bar actions as icons with hover labels

### ISSUE THREAD

**Issue by kimisgold** [omeka/omeka-s#134]
The edit views need a delete option in the top bar, but that bar is going to get crowded with actions soon, especially if we ever include the resource title up there. To save space, the top bar could utilize icons with hover labels so that the meaning is more immediately clear.

**Comment by kimisgold** [comment]
I tried this and disliked it immediately. For the time being, I've found space for the visibility check and delete actions outside of the top bar in a389cfdb16f7737aeaffc23167ffac06a0696faa. Neither actions need to be constantly present, so they follow the scroll of the page above the section tabs.

(Pinging @jimsafley, @patrickmj, kalbers for some eyes on it.)

**Comment by jimsafley** [comment]
I'm not surprised that the controls looked out of place in the top bar. I think there's potential where you placed them. What do you think about putting them in the sidebar, above the property selector? There's some padding there.

**Comment by kimisgold** [comment]
My concern about putting them there in the sidebar is that the sidebar content changes from tab to tab. They're not strongly associated with the content of any section, and finding some way to fix the visibility and delete actions across all the tabs in the sidebar seems cumbersome to apply.

**Comment by jimsafley** [comment]
That's a good point. My idea is not a good one.

**Comment by kimisgold** [comment]
I just pushed a version where the visibility checkbox sits in the top bar next to the save button. I removed the delete action again to condense page actions further—we had talked about how users can delete items directly from the browse view without going the extra step into edit view, so it might be unnecessary in the edit view.

I'm still a little worried about future scenarios where we might want other actions in the top bar and how much space that would require, but we can cross that bridge when we come to it.

**Comment by patrickmj** [comment]
Sorry I can't look at it...checking out that hash creates many errors for me

**Comment by patrickmj** [comment]
I don't think deleting from the browse page will be sufficient. There's too little information there for people to really know whether they want to delete the resource. They'll want to double-check exactly what they're deleting by either looking at the edit or show page, and deleting from the edit page makes a lot more sense to me.

**Comment by jimsafley** [comment]
I agree with @patrickmj. Another concern is that resource edit pages may be directly linked from somewhere else, so, without a delete control there, there would be no way to delete it.

**Comment by kimisgold** [comment]
I've added a working delete button to the item/edit view. Previously, @zerocrates had expressed concern that the delete and save buttons were too similar and close together, but the confirmation sidebar should provide a good in-between step to prevent accidental item deletion. I've also shortened the labels to minimize the occupied horizontal space.

**Comment by kimisgold** [comment]
Fixed in c6c4c0f6d68d1709ae6fcc7da8bc147dd3864252.
