### ISSUE TITLE
Testing: Set a custom thumbnail for resources

### ISSUE THREAD

**Issue by jimsafley** [omeka/omeka-s#1341]
We added a new "Thumbnail" tab to resource add/edit forms (item set, item, and media). In these tabs, the user should be able to select an asset and save the form to change the primary media of the resource. Once changed, every thumbnail of that resource should be the selected asset, e.g. on browse pages. The user should also be able to clear the thumbnail and select another one.

Uploading new assets in the asset sidebar should now be available to authors, reviewers, and editors (it was restricted to admin roles before). User should be able to filter assets by owner.

**Comment by mebrett** [comment]
What's the use case for this?

**Comment by sharonmleon** [comment]
If you wanted to do an artistic graphic for a resource that isn't technically primary that the item metadata describes... So, an icon, instead of page image.

**Comment by jimsafley** [comment]
Also, if the primary media for an item is a video or a multi-page file (e.g. PDF, TIFF) and the auto-generated thumbnail is undesired, the user can capture the desired thumbnail and set it here.

**Comment by mebrett** [comment]
"By default, the primary media of this resource will be its thumbnail"
to 
"By default, the top media on the media tab serves as the thumbnail. You may use an asset to serve as a thumbnail for the item instead; assets do not display as media on the items." (or something along those lines)
