### ISSUE TITLE
Apostrophe in metadata

### ISSUE THREAD

**Issue by pprw** [omeka/omeka-s#1342]
Omeka S allows to paste text containing `&rsquo;` symbol (`’`) into metadata. 

But using `’` in a metadata will break the search (both in Omeka S built in search engine and in Solr)

`Il ne s’est passé` will never be found.
`Il ne s'est passé` will be found.

Omeka S should either prevent the paste of `’`symbol or support the search for word or sentence containing `’`.  Since `’` `(&rsquo;)` is the correct way (at least in French) to display apostrophes in html, I think Omeka S should support it.

**Comment by zerocrates** [comment]
You mean if you use the "fancy" or "smart" apostrophe you can never get it back as a search result, even if you use the same apostrophe in your search?

Or do you mean that using the "dumb" or "typewriter" apostrophe in the search doesn't return the "fancy"-using item?

**Comment by pprw** [comment]
> You mean if you use the "fancy" or "smart" apostrophe you can never get it back as a search result, even if you use the same apostrophe in your search?
> 
> Or do you mean that using the "dumb" or "typewriter" apostrophe in the search doesn't return the "fancy"-using item?

Ok it is the second one. I have the expected result if I paste a "smart" apostrophe. I don't have result at all if I use "dumb" apostrophe which is logical. So it is not really a bug. But it is still a problem because we can only use "dumb" apostrophe in browsers (except when pasting). If someone feeds an Omeka S website with "smart" apostrophe content, the search will not work.

Could something be done about this in Omeka S development ?

If nothing can be done to support "smart" apostrophe, maybe the paste of data in metadata should convert "smart" apostrophes to "dumb" ones. But it will not cover the CSV/API import case.

**Comment by Daniel-KM** [comment]
You should never replace a smart by a dumb, because a lot of librarians respect the typographic rules. This is a mysql search engine issue. Perhaps to remove the punctuation before the search, but it require some work on the core.

**Comment by pprw** [comment]
I didn't see a fix for this bug in 1.3.0 release.

I would prefer to not replace my smart apostrophes by dumb ones, as Daniel-KM recommends.

Can you think of possible workarounds to have a working search when using smart apostrophes in metadata (and dumb one in queries)?

**Comment by zerocrates** [comment]
No changes related to this were made in the 1.3.0 release.

I don't think you really have a good option to keep them in the data and not use them in the search... at least with the current built-in search. We're looking at providing something akin to Classic's "sitewide" search which would mean having a separate search-specific index, which could potentially do things like replacing apostrophes, or simply stripping them from searches.

The Search/Solr modules that currently exist could also provide that kind of solution, since it already operates on this kind of "separate index" model... I'm not familiar enough with Solr to tell you how exactly you'd go about doing it, though.

**Comment by Daniel-KM** [comment]
For Solr, you have to set the default index into French (or English), so the punctuation will be managed automatically. By default, the index has no language. Just add `type="text_fr"` in the right place of the file "managed-schema" or the equivalent via the solr admin board:
```
    <dynamicField name="*_t" type="text_general" type="text_fr" indexed="true" stored="true"/>
```
It may be added in some other places according to your config.

I have some new commits that manage the language directly from the values, but I won't push them as long it still require to config Solr manually.

**Comment by jimsafley** [comment]
We don't currently plan on addressing this issue. Feel free to reopen and elaborate should you want further discussion.
