### ISSUE TITLE
Testing: Import vocabulary by URL

### ISSUE THREAD

**Issue by jimsafley** [omeka/omeka-s#1343]
In the [import-vocab-by-url branch](https://github.com/omeka/omeka-s/tree/import-vocab-by-url) we've added an option in the vocabulary import form to import using a URL instead of a file. Try importing these vocabularies using their URL:

- URL: `http://www.w3.org/2006/time`
- prefix: `time`
- namespace URI: `http://www.w3.org/2006/time#`
- label: `OWL-Time ontology`

BBC ontology
- URL: `https://www.bbc.co.uk/ontologies/bbc/1.10.ttl`
- prefix: `bbc`
- namespace URI: `http://www.bbc.co.uk/ontologies/bbc/`
- label: `BBC ontology`

**Comment by mebrett** [comment]
The only error I got was that the prefix "time" is reserved so I imported it as owltime.

**Comment by zerocrates** [comment]
This is just an issue of branches...

I merged it into develop, the reservation should be gone there.

**Comment by mebrett** [comment]
Error no longer shows up now that we're on develop.
