### ISSUE TITLE
Testing: media ingest

### ISSUE THREAD

**Issue by jimsafley** [omeka/omeka-s#1352]
The `media-ingest-file` branch introduces some underlying changes to how we ingest media files. These changes should be completely invisible to users but we should still test to see if each media ingester works as expected. Add every type of media to an item: Upload, URL, HTML, IIIF Image, oEmbed, and YouTube. Everything should work as before, no changes whatsoever to what the user sees.

**Comment by mebrett** [comment]
Does anyone have a handy IIIF image for testing? Or recommendations for a place to look?

**Comment by jimsafley** [comment]
https://media.nga.gov/iiif/public/objects/1/0/6/3/8/2/106382-primary-0-nativeres.ptif/info.json

**Comment by mebrett** [comment]
Everything worked as it normally does. I was able to do Upload, URL, HTML, IIIF Image, oEmbed, and YouTube media.
