### ISSUE TITLE
Thumbnail generation error when using graphicsmagick.org

### ISSUE THREAD

**Issue by symac** [omeka/omeka-s#1358]
I ran into an issue, which I'm not sure is related to omeka-s or to the way my system is configured. I am using Ubuntu 18.04, and the convert tool is provided by [GraphicsMagick](http://www.graphicsmagick.org/) rather than imagemagick. I am not sure if it's because of some local install I have done in the past or the default configuration on Ubuntu 18.04.

Anyway, with this configuration, the ```-alpha remove``` option used there:
https://github.com/omeka/omeka-s/blob/afe5d9516e62dd2323b921e70441fdc7064d05e6/application/src/File/Thumbnailer/ImageMagick.php#L52-L59

will generate an error and no thumbnail is generated. It seems that, even if IM & GM are almost identical in term of parameters, this one is not supported on GM's side. I don't know what is the best solution to deal with that. I will have IM on my server so I don't worry much about it and will just remove this option during my tests so if you think it's not really an issue, feel free to close this issue, I just wanted to report it.

**Comment by Daniel-KM** [comment]
The good option is probably to create a new thumbnailer, not to change the working one.

**Comment by symac** [comment]
Thanks @Daniel-KM for your valuable feedback, I followed your advice to create a new Thumbnailer, based on ImageMagick's one → PR #1465

**Comment by jimsafley** [comment]
We don't currently plan on addressing this issue. Feel free to reopen and elaborate should you want further discussion.
