### ISSUE TITLE
site_pages can't be paginated

### ISSUE THREAD

**Issue by goetzk** [omeka/omeka-s#1365]
Hi,
I've spent several hours trying to figure this out but I can't seem to come up with an efficient work around.

In Omeka S site pages api endpoint can't be paginated while items and media can.

```
(omekas_page_importer) DIV-LIB-27BJ1GJ:populate_omeka_s_site kgoetz$ time curl -s 'https://example/api/items?key_identity=key&key_credential=cred&per_page=50' |json_pp - |head
Wide character in print at /usr/bin/json_pp5.18 line 82, <STDIN> chunk 1.
[
   {
      "dcterms:creator" : [
         {
            "property_label" : "Creator",
            "property_id" : 2,
            "type" : "literal",
            "@value" : "Olive Pink "
         }
      ],

real	0m0.576s
user	0m0.099s
sys	0m0.020s
(omekas_page_importer) DIV-LIB-27BJ1GJ:populate_omeka_s_site kgoetz$ time curl -s 'https://example/api/site_pages?key_identity=key&key_credential=cred&per_page=50' |json_pp - 
malformed JSON string, neither array, object, number, string or atom, at character offset 0 (before "(end of string)") at /usr/bin/json_pp5.18 line 45.

real	0m0.344s
user	0m0.038s
sys	0m0.016s
```

This can be worked around - for my use case - by pulling /site/ID then running /site_pages/ID checks for every page within the site - but its slow and inefficient.

**Comment by zerocrates** [comment]
I don't see that there's any issue or difference doing _pagination_ for site_pages... what is missing that would be useful for you is a `?site=<id>` query parameter. Does that sound right?

**Comment by goetzk** [comment]
HI,
I'm not sure what the first bit of your comment means - that it does behave the same or that you don' think it needs to?

Either way, a site_id query parameter would certainly be a useful restriction for my use case.

**Comment by zerocrates** [comment]
"I don't have any problem" meaning that it seems to paginate like any other
resource in the API

**Comment by zerocrates** [comment]
Your use of `json_pp` in your example makes it a little unclear what result you're actually getting... is it just a blank result? Or something that cuts off in the middle? It seems you're encountering some kind of error... running into your memory limit perhaps? Have you tried [enabling error display](https://omeka.org/s/docs/user-manual/errorLogging/) (just the first bullet there)?

**Comment by goetzk** [comment]
ah yes json_pp does rather do that. The API returns nothing/empty. removing per_page=50 results in 25 pages being returned.

Application doesn't log anything but httpd does:

```
==> /var/log/httpd/exhibit-dev<==
[Fri Feb 15 15:37:00.134962 2019] [php7:error] [pid 47825] [client 202.12.92.74:51457] PHP Fatal error:  Uncaught Error: Call to a member function getReference() on null in /var/www/html/application/src/Api/Representation/SiteBlockAttachmentRepresentation.php:34\nStack trace:\n#0 [internal function]: Omeka\\Api\\Representation\\SiteBlockAttachmentRepresentation->jsonSerialize()\n#1 /var/www/html/vendor/zendframework/zend-json/src/Json.php(331): json_encode(Array, 15)\n#2 /var/www/html/vendor/zendframework/zend-json/src/Json.php(296): Zend\\Json\\Json::encodeViaPhpBuiltIn(Array, false)\n#3 /var/www/html/vendor/zendframework/zend-json/src/Json.php(97): Zend\\Json\\Json::encodeValue(Array, false, Array, false)\n#4 /var/www/html/vendor/zendframework/zend-view/src/Renderer/JsonRenderer.php(151): Zend\\Json\\Json::encode(Array)\n#5 /var/www/html/application/src/View/Renderer/ApiJsonRenderer.php(43): Zend\\View\\Renderer\\JsonRenderer->render(Array)\n#6 /var/www/html/vendor/zendframework/zend-view/src/View.php(207): Omeka\\View\\Renderer\\ApiJsonRenderer->render(Object(Omeka\\View\\Model\\ApiJsonModel))\n#7 /var/www/html/vendor/zendframework/zen in /var/www/html/application/src/Api/Representation/SiteBlockAttachmentRepresentation.php on line 34

==> /var/log/httpd/exhibit-dev <==
131.217.17.21 - - [15/Feb/2019:15:36:59 +1100] "GET /api/site_pages?key_identity=KEY&key_credential=CRED&per_page=50 HTTP/1.1" 500 - exhibit-dev "-" "curl/7.62.0"
```

I'll need to get access to .htaccess to get the extra logging; for some reason on our server its owned by root.

**Comment by zerocrates** [comment]
What version of Omeka S are you using? This looks like a bug that's been fixed... The paging is sort of a red herring here: it's probably just that with a higher limit the output happens to encompass a page that exhibits the bug.

**Comment by goetzk** [comment]
Hi,
The system in question is v1.2

**Comment by zerocrates** [comment]
The fix is in 1.3.

**Comment by goetzk** [comment]
I have put ina request to have our system upgraded, thanks.
Karl

On 19 February 2019 12:30:53 GMT+11:00, John Flatness <notifications@github.com> wrote:
>The fix is in 1.3.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/omeka/omeka-s/issues/1365#issuecomment-464942656

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by goetzk** [comment]
By the way, is this a variation of the bug you mention in  #1346?
https://github.com/omeka/omeka-s/issues/1346#issuecomment-440315093

**Comment by zerocrates** [comment]
Yes, I believe these are the same bug.

**Comment by goetzk** [comment]
Hi,
Our upgrade to 1.3 is complete and the API call is functioning correctly.

Thanks all!
