### ISSUE TITLE
Add Prev | Next navigation to the admin item show

### ISSUE THREAD

**Issue by sharonmleon** [omeka/omeka-s#1366]
I have **thousands** of items to edit, and upon edit the user is returned to the show for the item just edited. It would be nice to be able to click back and forth through the items in order without having to navigate back to the admin items browse pages.

**Comment by zerocrates** [comment]
Previous and Next... we have a bad history with this feature, part of the reason it's omitted.

Maybe we can do it better. There's also general occasional annoyance with the hard-coded nature of the redirect after adding/editing/etc: works for some flows not others. We could make that configurable maybe.

**Comment by sharonmleon** [comment]
Hmmm... I was just hoping to jump to the next item ID

**Comment by zerocrates** [comment]
Yeah. Our problem has been peoples' widely varying viewpoints on what "Next" should mean... and simply not having the navigational elements has removed that issue for S. On the admin only maybe it would be fine though.

Opening the edit pages in new tabs would at least save you the "go back to the right place" part of your described workflow.

**Comment by Daniel-KM** [comment]
I have such a feature in my last commit of [Next](https://github.com/daniel-km/omeka-s-module-next). The last browse page is saved in session, so it's easy to go back to the last browse page. It can work in public theme to via a helper.

**Comment by Daniel-KM** [comment]
And there is an helper for prev/next item too, but the button is currently not displayed in admin.
