### ISSUE TITLE
Gulp task for building module sass is broken.

### ISSUE THREAD

**Issue by kimisgold** [omeka/omeka-s#1367]
When attempting to run `gulp css:watch:module --module Scripto`, I get the following error:

`/usr/local/bin/node: bad option: --module`

I am running:

- Gulp CLI version 2.0.1
- Gulp local version 4.0.0
- Node v10.15.1

**Comment by zerocrates** [comment]
Should be fixed: you can now use `--module-name` in place of `--module` (`--module` will continue to work for those on less annoying Node versions)

**Comment by zerocrates** [comment]
also it's now called `css:module:watch`
