### ISSUE TITLE
Properties (and syntax) not translated when option "Apply templates" checked

### ISSUE THREAD

**Issue by ManOnDaMoon** [omeka/omeka-s#1368]
Hello,

I really like the new option to apply resource templates to advanced search forms, but unfortunately there is no translation applied to the properties list. In details:
* In the advanced search form, Dublin Core properties are displayed with their original english identifier. I had a look, but there is no easy way of just adding `//@translate` or calling a translator into the `PropertySelect::getValueOptions()` function. Maybe this would need to move in a proper view template to ease translation?
* The "syntax" used would also benefit to be customizable because
`property: label1; label2; label3` is very "english" and would need to be treated either as a translatable string or customizable template to suit foreign language use. E.g.: in french, we would need additional spaces: `property : label 1 ; label 2 ; label 3`. Or ultimately a more standard syntax could be used, like `property (label1, label2, label3)`.

Do not hesitate to ask for more details if needed.
Thanks in advance and have a nice day!

Laurent Thomas

**Comment by zerocrates** [comment]
OK, this makes sense... we get just-in-time translation "for free" out of the form components, but that only works when the complete, final string is something from the translation list: here, it's not. I think the only route we have is to pass the translator into this form element.

Localizing the syntax of the repeated values is possible at least partially, but it can be a little difficult to convey to translators what they're actually translating in a string like `; ` (plus it doesn't really help if what's desired is sufficiently different from the English version). Possibly we could use plural translations here... but that would probably also be a pain.

I don't imagine we have any issue with the parentheses-and-commas version you suggest, though.

**Comment by ManOnDaMoon** [comment]
Nice, works like a charm!
