### ISSUE TITLE
Drag and drop 

### ISSUE THREAD

**Issue by MickaelAHP** [omeka/omeka-s#1376]
Hi,

Omeka S could really use a feature to allow drag and drop for adding block.

I'm Creating a huge page i can't split (introduction of a book) and if i have to add a new block ( media or html for exemple) i have to go to the bottom of the page and slowly bring it up until it reach the top.
It could be really usefull to just drag and drop it from right panel to desired location.

Thx

**Comment by Daniel-KM** [comment]
A quick solution is to lower the zoom in the browser before moving the blocks.

**Comment by joebauer** [comment]
I came here to make this exact same request, so instead I'll comment here with another voice to request this feature.

**Comment by jimsafley** [comment]
We don't currently plan on addressing this issue. Feel free to reopen and elaborate should you want further discussion.
