### ISSUE TITLE
Per-resource configuration of title/description

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#1377]
We have a system where you can, in a site, choose the property that will be used as the title or description for resources... this works fine with fairly homogeneous collections but doesn't work so well if different resources have different templates/properties/etc.

We could invert where this control lies, placing it instead on the resource itself to mark which property serves as the title (or description/abstract/what-have-you)... in the simplest case we can just use that to decide which property to read, just as the current browse-based system works: this would get us the ability to cater better to mixed sets of resources, as well as to affect the display on the admin rather than just within a public site.

Additionally this could be the underpinning for doing something like saving the actual title to a column of the resource table, which would enable us to do things like more cheaply display titles for linked resources, potentially more easily use titles of linked resources for search results (could still be tricky as it means an extra join), or do much simpler and more efficient sorting by title.

**Comment by jimsafley** [comment]
@kim We need your help designing a UI for letting users choose which properties to use as title and description when editing a resource template. The [resource-titles branch](https://github.com/omeka/omeka-s/tree/resource-titles) adds the underlying functionality that makes this possible. We just need an interface that makes sense.

**Comment by kimisgold** [comment]
Here's a rough concept:

![Screenshot_2019-04-25 Resources · Sites · RRCHNM](https://user-images.githubusercontent.com/606764/56755736-311bc100-675e-11e9-9ebf-bf45bedfba4d.png)

* It strikes me that because these are settings made on a site-by-site basis, we can't actually select properties for titles within the items themselves. I was thinking that since we're managing an aspect of resources, we could slide this interface into the site resources section.

* With this setup, you can create many different title settings with as many resources as you like. The obstacle I haven't addressed in this interface is how to avoid mapping multiple title properties to a single resource.

Hopefully this is a good starting point.

**Comment by jimsafley** [comment]
The resource-titles branch already lays out the strategy we're going with: users will set their preferred title and description in the resource templates. We'd like your input on how to style the template form to accommodate this.

As for the browse heading and body settings: @zerocrates is doubtful they will remain as site settings.

**Comment by zerocrates** [comment]
> It strikes me that because these are settings made on a site-by-site basis, we can't actually select properties for titles within the items themselves. 

Yeah, the basic decision was to, in fact, actually do it this way: make the "what is the title" question something decided by the item(/set/media) rather than selected by the site. (technically at the template level, but...)

As Jim says, we still have those settings within the sites for choosing the properties on browse... I'm not sure what we'll do with those, they can either stay and just override the "real" title basically as they do now or possibly just get taken out.

**Comment by kimisgold** [comment]
My mistake for glossing over the part about the resource template. How about something simple, like an option in the configuration sidebar with a star marking the designated property? 

![Screenshot_2019-04-25 Base Resource · Resource templates · RRCHNM](https://user-images.githubusercontent.com/606764/56762280-7abfd800-676d-11e9-925b-ac95f292c69b.png)

**Comment by jimsafley** [comment]
It's  a good idea. We would need to somehow differentiate the title and description indicators.
