### ISSUE TITLE
"Edit All" in batch update not working

### ISSUE THREAD

**Issue by sharonmleon** [omeka/omeka-s#1380]
After performing an advanced search of items, I would like to use the "Edit All" select to append an item set to the results of my search, but I seem to be unable to. The job appears to complete but results in no items being linked to the set. I've gotten the same results whether the item set is public or private. When I actually select the desired items and use "Edit Selected," the job does complete and actually work, adding the items to the set.

**Comment by zerocrates** [comment]
This seems to have been a highly system-specific issue.
