### ISSUE TITLE
New user bar features translation

### ISSUE THREAD

**Issue by ManOnDaMoon** [omeka/omeka-s#1395]
Hi

I've been looking - with interest - at upcoming userbar features from @Daniel-KM merged recently (3df7462ecc266bf140e57ca2b3fb1db896fcf988) and I can see an issue with how the links labels are translated.

'Edit' and 'Show' links are built and translated from two parts: e.g. "Edit %s" and "Item" to build "Edit Item". This may work in english but does not in every language.

I've seen the use of icons has been discussed in #1283 but since it is not planned any more, I would suggest to use a specific mapping array for 'Edit' links and another for 'Show' links where fully translatable phrases can be used.

**Comment by zerocrates** [comment]
Your basic concern is what, differing genders between the different noun parts?

I have a recollection that we solved this in other places by just going to "Edit" as the text, but we'd have to change some things around to do that here. Icons wouldn't really solve the problem either, as we'd need a text equivalent for accessibility purposes anyway if we used an icon.

**Comment by ManOnDaMoon** [comment]
Genders (typically, "page" and "item" are of different genders in french) and also plurals.
