### ISSUE TITLE
Browse Preview block ignores limit setting

### ISSUE THREAD

**Issue by pprw** [omeka/omeka-s#1397]
Browse Preview block (inside a page) ignores the limit setting set inside the block. It is the global installation limit which will be applied even if there is another value for the browse preview block.

It should be possible to override the global limit when using Browse Preview block.

P-S : Maybe (?) related to #1273.

**Comment by pprw** [comment]
Precision: it is working when setting a lower value than the installation limit. The bug is for a higher value.

**Comment by pprw** [comment]
Update: not really a bug. It happens when the query is incorrect.

Mine was finishing with `&submit=Recherche&page=1&sort_by=dcterms:title&sort_order=asc`

**Comment by Daniel-KM** [comment]
Can you try without `page=1`?
