### ISSUE TITLE
Consider an item set selector

### ISSUE THREAD

**Issue by jimsafley** [omeka/omeka-s#140]
I have some reservations about the item set control that's now on item add/edit. While functional, it does not scale well and does not expose metadata about the item sets.

Instead I propose an *item set selector* (similar to the property selector) that exists in the sidebar and allows users to browse item sets and type for matches. When selected, the item set will be added to a list of item sets in the main part of the page, alongside any other item sets that the item is assigned to. Users could remove an item set from an item by clicking on a remove icon or something.

Any thoughts?

**Comment by zerocrates** [comment]
What additional metadata would this expose? Or are you thinking that it would incorporate "show details" (so, more like the *resource* selector than the property selector)?

**Comment by jimsafley** [comment]
The property selector has tooltips for property comments. I see the item set selector having the same for item set descriptions, and perhaps links to the item set show page.

**Comment by jimsafley** [comment]
I also see the item set *owner* being useful data to expose when selecting item sets. Especially helpful for item sets with identical titles.

**Comment by patrickmj** [comment]
Exposing owner sounds great to me. It would work well with what we talked about regarding deleting resources, and warning that it would affect others. This is a place to similarly expose who's using what, which makes a great pitch for S helping to make connections across an institution
