### ISSUE TITLE
Testing: Customizable resource titles and descriptions

### ISSUE THREAD

**Issue by jimsafley** [omeka/omeka-s#1407]
The [resource-titles branch](https://github.com/omeka/omeka-s/tree/resource-titles) introduces the ability to customize which properties will be used for the title and description of a resource (i.e. not just predetermined to be `dcterms:title` and `dcterms:description`). Admins can customize these properties in the resource templates.

First add or edit a resource template. When editing a property you should see two new checkboxes: "Use for resource title" and "Use for resource description." Use these to mark a property as a title that is not `dcterms:title` and as a description that is not `dcterms:description`.
After setting the changes you should see indicators on the form that tell you which properties are currently set as title and description. Save the template.

Now any resource that is set to that template should be titled using the configured title property, and when viewing the resource's details (on the browse page, for instance), it should be described using the configured description property.

**Comment by zerocrates** [comment]
This should be tested on develop now, as it's merged.

**Comment by mebrett** [comment]
I'm still trying to find a way to break it.

**Comment by mebrett** [comment]
I tried multiple ways to break it and could not, so I'd say it works.
