### ISSUE TITLE
Refactor value output to be self-contained and accessible from Representations

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#141]
Currently, the array/json output for a "value" is defined in several places, on the ValueRepresentation itself, and directly in the controllers for each of the resources that has a "show details" view.

These two separate implementations of the representation should be combined. This may mean moving the actual definition of the value structure to the abstract resource representation, where that could be used for "show details" output as well as the value output.

**Comment by zerocrates** [comment]
Moving the actual "value" output around so it's accessible from the right place is easily done, but the stumbling block is what else is actually being used by parts of the system.

The controllers, in both the show-details and the edit action, are manually including the `dcterms:title` in the value output so they can have something to display on the edit form. Right now, no part of this exists in the representation, so the controllers are either composing the array they want themselves, or just taking the "normal" value information and appending the title to that. 

Should we:
- just add `title` to the normal output for resource values so the controllers don't have to do anything special here
- rewrite the controllers to just use the *entire* representation for the attached resource rather than just the "value" linking part (this is not great because it would still require the controller to manually grab the full representation for resource values)
- have some flag or option in the Representation and/or API that makes `values()` return value representations that include the full data for the linked resources
- do something else?

I'm generally leaning toward the first option. Providing the simple first "title" could actually be useful for API clients, giving them just slightly more of the bare necessities of information about linked resources so they might not have to make a full-blown request for the full data.

(ping @jimsafley)

**Comment by jimsafley** [comment]
I'm fine with adding dcterms:title when it's not already there. Would it be a good idea to also add dcterms:description?

**Comment by zerocrates** [comment]
I think in this case I'd actually call it `title` or `display_title` and have it use the `displayTitle` method, so it matches up with other places where we're printing titles (and to make it less likely that we have some issue or confusion with the LD data by including a single "real" RDF data value in what are otherwise mere links).

As for description, I'm not opposed to it, but I think it would need similar treatment (displayDescription).

A side plus of relying on those passthrough displayX methods is that it gives us an easy place to allow for eventual configuration of what actual property is used for calculating the display title and/or description, a change that was basically impossible in Omeka 2.
