### ISSUE TITLE
npm install cant find files.

### ISSUE THREAD

**Issue by NLW-paulm** [omeka/omeka-s#1419]
Im having an issue installing from Github - I can download the repo fine and when I run npm install it creates the node_modules folder and adds a lot of modules. However towards the end it exits with the following error, saying it cant find one of the packages.

npm ERR! path /srv/www/omeka-s-two/public_html/node_modules/array-last/node_modules/is-number/package.json.3560125714
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open '/srv/www/omeka-s-two/public_html/node_modules/array-last/node_modules/is-number/packag
e.json.3560125714'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

**Comment by zerocrates** [comment]
I can't reproduce this. If you delete the node_modules folder and `npm install` again does it persist?
