### ISSUE TITLE
Should we remove the Media nav entry?

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#142]
The contents of the page that tab goes to are, admittedly, a temporary measure from a time before media were properly represented and linkable from Items.

Barring any objections (@jimsafley, @patrickmj?) it looks to me like it should be removed.

**Comment by jimsafley** [comment]
Media tab? Where?

**Comment by zerocrates** [comment]
Sorry, the entry in the main nav bar, not a tab.

**Comment by jimsafley** [comment]
Like any RDF resource, media are fully browseable and searchable. I forgot whether we settled on exposing those features. If so, the navigation should stay and the controller/actions should change to be more like items and item sets. If not, that page should go.

**Comment by kalbers** [comment]
I'm sort of with Jim on this one. If you're going to have the search include media, you need the browse page anyway. Not sure it's worth hiding from the main navigation at that point.

**Comment by jimsafley** [comment]
I don't oppose exposing the media browse page and making media clearly searchable, but the question remains whether we should. On one side, yes, everything's already set up to do these things. On the other, would exposing media as first-class citizens confuse users into thinking they can exist separately from items?

Still, given the fact that a search on items does not also search through their respective media (as one would think it should), we may have to expose media in this way.

**Comment by patrickmj** [comment]
I don't think the confusion would be that great -- it would be mostly likely among those who think they are using WordPress, and they can figure out that they are not. If people do use the metadata on media (or if it is imported from somewhere), then media should be searchable. So, much agreed with Jim's last point.

**Comment by kalbers** [comment]
I can see the argument for building out a page for search results, but not adding a browse link to directly to the sidebar. Since you can't attach media to items through that workflow, it only allows for editing and deleting media. Those tasks seem more likely accomplished via search.

**Comment by zerocrates** [comment]
It sounds like, then, that there's general agreement that we need a browse page for Media, for search if nothing else.

That being the case, I guess it doesn't make much sense to remove the nav entry at this point.
