### ISSUE TITLE
Add resource class to resource show pages

### ISSUE THREAD

**Issue by jimsafley** [omeka/omeka-s#1435]
None of our public themes seem to show the resource class when viewing a resource (item, media, item set). It's probably a good idea to add class to the resource show pages.

**Comment by zerocrates** [comment]
@kimisgold this is really a theme issue I guess, though it affects the fallback theme views of course.

The label text "Resource Class" I forsee being kind of a barrier to people actually wanting this... maybe something more in the vein of a heading/subheading/span-with-smallish-text-style hanging out near the title? We do this a little bit with text like "Item/Item Set" etc. I guess... maybe in the same ballpark?

**Comment by jimsafley** [comment]
The RDF way of defining a resource's class is `rdf:type`. So we could correctly label the class as "Type", but I see how people may conflate that with `dcterms:type`.

**Comment by zerocrates** [comment]
I don't think we want to go down the road of using different terms for the same thing... if we _do_ have a label for it it should probably be "Resource Class" (or _maybe_ Class but we don't use that either). Like, if we want to call it Type then we should be changing the admin labels too (and yes, confusion with Type is a factor, and in fact already is).

Obviously customized themes are free to call it whatever they want or omit it or whatever.

**Comment by kimisgold** [comment]
I could see this as a label like the "Item/Item Set" one that currently exists, though I think having both might be cluttered. We could possibly combine it into something like "Item | Document" so that we wouldn't have to worry about the specific label.

I could also see Resource Class appearing in the metadata, and in that context, maybe "Resource class" as a property label might not be so bad.

**Comment by sharonmleon** [comment]
I think it should probably go in the metadata, with Resource Class as the property label.

(That Item label is a sticking point for people who are trying to do reparative descriptions of human beings, but in that case, the class is usually Agent, which is just as clinical/dehumanizing.)

**Comment by zerocrates** [comment]
None of "Item," "Agent," "Resource," etc. are going to be acceptable terminology in that context I wouldn't imagine.

Another way around here is to have a simple way of turning on/off the various parts of display: it doesn't matter so much if we add something some people don't want to show if they have a trivial way to disable it... a theme setting? Could be overboard (certainly if just for this but I'm thinking more of more generally the "parts" of a show page).

**Comment by sharonmleon** [comment]
- New settings for hiding labels/resources. 
- Or, resource templates with alternate class label designation.
- Keep telling people how to hide things with CSS

Reaches out to advanced search and item pages.

**Comment by jimsafley** [comment]
Since this discussion we've added resource page blocks, so it is now possible to add a "Resource class" block that renders the resource class and only the resource class on the page. We're going to explore this solution.
