### ISSUE TITLE
Fulltext table index size

### ISSUE THREAD

**Issue by bfavaretto** [omeka/omeka-s#1443]
I was getting the following exception while trying to update an 1.4.0 installation to 2.0.1:

> **Doctrine\DBAL\Exception\DriverException**
> An exception occurred while executing 'CREATE TABLE fulltext_search (id INT NOT NULL, resource VARCHAR(255) NOT NULL, title LONGTEXT DEFAULT NULL, text LONGTEXT DEFAULT NULL, FULLTEXT INDEX IDX_AA31FE4A2B36786B3B8BA7C7 (title, text), PRIMARY KEY(id, resource)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB;': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

I am not sure if that is something that should be fixed in Omeka (i.e., by changing column sizes) or not. In my case I was able to finish the upgrade by extending the mysql limit. I did that by adding the following settings to my mysql config file, [mysqld] section:

```
innodb_file_format = Barracuda
innodb_large_prefix = ON
innodb_file_per_table = ON
innodb_default_row_format = 'DYNAMIC'
```

**Comment by zerocrates** [comment]
For other indexed columns we do constrain the sizes so that they're under this limit, so we should probably be doing so here, too.
