### ISSUE TITLE
Improve vocabulary import

### ISSUE THREAD

**Issue by psalido** [omeka/omeka-s#1444]
Currently is not possible import all properties from some vocabularies like http://id.loc.gov/static/data/downloads/vocabularyrelators.rdf.zip

Problem is related to resources with multiple definitions on vocabulary. Some definitions are related to type. I.e.
```

		  <rdf:Description rdf:about="http://id.loc.gov/vocabulary/relators/prm">
			<rdf:type rdf:resource="http://www.loc.gov/mads/rdf/v1#Authority"/>
		  </rdf:Description>
		  <rdf:Description rdf:about="http://id.loc.gov/vocabulary/relators/prm">
			<rdf:type rdf:resource="http://www.loc.gov/mads/rdf/v1#Topic"/>
		  </rdf:Description>
		  <rdf:Description rdf:about="http://id.loc.gov/vocabulary/relators/prm">
			<rdf:type rdf:resource="http://www.w3.org/2002/07/owl#ObjectProperty"/>
		  </rdf:Description>
		  ...
```

EasyRdf parser could read withoug problem this file, but omeka-s/application/src/Stdlib/RdfImporter.php only consider first declared type for resource. Thus, if first type isn't among supported types (classtype or property type delimited in two arrays $propertyTypes and $classTypes), resource is discared.

Solution is check all types, not only main (first defined) type from RDF resource.

![rdfimorterchanges](https://user-images.githubusercontent.com/3009909/63351035-c884cf80-c35e-11e9-8d0f-12b17dc8b7a6.jpg)

More details in https://forum.omeka.org/t/using-marc-relators-for-refine-dcterms-contributor/9194

**Comment by jimsafley** [comment]
Thanks for the changes. They are now [merged](https://github.com/omeka/omeka-s/pull/1447), along with several other improvements.
