### ISSUE TITLE
Unable to uninstall a module that is not compatible with my omeka-S version

### ISSUE THREAD

**Issue by symac** [omeka/omeka-s#1450]
I am currently upgrading my omeka-s install from omeka-s 1.* to 2.0.2 and there are some modules that are not compatible with this new version of omeka that I would like to uninstall. It would be great to be able to remove them easily from the module management screen.

Instead of : 

![uninstall_module](https://user-images.githubusercontent.com/300907/64794529-e53aae80-d57c-11e9-9db5-5ffd9b878fc7.png)

Having something like : 
![uninstall_module_need](https://user-images.githubusercontent.com/300907/64794728-3b0f5680-d57d-11e9-8a80-668e24cb8038.png)

**Comment by Daniel-KM** [comment]
In most of the cases, modules create settings and sometime new tables. 

For the settings, the point is to recommend developers to list all settings in the config or somewhere and to name them with the name of the module first, so they can be removed without the original module. 

For the tables, it's possible to list them too somewhere, or simpler, to use a separate file "uninstall.sql" (don't include the sql code in the file Module.php, and for install too in fact), so uninstall can be processed without the original module.

This is the way the [Generic module](https://gitlab.com/Daniel-KM/Omeka-S-module-Generic) is working. I can push these feature here if wanted.

**Comment by Daniel-KM** [comment]
So the idea is to make install/uninstall independant from the module itself.

**Comment by jimsafley** [comment]
We don't currently plan on addressing this issue. Most situations like this can be resolved by updating the module and then uninstalling it. Feel free to reopen and elaborate should you want further discussion.
