### ISSUE TITLE
Check multiple-string translations for use of numbered placeholders

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#1452]
Using multiple `%s` placeholders prevents translators from reordering the parts of the sentence.

**Comment by Daniel-KM** [comment]
It can be fixed with numbered placeholder (%1$s), but more largely with PSR-3 in many place (#1372).

**Comment by zerocrates** [comment]
As for PSR-3, it's possible that could be a better solution eventually: for the time being I don't want to go there because it probably would be a situation where that would change out _all_ strings with placeholders, which is many more. So for this moment I'm sticking with the sprintf style, which just brings us back up into line with what Classic was already doing (and a very very small number of strings in S were already doing as well).

**Comment by Daniel-KM** [comment]
Ok, it's simpler in the short term. Nevertheless, could you include the helper to create psr message (#1372) ?
