### ISSUE TITLE
Sub-navigation items unclickable when navigation menu wraps in Default theme

### ISSUE THREAD

**Issue by joebauer** [omeka/omeka-s#1453]
I’m seeing that when you set up child navigation menu items in the Default theme and when you navigate to the site and narrow your window enough that the menu items wrap so there are two rows, that the sub-menu navigation items on the top row are essentially un-navigatable because you can’t make your mouse jump the gap to the sub-items. Like this:
![Screen Shot 2019-09-23 at 3 22 32 PM](https://user-images.githubusercontent.com/6989685/65522819-581b2200-deb9-11e9-8deb-5d7fb6509764.png)

In this you can see the row of “Fake navigation menu item” navigation items wrap due to the narrow screen, but when I hover over the “Fake Navigation Menu Item with Sub menu items” the drop-down goes under the second row of navigation items, so the mouse can’t get to it and the sub-items disappear when you attempt to do so.

Here's what it looks like on the admin console:
![Screen Shot 2019-09-23 at 3 37 12 PM](https://user-images.githubusercontent.com/6989685/65522898-75e88700-deb9-11e9-943c-d197a9da0ddd.png)

I've tried this with vanilla installs of the Default theme in Omeka S version 1.4.0 and 2.0.2.

Is there a fix or workaround for this?

Thanks!

**Comment by kimisgold** [comment]
Hi, @joebauer. I've got a proposed fix in a branch over in the default theme's repository. With it, the navigation remains one line of items, but the individual items' text wraps. This should keep the dropdown menus from getting separated from their parent items. Could you try it out and let me know if it works for you? To do that, copy [this version of style.css](https://raw.githubusercontent.com/omeka-s-themes/default/flex-fix/asset/css/style.css) into `themes/default/asset/css/style.css` within your Omeka S installation.

**Comment by joebauer** [comment]
Just tried it and it certainly works better now! Thanks! Do you know when
that might get committed to the main code?

Best,
Joe

**Comment by kimisgold** [comment]
It needs to go through more internal testing, but after that I hope to do another release within the week.

**Comment by joebauer** [comment]
That sounds great! Thanks again for the super fast response on this!

**Comment by zerocrates** [comment]
The fix is available in version 1.4.2 of the default theme.

**Comment by m-art-in** [comment]
Sorry, I still have the bug with 1.4.2

**Comment by kimisgold** [comment]
@m-art-in Just to cover our bases, have you cleared your cache/performed a hard refresh?

**Comment by m-art-in** [comment]
it's a fresh/new installation, so no cache problem

**Comment by kimisgold** [comment]
Could you provide a live site or screenshot to look at?

**Comment by m-art-in** [comment]
It's on a local test machine, but here is a screen shot:
![image](https://user-images.githubusercontent.com/15324884/68868880-96360480-06f8-11ea-91f5-89631cbef687.png)

I hover with the mouse over "Digitale Bibliothek" but when I try to click e.g. "Drucke" the menu disappears right away.
and thats the Navigation in the backend:

![image](https://user-images.githubusercontent.com/15324884/68869140-fc228c00-06f8-11ea-8913-8bd8e24962b1.png)

**Comment by kimisgold** [comment]
I found some bottom padding on the header that I somehow missed when I made the fix. It should be simple to address and test. Thanks for bringing this to our attention!

**Comment by m-art-in** [comment]
@kimisgold thank you very much! Would be great to have a fix soon. Unfortunately, I don't know how I could do it myself. I have only noticed the issue...

**Comment by kimisgold** [comment]
We've released v1.4.3 with a fix: https://github.com/omeka-s-themes/default/releases/download/v1.4.3/default-v1.4.3.zip

**Comment by m-art-in** [comment]
Thank you! Now it's working fine
