### ISSUE TITLE
Isolate items not inside collection

### ISSUE THREAD

**Issue by pprw** [omeka/omeka-s#1454]
It is not simple (to my knowledge) to isolate all items which are *not* in a item set/collection.

I think this feature should be added.

**Comment by zerocrates** [comment]
We have a "not in any collection" feature in Classic... things would have to work a little differently in S given that items can be in multiple sets, so the query for "in no sets" has to be a join... I think, with the way the existing "in set(s)" filter works, we'd have to implement this as a separate check.
