### ISSUE TITLE
Center thumbnail alignment option for media blocks?

### ISSUE THREAD

**Issue by joebauer** [omeka/omeka-s#1455]
We would like to request adding a "Centered" option to be added to the current "left" or "right" options in the Thumbnail alignment for a Media block when editing a page. We read through the manual and forums (even looked through modules) but could not find any other way to display an item thumbnail centered on a page. 

<img width="867" alt="Screen Shot 2019-09-27 at 1 50 53 PM" src="https://user-images.githubusercontent.com/6989685/65790613-05966b80-e12e-11e9-8106-7459d12b487f.png">

**Comment by zerocrates** [comment]
@joebauer We're looking into some changes here, but one note: right now, the "item showcase" block should allow you to insert a centered thumbnail for an item.

**Comment by kimisgold** [comment]
Planned changes: 

* Provide a center alignment option for the "Media" block
* Adjust "Media" block labels for clarity
  * "Media" will change to "Media Embed"
  * "Thumbnail alignment" will change to "Alignment"
  * Alignment options will include "float left", "float right", and "center"
