### ISSUE TITLE
Omeka Freezes when relating an item into another item

### ISSUE THREAD

**Issue by hydrosIII** [omeka/omeka-s#1457]
I have a metadata that requires to relate one item in another when creating the item.  But when I try to select the item it loads the first time but the second time freezes the webpage. It also freezes my computer, the client. But it also makes the server work a lot. 

I send screenshot. 
![Captura de pantalla de 2019-10-03 15-06-13](https://user-images.githubusercontent.com/7807363/66160438-c1a0dc00-e5ef-11e9-90b3-9215bb23769a.png)

**Comment by hydrosIII** [comment]
After some time. Firefox asks me to stop the webṕage. If not firefox freezes also, or the page breaks.

**Comment by zerocrates** [comment]
Hmmm... I can't reproduce this. Anything "interesting" about your install? Modules maybe? Settings particularly far from the defaults?

The sidebar there doesn't really do anything that the actual item browse page doesn't... if anything it's actually less. I'm particularly surprised at it hanging the browser... the stuff happening there should be asynchronous.

**Comment by hydrosIII** [comment]
It only happens when trying to relate the second reference, not the first.

**Comment by hydrosIII** [comment]
Yes, the list of modules that we are using is the following.

ArchiveRepertory |         1 | 3.15.7  |
| IiifServer       |         1 | 3.5.14  |
| Lockout          |         1 | 3.2.3   |
| Log              |         1 | 3.1.3   |
| Mapping          |         1 | 1.1.1   |
| MetadataBrowse   |         1 | 1.2.0   |
| RdfDatatype      |         1 | 3.0.2   |
| Reference        |         1 | 3.4.13  |
| Sharing          |         1 | 1.1.0   |
| UniversalViewer  |         1 | 3.6.0   |
| ValueSuggest     |         1 | 1.4.1   |

**Comment by hydrosIII** [comment]
I have tried disabling all the modules.:

| ArchiveRepertory |         0 | 3.15.7  |
| IiifServer       |         0 | 3.5.14  |
| Lockout          |         0 | 3.2.3   |
| Log              |         0 | 3.1.3   |
| Mapping          |         0 | 1.1.1   |
| MetadataBrowse   |         0 | 1.2.0   |
| RdfDatatype      |         0 | 3.0.2   |
| Reference        |         0 | 3.4.13  |
| Sharing          |         0 | 1.1.0   |
| UniversalViewer  |         0 | 3.6.0   |
| ValueSuggest     |         0 | 1.4.1   |
+------------------+-----------+---------+

I did the same stuff, just tried to add some references to an item. I have Firefox in linux, also it happens in Windows with Chrome.

**Comment by hydrosIII** [comment]
I send a screenshot of the hung browser. Now I tested it in chrome. 
![Captura de pantalla de 2019-10-03 16-30-44](https://user-images.githubusercontent.com/7807363/66165849-480eeb00-e5fb-11e9-8129-1c0e78c5ef37.png)

**Comment by hydrosIII** [comment]
I have checked everything from database to php. I cannot find a clue. Also  I get an empty error in the Omeka log.
![Captura de pantalla de 2019-10-03 16-37-15](https://user-images.githubusercontent.com/7807363/66166151-1ba79e80-e5fc-11e9-97c6-d30a37710a12.png)

**Comment by hydrosIII** [comment]
My omeka-s version is 1.4.0:
![Captura de pantalla de 2019-10-03 16-38-57](https://user-images.githubusercontent.com/7807363/66166210-527db480-e5fc-11e9-9c71-c0b38222abdc.png)

**Comment by zerocrates** [comment]
We never were able to reproduce this, so weren't able to really investigate. Obviously it's been a while since the report. If it's still an issue feel free to comment or open a new issue.
