### ISSUE TITLE
Limit item set advanced search options to attached sets in sites

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#1459]
At least an option/site setting to do so.

Sites already have a slightly different advanced search input for item sets so this shouldn't be too much trouble.

**Comment by zerocrates** [comment]
To clarify: this is about the item set selector on the _item_ advanced search page.

**Comment by sharonmleon** [comment]
@zerocrates Should we add this to the 3.0 release cleam up? Or is it now irrelevant?

**Comment by sharonmleon** [comment]
Testing and Documentation.
