### ISSUE TITLE
CSRF: Value is required and can't be empty

### ISSUE THREAD

**Issue by Heimlix** [omeka/omeka-s#1472]
Hello everybody.

Saying thanks in advance, I write about this topic in spite of existence of issues #907 and #910 

I'm new in the Omeka's world and I have the refered trouble when I'm try to add a new value or even delete it. The trouble doesn't come always but some Items, the very long and heavy Items, I guess.

The log error reports: "Error: Call to undefined method Zend\Form\Element\Hidden::getCsrfValidator() in /var/www/html/application/src/Form/Initializer/Csrf.php:33

Stack trace:
#0 /var/www/html/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(779): O…"

I must to say that it's a legacy installation that use to work fine but with some troubles like this.

This is the sytesm's info:

![omekaB](https://user-images.githubusercontent.com/57276227/68219110-1054e380-ffab-11e9-8c12-c123220b7c85.png)

These are the modules installed and working:

Custom Vocab 1.1.0, Archive Repertory 3.15.7, IIIF Server 3.5.14, Log 3.1.3, Mapping 1.1.1, Metadata Browse 1.2.0, RDF Datatype 3.0.2, Reference 3.4.13, Sharing 1.1.0, Universal Viewer 3.6.0 and Value Suggest 1.4.1

Due to, I think, IIIF Server, RDF Datatype and Universal Viewer are not working on Omeka S 2.0.0> I believe it's not the moment to update the Omeka S version.

Thanks in advance.

**Comment by zerocrates** [comment]
So, are you having the "CSRF" error indicated in the title, or the error in the log? The log problem seems like it might be unrelated.

With your description of it only happening on "long" items, maybe you're seeing the same thing as #1330. Currently, increasing the PHP setting `max_input_vars` is the solution/workaround to this problem.

**Comment by Heimlix** [comment]
Hello.

Thanks a lot @zerocrates 

The message appears in the title:

![csrf](https://user-images.githubusercontent.com/57276227/68255137-0dc9ac80-fff2-11e9-8e74-c22f9873d89f.png)

I have increased the max_input_vars to 2000 in php.ini and it doesn't work :( (I read about modify .htaccess file did the trick for you, may I ask how does it work?)

This is a relation of values in each item of the HTML form:

Item                | # Values
-------------------------------
bibo:authorList       122
bibo:editorList       41
bibo:interviewee      36
dcterms:spatial       89
dcterms:subject       5

Thanks again.

**Comment by Heimlix** [comment]
Hello again,

Even more, I have increased max_input_vars to 5000 in php.ini and nothing changes.

Even when I open those trouble Item and just click, without any change, on save button i get the same error message.

Thanks.

**Comment by zerocrates** [comment]
Are you restarting/reloading PHP-FPM after making that change? Otherwise it won't be picked up and actually used.

**Comment by Heimlix** [comment]
Yes I did.

Now I have added this line to my Omeka's document root .htaccess and the error persists.

php_value max_input_vars 5000

Thanks.

**Comment by Heimlix** [comment]
Hello again.

I'm sorry. When @zerocrates  asked me about PHP-FPM I realized that I modified /apache/php.ini instead /fpm/php.ini where I increased max_input_vars to 5000 (I don't know if I am exaggerating). It's working!

Thanks a lot!
