### ISSUE TITLE
Provide base styles for site page blocks

### ISSUE THREAD

**Issue by kimisgold** [omeka/omeka-s#1474]
While working on #1455, I noticed that styles for item showcase and media blocks were inconsistently applied across the Omeka Team's supported themes. Is there a way we can provide a default stylesheet for page blocks, the way the Exhibit Builder provided default styles for its blocks in Omeka Classic?

**Comment by zerocrates** [comment]
There's a system in the block layouts that allows you to add a stylesheet or whatever on the public page whenever the block is used... but we'd have to be making separate sheets for each of these for that to work, I guess.

What kind of differences are we talking about here? There's some argument to be made that some variation in styling is a feature, not a bug. But obviously it's an issue when trying to introduce new block features and so on.

**Comment by kimisgold** [comment]
When we were talking the differences between the item showcase and media blocks, I mentioned that the item showcase takes up the full width of the content area and centers the thumbnails. The centering was inconsistently applied across the themes in a way that I'm not sure makes sense. Mainly, though, it's that point you mentioned about being an issue when introducing new block features.

**Comment by kimisgold** [comment]
Tested in https://github.com/omeka/omeka-s/issues/1480.
