### ISSUE TITLE
Unnecessary temp files can be left over when errors occur during file ingest

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#1475]
The TempFile class has several situations where it doesn't clean up after itself and delete the temp file: like when the mime/extension validators fail, for example.

Fixing the issue is trivial, but there's a complication: the FileSideload module currently uses the TempFile class for files that aren't really "temporary," the files in the sideload directory, and as a result, fixing TempFile would lead to undesirable deletions of files from the sideload directory when errors occur.

As a result, this is basically blocked on omeka-s-modules/FileSideload#14

**Comment by Daniel-KM** [comment]
I think FileSideload is fixed in last pull requests, even if it can be improved.
