### ISSUE TITLE
CSRF error when modifying a imported item

### ISSUE THREAD

**Issue by pprw** [omeka/omeka-s#1477]
I have an `CSRF: Value is required and can't be empty` error when trying to modify an item. This item was imported from a csv table. It is an item with a lots of metadata and urls (so some weird symbol). This item takes some time to my load in Omeka admin interface.

I can send information to help debug this (and a link to the api for this item in private).

**Comment by zerocrates** [comment]
I think this is likely the same issue as #1330.

For now, the solution is to increase the php.ini setting `max_input_vars` and restart Apache and/or PHP.

**Comment by pprw** [comment]
It is indeed the same issue and increasing `max_input_vars` fixes it. Thanks!
