### ISSUE TITLE
Test new core page block styles

### ISSUE THREAD

**Issue by kimisgold** [omeka/omeka-s#1480]
Test with the `block-styles` branches of Omeka S and default.

Omeka S core will provide default styles for the following page blocks:

  

-   **Item Showcase** — Attachment thumbnails are laid out horizontally and wrapping to new rows.
    

	-   The block has a top and bottom border.    
	-   A single attachment will display at its full width and centered.
	-   Multiple attachments display at 25% width, wrapping to new lines every 4 attachments.
    

-   **Media** — This block renders a file derivative for image attachments or the original file if supported.
    

	-   **Alignment: "Left"** — The attachment group floats left with text wrapping around it.
	    
	-   **Alignment: "Right"** — The attachment group floats right with text wrapping around it.
	    
	-   **Alignment: "Center"** — The attachment group sits in the center of the page with no text wrapping.
	    
	-   Rendered attachments stack vertically.
	    
	-   Media blocks stop at 40% of the page width, except for centered blocks.
	    
	-   Non-centered media block widths default to the width of the largest image on all browsers except IE and Edge. IE and Edge will default to the width of the largest element up to the maximum 40% width.
	    
	-   The attachment group has a top and bottom border.
	    
	-   The attachment title defaults to h3 sizing when large thumbnails are selected. The title defaults to paragraph sizing when square or medium thumbnails are selected.
    

-   **Line Break** — This creates vertical space between blocks and clears subsequent blocks from any floating that would come from preceding blocks.
    

	-   **Opaque** — The line break has a thin, gray border.
	    
	-   **Transparent** — The line break's border is transparent.
    

-   **Browse Preview** — This produces a list of resources based off a query.
    

	-   The list takes up the full width of the page and clears preceding content.
    

-   **Table of Contents** — This block creates an indented list of a page's child pages.
    

	-   The list indents up to three child levels.
    

-   **Item with Metadata** — Presents the contents of item/show within the flow of a page.
    

	-   This block has top and bottom margins to give it space amidst the page content.
    

-   **List of Sites** — Provides a list of other sites within the Omeka S installation.
    
	-   Each site title is 20px in size by default.
	    
	-   Site descriptions are indented under their titles.

**Comment by mebrett** [comment]
I'm not seeing the "center" option for media blocks. 
fwiw, testing page is here: http://dev.omeka.org/mebrett/testomekas/s/austen/page/blocktesting

**Comment by kimisgold** [comment]
Ah, I forgot I was working on that as a separate branch. I've merged that into `block-styles` for Omeka S, so please pull—that should make it appear for you.

**Comment by mebrett** [comment]
Thank you - I see it now. 
Centered media embeds stack right down the middle of the page, exactly as I would expect them to.

**Comment by mebrett** [comment]
I'm able to get Table of Contents to go deeper than 3 levels.
![Screen Shot 2019-12-09 at 10 50 00 AM](https://user-images.githubusercontent.com/2314070/70450708-31a96380-1a72-11ea-9e34-1f295adf5f5c.png)

**Comment by mebrett** [comment]
Everything else is working as expected.

**Comment by zerocrates** [comment]
Font sizes and stuff feels like a likely problem area here: not necessarily for our themes but for others pretty reasonably... could we use `rem` for the font sizes where they're needed here and define the line-heights as unitless (or using rem also, I suppose), so they're both just multipliers off the font size? Possibly the spacing stuff too, if the intent is for that to scale with font size.

`inherit` styles could also be useful for things that are currently just defined to be the base font size, line height, etc. to override browser defaults for things like headings.

**Comment by kimisgold** [comment]
@mebrett As a heads up, I've also removed `min-content` sizing from the media embed blocks. This sizing helped constraint text accompanying narrow images to the width of the images, but it kept causing more problems than it's worth (ex: responsive video attachments). The text should wrap once it hits the maximum column width, which is currently a third of the page content width.
