### ISSUE TITLE
Item w/ metadata does not use captions

### ISSUE THREAD

**Issue by kimisgold** [omeka/omeka-s#1483]
The "Item with Metadata" block provides caption fields for its attachments because it's using the standard attachment sidebar form. However, its partial does not use values from that field. We should either eliminate that caption field or figure out the best use of the caption within the block's partial. I lean towards the former because the purpose of the block seems to be replicating the item show view within a page, and there's no caption equivalent in the original view.

**Comment by zerocrates** [comment]
Consensus is remove/hide the caption here.

**Comment by zerocrates** [comment]
This looks to be a simpler problem than expected, actually: the block doesn't use the selected media, either, so we should be able to just use the pre-existing functionality for putting the chooser in "item only" mode, which will skip the caption and media selection panel completely.
