### ISSUE TITLE
Create actual browse page for Media

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#150]
Media should have a browse page essentially paralleling the item and item set browses.

**Comment by kalbers** [comment]
Do we have thoughts about what columns the table should have? Title and owner seem to make sense. Maybe also the resource it belongs to?

**Comment by zerocrates** [comment]
I'd go with those three provisionally.

We don't really have a good handle on which columns we want/need, so we might need to take a look at that for all the browses at once.
