### ISSUE TITLE
Testing for 2.1

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#1505]
The current draft release notes are [up as a draft](https://github.com/omeka/omeka-s/releases/tag/untagged-efd90f2dc989f745171b)

Obvious places for documentation updates at least, some of this has been tested as part of the corresponding PRs:
- the changed site block names and options (media embed and list of sites, possibly also item with metadata)
- the vocabulary importer/updater
- Media search
- batch editing to account for Editor user access
- item set and user permission configuration for sites
- public-side user bar (to include View link?)

**Comment by mebrett** [comment]
I've updated the documentation for these changes in a branch (2-1), and was not able to find any bugs while testing/writing.
