### ISSUE TITLE
Laminas migration

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#1508]
We need to at least try out the move to the new Laminas packages and the translation layers they're offering to gauge what kinds of effects they have on the core and modules.

This will be in a branch on its own, at least to start.

**Comment by sharonmleon** [comment]
Followed by testing of the modules for the migration tools.

**Comment by zerocrates** [comment]
The Laminas branch is now merged with develop

**Comment by Daniel-KM** [comment]
What is the forecast date for release of this update?

**Comment by zerocrates** [comment]
I don't have a specific date to give you, Daniel. This will be part of Omeka S version 3, and the timing of that depends more on our other work that's going into that release like the changes to enable cross-site search.

In all likelihood, there will be a public alpha/candidate release in advance of the actual release, in part to allow time for modules to update to the Laminas classes on their end.
