### ISSUE TITLE
Tweak user role names?

### ISSUE THREAD

**Issue by mebrett** [omeka/omeka-s#1509]
Inspired by [this forum post](https://forum.omeka.org/t/viewer-site-permissions-does-not-work-as-i-expect/10484/7) - do we want to tweak the site-specific user roles names? So that there's no overlap between role names at the installation level and the site level?

**Comment by sharonmleon** [comment]
I want to flag this and revisit the question of both naming and whether or not the site level permissions are adequate.

**Comment by Daniel-KM** [comment]
Ideally, the user should be able to have one role for the editorial part and a different role for the resource management part.

**Comment by sharonmleon** [comment]
Some more concrete thoughts.... These are the current roles and their explanations in the User manual.

### Installation Users:
- Global Admin: full installation privileges
- Site Administrator: robust site and content privileges
- Editor (Content Expert): full privileges for content creation
- Reviewer: robust content privileges but can only delete own content.
- Author: Create own content.
- Researcher: Search and read privileges only.

We probably need to define what "full installation privileges" means: adding and editing users? installing modules? Adjusting settings? The term "robust privileges" probably isn't explicit enough. Does that mean that the person can create and edit items, item sets, and media, but only delete things they own? It's used both in the context of site administrators and in that of reviewers and seems like a stand-in for two very different sets of permissions in those two contexts. Can Editors run the modules, i.e. execute an import? Can Reviewers? Authors: They can create and edit their own content, but they can also see everything else?

### Site Users: 
- Viewer: user can see the site’s backend but cannot edit.
- Editor: user can access and edit the site’s backend.
- Admin: user has full administrative privileges for the site, including adding users and deleting the site.

These users are listed in the opposite order of their degree of permission, which is different than the Installation list. I agree that the term Editor is a problem. We might fix that just by prepending the term "Site" to each of the roles. It also seems like "edit the site's backend" is not clear enough to really differentiate the Site Editor from the Site Admin. Can the Site Editor really adjust all of the settings for a site, including changing the defined pool of attachments? Can they edit how modules work on sites? Or can they just create, edit, and delete pages? 

Do pages have owners? Can Site Editors delete pages created by other users? Do we need another role that allows people to create and edit their own pages, but not mess with other peoples? 

@mebrett

**Comment by mebrett** [comment]
The two major conflicts to consider:
- Editor vs. site-level Editor
- Site Administrator vs. site-level Admin

**Comment by sharonmleon** [comment]
I vote that we change the installation level role names to the following:

- Global Administrator
- Supervisor
- Editor
- Reviewer
- Author
- Researcher

And the Site rolls should be:

- Manager
- Creator
- Viewer

And, I continue to think that at the documentation level, these rolls need much more specific discussion of the permissions associated with each. I think that had to have been hard when the initial descriptions were created because there just weren't that many actions to be detailed.

**Comment by mebrett** [comment]
I really like Supervisor and Manager, and breaking out "editor" vs "creator." 

It was very hard to write those user role descriptions in the early days. When we update them, I think it would be helpful to get input from everyone regarding the subtleties of some of the role permissions.

I'll also try to add something to the site user documentation to clarify how site user roles interact with installation roles, with examples.
