### ISSUE TITLE
Large amount of pages slows down site

### ISSUE THREAD

**Issue by JorisLambrechts** [omeka/omeka-s#1515]
We have an omeka's installation containing 2 sites with a major difference in load time which I gather is caused by the amount of pages, or more specifically, the site navigation. 

Site A has 700 pages (pretty much all of them are used in the navigation tree)
Site B has 50 pages

Site A takes 5800ms to load with almost half of that spent on the breadcrumbs alone
Site B takes 137ms to load

During tests I tried removing the breadcrumbs, pagination and even the public navigation (set to top-level only) from the theme but I can only get it down to about 3000ms so I suspect that the navigation is being loaded anyway.  

_Possible solutions_
- I could split the big site up into smaller sites but I'd like to exhaust other options first.
- Connect a redis caching server

Is there something else I could try and do you think redis would provide a solution here?

_Extra information_
Both sites have about the same number of items in the item pool (14 000). They also have the same theme, apart from a few differences in color, etc.

Omeka-s 2.0.2
PHP 7.1
MYSQL 5.7
opcache enabled

**Comment by zerocrates** [comment]
That's certainly a lot of pages.

A caching server like varnish or redis or whatever would presumably deal with this problem just fine: the problems with those systems usually just have to do with when to tell them to update their cached copies of things.

Splitting into smaller sites, as you say, is probably a solution if you're willing to go down that road.

The sites were built around our experiences and assumptions related to Omeka sites and exhibits, where 700 pages would be a pretty extreme outlier, so there are certainly some places where navigation is being used and loaded that are non-optimal for larger numbers of sites.

**Comment by JorisLambrechts** [comment]
It's actually an update of a Omeka Classic site that had tons of exhibits. We where not quite sure how to translate those to Omeka-s (which was required for other reasons) so we opted to use a combination of items and pages instead of making a separate site for each 'exhibit'.

Anyway, thanks for the response! We'll try the redis solution for now.
