### ISSUE TITLE
Omeka 2.1.0: advanced search broken because of "media typ"

### ISSUE THREAD

**Issue by m-art-in** [omeka/omeka-s#1518]
With version 2.1, Omeka introduced the ability to search by media type. However, this now leads to the error that the Advanced Search no longer works at all. 
For example, under Media I only search for a specific template and get no hits. However, if I delete the following from the URL 
"media_type=&" I get the desired amount of hits. In version 2.0.2. the advanced search still works. 

Can this error be confirmed? Is there already a fix?

**Comment by zerocrates** [comment]
Thanks for your report. I can confirm this is a regression in version 2.1.0. The commit attached to this issue represents the fix.
