### ISSUE TITLE
Advanced Search by res returning no results

### ISSUE THREAD

**Issue by alexdryden** [omeka/omeka-s#1526]
I'm not sure if there is something I'm missing, but when I use the advanced and select `is resource with id` and enter the resource id of a known item or item set, no results are found. Looking at the query that is sent to the db:
```
SELECT 
	r0_.id AS id_0, 
	r0_.is_public AS is_public_1, 
	r0_.created AS created_2, 
	r0_.modified AS modified_3, 
	r0_.resource_type AS resource_type_4 
FROM item i1_ INNER JOIN resource r0_ 
ON i1_.id = r0_.id 
LEFT JOIN value v2_ ON r0_.id = v2_.resource_id 
WHERE (v2_.value_resource_id = '470') 
GROUP BY r0_.id ORDER BY r0_.created DESC, r0_.id DESC;
```

it looks like this would never produce any results because (at lease in the installation I inherited) everything in the `value` table has `null` in the  `value_resource_id` column.

When I replace `value_resource_id` with `resource_id` in the where clause, I get the results that I would expect (e.g. a single result with the item or item set with id = the value in the where clause).

I've seen several references to the `res` search param, but nothing that mentions this issue.

**Comment by zerocrates** [comment]
The "res" search is for _values_ that use the given ID: it results only in items that link to the ID that you provide using "Omeka resource"-type values.

If you have `value_resource_id` as null for your whole value table, that just means you aren't using any "linking" values, and the query is therefore returning zero results, as expected.

**Comment by alexdryden** [comment]
Ah, gotcha! That makes much more sense. And that makes the data model make more sense to me, too. So is there any way for the advanced search (and by extension, site pools) to generate a result from a collection of item ids without linking those ids to one another somehow?

**Comment by alexdryden** [comment]
I see. There doesn't seem to be a way natively, but that feature or others could be implemented in a module by attaching a listener to the `'api.search.query'` event inside the AbstractEntityAdapter to add statements to the queryBuilder that generates the search results, and then the advanced search input option can be added to the advanced search form using its events/triggers. And the same implementation will populate the item_pool field. I think I have that right.

**Comment by zerocrates** [comment]
So, we're in the process of making some changes to the item pool implementation that allow you to just choose specific items, which may do what you're looking for.

As for what you have now, you're correct: there's no search option that just uses IDs or a range of IDs; a module could indeed add such a option, and that would be respected by the pool.
