### ISSUE TITLE
2.1.1 testing

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#1527]
Branch is release-2.1

Bugs fixed in this version include:

- nonfunctional Media advanced search when not specifying a MIME type
- broken API/item view when a visible item links through a specific-resource-type value (must be set by a template) to a non-visible resource

**Comment by mebrett** [comment]
Can confirm that both function as expected.
On the first, is there any way of making it clear that MIME type is required? Either in the 'no results' or even just by adding a red asterisk or 'required' message on the search form? Otherwise there's no clear reason *why* it's failing.

**Comment by zerocrates** [comment]
It's not required: it should be working when blank in 2.1.1, it was a bug in 2.1.0.

**Comment by mebrett** [comment]
Oh, I misread that. Can confirm you can search without it (it helps if I spell the thing right)
