### ISSUE TITLE
Clarify relationship between "assign new items" and "assignment action"

### ISSUE THREAD

**Issue by kimisgold** [omeka/omeka-s#1529]
In the new site attachment interface, how does the "assign new items" checkbox interact with the "assignment action" select? In what use cases can the "assign new items" checkbox remain unselected while using the "assignment action" select?

**Comment by jimsafley** [comment]
There is no interaction between "Assign new items" and "Assignment action." The former is a **persistent** flag that tells Omeka to automatically assign newly created items to the site. The latter is a **one-time** process that adds, replaces, or removes item assignments.

**Comment by kimisgold** [comment]
That makes more sense. The "assign new items" checkbox probably requires a different label and/or a field description. @mebrett might have good input on that kind of language.

**Comment by kimisgold** [comment]
"Assign new items" is still too vague at first glance. Would something like "Automatically assign newly created items to site" be too lengthy of a setting field name?

**Comment by kimisgold** [comment]
I think we're mostly in agreement. I lean towards including "newly created" to further differentiate between the items that setting affects versus items assigned with the search underneath this field.
