### ISSUE TITLE
Investigate "utf8mb4" charset for MySQL

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#153]
MySQL's `utf8` charset only supports three bytes per character, though some UTF-8 characters require four. Using just "utf8" means there are some UTF-8 characters that can't be saved in the database. This includes some ancient alphabets, symbols, and emoji, and likely most importantly, a large number of CJK characters, though these too are generally rarer ones.

There is an alternative charset/collation that allows 4-byte characters called `utf8mb4`, but it requires MySQL 5.5 or higher.

The change would require changing the connection charset, the charset/collation for every table (this requires changing the Doctrine mapping data), and migrating existing tables to the new charset/collation, and of course imposing MySQL 5.5 as the minimum supported version.

**Comment by zerocrates** [comment]
International support has long been one of our key selling points, so I think it's worth taking a good long look at this at least.

**Comment by zerocrates** [comment]
The version this would actually require at minimum is MySQL 5.5.3, released March 2010.

**Comment by zerocrates** [comment]
Of the hosts we've gathered data for, Dreamhost is the one that would be left out if we moved to PHP 5.5: they offer only 5.1.56.

They've had a minor kerfuffle over the fact that Moodle's newer versions require MySQL 5.5, but that hasn't budged them.

**Comment by zerocrates** [comment]
We have consensus that Dreamhost is acceptable collateral damage here.

**Comment by zerocrates** [comment]
- make doctrine generate utf8mb4 tables (w/ listener?)
- check/fix text column index sizes where they're too large

**Comment by buckett** [comment]
Is this worth documenting in the installation notes (README)?

**Comment by zerocrates** [comment]
Which part?

**Comment by buckett** [comment]
About creating your database as `utf8mb4`.

**Comment by zerocrates** [comment]
Are you having an issue related to this?

The database collation doesn't do much interesting if you specify each table's collation, which Omeka S does when it creates them.

**Comment by buckett** [comment]
Ah, ok, got it. Thanks. I'd missed the point that you were specifying the encoding when creating the tables.
