### ISSUE TITLE
Password constraints strings not translated

### ISSUE THREAD

**Issue by ManOnDaMoon** [omeka/omeka-s#1535]
Hello,

On password creation or modification forms, that is in the user administration panel or in a password-create view, the password constraints strings are not translated and are printed in english, although present and translated on Transifex.

I believe this is because the global string is dynamically constructed in `Omeka\Form\Element\PasswordConfirm::init()`?

Have a nice day

Laurent

**Comment by zerocrates** [comment]
Ah, you're correct, there is an issue there: the strings there are _marked_ as being translatable but they're not actually being translated by the system.
