### ISSUE TITLE
Generalize resource selector sidebar pattern introduced in #1462

### ISSUE THREAD

**Issue by kimisgold** [omeka/omeka-s#1536]
The `site-items` branch introduced another application of the resource selector sidebar (site attachment within the item form) that needed to be updated to the pattern introduced in #1462. 

The pattern features the following:

* After a resource has been added to the main form area, the total count and owner count of available resource updates.
* When removing a resource row, it disappears from the table in the main form area and becomes available in the right hand selector.
* The total counts in the selector sidebar update with each action.
* When all resources have been added to the main form area, a message appears in the sidebar notifies the user.

The pattern has been applied to the following areas on the `site-items-attachment-selectors` branch:
* item add/edit
  * sites
  * item sets
* site admin
  * user permissions
  * resources > item sets 

The branch should be ready for feedback. @zerocrates @jimsafley

**Comment by zerocrates** [comment]
My basic concern here is that the result doesn't really look refactored/generalized... I'm thinking of things like the new initializeSelector picking up the `rowTemplate` but so are all the individual ones. Ditto counting children/totals, etc. The red flag for me being that this is shared functionality used in 4 places but it's still a net increase of code.

**Comment by kimisgold** [comment]
Would it help if I actually deleted a bunch of the js made redundant by these changes (https://github.com/omeka/omeka-s/commit/2427c14bebc82b7a4e7b0ee50eb1533d3cb0b1ab)?

**Comment by zerocrates** [comment]
Yes. Yes it would.

Makes much more sense now.
