### ISSUE TITLE
Feature to add all items when attaching items to a block 

### ISSUE THREAD

**Issue by jimsafley** [omeka/omeka-s#1544]
We currently have a "Quick add" option where users can attach multiple items at once. While convenient, users can only select one page of the result set at a time. It would be even more convenient to have an option to simply "Add all" items of the entire result set.

**Comment by zerocrates** [comment]
I'm a little skeptical of the feature: an encouragement to add _so_ many items to a block that the pagination of the selection sidebar is an issue sounds like an invitation to problems that the attachment system isn't really designed for: in particular I'm thinking of issues with memory on both the admin and public sides, as well as UI issues simply displaying hundreds, thousands or more entries in a single block's attachments area.

**Comment by jimsafley** [comment]
I agree. We'll come up with a better solution where it is needed the most (in this case, the Mapping module).
