### ISSUE TITLE
Sites: Pages: Browse -- add a column that contains most recent edit date

### ISSUE THREAD

**Issue by sharonmleon** [omeka/omeka-s#1549]
Would be nice to see most recent edit date stamp on the pages browse table. Seems like there is plenty of room to the right of the slug column.

**Comment by Daniel-KM** [comment]
At the same time, isn't it possible to add a private/public button for pages?

**Comment by mebrett** [comment]
If there's room, date created would also be good. Of the two, last edited is more useful in the long run, I think.

**Comment by sharonmleon** [comment]
I think that you're probably right.
