### ISSUE TITLE
Rework .htaccess planned ?

### ISSUE THREAD

**Issue by thiboot** [omeka/omeka-s#1553]
Hello,

I'm preoccupied to serve Omeka S with a maximum security in Apache but the .htaccess packaged is very light. It seems to be a basic ZF3 with just in addition, rules to forbid .ini access and to delete trailing '/'.

https://github.com/omeka/omeka-s/blob/develop/.htaccess.dist

We can access all folders, log file, all others php files independently and errors are not catched to be redirected. Have you a .htaccess more efficient to block direct access to all non-public destinated files/folders ? With rewriting rules more secure ?

In my opinion we should not be able to access php|phtml|phps or log files directly, restrict access to system directories, shouldn't list content of some and correctly redirect erros catched like 403 or 500.

**Comment by zerocrates** [comment]
I'm not opposed to making some of the kinds of changes you're suggesting here...

You're right that the rules are basically the stock zf3 rules with some tweaking. On your concerns of access to php/phtml/phps, replacing the top set of rules with

```
RewriteCond %{REQUEST_FILENAME} -f
RewriteRule !\.(php[0-9]?|phtml|phps)$ - [C]
RewriteRule .* - [L]
```

should be sufficient, causing any bare directory paths or paths directly to php/phtml/phps files to be routed into the application instead. Listing contents of directories is an Apache configuration I don't think we need to mess with, but that same block of rules would cover that problem as well, since directories would be routed to Omeka S.

We could also expand the default deny rules to cover more things like the log folder.

I'm not sure what you're suggesting about redirecting errors, though.

**Comment by thiboot** [comment]
For errors, I'm not sure Omeka catches 403 if we deny access to a subfolder.
I was suggesting to add `ErrorDocument 403 https://my-website.com` for exemple

**Comment by thiboot** [comment]
I'm not familiar with rewriting rules
Replacing
```
# The following rule tells Apache that if the requested filename
# exists, simply serve it.
RewriteCond %{REQUEST_FILENAME} -s [OR]
RewriteCond %{REQUEST_FILENAME} -l [OR]
RewriteCond %{REQUEST_FILENAME} -d
RewriteRule ^.*$ - [L]
```
With
```
RewriteCond %{REQUEST_FILENAME} -f
RewriteRule !\.(php[0-9]?|phtml|phps)$ - [C]
RewriteRule .* - [L]
```
Lead to 500 error :-/
Is there a conflict with following rules ?

**Comment by zerocrates** [comment]
Let me check to see if I made some mistake there..

**Comment by zerocrates** [comment]
Okay, sorry about that: that suggestion was basically applying the rules of the Omeka Classic .htaccess to the Omeka S one, but the way the default Zend rules work mean things have to go slightly differently:

Try this in replacement of all the rewrite rules instead:

```
# The following rule tells Apache that if the requested filename
# exists, simply serve it.
RewriteCond %{REQUEST_FILENAME} -f
RewriteRule !\.(php[0-9]?|phtml|phps)$ - [C]
RewriteRule .* - [L]

# Strip any trailing slashes from incoming requests
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_URI} ^(.+)/+$
RewriteRule .* %1 [R=301,L]

# The following rewrites all other queries to index.php. The
# condition ensures that if you are using Apache aliases to do
# mass virtual hosting, the base path will be prepended to
# allow proper resolution of the index.php file; it will work
# in non-aliased environments as well, providing a safe, one-size
# fits all solution.
RewriteCond %{REQUEST_URI}::$1 ^(/.+)(.+)::\2$
RewriteRule ^(.*) - [E=BASE:%1]

RewriteCond %{ENV:REDIRECT_OMEKA_REQ} !"1"
RewriteRule ^(.*)$ %{ENV:BASE}index.php [E=OMEKA_REQ:"1",L]
```

**Comment by thiboot** [comment]
Yeah ! You are the best, it seems to work well on my primary tests :-)

**Comment by thiboot** [comment]
My final file with https redirect and 403 redirects for the .ini attempts

```
SetEnv APPLICATION_ENV "production"

RewriteEngine On
# Redirection to https permanently
RewriteCond %{HTTPS} off
RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]

# The following rule tells Apache that if the requested filename
# exists, simply serve it.
RewriteCond %{REQUEST_FILENAME} -f
RewriteRule !\.(php[0-9]?|phtml|phps)$ - [L]

# Strip any trailing slashes from incoming requests
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_URI} ^(.+)/+$
RewriteRule .* %1 [R=301,L]

# The following rewrites all other queries to index.php. The
# condition ensures that if you are using Apache aliases to do
# mass virtual hosting, the base path will be prepended to
# allow proper resolution of the index.php file; it will work
# in non-aliased environments as well, providing a safe, one-size
# fits all solution.
RewriteCond %{REQUEST_URI}::$1 ^(/.+)(.+)::\2$
RewriteRule ^(.*) - [E=BASE:%1]

RewriteCond %{ENV:REDIRECT_OMEKA_REQ} !"1"
RewriteRule ^(.*)$ %{ENV:BASE}index.php [E=OMEKA_REQ:"1",L]

# Block access to all .ini files.
<FilesMatch "\.ini$">
    <IfModule mod_authz_core.c>
        Require all denied
    </IfModule>
    <IfModule !mod_authz_core.c>
        Order Allow,Deny
        Deny from all
    </IfModule>
</FilesMatch>

ErrorDocument 403 https://my-site.org
```

**Comment by thiboot** [comment]
EDIT: i added NC to catch eventual .PHP etc.
`RewriteRule !\.(php[0-9]?|phtml|phps)$ - [NC,L]`
