### ISSUE TITLE
Inability to search the two character count

### ISSUE THREAD

**Issue by fofwisdom** [omeka/omeka-s#1557]
Omkea is searchable from 3 characters or more.
But most Asian languages function as words from 2 letters. Omeka is inconvenient to use multi-language.
Please consider improving the features.
So many thanks.
![주석 2020-05-09 170459](https://user-images.githubusercontent.com/205521/81467962-4784a580-9217-11ea-80e8-3db9a44b41b3.png)
![주석 2020-05-09 170508](https://user-images.githubusercontent.com/205521/81467965-494e6900-9217-11ea-83ef-73ae22290d5a.png)

**Comment by zerocrates** [comment]
The 3-character limitation comes from MySQL server defaults and we can't really change them from the Omeka side.

You might have some interest in [this forum thread](https://forum.omeka.org/t/using-mroonga-to-enable-full-text-search-of-cjk-text/10334) which goes over some options of changing the MySQL settings or the storage engine for the fulltext table to better support CJK search.

**Comment by fofwisdom** [comment]
Thanks for the advice!
