### ISSUE TITLE
Public listing of which pages within a site an item appears on

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#1562]
This provides the "missing link" of being able to search for items and find where they appear in context in the page content.

Could be controlled by a setting to enable/disable... unsure if this is necessary.

**Comment by jimsafley** [comment]
A caveat: the increased use of queries to "attach" items to blocks will make this list more and more incomplete. Instead of labeling the list "Pages", we could label it "Attached pages" or, more accurately, "Pages to which this item is attached" if we feel the distinction is worthwhile.

**Comment by jimsafley** [comment]
Added in 960f5e050cf59019a498dc47f955a090863fd034
