### ISSUE TITLE
Admin interface: Site sort by Owner does not behave as expected

### ISSUE THREAD

**Issue by triplingual** [omeka/omeka-s#1569]
When in our instance's Sites view, I select to sort by Owner Ascending, yet the owners, as shown in the partial screengrab, are not in consistent order, whether by visible name or by backing ID.
<img width="261" alt="Screenshot 2020-06-03 16 11 09" src="https://user-images.githubusercontent.com/1789625/83684447-08970500-a5b5-11ea-8fc7-3c13732618d3.png">

**Comment by zerocrates** [comment]
It looks like the Sites API (and therefore browse page) just doesn't support sorting by owner, so you're basically getting "some unspecified order" instead.

This looks like an oversight: the code for sorting by owner names is shared by all the "resource" types (items, sets, media) so someone (me, probably) must have assumed that the implementation of that was globally shared and didn't need reimplementing when we added the sort control for sites.

**Comment by triplingual** [comment]
Makes sense. It was too far off for it to be intentional. 😄
