### ISSUE TITLE
Add text/documentation link for error pages

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#1572]
We don't have an equivalent to the link to the codex about enabling error display on the default error pages.

**Comment by zerocrates** [comment]
Classic's: https://github.com/omeka/Omeka/blob/master/application/views/scripts/error/index.php#L33

**Comment by mebrett** [comment]
Is "To turn on detailed error messages which will help you understand what caused this error, see the  Omeka S User Manual page on <a href="https://omeka.org/s/docs/user-manual/errorLogging/">error logging</a>" too technical?

**Comment by zerocrates** [comment]
"To access the details of this error, follow the directions in the Omeka S User Manual page on error logging" ?

in terms of simpler

**Comment by mebrett** [comment]
"For more information on this error, follow the directions..." ?

**Comment by mebrett** [comment]
Or would that make people think that the documentation page would tell them about the error? Because some might read it that way. 
I'm also okay with just wholesale using what we have on Classic "To learn how to see more detailed information about this error,"
