### ISSUE TITLE
Seeking public feedback on new site attachment/search setup - 3.0.0-alpha

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#1581]
We're going to be making a 3.0.0-alpha release and announcing it publicly for feedback: indicate here what we're seeking feedback on specifically for inclusion in a blog post, etc.

**Comment by jimsafley** [comment]
Some initial notes on what we're seeking feedback on:

- The new, combined "Site admin" page of a site:
  - the "Info" section
  - the "Settings" section
- The new "Search type" site setting ("This site" or "All sites")
- The new cross-site ("All sites") search on sites
- The new cross-site search on the "top" route:
  - the fulltext search input
  - the fulltext "Search results for x" page
  - the "View all results" pages
  - the "Advanced item search" page
  - the item "Search results for x" page
