### ISSUE TITLE
JS assumes URL fragment is a recognized expression

### ISSUE THREAD

**Issue by jimsafley** [omeka/omeka-s#1582]
See https://github.com/omeka/omeka-s/blob/develop/application/asset/js/admin.js#L295

Note the `$('.section').filter(window.location.hash)` below. It assumes a URL fragment will always be a recognized expression. If it's not it will throw a `Syntax error, unrecognized expression` exception. In effect, this prevents other uses of fragments.

```js
if (window.location.hash && $('.section').filter(window.location.hash).length) {
    // Open the section that corresponds to the URL fragment identifier.
    Omeka.switchActiveSection($(window.location.hash));
}
```
There should either be a try/catch around the block, or a `.section` must exist in the page.

**Comment by zerocrates** [comment]
Hmm the presence/absence of a `.section` shouldn't be what matters here, more likely the "syntax" of the fragment.
