### ISSUE TITLE
Allow reordering of values when a property has more than one

### ISSUE THREAD

**Issue by sharonmleon** [omeka/omeka-s#1589]
I would like to be able to reorder values when there are more than one for an individual property. 

For example, I have two instances of the property "end date": 
- April 1796 
- May 7, 1795

I'd like to rearrange them into chronological order.

**Comment by zerocrates** [comment]
Well there's always copy and paste.

We've had a couple people ask for this on the forums also. I actually have thought about it a little... in the current system we use to submit values it should actually be somewhat easy to allow reordering (if I'm thinking about it correctly), with the main issue just being possible UI stuff, sorting handles and so on.

**Comment by sharonmleon** [comment]
Certainly, and in this case, just remaking the value is not a big deal, but I could see a case where you had a big list and wanted to shuffle them around.

**Comment by kimisgold** [comment]
I mistagged the commit, but the proper selector for the sortable handle should be in now: 7db4b27753d6fb24509c7eab32cecad6091279c4.

**Comment by zerocrates** [comment]
The issue with this is going to end up being that we don't actually store the order/position of values, we just insert/update them "in order," and there's no guarantee that they actually come back in that same order.

It's probably something where we'd only see an issue with really large sets of values, or after things like repairing/optimizing/restoring the values table.

We'd have to introduce a "position" column and sort on that when retrieving values to be actually assured of always getting back values in the order we set them, much as we do for the similarly-reorderable media.

**Comment by zerocrates** [comment]
Well I immediately take that back to some extent, we are ordering them by ID at present so there is _some_ defined order which should mostly handle this... I'll do some noodling around to see if it's enough to rely on by itself.
