### ISSUE TITLE
Change links/icons on admin dashboard for sites to be consistent with sites browse

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#1593]
On the Sites browse, the linked name goes to the "show" page for the site, and there's an icon for viewing the public page.

This is more or less reversed on the dashboard index page where the main link is to the public view and there's a pencil icon going to the edit info page.

Changing it so it aligns with the browse, so the name links to the admin show and there's a "view" icon for the public side, probably makes more sense here.

Coming from an observation by @kalbers

thoughts, @kimisgold, @mebrett ?

**Comment by mebrett** [comment]
I think changing the dashboard so that there's a view button rather than edit makes sense to me (or both, but with the name going to the edit). Consistency is a good practice for accessbility.
