### ISSUE TITLE
Site page feature requests

### ISSUE THREAD

**Issue by mebrett** [omeka/omeka-s#1602]
Two features which would be nice to have, from a project management standpoint (based on work on HtA). The use case is a project which is using Omeka S to build out a site, with multiple contributors, and which is continuing to add complex page content after the site has gone live/public. 

1. Adding a column for the date the page was created in the table at `site/s/sitename/page`, which allows project managers and site admins to quickly see what is the newest page added by a team member.
2. Ability to set a page either not public or to exclude it from site search. Useful for drafts of new content which aren't quite ready to go, being added to an already live site. At the moment, the only way (that I can think of) a site visitor would find these pages is through search.

**Comment by sharonmleon** [comment]
Related to issue #1549, which ask for edit date and issue #1361, which asks for a public/private check box for pages so that they can be reviewed by logged-in users in the public interface before going public.

**Comment by sharonmleon** [comment]
I don't know that we want to close this yet. Accumulating interest, etc.

**Comment by Daniel-KM** [comment]
The second point is fixed in #1603.

**Comment by Daniel-KM** [comment]
I added a date column in #1615.
