### ISSUE TITLE
"mergeValuesJson" plugin not found error when adding items

### ISSUE THREAD

**Issue by GhastlyParadox** [omeka/omeka-s#1605]
Greetings - I'm currently encountering a strange Zend framework error below when attempting to add items (any item). I followed the stack trace, and I found MergeValuesJson in `application/src/Mvc/Controller/Plugin`, but for some reason it's throwing the not found error. I've uninstalled the handful of plugins I had installed, but unfortunately that didn't help. 

Any thoughts/suggestions much appreciated. Thanks!

--

` Zend\ServiceManager\Exception\ServiceNotFoundException
A plugin by the name "mergeValuesJson" was not found in the plugin manager Zend\Mvc\Controller\PluginManager

Details:

Zend\ServiceManager\Exception\ServiceNotFoundException: A plugin by the name "mergeValuesJson" was not found in the plugin manager Zend\Mvc\Controller\PluginManager in /var/www/html/omeka-dev.lsait.lsa.umich.edu/vendor/zendframework/zend-servicemanager/src/AbstractPluginManager.php:142
Stack trace:
#0 /var/www/html/omeka-dev.lsait.lsa.umich.edu/vendor/zendframework/zend-mvc/src/Controller/PluginManager.php(97): Zend\ServiceManager\AbstractPluginManager->get('mergeValuesJson', NULL)
#1 /var/www/html/omeka-dev.lsait.lsa.umich.edu/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(259): Zend\Mvc\Controller\PluginManager->get('mergeValuesJson', NULL)
#2 /var/www/html/omeka-dev.lsait.lsa.umich.edu/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(274): Zend\Mvc\Controller\AbstractController->plugin('mergeValuesJson')
#3 /var/www/html/omeka-dev.lsait.lsa.umich.edu/application/src/Controller/Admin/ItemController.php(201): Zend\Mvc\Controller\AbstractController->__call('mergeValuesJson', Array)
#4 /var/www/html/omeka-dev.lsait.lsa.umich.edu/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(78): Omeka\Controller\Admin\ItemController->addAction()
#5 /var/www/html/omeka-dev.lsait.lsa.umich.edu/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#6 /var/www/html/omeka-dev.lsait.lsa.umich.edu/vendor/zendframework/zend-eventmanager/src/EventManager.php(179): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
#7 /var/www/html/omeka-dev.lsait.lsa.umich.edu/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(106): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#8 /var/www/html/omeka-dev.lsait.lsa.umich.edu/vendor/zendframework/zend-mvc/src/DispatchListener.php(138): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#9 /var/www/html/omeka-dev.lsait.lsa.umich.edu/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#10 /var/www/html/omeka-dev.lsait.lsa.umich.edu/vendor/zendframework/zend-eventmanager/src/EventManager.php(179): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
#11 /var/www/html/omeka-dev.lsait.lsa.umich.edu/vendor/zendframework/zend-mvc/src/Application.php(332): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#12 /var/www/html/omeka-dev.lsait.lsa.umich.edu/index.php(21): Zend\Mvc\Application->run()
#13 {main}`

**Comment by zerocrates** [comment]
Check out this thread from the forums:

https://forum.omeka.org/t/creating-resource-failer-via-admin-interface/11594

Can you check that same file and line mentioned there?

**Comment by GhastlyParadox** [comment]
Ah yep, that did the trick - thanks!
