### ISSUE TITLE
Friendlier error pages

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#1616]
Particularly the ones that are displayed when error display is not enabled.

**Comment by zerocrates** [comment]
focus on 404s specifically

**Comment by zerocrates** [comment]
@mebrett what are we thinking in terms both of additional text (or any text at all) and of changing the heading?

I'm thinking of 404 here mostly, but 403 and the general error page are also in scope here I suppose. We just added text on the general error page so we should be okay there.

**Comment by mebrett** [comment]
WCAG guidelines for accessible error messages say that they should "be easy to understand and should provide simple instructions on how they can be resolved." The thing our pages don't do right now is give an idea of what actions the Visitor User can take when they hit a 404.  Our usual "here's how to turn on error logging" is great for people with access to the backend, but less helpful for someone browsing a site.

I'd say we do two things - one is add a little bit more language, along the lines of "use back button, if you think you hit this in error please contact site admin". And the other is to document somewhere (developer docs?) how people can tweak this language to point to a contact us page if they have one.
