### ISSUE TITLE
Referencing operation/state dynamically in message prevents correct translation

### ISSUE THREAD

**Issue by nebulon42** [omeka/omeka-s#1625]
The following message is problematic for translation:
https://github.com/omeka/omeka-s/blob/bdbf5eca1a2f9f6589895d9a7018756ed2d58fdb/application/src/Api/Manager.php#L209
When referencing the operation dynamically in the error message it is not possible to provide a grammatically correct translation for some languages e.g. German. If I understand it correctly the operation name will be always in English?

This would need adjustment in code. There is another occurrence of this message.
I also found plenty of other messages that use the same pattern e.g.
https://github.com/omeka/omeka-s/blob/bdbf5eca1a2f9f6589895d9a7018756ed2d58fdb/application/src/Module/Manager.php#L170
where the state is referenced dynamically.

Edit: Those might all be exception messages? Maybe best to not translate them at all?

**Comment by Daniel-KM** [comment]
A similar issue is when the placeholder is used for the resource type and may be singular or plural : "item", "item set", "media". Ideally, the singular and plural labels should be available somewhere, for example in representation.

**Comment by zerocrates** [comment]
These are indeed error messages. Could the grammar issue be resolved if translated along the lines of 'Permission denied for the current user to perform the operation "%1$s" on the resource "%2$s"' ?

Simply not translating the error messages at all is an option, but not currently the path we've been taking.

**Comment by nebulon42** [comment]
I think I should have been a bit more precise in my wording. For me the most important consideration is if the message shows up in the UI or just in a log file. If the latter is the case I thought it might be possible to not translate it at all as the system administrators anyway need a bit of proficiency in English. For users I think both completely translated messages with correct grammar should be provided.

@zerocrates your suggestion for resolving the grammar problem is what I have done so far despite it deviates from the source message. But my concern here would still be that that the operation would still be in English? Here again I think the distinction between log file and user facing message is important. For a log file the message partly being in English would be acceptable, but then again I'm wondering if it would be necessary to translate the message at all.

**Comment by zerocrates** [comment]
These kinds of messages can appear on the interface, but generally only if the site is configured to display errors, which is not the default.

**Comment by jimsafley** [comment]
We don't currently plan on addressing this issue. Feel free to reopen and elaborate should you want further discussion.
