### ISSUE TITLE
Site Blocks: Browse preview carousel

### ISSUE THREAD

**Issue by sharonmleon** [omeka/omeka-s#1636]

**Comment by matthewjmckinley** [comment]
Make carousel a separate module: either select items individually, or from a search string

**Comment by Daniel-KM** [comment]
The module [BlockPlus](https://gitlab.com/Daniel-KM/Omeka-S-module-BlockPlus) has such a feature. 

The main point of this module is to be able to use multiple templates by block, so it's easier for the designer to create multiple designs with the same block. Maybe can it be implemented directly in the core. If yes, I can open a pr here.

**Comment by sharonmleon** [comment]
Thanks, @Daniel-KM. We've got an implementation of this almost ready to be pushed. We'll get that in and then we can go from there for enhancements, etc.
