### ISSUE TITLE
Alt Text Everywhere

### ISSUE THREAD

**Issue by sharonmleon** [omeka/omeka-s#1642]
Check issue request: [https://github.com/zerocrates/AltText/issues/3](context specific alt text)
No coverage for assets

**Comment by sharonmleon** [comment]
- Allow input of Alt Text on asset upload
- Add Assets area to the main admin menu so that Alt Text can be edited.

**Comment by drjwbaker** [comment]
So glad this is happening. Can/should/will Alt Text handling in Omeka S interact with csv import https://omeka.org/s/modules/CSVImport/ or Bulk Edit https://omeka.org/s/modules/BulkEdit/? My use case - should it be of interest - is that I have images in an Omeka S site and I'm looking to use the data in the dc:description field to populate the Alt Text without doing in manually. Happy to help test if you need testers. Thanks!

**Comment by zerocrates** [comment]
@drjwbaker There's a sub-feature here to have this pull alt text from the metadata values (of the _media_), so your description suggestion would work (and does work with the AltText module currently).
