### ISSUE TITLE
Put an HTML editor on HTML Media Type

### ISSUE THREAD

**Issue by patrickmj** [omeka/omeka-s#165]
Writers will want a standard HTML editor (e.g., TinyMCE or FCKEditor or something) on the HTML Media type.

Needs some JS infusion on Media add/edit pages, invoked based on selection of HTML Media type

**Comment by zerocrates** [comment]
I would lean toward CKEditor rather than TinyMCE (and I think FCKEditor is actually the old version), but nobody's looked into this in depth
