### ISSUE TITLE
Release order of modules

### ISSUE THREAD

**Issue by Daniel-KM** [omeka/omeka-s#1658]
The releases are not ordered by last version on omeka.org (see https://omeka.org/s/modules/Log/).

**Comment by zerocrates** [comment]
That's interesting...

I presume the issue is that we're using semver sorting and it doesn't know what to do with the fourth digit there.

**Comment by zerocrates** [comment]
OK, I've made a tweak that should resolve this specific case.

I'd generally recommend sticking to the semver X.Y.Z pattern, though. We use semver tooling in a few places and it generally doesn't deal with "extra" version parts reliably (in this case, the 4th "digit" is being treated as build metadata which by the spec doesn't contribute to ordering).
