### ISSUE TITLE
More robust site list: Allow for image assets and perhaps other metadata

### ISSUE THREAD

**Issue by sharonmleon** [omeka/omeka-s#1663]
Allow for image assets and perhaps other metadata

**Comment by matthewjmckinley** [comment]
With Site List Thumbnail merged, is this finished? Is there other metadata we want to display with sites?

**Comment by kimisgold** [comment]
On the `site-list-thumbnail` branch, test the following:

* The site list block renders site titles linking to the respective sites.
* The block renders thumbnails with the site titles when the option is active.
* The block shows summaries when the option is active.
* The block shows bottom pagination when the option is active and there is a maximum limit assigned.
* Each of the sorting options displays sites in the expected order.

@georgiawebgurl

**Comment by sharonmleon** [comment]
@kimisgold Can I get a refresh on where this is? There isn't a site-list-thumbnail branch any longer, but the site list block appears not to be updated on develop.

**Comment by matthewjmckinley** [comment]
Here's the PR/commits https://github.com/omeka/omeka-s/pull/1712 and the code looks to be in place on develop

**Comment by sharonmleon** [comment]
Okay. There it is. Odd. I'll pull again.

**Comment by sharonmleon** [comment]
@kimisgold All looks good. Tested on Mac OS (11.4) on newest Firefox, Safari, and Chrome for all current themes. Also, Firefox on Google Pixel 4.

Text is wrapping around thumbnails. Not sure if that is expected or if it should hang.

**Comment by sharonmleon** [comment]
@georgiawebgurl @dth1692 Could you check this on a PC? Make sure you're using the most recent pull of the develop branch on the Omeka S core, and all the regular themes.

**Comment by sharonmleon** [comment]
@kimisgold Another question here from testing. Should the size of the thumbnails be constrained for consistency? In the site context, should the thumbnails be governed by the parameters that control the item thumbnails?
