### ISSUE TITLE
Queue mechanism

### ISSUE THREAD

**Issue by Daniel-KM** [omeka/omeka-s#1669]
With some of my last modules, some cpu-intensive work is done in the background in a simple way for the user: tiling with [Image Server](https://gitlab.com/Daniel-KM/Omeka-S-module-ImageServer), audio/video conversion with [Derivative Images](https://gitlab.com/Daniel-KM/Omeka-S-module-DerivativeMedia), so when the import is done in bulk or by multiple people, or on a shared host, the server may hang or kill them.
So for heavy processing, the dispatcher should be replaced by a queue. Or do you think there is another way?

**Comment by zerocrates** [comment]
In Classic we have a dispatcher for beanstalkd to do a queue if sites want to set it up that way... I imagine we'd not want to do beanstalkd at this point, but I'm not sure. The dispatcher is pluggable so this could be a module I guess.

**Comment by zerocrates** [comment]
One other option, though maybe not the most efficient one, could be to have an import process switch jobs that are dispatched from within the main import job to synchronous mode, so instead of an import cheerfully throwing off 100 simultaneous video render jobs or something like that, it would only process one at a time.

**Comment by Daniel-KM** [comment]
I'm searching for a pure php solution, because usually, admin don't read the docs and users (or the next substitute) don't know that wav is not a good format for web. I see that there is a package for laminas. For media derivative, i updated the module to process the job by item instead of media, but it doesn't fix bulk import.

**Comment by zerocrates** [comment]
I can definitely see the utility of a queue, I'm just not sure how feasible a system that doesn't involve any outside moving parts to handle the queuing and execution is. Those simpler solutions are what we like to aim for but I don't have any great ideas for one here.
