### ISSUE TITLE
Lang tags should be compared case insensitively

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#1672]
BCP 47 2.1.1 calls for language tags to be treated as case insensitive at all times.

We get some case insensitivity for free from our MySQL collation, but in places where we're doing comparisons in PHP code, we're currently case-sensitive. I'm thinking particularly of the "lang" option for `value()` in representations

**Comment by Daniel-KM** [comment]
Isn't the point to save it as lowercase instead of fixint it anywhere?

**Comment by zerocrates** [comment]
The issue there I think is that there _is_ conventional capitalization of things like region and script parts, so if we force it to lowercase on input, I feel like we'll hear from people who want it presented "correctly".

As far as the database is concerned, they're already compared insensitively, because of the standard ci collation being used. It's just that here we're doing the comparison with PHP.

**Comment by Daniel-KM** [comment]
I pushed a fix for that, i don't find any other place where the lang is checked.

**Comment by zerocrates** [comment]
Yes, that commit is basically what I'd planned to do (though the lang codes are defined to be ascii-only so we should be able to just do plain `strtolower` here)

**Comment by Daniel-KM** [comment]
I updated the pr.
