### ISSUE TITLE
Backend: Page Block - quick select ItemSets (Feature Request)

### ISSUE THREAD

**Issue by m-art-in** [omeka/omeka-s#1679]
There is the nice function to add items to a page block with "*quick add*" as attachments to a block element, e.g. at the block element "Item showcase".

This fine for items.

 Now I am looking for a way to select ItemSets in the same way. Would it be possible to provide such a functionality soon?
 
 Edit: I just saw the Pull Request for Pages: #1666 This would be similiar to List ItemSets, or?!

**Comment by zerocrates** [comment]
To clarify, you're looking to do this attachment to a block in a site? So it's not so much about Quick Add so much as just being able to attach them at all?

**Comment by m-art-in** [comment]
That's right of course: it doesn't only refer to the element "item showcase" but would be a general feature. Would this be possible? It is not clear to me at which point in the Omeka code/core the "quick add" is generated?

**Comment by jimsafley** [comment]
We'll look into adding quick-add for item sets (#1350). As for having a page block that attaches item sets instead of item, that's something that we don't currently plan to implement. Feel free to reopen and elaborate should you want further discussion.
