### ISSUE TITLE
Select a default resource template for users

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#168]
We had a somewhat contentious conversation about this feature several weeks ago but I don't think the results got recorded anywhere.

Should there be a setting that controls the default resource template selection for new items:
- On a global, site-wide basis (controllable by global admins)
- On a per-user basis (controllable by each user)
- Both?

**Comment by zerocrates** [comment]
This also ties in with related discussion about either removing the currently-hardcoded Title and Description defaults, or transforming them from a de facto default template to an actual template.

**Comment by patrickmj** [comment]
Don't know if it is possible, but site-specific default template seems to make the most sense. A site will often enough be about a particular kind of object, and so the default template should reflect the choices for how to represent such objects in the way the site builders interpret them.

**Comment by kalbers** [comment]
Assuming that all resource templates are shared among all users, then I think allowing the choice for one to be chosen by each user as the default template makes the most sense. It's easy enough for all of the members of a team working on a single site to choose the same template.

**Comment by jimsafley** [comment]
I think this is a feature we can implement at a later date. If we are to do something at this stage, I can see some benefit in including a "Basic Template" that includes `dcterms:title` and `dcterms:description`, and setting that automatically to new resources. This is similar to what we have now, but requires less specialized code to include title and description during page load.

I'm not averse to the idea of default template customization, I just think it's something we can add later.
