### ISSUE TITLE
Mailer: 'from' in default_message_options overriden by administrator_email

### ISSUE THREAD

**Issue by jajm** [omeka/omeka-s#1685]
Hi,

I just stumbled upon these lines:
https://github.com/omeka/omeka-s/blob/f7a5cadaa2d7c02fd256eb89aeb9694d7b4a9dee/application/src/Service/MailerFactory.php#L29-L32

Which I understand as  "If `administrator_email` is not set, then set `from`". It looks like it's not the intended behaviour. Shouldn't it be: 

```php
if (!isset($defaultOptions['from'])) {
```
?

**Comment by zerocrates** [comment]
I think you're right about that. I'll check into it some more but I believe you're correct about what's intended there.

**Comment by zerocrates** [comment]
Yes, it was definitely a bug/typo.

**Comment by jajm** [comment]
Thanks for fixing it :)
