### ISSUE TITLE
Expose Omeka ID on Item Pages 

### ISSUE THREAD

**Issue by sharonmleon** [omeka/omeka-s#1687]
Can we print the Omeka ID on the Admin item page, and make it visible to the sidebar search for linking of resources as values?

**Comment by zerocrates** [comment]
So, it's "available" in the search sidebar in one sense: you can search by ID to find a specific item.

We could certainly add the ID to the sidebar of the item show pages... I don't necessarily want to expose it as conspicuously as in Classic, right in the title and places like that.

**Comment by sharonmleon** [comment]
I think adding the ID to the item show page in an inconspicuous way would be a help.

**Comment by sharonmleon** [comment]
I wonder if we might boost this to slide it into the next minor release?
