### ISSUE TITLE
UI: Query form element

### ISSUE THREAD

**Issue by jimsafley** [omeka/omeka-s#1693]
The [query-element](https://github.com/omeka/omeka-s/tree/query-element) branch introduces a new form element that standardizes the query building process that has become prevalent. With it, a user can build a query using an inline advanced search form instead of copying the URL's query string from the browse page.

You can test the element by adding the "Browse preview" block to a site page. You'll see an empty text input and three buttons: Edit, Restore, and Clear.

- The "Edit" button will open a sidebar containing the advanced search form.
- The "Restore" button will restore the query to its original state (this is helpful during an accidental "Clear" or "Set query"). **Do you think this button is needed?**
- The "Clear" button will clear the text input. **Do you think this button is needed?**

After pressing the "Edit" button you'll see the advanced search form open in a sidebar. **Given the narrow width in which the form has to fit, the styling will need your attention.** The search interface should operate as normal. At the bottom of the form you'll see three buttons: Set query, Preview query, and Reset form.

- The "Set query" button will create a query based on the current state of the search form and copy it to the text input in the originating form. You'll notice that the query string is still available to the user to edit directly and copy. **Can you think of a better way to allow users to edit/copy without showing the query?**
- The "Preview query" button will open another sidebar containing a paginated list of items that represent the current state of the form. **This sidebar will need your styling attention as well.**
- The "Reset form" button will reset the search form to an empty state. **Do you think this button is needed?**

**Comment by kimisgold** [comment]
I like the "Restore" button for the reasons you cited, while "Clear" is the least necessary. The user can manually delete what's in the text field, and I like simplifying the number of actions we present to the user. Within the query editor sidebar, I do think the "Reset" form button is useful, particularly in instances where users are experimenting with the query building.

For an interface that doesn't show the query, I mocked up an interface that mimics the search filter display on browse views. 

![image](https://user-images.githubusercontent.com/606764/110378993-446b6900-8024-11eb-94af-44209c60c325.png)

The user would mainly see this query visualization and use the edit sidebar to configure. Users who want to copy/paste a query string could toggle the visibility for the input (via the "Show query string" button), after which we'd probably need some kind of ajax interaction to update the filter display.

This is a concept for improving the interface, but I do think what's already on the branch is a big improvement over the simple text input.

**Comment by jimsafley** [comment]
I've implemented the search filter display and the show/hide query string feature. The interface will likely need a touch up due to these changes.

**Comment by kimisgold** [comment]
I'll make those adjustments. In the meantime, I'd like to discuss the interaction between the query string input and what I'll call the "pretty filters" for the moment. In implementation, my concern is that users editing the query string in the input would expect to see the changes reflected in the pretty filters. it looks like it currently works in one direction, where updates to the pretty filters update the query text input, so I'm mainly looking for it to function both ways. Here are my current ideas:

1. Show live updates in the pretty filters as the user changes the text. However, this seems like a lot of work and finicky to implement.
2. When the user shows the query string input, the pretty filters are toggled hidden. If the user chooses to toggle the pretty filters back on, the query string input is hidden and we do a one time update of the pretty filters based off the value within the query string input.
3. We set the toggle to show only the pretty filters or the query input string, and document that the form will use only whichever is active and visible on submission.

For both ideas 2 and 3, we would probably want to deactivate the "edit" button while the query string input is open so there's no confusion.

What do you think? Also sorry in advance if you're already addressing this and I'm overthinking things.

**Comment by jimsafley** [comment]
The "Clear" button now appears only when there's a query string to clear. There was discussion of moving the button to the same line as the filters. Would you do this, @kimisgold?
