### ISSUE TITLE
Select All in Attachment sidebar 

### ISSUE THREAD

**Issue by georgiawebgurl** [omeka/omeka-s#1695]
Consider as an enhancement to the Attachment sidebar:
Change ‘Quick add’ to ‘Select multiple’ and add a button to ‘Select all’ 

This came out of a discussion about adding multiple images in the carousel browse and what might be an more efficient workflow. 
Thanks!

**Comment by kimisgold** [comment]
This feature is ready for a look on the `select-all-sidebar` branch.
