### ISSUE TITLE
.htaccess File Missing

### ISSUE THREAD

**Issue by covertmichael** [omeka/omeka-s#1697]
I could be missing something but I am getting errors when I try to access any of my items in item sets. I am trying to turn on error reporting but I am not seeing the .htaccess file that is reference in the support documentation. Would someone be able to assist me?

**Comment by sharonmleon** [comment]
Usually, we field these kinds of questions on the [forums](forum.omeka.org/), but I suspect that your system settings are hiding the files that are preceded by the "."
