### ISSUE TITLE
XSS vulnerability in search

### ISSUE THREAD

**Issue by drbauder** [omeka/omeka-s#1698]
Hitting /search/results?fulltext_search=%3C%2Fscript%3E%3Cscript%3Ealert(%22Hello%22);%3C%2Fscript%3E reveals an XSS vulnerability.

**Comment by zerocrates** [comment]
Thanks for the report.

**Comment by drbauder** [comment]
You're welcome! Is there any chance you'll be distributing a new release soon, or can you issue a patch for this? Our IT department won't allow us to deploy this in production while this vulnerability exists.

**Comment by zerocrates** [comment]
The patch is the commit itself: you can get it easily [in patch form](https://github.com/omeka/omeka-s/commit/05ac39a74067724fb5982016f1c9253486d2ceaa.patch)

There should be a release containing it relatively soon, but I can't give you any firm date.

**Comment by drbauder** [comment]
Thank you!
