### ISSUE TITLE
Advanced Search: properties from custom LOD vocab not appearing in menu

### ISSUE THREAD

**Issue by sharonmleon** [omeka/omeka-s#1700]
I'm using the public-facing advanced search in a site to gather data about the usage rate of some properties in my project's ontology testing. To do so, I'm selecting the property and setting it to "has any value" and then selecting the class with which property is used. 

The properties that come from the vocabulary that I created by hand are not available to select from the dropdown menu. Those properties are available from the menu if I am using the advanced search in admin interface. Not sure if this is about the way I made the vocab, or about the way that the advanced search interface works.

**Comment by jimsafley** [comment]
In site settings under the "Search" section, do you have any "Templates" selected? If you do, only those properties that are assigned to those templates will be available in the advanced search form.

**Comment by sharonmleon** [comment]
There we go. I was missing a template. Sorry about the false alarm.
