### ISSUE TITLE
Testing: Query form element

### ISSUE THREAD

**Issue by jimsafley** [omeka/omeka-s#1701]
The [query-element](https://github.com/omeka/omeka-s/tree/query-element) branch introduces a new form element that standardizes the query building process that has become common. With it, a user can build a query using an inline advanced search form instead of copying the URL's query string from the browse page.

You can see the element in four places:

- Site > Resources > click "Add," "Replace," or "Remove"
- Site > Pages > Page > "Browse preview" block
- Site > Navigation > "Browse" custom link
- Site > Navigation > "Browse item sets" custom link

You should see two buttons: "Edit" and "Advanced edit." Clicking "Edit" should open a sidebar containing an advanced search form. At the bottom of the sidebar you should see three buttons:

- "Preview": Click this button to preview the search (it should open another sidebar)
- "Reset": Click this button to reset the advanced search form (it should clear the form)
- "Apply": Click this button to apply the current search parameters to the query element (it should close the sidebar)

Once applied, the query element should show a visual filter that represents your search. You should see two additional buttons:

- "Restore": Click this button to restore the query to its original state
- "Clear": Click this button to clear the query

Click the "Edit" button again to open the advanced search sidebar. The form should be "sticky" - that is, it should reflect the same parameters that you entered before. Make a few more changes and click "Apply." Same as above, you should see any additional search parameters reflected visually.

Now save the entire form and the query should have "stuck" in the query element. After saving, you should see the "Clear" button, but not the "Restore" button. Only if you change the original state of the query should you see the "Restore" button.

Click "Advanced edit" and you should see an editable text input containing your query string as well as two buttons:

- "Apply": Click this button after modifying the query string to apply it to the query element
- "Cancel": Click this button to cancel advanced edit (any change you made to the query string should be discarded)

In general, test the element everywhere it exists, make changes, click all the buttons, and evaluate based on expected behavior.

**Comment by jimsafley** [comment]
Once tested and merged, remember to close #1639, #1693, and #1696.

**Comment by georgiawebgurl** [comment]
Testing is still in progress.

**Comment by georgiawebgurl** [comment]
Problems encountered:

- Edit search sidebar/panel scales oddly in Windows 10 Chrome 89.0.4389.90 (Official Build) (64-bit): When browser is resized to less than full screen and/OR the font size is set to greater than 100%
![image](https://user-images.githubusercontent.com/14911873/113070118-d6801080-918f-11eb-90f5-65b3da3a1444.png)
- Sites>Resources in Windows 10 Chrome 89.0.4389.90 (Official Build) (64-bit); Firefox 87.0 (64-bit) >After clearing search & refresh of page,  the search interface does not always appear in full
 ![image](https://user-images.githubusercontent.com/14911873/113070347-5b6b2a00-9190-11eb-937b-dd67f65c672f.png)
- Site>Navigation>Browse item sets custom link in  Windows 10 Chrome 89.0.4389.90 (Official Build) (64-bit); Firefox 87.0 (64-bit); Edge Version 89.0.774.63 (Official build) (64-bit); Android 11 - Did not work for me. 

 - I thought the search fulltext would search within a set, but instead it only searches the name of the set (?) If I search by the set name or set owner, I do see the Set title. Once I was able to identify a set, the results displayed did not show the items in the set. 
![image](https://user-images.githubusercontent.com/14911873/113070849-86a24900-9191-11eb-8d98-e694788862d0.png)
 - Public view of link/results (there are 25 public items in this set)
![image](https://user-images.githubusercontent.com/14911873/113070988-cff29880-9191-11eb-87fe-e757f60381bc.png)

Suggestions for consideration: 
Edit search sidebar/panel:
- After Preview of a search, have an 'Apply' or 'Accept search' button that appears after preview to set/apply/accept preview as search.
- Cancel: After Cancel of the Advanced edit, keep Advanced edit box open to make it easy for users to see that the search string was reverted back to its previous state.  
- Continue discussion of terminology and consistent application of terminology across functional areas.

**Comment by jimsafley** [comment]
This branch introduced a regression. In site resources, the item sets interface does not display assigned item sets or allow item sets to be added. It's likely a consequence of moving the JS around.

**Comment by zerocrates** [comment]
Clarification for a couple of these points: the item sets browse only searches metadata of sets, and only returns sets themselves, by design. It's not intended to include the items in the results or anything like that.

**Comment by jimsafley** [comment]
Responding to testing feedback:

> Edit search sidebar/panel scales oddly in Windows 10 Chrome 89.0.4389.90 (Official Build) (64-bit): When browser is resized to less than full screen and/OR the font size is set to greater than 100%

@kimisgold Would you look at this?

> Sites>Resources in Windows 10 Chrome 89.0.4389.90 (Official Build) (64-bit); Firefox 87.0 (64-bit) >After clearing search & refresh of page, the search interface does not always appear in full

On page load, the query element should be hidden until the user chooses Add, Replace, or Remove. Or am I misunderstanding the problem?

> Site>Navigation>Browse item sets custom link in Windows 10 Chrome 89.0.4389.90 (Official Build) (64-bit); Firefox 87.0 (64-bit); Edge Version 89.0.774.63 (Official build) (64-bit); Android 11 - Did not work for me.

I pushed some changes to the branch that should make the preview have expected results. Pull and try it again. Remember that the preview should only have item sets that are assigned to the site in Site > Resources.

> After Preview of a search, have an 'Apply' or 'Accept search' button that appears after preview to set/apply/accept preview as search.

@kimisgold Should the preview sidebar include an Apply button that circumvents the search sidebar's Apply button? My concerns are a) where we would place it and b) whether there's value in applying a query outside of the search form.

> Cancel: After Cancel of the Advanced edit, keep Advanced edit box open to make it easy for users to see that the search string was reverted back to its previous state.

@kimisgold Should the advanced edit interface remain visible when the user clicks the Cancel button? My concern is that it would then be an "undo" button, which comes with presumptions of its own that are not easy to implement.

> Continue discussion of terminology and consistent application of terminology across functional areas.

My only question (and it's an important one) is whether we should label the query elements "Query" or "Search". Whatever we decide, it should be consistent across Omeka.

**Comment by jimsafley** [comment]
@zerocrates That was fixed in a0d9011e56d91919287ec1a57fe2c62cae648619

**Comment by zerocrates** [comment]
Yeah, confirmed, I was unknowingly looking at an older version

**Comment by georgiawebgurl** [comment]
Ok, this sounds good - the item browse issue was that it didn't seem to find my items. So, it found the set, but didn't display any items.  They are assigned to my site in a collection and as part of the Resources.  I will pull and test again. Thanks!

**Comment by georgiawebgurl** [comment]
Ok, this seems resolved or it might have been a glitchy thing (but I was able to repeat it several times in Chrome with the query element branch before a0d9011) - #Edit search sidebar/panel scales oddly in Windows 10 Chrome 89.0.4389.90 (Official Build) (64-bit): When browser is resized to less than full screen and/OR the font size is set to greater than 100% 
It seems fine now.  Screenshot below is at 45% browser screen width and 125% font. Font is the same Arial / sans serif UTF 8 as before. 

![image](https://user-images.githubusercontent.com/14911873/113206427-72b42100-923d-11eb-99c3-36814f20ebb2.png)


> > Edit search sidebar/panel scales oddly in Windows 10 Chrome 89.0.4389.90 (Official Build) (64-bit): When browser is resized to less than full screen and/OR the font size is set to greater than 100%
> 
> @kimisgold Would you look at this?

**Comment by georgiawebgurl** [comment]
@jimsafley  > Sites>Resources in Windows 10 Chrome 89.0.4389.90 (Official Build) (64-bit); Firefox 87.0 (64-bit) >After clearing search & refresh of page, the search interface does not always appear in full 

On page load, the query element should be hidden until the user chooses Add, Replace, or Remove. Or am I misunderstanding the problem?

That was the problem, it seems and it was repeatable in both Chrome and Firefox prior to the branch update.  The query element was showing up but only partially (just the advanced edit box). It seems to be working properly now in Chrome and Firefox with the query element disappearing.

**Comment by georgiawebgurl** [comment]
Browse item sets works as expected in Chrome, Firefox, and Edge. I do think this may need some guidance about troubleshooting. :-)

**Comment by jimsafley** [comment]
Implemented in #1707
