### ISSUE TITLE
CKEditor implementation questions

### ISSUE THREAD

**Issue by patrickmj** [omeka/omeka-s#171]
CKEditor seems much easier to work with than tinyMCE. But, some questions come up:

* Include code in release, or just link to their code?
* What pages to make it available on?
* Where to put configuration, and how to include it (related to above)?
* What to include in the toolbar?
  * Toolbar options: http://ckeditor.com/forums/CKEditor/Complete-list-of-toolbar-items

**Comment by zerocrates** [comment]
> Include code in release, or just link to their code?

Meaning that they have a CDN version somewhere?

**Comment by patrickmj** [comment]
yep. //cdn.ckeditor.com/4.4.7/standard/ckeditor.js

**Comment by zerocrates** [comment]
I'd say:

* include the code
* for now, just case-by-case use on pages using it
* config can probably go in module config and be json-ified for use on the page, a view helper could run two `headScript->append`s, one for the editor include itself, the other setting the options
* undetermined, leave the ugly too-big toolbar for the time being and we'll come back to it
