### ISSUE TITLE
Creating and Maintaining Docker Image and K8s cluster Deployment Template

### ISSUE THREAD

**Issue by sunnythepatel** [omeka/omeka-s#1713]
Hi Team,
I was hoping to maintain and create a docker image and Kubernetes template for the omeka-s image. I have created a template is there any way I can add or include it over here. Can you please let me know? I have seen the image provided by you on Docker isn't being managed by anyone.
https://github.com/sunnythepatel/omeka-s-docker-image

Thank you and hope to hear from you.

**Comment by zerocrates** [comment]
Same resolution here as for omeka/omeka#950, that I don't think we'd want to bestow official status on anything.
