### ISSUE TITLE
Even trigger of Site Settings 

### ISSUE THREAD

**Issue by alexdryden** [omeka/omeka-s#1718]
There isn't currently a event for the [site settings form](https://github.com/omeka/omeka-s/blob/5a35a335c6b90f44749ae4b8fb194919bca46f66/application/view/omeka/site-admin/index/edit.phtml#L41). Would it be possible to add before and after events for this form? I have a module that needs access here.

**Comment by zerocrates** [comment]
Are you looking to add things to that form?

The form itself has `form.add_elements` and `form.add_input_filters` events to allow that.

**Comment by alexdryden** [comment]
I'm wanting to change the `Auto-assign new items` field. The module manages how items, users and sites are associated, so I wanted to remove/disable or at least add a disclaimer in the description so that our authors aren't confused by it.

**Comment by alexdryden** [comment]
Oh, I see how it works now. Yeah I think I should be able to do anything I need with `form.add_elements`. Thanks!
