### ISSUE TITLE
Dc title and dc description appended to resource templates that do not use them (new item creation)

### ISSUE THREAD

**Issue by sharonmleon** [omeka/omeka-s#1727]
The default fields for an item without a resource template are dc title and dc description. When one goes to create a new item, and use a resource template that does not use those dc fields, they are appended to the end of the template.

**Comment by sharonmleon** [comment]
Just a follow to say that I understand now that this is how this has always worked, but I still maintain that it is confusing for the user and that we might want to change it.

**Comment by jimsafley** [comment]
Possibly use the `default-value` class that's set to Title and Description?
