### ISSUE TITLE
Documentation: Query Element

### ISSUE THREAD

**Issue by jimsafley** [omeka/omeka-s#1730]
The new query form element needs to be documented. The [testing issue](https://github.com/omeka/omeka-s/issues/1701) clearly explains its purpose, functionality, and relevant nomenclature, so we can use that as a reference while writing the doc.

**Comment by sharonmleon** [comment]
@jimsafley The query builder appears to be documented in the Sites: Resources area: https://omeka.org/s/docs/user-manual/sites/site_resources/ 

Does this documentation look okay for adaptation for use in other situations?

**Comment by sharonmleon** [comment]
Sorry, @jimsafley. Dumb. I was confused; nevermind.

**Comment by sharonmleon** [comment]
Documentation submitted in enduser documentation [pull request](https://github.com/omeka/omeka-s-enduser/pull/99)
