### ISSUE TITLE
Private page still displays in List of pages even when logged out

### ISSUE THREAD

**Issue by georgiawebgurl** [omeka/omeka-s#1738]
If I make a page private, the page still appears in the display of the List of pages block, even when logged out. The page link of a private page does not open, tho.  

This behavior appears in Chrome Version 91.0.4472.124 (Official Build) (64-bit), Edge Version 91.0.864.67 (Official build) (64-bit), Samsung Galaxy S21, Iphone 6 & 11, Firefox 90.0

**Comment by matthewjmckinley** [comment]
This seems like desired behavior, to me. The page link doesn't work so that's the most important bit, and if they don't want it to appear on their list they can manually remove it on the page edit screen. Perhaps someone would want a list of all their pages, even private, for whatever reason? It seems better to leave that option open than forbid private pages from displaying altogether?

**Comment by sharonmleon** [comment]
Right now, you can add a page to the navigation when it is not public. It shows up on the navigation with some kind of placeholder.

**Comment by sharonmleon** [comment]
Follow-up: Right now, in the page list, if the page is private, you can see the title as a link and it just reloads the current page. However, when a page is private but in the navigation, the title is replaced with [Missing Page]. I don't love that, but it might be better than the silent reload of the current page.

**Comment by zerocrates** [comment]
The "Missing Page" thing is done because the private page might be above a whole hierarchy and it's easier to just have it have some placeholder than try to actually remove it

**Comment by sharonmleon** [comment]
That totally makes sense. And I think we need something like that on the list of pages.

**Comment by georgiawebgurl** [comment]
Should I close this then, as not an issue?
Robin

**Comment by sharonmleon** [comment]
No. Not yet, because we need to talk about the functioning of the private page link.

**Comment by sharonmleon** [comment]
Add a page; save it; then delete the page; check on output.

Output should print Missing Page.

**Comment by matthewjmckinley** [comment]
Fixed by https://github.com/omeka/omeka-s/commit/da2211ccce76abe031dcd9f414bcec18372f35b2
