### ISSUE TITLE
Can add page to its own List of pages block

### ISSUE THREAD

**Issue by georgiawebgurl** [omeka/omeka-s#1739]
I originally noted this in my earlier testing notes but didn't consider it an issue, but now I'm not so sure. 

So, I'm noting here : :-)
In a List of pages block, you can add the page to its own List of pages block. The page title appears as it should and the link works as it should, because, well, you're already on the page. :-) 

For example, in my Welcome page, List of pages block, I added the Welcome page to that block. 
I don't know why anyone would want to do that (except me, in testing adding all of my pages to a List of pages block). :-) 

I also created multiple List of pages blocks on one page, which then had duplicates of some of my pages in them. That functionality made sense to me, in that if you're curating pages in some way, and want to list a page in multiple places.  

However, being able to list the page itself in the List of pages block, feels a little bit like circular logic. Or at least how I am thinking about it now, thus reporting.

**Comment by matthewjmckinley** [comment]
This also feels like desired behavior to me. I'd rather give people the option to show all pages related to a site, even the current page itself, especially since they are manually adding pages from the sidebar so will need to make that conscious choice to display it.

**Comment by sharonmleon** [comment]
I bet this block could be styled like sidebar navigation in Wordpress, and in that way, you'd want it to be consistent across all implementations and at each place it would include the page you were on, as well as the others.
