### ISSUE TITLE
Testing: item sets search limited to attached sets for sites

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#1743]
On branch develop.

This feature changes the public advanced search page for sites to make the item set dropdown only include those sets that have actually been attached to the site in the Resources tab. Only the advanced search form is affected.

Testing this involves adding/removing sets from the site's Resources section and confirming the public advanced search form matches. If there are no sets assigned, the item set part of the advanced search should not display at all.

The admin side advanced search should be exactly the same as it previously was.

**Comment by sharonmleon** [comment]
Works as expected.
