### ISSUE TITLE
Media: Batch edit: wierd plural

### ISSUE THREAD

**Issue by sharonmleon** [omeka/omeka-s#1758]
Head reads: Batch edit medias

**Comment by jimsafley** [comment]
There are 13 places where we display "medias" instead of "media". It's wrong, of course, but the distinction between media (singular) and media (plural) is sometimes meaningful. Nevertheless, we should correct them.

**Comment by sharonmleon** [comment]
Is it a constructed string that takes the resource label and makes it plural?

**Comment by jimsafley** [comment]
No, at least not as far as I can tell. Those 13 places are simply hard coded as "medias". Probably due to some code-switching oversight going from codeland to userland.

**Comment by zerocrates** [comment]
So one issue here is that the English strings are what get used for other languages to translate, so for other languages that don't have the "singular is plural" issue of "media" they'd be unable to have plural and singular translations themselves, because there'd be just one English string.

**Comment by sharonmleon** [comment]
Fascinating. I’m open to being convinced that it shouldn’t be changed.
