### ISSUE TITLE
can't create item referencing an imported resource template

### ISSUE THREAD

**Issue by missinglinks** [omeka/omeka-s#1764]
Hi,
I am having a weird issue when creating items refering to a resource template, which was imported with the Omeka S import function. 
The controller action I use is the following:

```php
        $resourceTemplateId = $this->params('id');
        $resourceClass = $resourceTemplate->resourceClass();

        $item = [];
        $item['o:resource_template'] = [
            'o:id' => $resourceTemplateId
        ];     
        $item['o:resource_class'] = [
            'o:id' => $resourceClass->id()
        ];

        $newItem = $this->api()->create('items', $item)->getContent();
        return $this->redirect()->toURL($newItem->url('edit'));
```

It works perfectly fine if the template id refers to an newly/manually created resource template. but the create call fails when the template id refers to an imported resource template.

I am not sure if I missed something or if it's a bug (I am pretty new to Omeka), but if someone can point me in the right direction, that would be awesome. 

Omeka S version: 3.0.2

**Comment by jimsafley** [comment]
I can't reproduce this. How exactly does the create operation fail? Is there an error message? One thing that stands out in your code is that `$resourceClass->id()` will fail if your template doesn't have a class. There would be a `Call to a member function id() on null` error.

**Comment by zerocrates** [comment]
I'm closing this issue as inactive. If you're still having a problem with this feel free to re-open or re-file.
