### ISSUE TITLE
Provide means to translate strings introduced in themes

### ISSUE THREAD

**Issue by kimisgold** [omeka/omeka-s#1769]
Some of the themes that use a visual media viewer separate out unsupported file attachments under "Other Media", a string that doesn't exist within the core. [A recent issue for Center Row](https://github.com/omeka-s-themes/centerrow/issues/48) points out we don't currently have a way to translate theme-specific strings.

**Comment by zerocrates** [comment]
OK, an initial version of this is in the branch theme-translations

Translations are stored in a "language" folder, same as the core and modules. Add has_translations = true to the theme INI to use the feature.

At the moment I have these loading on the admin side as well, on the theory that they might include translations for things like theme config form elements.

**Comment by zerocrates** [comment]
This was merged so I'm calling this closed.
