### ISSUE TITLE
Additional trigger options

### ISSUE THREAD

**Issue by patrickmj** [omeka/omeka-s#177]
Omeka 2.x generally has hooks for inserting content at the ends of pages. This mostly works, but has also come up as a limitation for site builders.

How expansive should trigger placements be for Omeka S? I can see utility for:

* admin edit resource pages between the class and template fields, and the metadata inputs
* top and bottom of the show-details sidebars
* delete sidebar
* elsewhere?

:horse: <--- His name is Trigger, of course.

**Comment by zerocrates** [comment]
> between the class and template fields, and the metadata inputs

By this you mean the single location in between those two groups of inputs, or "between" the class and template fields and "between" *each* metadata input?

**Comment by patrickmj** [comment]
The former -- just the single location between those groups. Even I am not kooky enough to think that between each input would be a good idea.
