### ISSUE TITLE
List of sites not reorganizing

### ISSUE THREAD

**Issue by AlyxTaj** [omeka/omeka-s#1780]
Hello,

I do not think I have seen a similar issue raised here.
I am on Omeka S version 3.1.1

I have been using the block "list of sites" to display the various exhibits we have from a page on our digital library, the default site. However, I have come across a problem which is that, when trying to organize the list of a specific number and in a specific order, IF I have set the default site and/or the site being visited not to be shown, then it does not take into account the other parameters.
What I've done not to display the default site is set a specific number of sites and deactivate pagination. But I believe there is some issue here.

Thank you very much!

**Comment by zerocrates** [comment]
I think what you're reporting is that enabling the "Exclude current site" option for the List of sites block causes the other options to be ignored?

If so, I can't reproduce that issue.

**Comment by jimsafley** [comment]
We can't reproduce this and haven't heard back, so we're going to close. Feel free to reopen and elaborate should you want further discussion.
