### ISSUE TITLE
Multiple file select for manual upload

### ISSUE THREAD

**Issue by sharonmleon** [omeka/omeka-s#1785]

**Comment by Daniel-KM** [comment]
Hi Sharon, 

Very useful indeed!

This is a new feature of the module [BulkImport](https://gitlab.com/Daniel-KM/Omeka-S-module-BulkImport). I can push it here, but it here if needed.

![image](https://user-images.githubusercontent.com/2138485/148894606-be2a012d-0200-4545-82c4-4548b070e579.png)

**Comment by Daniel-KM** [comment]
In fact, unlike in the module, it can be merged with the default "Upload button". To upload folders, it should be a separate button.

**Comment by Daniel-KM** [comment]
Furthermore, there will be another feature to bypass the max number of files by post and to avoid many issues with files. In fact, it exists since some years in module [Bulk Import Files](https://gitlab.com/Daniel-KM/Omeka-S-module-BulkImportFiles), but I'm currently merging some modules to simplify maintenance.

**Comment by Daniel-KM** [comment]
I updated the module and now the files are not only uploaded one by one, but with chunks, so there is no more server size limit. It supports the drag-and-drop too. And the thumbnails are delayed in a background job, so there is no more the 30 seconds issue. 

![image](https://user-images.githubusercontent.com/2138485/151130291-367d73a5-dd67-4246-b799-5424efe2f84c.png)

**Comment by Daniel-KM** [comment]
Module BulkImport is [here](https://gitlab.com/Daniel-KM/Omeka-S-module-BulkImport) or on [Github](https://github.com/Daniel-KM/Omeka-S-module-BulkImport) (version 3.3.30.0).

**Comment by Daniel-KM** [comment]
New features in last version, in particular the possibility to sort uploaded files :
![image](https://user-images.githubusercontent.com/2138485/167612239-37aecbe7-54b0-4c40-a37e-b6956a5c072d.png)
