### ISSUE TITLE
Public Advanced Search Clutttered with Unused Options

### ISSUE THREAD

**Issue by alexdryden** [omeka/omeka-s#1788]
Advanced Search's "search by Property" and "search by Class" fields present users with all installed Properties and Classes as search options, even when only a small number of those Properties or Classes are used by items in the site. This is especially problematic when additional ontologies are installed, as users may be presented with hundreds of options, including ones from subjects unrelated to the site they are searching. 

This presents several related usability issues. Among users who are very familiar with the content, it forces them to sift through many unrelated options to find the ones they need. For users who are less familiar with the content, it conceals the properties and classes used by the collection by intermixing them with unused options, forcing the user to discover meaningful choices through trial and error. And for users with the least experience with collection, the options may set an expectation that all listed properties will appear somewhere in the collection, leading to confusion and frustration when queries produce no results. 

Because Omeka S 3.x provides additional support for a multi-tenancy approach to sites, it seems appropriate that the Property and Class options be sensitive to the properties and classes used by items in the site.

**Comment by jimsafley** [comment]
We'll look into this. In the meantime, take a look at the new [Faceted Browse](https://omeka.org/s/modules/FacetedBrowse/) module, which allows site administrators to tailor the advanced search functionality to the content of the site.

**Comment by alexdryden** [comment]
Thanks @jimsafley, I'll check it out! I was futzing around and noticed that there is already a `used` [parameter](https://github.com/omeka/omeka-s/blob/71e3938b8c53614d4802c98b1e82f699fff630c1/application/src/Api/Adapter/PropertyAdapter.php#L140), which seems to limit the options to those that are used anywhere in the values table. I don't see any instances that this option is is passed to search, are there other plans for this option?

**Comment by jimsafley** [comment]
There is no advanced search for properties, so we have no plans to integrate it into the interface. An equivalent option for items would be to "Search by value," select a property, and select "has any value."

**Comment by alexdryden** [comment]
Thanks for the insights @jimsafley. I've been asked to include this feature for our Omeka S instances. My plan was to check if the site had selected "Search this site only", and then filter the property and class options based on the properties and classes from the site's items. If you are interested in a pull request, I can implement it in core codebase and submit one. Otherwise I'll put it into a module where we have a few other custom options.

**Comment by Daniel-KM** [comment]
Note that there was already a pull request that had the same aim three years ago (https://github.com/omeka/omeka-s/pull/1423), still alive.
