### ISSUE TITLE
Testing: Value Annotation

### ISSUE THREAD

**Issue by jimsafley** [omeka/omeka-s#1813]
We recently added a feature that allows users to annotate their values, or, put another way, make statements about their statements. This introduces the concept of [reification](https://patterns.dataincubator.org/book/reified-statement.html) to Omeka S, so it's a significant addition to our RDF implementation. The advantage of value annotation is that, now, users can choose to make ambiguous facts more concrete by annotating things like:

- Provenance: Where is this fact from?
- Time: When did this fact occur?
- Location: What is the location associated with this fact?
- Certainty: What is the confidence of this fact?
- Type: What type of concept/thing is this fact?

To test this, you can make any number of annotations of individual values directly on a resource form via a sidebar. Add an item and add any property. Add any arbitrary text and click the ellipsis then the "Annotate value" dialog bubble. That should open an "Annotate value" sidebar. Select any property, any data type, and then press "Add annotation". An input should appear below. Enter anything into the input and click the "Set annotations" button. The sidebar should close. Now, in the same value, click the ellipsis then the "Annotate value" dialog bubble and see if the annotation your just entered is there. Go ahead and add multiple annotations of multiple different data types, set them, and see if they persist. Now save the item. On the item show page you should see a "Has annotation" dialog bubble next to the value you entered. Click on it and you should see every annotation you made below the value. Now edit the item and confirm that the annotations are still assigned to the value.

Do this many times in many configurations for many values and confirm that everything works as expected.

**Comment by katknow** [comment]
Where should I be seeing the ellipsis for annotation? I tried to re-pull this morning and am getting this message, so I don't know if this might be the problem:

`[katknow@omeka-dev OmekaSTesting]$ git pull
Updating 09b9a68c1..60076613e
error: Your local changes to the following files would be overwritten by merge:
        package-lock.json
Please commit your changes or stash them before you merge.
Aborting`

I haven't done anything other than try to pull, so not sure what changes it is referring to.

**Comment by katknow** [comment]
This seems to work well. Can add/delete/save/edit no problem. Tried with a variety of properties and annotation types text, uri, item, item set, and media.

**Comment by sharonmleon** [comment]
@jimsafley Testing this as well, and all looks good. Eventually will the other data types be incorporated? Numeric data and controlled vocabs?

**Comment by jimsafley** [comment]
There's already a NumericDataTypes [branch](https://github.com/omeka-s-modules/NumericDataTypes/compare/value-annotation) that adds data types to value annotations. I do plan on incorporating CustomVocab.

**Comment by sharonmleon** [comment]
Excellent. I thought that was what I remembered, but I just wanted to check. I think we can close this, and open a documentation issue if we don't have one.
