### ISSUE TITLE
Testing: Asset block fixes

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#1814]
On develop.

- Private pages should be chooseable if the editing user can see them (this also extends to any pages at all if the whole site is private)
- Both the edit and view sides should work correctly if either the page or asset previously attached becomes private to the viewing/editing user or is removed entirely
- There should be no effect when saving the edit page if the asset sidebar is open but hasn't been confirmed/applied.

**Comment by zerocrates** [comment]
Testing for missing or inaccessible pages/assets is easiest accomplished by making and saving a block pointing to the asset/page, then deleting it: check both the edit form for the page and its public view. Similar applies to private, though checking it requires browsing as a lower-privileged user (or nonprivileged for viewing the public site) rather than deleting.

**Comment by katknow** [comment]
These all seemed to work across browsers. The one thing that seems off is now if I make a page private it replaces the text in the nav bar (if logged in as lower user/not logged in) include "Missing Page," but this may be normal and I just haven't noticed before

**Comment by zerocrates** [comment]
Thanks. Yes, "Missing Page" is preexisting behavior.
