### ISSUE TITLE
Filter / search for items not attached to a site

### ISSUE THREAD

**Issue by lguariento** [omeka/omeka-s#1815]
Is it possible to get the items which do not have a site attached? It would be nice if a query like`admin/item?site_id=ne` would indeed return the items without site. Right now if the above returns all the dataset.

Or/and return the items not assigned to a specific site: `admin/item?site_id=1?joiner[not]` <- warning: pseudo-code.

**Comment by lguariento** [comment]
PS: this is not a duplicate of [this](https://github.com/omeka/omeka-s/issues/1743). My issue is about retuning, on the admin backend, the items not attached to any site or not attached to a specific site, so that I can select them and batch-assign a site to them.

**Comment by zerocrates** [comment]
We'll look into that... I believe I understand correctly what you're asking for.

A "none" search option sometimes require a different query on the backend when we have these "many-to-many" relationships at play.

**Comment by HJB1972** [comment]
Please can someone tell me if this has been actioned. I have 100s of items in my library and I need to perform a search to check if items are missing an assigned item set or assigned website. Items that do not belong to either a set or site are will not appear in their respective navigation pages. How is such a search performed to show an item which has not website and/or item set assigned to it?

**Comment by lguariento** [comment]
Hi @HJB1972 , while we wait for some Omeka developers to reply to this, I can tell you that I have found a table called `item_site` in the database which, I think, lists items with their assigned site next to them in the `site_id`. This is less than ideal of course although it might be of help for the time being, maybe.

**Comment by zerocrates** [comment]
The API param for this is in 3.2.0: you pass 0 or false as the value for the `in_sites` parameter.
