### ISSUE TITLE
Feature: page templates

### ISSUE THREAD

**Issue by kimisgold** [omeka/omeka-s#1835]
A project that featured a network of partner sites within the same installation was wondering if there was a way to create page templates for their partner sites to use for some consistent content tying the sites together. This would look something like the standard "Welcome" page that Omeka S sites start with, but pre-populated with a configuration of blocks.

**Comment by jimsafley** [comment]
We don't currently plan on addressing this issue. It sounds better suited as a module. Feel free to reopen and elaborate should you want further discussion.
