### ISSUE TITLE
pre-3.2 testing

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#1836]
Testing on develop

- Search indexing for media and value annotations
  - Text in value annotations should bring up the parent item, set, or media as a result
  - Metadata within media should bring up the parent item as a result
- Show/hide value annotations control
  - This is controlled in Site settings ("Show value annotations") and controls the public display of value annotations
  - Should be checked across themes (make sure the themes are updated)

**Comment by sharonmleon** [comment]
All of the search results are appropriate upon testing.

The show/hide of annotations works with all themes except Foundation, where annotations are not appearing at all. (@kimisgold)

**Comment by katknow** [comment]
Search results are working for me as well. 

Foundation's annotations now work, too.
