### ISSUE TITLE
Merge user profiles created locally and those created using ldap module

### ISSUE THREAD

**Issue by zkapfumvuti** [omeka/omeka-s#1838]
Hi Team,

I would like to inquire on how to merge users profiles created locally within Omeka-S admin page and those created dynamically using the biblibre module https://github.com/biblibre/omeka-s-module-Ldap 

This is so my existing users do not lose their created sites once they dynamically login with their LDAP credentials

**Comment by zerocrates** [comment]
It might be better to ask on that module's repository instead... I'm not sure how they handle things with existing users.
