### ISSUE TITLE
Invalid JSON-LD syntax; "@reverse" value must be an object.

### ISSUE THREAD

**Issue by coret** [omeka/omeka-s#1840]
https://github.com/omeka/omeka-s/pull/1795 added the `@reverse` property to the JSON-LD API. But, when an object doesn't have `subjectValuesForReverse()` the resulting JSON-LD will have `@reverse: []` making the JSON-LD invalid. 

I ran into this issue when processing the API's JSON-LD with https://json-ld.org/playground/ and https://www.easyrdf.org/converter. According to https://json-ld.org/spec/latest/json-ld/:
> If the [node object](https://json-ld.org/spec/latest/json-ld/#dfn-node-objects) contains the @reverse key, its value MUST be a [JSON object](https://json-ld.org/spec/latest/json-ld/#dfn-json-objects) containing members representing reverse properties. Each value of such a reverse property MUST be an [absolute IRI](https://json-ld.org/spec/latest/json-ld/#dfn-absolute-iris), a relative IRI, a compact IRI, a blank node identifier, a [node object](https://json-ld.org/spec/latest/json-ld/#dfn-node-objects) or an [array](https://json-ld.org/spec/latest/json-ld/#dfn-arrays) containing a combination of these.

A possible fix would be to change https://github.com/omeka/omeka-s/blob/d167ddeeebbd331e745cda85814153aea399eef2/application/src/Api/Representation/AbstractResourceEntityRepresentation.php#L123 into `(count($reverse)>0?['@reverse' =>$reverse]:null)`

where `        $reverse=$this->subjectValuesForReverse();` is added before https://github.com/omeka/omeka-s/blob/d167ddeeebbd331e745cda85814153aea399eef2/application/src/Api/Representation/AbstractResourceEntityRepresentation.php#L110

**Comment by zerocrates** [comment]
Thanks for the report: we'll look into it, either removing the key or making it be an empty object rather than an empty array.

**Comment by zerocrates** [comment]
The fix here is released, as part of version 3.2.1.
