### ISSUE TITLE
Test resource selector improvements

### ISSUE THREAD

**Issue by kimisgold** [omeka/omeka-s#1843]
We looked at improvements to the resource selector awhile ago in #1536, and since then those changes were lost in a merge or reorganization. Upon discovering this, they've been restored, but we need to look at it again to make sure everything looks as it should.

Please test the following: 

* After a resource has been added to the main form area, the total count and owner count of available resource 
* When removing a resource row, it disappears from the table in the main form area and becomes available in the right hand selector.
    * The total counts in the selector sidebar update with each action.
    * When all resources have been added to the main form area, a message appears in the sidebar notifies the user. If the user then removes resources from the main form area, the resource selector reappears.
* When the user filters the available resources, only the relevant results appear in the selector.
    * If the user adds all the results from a filtered search, the total count reads '0', but the selector is still active if other filtered out resources are still able to be added.

The pattern has been applied to the following areas:

* item add/edit
    * sites
    * item sets
* site admin
    * user permissions
    * resources > item sets

**Comment by zerocrates** [comment]
These changes are currently on the release-3.2 branch and develop. Particularly if you're currently on a 3.2 release (rather than the "version 3.99.0-alpha" develop branch, it will be easier to test on release-3.2.

**Comment by katknow** [comment]
This worked really well for me! Tested on release-3.2.
