### ISSUE TITLE
When adding resources with the "Quick Add" option, the data type constraint do not apply to resources after the first.

### ISSUE THREAD

**Issue by sharonmleon** [omeka/omeka-s#1844]
I'm not sure if this matters at all, but when selecting multiple items to add as values for a property, the first attached item holds the data type as indicated by the resource template, but the other items in the selection do not. Subsequently clicking the Add Value button does respect the constraint
<img width="550" alt="Screen Shot 2022-05-23 at 3 16 36 PM" src="https://user-images.githubusercontent.com/741480/169891458-0b58c71e-8e69-46b3-98f8-a68b8a4a7df8.png">
.

**Comment by zerocrates** [comment]
Yeah this is probably a bug with quickadd, for sure.

**Comment by zerocrates** [comment]
Should be fixed on a fresh pull of release-3.2

**Comment by sharonmleon** [comment]
Fixed
