### ISSUE TITLE
Testing: Configurable browse columns and browse defaults

### ISSUE THREAD

**Issue by jimsafley** [omeka/omeka-s#1845]
The [browse-columns](https://github.com/omeka/omeka-s/compare/browse-columns) branch introduces several ways to configure certain browse pages. Users now have the option to select which columns are rendered on the administrative item, item set, media, and site browse pages. They may also configure the "browse defaults" (i.e. sort) of those pages, as well as the browse defaults of the public item browse page.

The branch adds more features and enhancements, but the remainder are developer oriented and invisible to the end user. Most notably, it moves hard-coded sort options and browse defaults from views and controllers to the configuration file, so modules can have greater control over the new browse features. The features are written to be future-proof, so developers may add more browse configuration options using existing code. You won't need to test these things. It's just something to note.

After checking out the `browse-columns` branch, you'll need to either update the dependencies or create a new installation. It's branched off the `develop` branch, which is currently being developed for a major version update, so the branch is not compatible with previous versions. I can help with upgrading if needed.

To test the branch, there are two places you need to look, user settings and site settings. There are nine new form controls to test, most in user settings, and one in site settings.

### Admin browse columns

This is where you select which columns are rendered on administrative browse pages. (Remember that browse pages render tabular data, where a row represents the resource and a column contains the resource's metadata.) There are four browse pages you can configure, each having a corresponding form control that first loads with default columns:

- Item browse columns
    - Resource class
    - Owner
    - Created
- Item set browse columns
     - Resource class
    - Owner
    - Created
- Media browse columns
    - Resource class
    - Owner
    - Created
- Site browse columns
    - URL slug
    - Owner
    - Created

To add a column, simply select one from the list of available columns, click the [+] button, configure the column in the opened sidebar, and click the "Set column" button. The new column should appear on the list of columns. You may sort the columns by clicking and dragging the sort handle up and down. Click on the pencil icon to open the "Edit column" sidebar. Click on the trashcan icon to remove the column from the list. Click on the restore icon to restore a removed column.

The "Edit column" sidebar contains additional column options. You may configure "Header" and "Default" for every column, but both are optional. "Header" is where users can customize the column header. "Default" is where users can customize what appears in a cell if there is no metadata. The "Value" column type also includes "Property" (required) and "Max values" (optional).

Once you've finished configuring the columns, go to the respective browse pages and see if the tables include the correct columns, the correct column configuration, and the correct column order.

### Admin browse defaults

This is where you select the default "sort by" and "sort order" on administrative browse pages. There are four browse defaults you can configure, each having a corresponding form control that first loads with default options:

- Item browse defaults
    - Created
    - Descending
- Item set browse defaults
    - Created
    - Descending
- Media browse defaults
    - Created
    - Descending
- Site browse defaults
    - Title
    - Ascending

To set browse defaults, select the possible ways to sort the resources: what you're sorting by and in what order. The select menu on top is what you're sorting by. It should include any columns you've added above. There's also an option to set a custom sort by. Just click on [Custom sort by] and enter a custom sort string in the opened input. If you've entered a custom sort string and save the form, you should see an additional "Custom (<my_sort>)" option in the menu. The select menu on bottom is what order you're sorting by, descending or ascending.

Once you've finished configuring the browse defaults, go to the respective browse pages and see if the tables are sorted in the correct way by default.

### Item browse defaults

This is where you select the default "sort by" and "sort order" on the public item browse page. It's exactly like the admin browse defaults above, so just test the same. Make sure to test whether your configured defaults are reflected in the public item browse page.

**Comment by jimsafley** [comment]
> For the custom sort, can I theoretically just type in any of the fields in the metadata page? Or is it more complex than that and I'm missing something?

Custom sort gives advanced users the opportunity to use an unlisted sort by parameter (documented or undocumented). You can test this by sorting by a property term, e.g. `dcterms:title` or `dcterms subject`. There are other special sorts that modules introduce, but you don't need to test those.

>  can no longer move past the first page on the item browse page

Great catch. It should be fixed now.

**Comment by katknow** [comment]
The custom sort definitely works! I tried to re-pull, but I'm still stuck on the first page on item browse. I've tried in three different browsers and hard refreshed, cleared cache, etc. and can't get it work.

When I pull, I get this message:
`Already up to date.`

When I check the status, I get this: 
On branch browse-columns
Your branch is up to date with 'origin/browse-columns'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   package-lock.json

no changes added to commit (use "git add" and/or "git commit -a")

**Comment by sharonmleon** [comment]
I'm going to reopen this because once I've added a resource value column to a browse, and saved, that column is not available for the default sort by choices below.

So, I've added a date column to the item browse, and I don't have the option to select that as by default sort by column.

**Comment by sharonmleon** [comment]
Nevermind. Stupid caching.
