### ISSUE TITLE
Public/Private admin search criteria

### ISSUE THREAD

**Issue by jbuwlaw** [omeka/omeka-s#1847]
It appears that since 3.2.1 the public/private search result parameter is reversed.  That is, in the admin search you can do a search for Private records.  The correct records return but the search parameter at the top of the result page says 'Public'.

**Comment by zerocrates** [comment]
Can you show a screenshot of the problem?

We don't actually have a really easily accessible public/private search input and don't show it at the top either... unless this is just some part of the interface I'm just not thinking of. Or maybe it's a module?

**Comment by jbuwlaw** [comment]
Oh that's right, it's enabled by a module.  Sorry about that!
