### ISSUE TITLE
Testing: value annotations with different user roles

### ISSUE THREAD

**Issue by jimsafley** [omeka/omeka-s#1849]
Test the value annotations feature while logged in as each user role. You can find value annotations when adding/editing an item, media, and item set. Beside each value is an ellipsis that reveals an "Annotate value" balloon that opens an "Annotate value" sidebar.  

- **Global administrator**: can create, update, and delete annotations for all resources
- **Supervisor**: can create, update, and delete annotations for all resources
- **Editor**: can create, update, and delete annotations for all resources
- **Reviewer**: can create, update, and delete annotations for all resources
- **Author**: can create, update, and delete annotations _only for resources they own_
- **Researcher**:  _cannot_ create, update, and delete annotations

**Comment by zerocrates** [comment]
This can be tested on the release-3.2 branch or develop.

**Comment by katknow** [comment]
Global Admin and Supervisor seem to work fine, but for editor and below I'm getting this error when I try to edit annotations:

 Omeka\Api\Exception\PermissionDeniedException
Permission denied for the current user to search the PersistentIdentifiers\Api\Adapter\PIDItemAdapter resource.

Details:

Omeka\Api\Exception\PermissionDeniedException: Permission denied for the current user to search the PersistentIdentifiers\Api\Adapter\PIDItemAdapter resource. in /var/www/html/katknow/OmekaSTesting/application/src/Api/Manager.php:208
Stack trace:
#0 /var/www/html/katknow/OmekaSTesting/application/src/Api/Manager.php(59): Omeka\Api\Manager->execute(Object(Omeka\Api\Request))
#1 /var/www/html/katknow/OmekaSTesting/modules/PersistentIdentifiers/Module.php(101): Omeka\Api\Manager->search('pid_items', Array)
#2 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-eventmanager/src/EventManager.php(321): PersistentIdentifiers\Module->PersistentIdentifiers\{closure}(Object(Laminas\EventManager\Event))
#3 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-eventmanager/src/EventManager.php(170): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\EventManager\Event))
#4 /var/www/html/katknow/OmekaSTesting/application/src/View/Helper/Trigger.php(60): Laminas\EventManager\EventManager->triggerEvent(Object(Laminas\EventManager\Event))
#5 [internal function]: Omeka\View\Helper\Trigger->__invoke('view.show.sideb...')
#6 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-view/src/Renderer/PhpRenderer.php(396): call_user_func_array(Object(Omeka\View\Helper\Trigger), Array)
#7 /var/www/html/katknow/OmekaSTesting/application/view/omeka/admin/item/show.phtml(100): Laminas\View\Renderer\PhpRenderer->__call('trigger', Array)
#8 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-view/src/Renderer/PhpRenderer.php(505): include('/var/www/html/k...')
#9 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-view/src/View.php(206): Laminas\View\Renderer\PhpRenderer->render(NULL)
#10 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-view/src/View.php(235): Laminas\View\View->render(Object(Laminas\View\Model\ViewModel))
#11 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-view/src/View.php(199): Laminas\View\View->renderChildren(Object(Laminas\View\Model\ViewModel))
#12 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-mvc/src/View/Http/DefaultRenderingStrategy.php(104): Laminas\View\View->render(Object(Laminas\View\Model\ViewModel))
#13 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-eventmanager/src/EventManager.php(321): Laminas\Mvc\View\Http\DefaultRenderingStrategy->render(Object(Laminas\Mvc\MvcEvent))
#14 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-eventmanager/src/EventManager.php(170): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent))
#15 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-mvc/src/Application.php(366): Laminas\EventManager\EventManager->triggerEvent(Object(Laminas\Mvc\MvcEvent))
#16 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-mvc/src/Application.php(347): Laminas\Mvc\Application->completeRequest(Object(Laminas\Mvc\MvcEvent))
#17 /var/www/html/katknow/OmekaSTesting/index.php(21): Laminas\Mvc\Application->run()
#18 {main}

**Comment by zerocrates** [comment]
And to double-check, you're on the most recent release-3.2? And/or develop, whichever you're on?

**Comment by katknow** [comment]
I re-pulled and I think its working now. I was flipping between release-3.2 and develop earlier and I think I got confused.
