### ISSUE TITLE
Undefined variable: pageBodyClass

### ISSUE THREAD

**Issue by lguariento** [omeka/omeka-s#1854]
In development mode, I'm getting this error:

```
Notice: Undefined variable: pageBodyClass in /var/www/html/boslit.glasgow.ac.uk/www/application/view/omeka/site/page/show.phtml on line 3
```
Line 3 of that file is this:

```
$this->htmlElement('body')->appendAttribute('class', $pageBodyClass);
```

Omeka S 3.2.1

**Comment by zerocrates** [comment]
Hmm, that should be getting set by the Page controller.

Are you using a module or something that replaces the Page controller maybe?

**Comment by lguariento** [comment]
Is it a Clean URL issue then?

**Comment by zerocrates** [comment]
I suppose it would be. The problem is just that this was added to the core's Page controller, so the view expects it to be there. Presumably Clean URL's copy of the controller just isn't updated to have this.
