### ISSUE TITLE
Low-level user roles can see other users' email addresses

### ISSUE THREAD

**Issue by allanaaa** [omeka/omeka-s#1855]
The lowest levels of users (researchers, authors, reviewers) can see all Users under the Admin > Users tab. 

Three potential solutions: Hide all other user rows in the table. (Or maybe only display the global admins, if that's useful?)
Or: Hide email addresses but leave display names. 
Or: Display a different page instead, where a user can edit their own details but there is no table.

**Comment by zerocrates** [comment]
We don't treat the user info as secret from other authenticated users, it can also appear other places like dropdowns that separate things by the user that owns them.

We could potentially have a setup where you don't go through the Users browse though. To a certain extent that already exists, you can click your name in the sidebar to go to your page directly.

**Comment by allanaaa** [comment]
Right, that's smart. Then you can just hide the Users sidebar entry entirely from those roles. 

I realize display names are not unique, so it's not as simple as just removing email addresses from those dropdowns. Maybe we can put a pin in that bit, rather than me suggesting you suddenly start enforcing unique display names.....
