### ISSUE TITLE
Editors get an error when creating users

### ISSUE THREAD

**Issue by allanaaa** [omeka/omeka-s#1856]
Came up while doing [#127](https://github.com/omeka/omeka-s-enduser/issues/127). 

Supervisors work as described. 

Editors, who are supposed to be able to create users as per the manual, can click the "Add new user" button. But upon submission I get a "Forbidden" page. 

So, either editors are supposed to be able to create users (if so - at what level(s)?), or editors shouldn't see the "Add new user" button, and I'll update the manual accordingly. 

The add-user form doesn't have a role dropdown, so I'm not sure what the default role would be, were this to work. I am not sure if there is a good reason why an editor doesn't see the same add-user form as a supervisor (missing are the role dropdown, and the "is active" checkbox).

**Comment by zerocrates** [comment]
I'll try to run this down.

They're not seeing the "role" dropdown because "change role" is a separate permission that they don't have.

I'm thinking the reality here is that they've really never been able to do it, despite the manual and permissions being a little confused on the fact.

**Comment by sharonmleon** [comment]
I'd also rather that they do not see the page, rather than have the permission.

**Comment by allanaaa** [comment]
Great. 

So, as far as discussion over the last few days/weeks, Supervisors are now
- Can create users at lower levels (editor, researcher, author, or reviewer). Cannot create other Supervisors or Global Admins.

as per [omeka/omeka-s-enduser/issues/127 ](https://github.com/omeka/omeka-s-enduser/issues/127).

Editors are now 
- Can see other users of the installation and their email addresses, but not add users.

and lower level user roles are
- Can see other users of the installation and their email addresses.

which may or may not change if we do something re: #1855.

**Comment by zerocrates** [comment]
I think that all sounds correct.
