### ISSUE TITLE
API query itens associated to month and day 

### ISSUE THREAD

**Issue by ronniebrito** [omeka/omeka-s#1858]
we what to query items associated to a date (month /day), for example all todays birthdays or the next ones (items with dates greater than today but ignoring the year)

but could`t find a way to do this search using the JS API, if no year is defined all items are returned, like in

api/items?item_set_id[]=9&numeric[ts][gt][pid]=182&numeric[ts][gt][val]=&year=&month=10&day=3

pid 182 is foaf:birthday

is there any solution to get this result using the API? workaround suggestions?

thanks

**Comment by jimsafley** [comment]
This is an issue with Numeric Data Types. The module cannot do what you want it to do, unfortunately.
