### ISSUE TITLE
Testing: Resource page block layouts

### ISSUE THREAD

**Issue by jimsafley** [omeka/omeka-s#1859]
The `develop` branch includes a feature that allows theme administrators to sort individual components on a public resource show page. To test this you will need to run `gulp deps` in your Omeka directory. Then, go to a site and set the "Default" theme. You should see a "Configure resource pages" button. Click on it. That will take you to a page where you can manage the components of resource show pages: Item page, Media page, and Item set page. In a separate tab, go to a public show page so you can track any changes you make. Go ahead and reorder the blocks, remove the blocks, and re-add the blocks and see if your changes are reflected in the public page.

**Comment by katknow** [comment]
This seems to work as described. My only questions are:

- Should "Main" be the only region available in the drop down on each tab?
- Should "Values" be the only block available on the Item Sets tab?

If so, I think this is good to go. All additions, subtractions, and re-orderings were reflected on the public page.

**Comment by sharonmleon** [comment]
The Light Gallery and Media embed implementation is a little bit inconsistent. I can get it to work on the media pages but not always on the item pages.

**Comment by jimsafley** [comment]
I'm not having problems with the "Media embeds" or "Lightbox gallery" blocks. What media are you having problems with? Describe the inconsistencies.

**Comment by sharonmleon** [comment]
Here is the page: http://6floors.org/workspace/omeka-s/s/photographs/item/8039

The image doesn't get the lighbox implementation, but rather just the square thumbnail listed as other media.

The lightgallery works on the media page.

**Comment by sharonmleon** [comment]
Note for documentation: Embed media on Item page must be checked in the Site Settings for the Light Gallery and Media Embed to work with the Item Pages blocks.

**Comment by kimisgold** [comment]
I'm wondering how necessary the embed media setting is with introduction of the resource page blocks. I feel like it's rendered obsolete and can only confuse.

**Comment by jimsafley** [comment]
My sense is that we can't remove the setting because we can't assume that all themes will implement resource page blocks, and, for those themes, users may expect media embed to be configurable.

**Comment by jimsafley** [comment]
That's a great idea. I've removed `item_media_embed` conditions from the media blocks. Far more predictable behavior, in my opinion. @katknow @sharonmleon Try it out and let me know what you think.

**Comment by zerocrates** [comment]
We'll need text/docs changes to the site setting to clarify its legacyness with this change.

**Comment by katknow** [comment]
Just tried this with the changes and it seems to be working smoothly for me
