### ISSUE TITLE
Documentation: Configurable browse columns and browse defaults

### ISSUE THREAD

**Issue by jimsafley** [omeka/omeka-s#1861]
This new feature needs documentation. The [testing issue](https://github.com/omeka/omeka-s/issues/1845) explains it.

**Comment by allanaaa** [comment]
If Title is always included in the browse views (or at least on Items, that I'm aware of), should it be removed from the list of properties in the dropdown? Or maybe included in this interface as a greyed-out option to indicate that it's hard-coded in? I was messing around and immediately added Title superfluously.

**Comment by allanaaa** [comment]
The sort dropdown is ordering alphabetically, which seems a bit weird here. I think it should reflect the column order.

![dropdown](https://user-images.githubusercontent.com/28012148/192886427-07c781dd-ff08-4a55-b3ad-820ffded2851.PNG)

**Comment by allanaaa** [comment]
Some other miscellany:

The sort dropdowns on the user settings page don't update dynamically when you're adding and deleting columns above, they only update when you save the page. Saving directs you away from the tab you're on, so there's just a little extra step to get back to that bit. I'm not sure a fix for either minor annoyance is possible.

The sort dropdowns also don't fall back to anything gracefully if you select a sort column, then delete that column from the view later. I can keep sorting by Owner long after the Owner column stops being visible on the screen.
