### ISSUE TITLE
Filter by visibility on admin end

### ISSUE THREAD

**Issue by fitnycdigitalinitiatives** [omeka/omeka-s#1863]
Tiny feature request: the old omeka had that little quick filter on the admin side to filter public or private item, might be nice also for Omeka-S, even just as an additional drop-down on the item advanced search.

Thanks,

Joseph Anderson

**Comment by zerocrates** [comment]
Good point. The absence of a UI-visible search option for public/private is one of those things I occasionally notice but fail to note for a future change.
