### ISSUE TITLE
Set default language for resource template property

### ISSUE THREAD

**Issue by jimsafley** [omeka/omeka-s#1867]
There is [interest](https://github.com/omeka-s-modules/ValueSuggest/pull/67#issuecomment-1180864659) in setting a default language for resource template properties, so that every value initiates with a configured language code.

**Comment by jimsafley** [comment]
I was thinking a setting for each property, alongside alternate label/comment in the "other options" section. I don't have a sense of whether this is more desirable than a template-wide setting.

**Comment by raboof** [comment]
I think it might be 'noisy' to set it for the whole template, since language perhaps doesn't really apply to each property. If the idea seems reasonable (and no-one beats me to it) I might find time to contribute this feature somewhere towards the end of this year.

**Comment by raboof** [comment]
Tried it out and this works great, thanks!
