### ISSUE TITLE
What is Omeka S ?

### ISSUE THREAD

**Issue by JBPressac** [omeka/omeka-s#187]
Hello,
I am already an Omeka user and I found this project searching implementations of IIIF with Omeka. Is Omeka the future version of Omeka ? Do you have a list of features ? Is Omeka S linked to Omeka Everywhere you annouced on september 2014 ?
Thanks,

**Comment by sharonmleon** [comment]
Hello,

Omeka S is not related to Omeka Everywhere. Omeka Everywhere is a set of
enhancements for the original version of Omeka. Omeka S is new system for
medium and larger organizations that allows a global administrator to care
for and oversee many sites that are tied to a single pool of items. See the
synopsis on the GitHub wiki:
https://github.com/omeka/omeka-s/wiki/What-to-expect-in-Omeka-S

Sharon

___________________________________
Sharon M. Leon, Ph.D.
Director of Public Projects, Roy Rosenzweig Center for History and New Media
 and Associate Professor, Dept of History and Art History
George Mason University | 4400 University Drive, MSN 1E7 Fairfax VA 22030

703-993-3831 | @sleonchnm |  sleon@gmu.edu
<http://chnm.gmu.edu/> | <http://6floors.org/bracket/>
