### ISSUE TITLE
Documentation: IIIF presentation media type

### ISSUE THREAD

**Issue by jimsafley** [omeka/omeka-s#1871]
This new media type needs documentation. See the testing issue (#1869) for more information.

**Comment by allanaaa** [comment]
Does CSV Import still need to be updated to allow for IIIF presentation imports? Should I leave that page until the module changes?

**Comment by allanaaa** [comment]
You're probably aware of this, but a few themes don't load a IIIF viewer on the item page - The Daily, Center Row. 

The Daily, I think, is supposed to load it on the media pages - the Presentation is working, but not the Image (compare http://dev.omeka.org/amayer/amayer-s/amsdev/omeka-s/s/my-third-site/media/1438 to http://dev.omeka.org/amayer/amayer-s/amsdev/omeka-s/s/my-third-site/media/1441).

Thanks Roy and Papers don't load it on the item page OR the media page for either media type. (http://dev.omeka.org/amayer/amayer-s/amsdev/omeka-s/s/my-second-site/media/1441)

Just wanted to register all that in case any of it's unintended.

**Comment by allanaaa** [comment]
I just updated all my themes from the repositories and The Daily is still loading Presentation but not Image (on the item pages now, thanks resource blocks: http://dev.omeka.org/amayer/amayer-s/amsdev/omeka-s/s/my-third-site/item/1437 vs http://dev.omeka.org/amayer/amayer-s/amsdev/omeka-s/s/my-third-site/item/1439). 

Papers now has the same problem: Presentation yes, Image no (http://dev.omeka.org/amayer/amayer-s/amsdev/omeka-s/s/my-omeka-s-site/item/1437 vs http://dev.omeka.org/amayer/amayer-s/amsdev/omeka-s/s/my-omeka-s-site/item/1439). 

Thanks Roy is fixed I think.
