### ISSUE TITLE
Testing: Language for URI values

### ISSUE THREAD

**Issue by jimsafley** [omeka/omeka-s#1885]
On the develop branch, users now have the option to add a language to a URI value, much like they can already do to a Text value.

To test this, add an item and add a URI value to any property. You should see a globe icon to the right of the URI input—click it. A language input should open above the URI input. Enter a valid language code (e.g. en, fr, es). Then enter any URI and Label and save the item. The language you entered should appear next to the URI value. Edit the item. The language input should be open and contain the language you entered.

Do the same as above for a URI value annotation. Add an item, click on the ellipsis next to any value and click on the "Annotate value" icon. Add any property, select the URI type, and click "Add annotation." Test exactly as above, remembering to click "Set annotations" before saving the item.

**Comment by katknow** [comment]
This is working as described.
