### ISSUE TITLE
Testing: Active/inactive navigation browse links

### ISSUE THREAD

**Issue by jimsafley** [omeka/omeka-s#1887]
On the develop branch, in public navigation, multiple browse links with distinct queries will highlight separately (see #695).

To test this, go to a site's Navigation page, add several Browse custom links _each with different queries_, and save. Go to the public site and click on each navigation link. When one link is active, all others should be inactive. In this case, an active link will be bolder than the non-active links.

**Comment by katknow** [comment]
This seems to be working as described across browsers.
