### ISSUE TITLE
Setting to select Alternate Label for properties in linked resources table

### ISSUE THREAD

**Issue by sharonmleon** [omeka/omeka-s#1900]
Maybe a site setting?

**Comment by sharonmleon** [comment]
@jimsafley What I'm asking for here might not be possible, but I continually hear that the linked resources table is confusing. 

Currently the tables are titled by the Property Label and then the Alternate Label is a column head within the table. In many cases there is no Alternate Label and that whole column is blank.

What I'm wondering is if the Alternate Label (if there is one) can be selected to replace the Property Label as the title for the table. If that setting was selected, then we could eliminate the Alternate Label column from the table.

**Comment by jimsafley** [comment]
I see how this could be less confusing, but they're two complications that make this impracticable, at least in the way that you describe. First, we cannot assume that linking items will use the same resource template (or any template for that matter), so there may be multiple alternate labels for one property. Second, the pagination may make the headers inconsistent across pages, given that, again, we can't assume the same property labels for every linking item.

One solution that we could try is a setting where an administrator selects a resource template as the _archetypal_ template that defines how properties are labeled in the linked resources table. This way there's no ambiguity in the property labels and no inconsistency between pages. Of course this would only work for certain installations with specific data models, but I think it would get us to your goal of simplicity in that area.

**Comment by sharonmleon** [comment]
I think this is kind of why I suggested that it might be a site setting. That the site admin could make some decisions. But that table and the site might not be very connected....

**Comment by jimsafley** [comment]
We've merged a change that resolves the underlying issue. Now, using far more clever database queries, the linked resources page differentiates properties with and without alternate labels, so there's no need for the "Alternate label" column. This is how the feature should have always been implemented.

I do want to discuss the presentation and any other features that we may want to include. For one, could the layout possibly be clearer? Since we're showing the inverse relations between resources, there's a semantic order that makes sense:

`This other resource` `Is related to` `This resource`.

But because the property is in a table caption, it reads like:

`Is related to` `This other resource`

@kimisgold Is this a problem that needs to be solved? Can you think of a way to better communicate the former statement? I admit I can think of no alternative to the current layout, but in my opinion it doesn't immediately communicate the semantics in an intuitive way.

**Comment by kimisgold** [comment]
Jim and I discussed this a little further. I think the newer, smaller table is fine and that it might be a matter of relying on the phrasing of the caption. One of the issues is the diversity of property grammar. We would need to figure out how to accommodate examples such as "Creator", "Is Created By", "Creates", etc. 

My thinking is that whatever we do would include the property and resource title as they appeared on the link resources page. I had some verbose examples to convey intent: `These Resources Include the Relation "Property: Resource Title"`. The way the relation is quoted sidesteps grammatical concerns and provides better context. So you could have examples that look like this:

* `These Resources Include the Relation "Creator: Arthur Conan Doyle"`
* `These Resources Include the Relation "Is Version of: Pride and Prejudice"`
* `These Resources Include the Relation "Has Part: Introduction"`

That's the main thrust, though I think we could make the language more concise. Possibly `Includes: "Property: Resource Title"` or `"Property: Resource Title" appears on..."`

---

Jim also suggested this table layout that would be familiar to those who frequently work with RDF .

![image (1)](https://user-images.githubusercontent.com/606764/194078347-431c14b3-40fe-482c-a3b9-3b51b832b8b2.png)

We think it's a little cludgy and repetitive, but I would be open to using it if it's a standard in use that our users would know. We should see if we can collect some similar tables and use cases for comparison.

@sharonmleon, @allanaaa, do you have any thoughts on these possibilities?

**Comment by sharonmleon** [comment]
I'm not sure that our users are going to be used to any particular linked data formation. I kind of like the sentence format over the table something like.

<header>This resource includes the following links:</header>
- Property: Title
- Property: Title
- Property: Title
