### ISSUE TITLE
Testing: New resource class resource page block

### ISSUE THREAD

**Issue by jimsafley** [omeka/omeka-s#1903]
On the develop branch there's a new "Resource class" resource page block. It lets site administrators include a resource's (item, item set, media) class on the resource show page. To test this go to Site > Theme > Configure resource pages. Under "Add a block to selected region" you should see "Resource class". Click on it and save the page. Then go to an item's public show page. You should see a item's class only if the item is assigned a class.

**Comment by katknow** [comment]
This works as described across browsers. I know when I initially tested the Resource block pages it was only in Default so I'm guessing it's okay, but I just wanted to note that in my testing the button appeared for Default and Center Row but not for The Daily or Foundation.

**Comment by jimsafley** [comment]
Thanks for checking. It seems for now, only Default and Center Row have enabled that section.
