### ISSUE TITLE
Documentation: New resource class resource page block 

### ISSUE THREAD

**Issue by jimsafley** [omeka/omeka-s#1904]
See #1903

**Comment by allanaaa** [comment]
This will depend on https://github.com/omeka/omeka-s-enduser/issues/133 (more info at https://github.com/omeka/omeka-s/issues/1865). Should I take over on the "Configure Resource Page" docs work, @sharonmleon?

**Comment by sharonmleon** [comment]
Thanks @allanaaa, I'd appreciate that. I'm pretty jammed up at the moment. There is a branch that you can build on.
