### ISSUE TITLE
Testing: Batch actions now return to previous browse state

### ISSUE THREAD

**Issue by jimsafley** [omeka/omeka-s#1905]
On the develop branch there's new behavior for batch edit/delete actions. Now, if you used the advanced search to fetch a specific result and then used a batch action on that result, you should be taken back to the original search result.

You'll need to test this for items, item sets, and media. Do an advanced search, select a few resources, and "Edit selected". Just submit the batch form and _you should be taken back to the same search results_. Do the same for "Edit all" and "Delete selected". No need to "Delete all", because it's too destructive.

**Comment by katknow** [comment]
This is working as described.
