### ISSUE TITLE
Testing: Search for items that are not in item set

### ISSUE THREAD

**Issue by jimsafley** [omeka/omeka-s#1913]
On the develop branch users can now search for items that are _not_ in an item set. To test this, go to item advanced search and under "Search by item set" select "Not in" and select an item set. Verify that the resulting items are not in the selected item set. Try multiple combinations of "In" and "No in" with multiple item sets and see if you get expected results.

**Comment by katknow** [comment]
This seems to work as described with a variety of different sized item sets alone and in combination with one another.
