### ISSUE TITLE
Testing: New "Page date/time" block

### ISSUE THREAD

**Issue by jimsafley** [omeka/omeka-s#1921]
On the develop branch there's a new "Page date/time" block layout that allows site administrators to display the date/time a page was created and modified. To test this, go to Site > Pages and add a "Page date/time" block. By default, the block will display created and modified date (in the "medium" format). Save this page and look at the corresponding public page. You should see the configured dates. Now make multiple combinations of configurations and test on the public side.

**Comment by katknow** [comment]
I tried a bunch of different combinations and it worked as described each time.

**Comment by allanaaa** [comment]
Is it possible to add some default styling to how this appears on pages? Maybe in italics and in a smaller font by default, more like a page metadata bit might look on other platforms. I realize this is a block that might go anywhere on a page, but I imagine many authors would have it display either just under the page title or at the end of the page, and would want to differentiate it from text paragraphs. 
I think if you put it in a div with an ID, it would be easy to override the styles with the CSS editor.

**Comment by jimsafley** [comment]
@kimisgold See above comment.

**Comment by kimisgold** [comment]
I've provided some default styles for the block. I'm also wondering if it would make sense to let the user configure alternative labels for "Created" and "Modified", like "Posted", "Updated", etc.
