### ISSUE TITLE
Testing: Search filter and quick add for item set linked resource

### ISSUE THREAD

**Issue by jimsafley** [omeka/omeka-s#1922]
On the develop branch we've added the search filter and quick add features for item set linked resource. To test this, add an item, click "Omeka resource," click "Item sets," and the "Select item set" sidebar should open. Under "Filter search" you should see "Filter by class" and "Filter by item set ID" fields. Below, you should also see a "Quick add" toggle. These features should operate identically to the existing features in the "Items" linked resource sidebar. Test the search filters and quick add feature for expected behavior.

**Comment by katknow** [comment]
All these filter functions are working fine for me.

**Comment by jimsafley** [comment]
Does the quick add feature work as well?

**Comment by katknow** [comment]
It does!
