### ISSUE TITLE
Testing: Select primary media

### ISSUE THREAD

**Issue by jimsafley** [omeka/omeka-s#1926]
On the develop branch users can now explicitly select an item's primary media. The default behavior remains the same: the first media in the list of media is the primary media; but now the user can flag any media in the list as primary.

To test this, edit an item that has multiple media. Go to the "Media" tab and you should see "Primary media" radio buttons. Select a media that is not the first and save the item. The item's thumbnail should now be the new primary media. Edit the item again and change the primary and reorder the media a few more times to ensure expected behavior.

Note that the "Advanced" > "Thumbnail" option should always override the primary media, regardless if it was explicitly selected. Definitely test that this is the case.

**Comment by jimsafley** [comment]
Another thing to note is that there is no "default" option that reverts back to the original "first-in-list" primary. The way it works now is it will lock in the top choice as the primary media when you save the item without changing the primary, and then you'll always have to manually update it when changing order. Consider this while testing. Do you see this as a problem?

**Comment by katknow** [comment]
I'm having an issue where I cannot save a Thumbnail at all when there is primary media selected. However, selecting primary media and reordering is working fine. 

I don't think the order not reverting to default is an issue, as I'm guessing people will generally upload in the order they want or change the order of the media once and pick the primary then (at least based on the test collections I've imported, that seems to be the case). None of the items I've seen included in any of these collections ever have more than an few media files per item anyway, so even if someone would want to rearrange things and pick a new primary occasionally I don't think it'd ever be too cumbersome.

**Comment by katknow** [comment]
If I go into the Advanced tab, select a thumbnail, and then save, I get the little green saved changes banner but nothing actually happens. And if I go back into the advanced tab, it is not showing that there was ever a thumbnail selected (although, if I try uploading a new asset it does show that as being saved in the asset options). So, the Advanced Thumbnail selection is not just not overriding the primary media, but it isn't letting me select one at all.

**Comment by jimsafley** [comment]
We've looked into it and still can't reproduce. We're stumped, really. Try disabling all modules and see if that works.

**Comment by katknow** [comment]
It does work as expected when modules are disabled.

**Comment by jimsafley** [comment]
Try enabling modules one at a time to deduce which module or module combination is responsible for this bug.

**Comment by katknow** [comment]
I've reactivated all of them and it is still working, so not sure what was happening earlier.

**Comment by jimsafley** [comment]
That's a bit worrisome. Whatever was happening, it was most likely not caused by changes introduced by this feature, so I'm closing this issue.
