### ISSUE TITLE
CSS issue on admin/item view

### ISSUE THREAD

**Issue by allanaaa** [omeka/omeka-s#1927]
On the develop branch, some metadata on the admin/item view pages is getting weird placement:

![right-aligned-class](https://user-images.githubusercontent.com/28012148/190254514-0c51a651-173a-4c50-bf28-9bc082748720.PNG)

The relevant bit (from 3.2.2) that seems to be missing:

>  .show .property h4,
 #item-metadata .meta-group h4 {
  width:22.2222222222%;
  vertical-align:top;
  padding:6px 0
 }
 .show .property h4+.value,
 .show .property .values,
 #item-metadata .meta-group h4+.value,
 #item-metadata .meta-group .values {
  padding:6px;
  margin-bottom:0;
  word-wrap:break-word;
  width:77.7777777778%
 }

**Comment by zerocrates** [comment]
@kimisgold almost certainly a regression from the styling updates for the values.

Maybe you want to `dl`-ify the other metadata that can appear there also, rather than restore these styles.

**Comment by kimisgold** [comment]
Should now be addressed in https://github.com/omeka/omeka-s/commit/fe2fccaa1d5a7928bc98d430af310aa6827a21fe
