### ISSUE TITLE
Testing: Improved batch permissions across more roles

### ISSUE THREAD

**Issue by jimsafley** [omeka/omeka-s#1931]
On the develop branch we've improved batch edit and batch delete permissions for the author, reviewer, and editor roles. Now, **authors** can batch edit/delete selected resources _that they own_. They cannot batch edit/delete all. **Reviewers** can batch edit/delete selected resources and batch edit all resource. They cannot batch delete all.  **Editors** can batch edit/delete selected resources and batch edit/delete all resources.

To test this you'll need to have an author, a reviewer, and an editor account. Log into each account and see if the above permissions are accurate on the item, item set, and media browse pages. Note that the author should not be able to select resources that they do not own.

**Comment by katknow** [comment]
I don't know if this is really a problem, but when you are an admin and select resources then hit the back button in your browser, it unchecks the boxes and you have to recheck before you select a new batch edit/delete selected option from the dropdown. The behavior is similar in these other roles, where the options are greyed out until you re-select; however, the different boxes you selected prior to choosing batch edit/delete selected don't automatically uncheck. So, if you go to batch edit/delete selected then hit the back button you have to manually uncheck then recheck the boxes before you can select these options again from the dropdown menu (edit/delete all are still clickable, which I think would be expected). I think if possible it would be better if they uncheck automatically after hitting the back button like the Admin does to avoid confusion over losing access to certain choices--it threw me for a loop for a minute until I realized the boxes weren't auto-unchecking like I was used to. (Please let me know if I can clarify anything--written out it sounds a bit convoluted.) Other than this, it works exactly as described.
