### ISSUE TITLE
Testing: Search by media presence

### ISSUE THREAD

**Issue by jimsafley** [omeka/omeka-s#1935]
On the develop branch users can now search by items with and without media. To test this, go to the item advanced search page, select "Has media" or "Has no media" under "Search by media presence", and submit. For "Has media" the results should only be items that have at least one media. For "Has no media" the results should only be items that have no media. Try this on the administrative and public sides.

**Comment by katknow** [comment]
This seems to be working really well on both the admin and public sides and in combination with other fields on the advanced search page.
