### ISSUE TITLE
Documentation: Select primary media

### ISSUE THREAD

**Issue by jimsafley** [omeka/omeka-s#1938]
See #1926

**Comment by allanaaa** [comment]
Are there any other consequences to choosing a primary media? Other than changing the thumbnail, and what shows up in carousels and other page blocks?

**Comment by zerocrates** [comment]
There's an internal call that allows us to get the primary media, and this affects anywhere that's used. Mostly that's for what thumbnail to display, which media to attach/display by default.... I can't think of any other situations where we use it actually.
