### ISSUE TITLE
User permissions for Assets

### ISSUE THREAD

**Issue by allanaaa** [omeka/omeka-s#1941]
On the develop branch, Editor-level users cannot access the Assets tab, but lower-level users can access it and modify assets. 

I believe it's the lower-level users that need to be fixed, and the Editor is fine. AFAIK only Admins and Supervisors should have access to the Assets tab at all, whether for viewing or changing.

**Comment by zerocrates** [comment]
I think its intended that basically everyone can see that, and that its just the Editors being left out that's the bug here.

The permissions for Assets basically mirror those for resources: all the user roles can view, authors can create and edit/delete their own creations, higher levels can edit/delete everything.  Partially this is just an effect of the asset selection being potentially part of creating an item so they purposely are parallel.

Where does your sense of what the rules should be here come from?

**Comment by allanaaa** [comment]
Anything is fine really. Right now, if I'm recalling right from yesterday,
people who can add assets (site logos etc) can't then delete them. It
doesn't matter too much to me either way, you can just fix Editors.

**Comment by allanaaa** [comment]
I mean, the user manual suggested lower levels couldn't delete.

**Comment by zerocrates** [comment]
I had taken a quick look at the manual before posting and didn't see any obvious statements like that in the manual but it was probably just somewhere I didn't look.

**Comment by allanaaa** [comment]
Huh, I wonder where I got that from then! Seriously, set it up however you'd like.

**Comment by zerocrates** [comment]
I was just thinking more along the lines of if there might be something to fix in the manual related to this also.

**Comment by allanaaa** [comment]
No, I had drafted a line about it in this new table about user permissions, back in July maybe, but I don't think there is anything currently. 

On a 3.2.3 install it looks like it works the same as items: Reviewers can edit anyone's existing assets, authors can view others' and edit their own, researchers can view but not add anything, but again editors can't even see the tab. So it's not actually a develop branch issue. 

Related, you can't change an asset's owner like you can with items and media. I have a few [no owner] assets because I keep making and deleting user accounts, but there's no way to fix them.

**Comment by allanaaa** [comment]
Okay, so what I am observing (based on develop right now) with the exception of Editors still not being able to see the Assets tab:

| Category | Permission | Global Admin | Supervisor | Editor | Reviewer | Author | Researcher |
|-----|-----|---|---|---|---|---|---|
| Assets | View | Yes | Yes | Yes | Yes | Yes | Yes | 
| | Edit | All | All | All | All | Their own | No |
| | Delete | All | All | All | Their own | Their own | No |

I assume this is what we're happy with. So, the only actual issue is: Editors need access to Assets.
