### ISSUE TITLE
Should Jobs have a postPersist() function?

### ISSUE THREAD

**Issue by patrickmj** [omeka/omeka-s#195]
If a job has anything to clean up after itself, or to create related records (like the FedoraImport additional data that corresponds to the Job itself), should that happen via a postPersist() that fires a lifecycle event? I ask that not quite understanding lifecycle events, but it seems like that'd be the approach.

**Comment by zerocrates** [comment]
I would think that in the Fedora instance you'd want to be creating that related record within the job perform code.

The postPersist event will happen right when the Job record is created, which would mean it would happen *before* the job actually did its work. I don't think that would often be useful for "cleanup."

All that said, there should *already* be a Zend event being fired using the lifecycle event system, as that's already set up for all entities for pre and post remove, persist, and update.

**Comment by patrickmj** [comment]
Thanks. currently that code is in the perform stuff. just wondered if there was a better approach.
