### ISSUE TITLE
Testing: Search by resource ID

### ISSUE THREAD

**Issue by jimsafley** [omeka/omeka-s#1950]
On the develop branch users can now search by resource (item, item set, media) ID. To test this, go to the item advanced search page and under "Search by ID" enter an existing item ID. After submitting the form the result should only include the item you entered. Now enter more than one ID, separated by commas. The results should include every item you entered. Now try the same for the item set and media advanced searches.

**Comment by katknow** [comment]
This works as described across item, item set, and media searches.
