### ISSUE TITLE
Testing: Remove unused Title and Description fields on template change

### ISSUE THREAD

**Issue by jimsafley** [omeka/omeka-s#1951]
On the develop branch, when adding a resource (item, item set, media), the Title and Description fields will now disappear after switching to a resource template that does not include them. To test this, create a resource template _that does not include_ Title or Description. Then add an item. You should see Title and Description by default. Now switch to the resource template that you created. Title and Description should disappear. Add another item, enter any text into Title, and switch to the template. Title should remain and Description should disappear.

**Comment by katknow** [comment]
This is working as described.
