### ISSUE TITLE
Resource Template page - Item display count is wrong?

### ISSUE THREAD

**Issue by mebrett** [omeka/omeka-s#196]
On /admin/resource-template it seems like the third column, items, should give the number of items using a specific resource template, but right now every row is displaying the same number, which is the total count of items for the whole install (see image) 

Question 1. Am I reading the function of the Items column correctly? 

Question 2. Has this just not been built yet?

![screen shot 2015-06-04 at 1 51 38 pm](https://cloud.githubusercontent.com/assets/2314070/7990741/0b36fe3a-0ac1-11e5-91b2-40fda3b69505.png)

**Comment by jimsafley** [comment]
Thanks. Fixed in ead9ea5
