### ISSUE TITLE
Testing: Site setting to exclude resources not in site

### ISSUE THREAD

**Issue by jimsafley** [omeka/omeka-s#1962]
On the develop branch users can now exclude resources from public resource show pages that are not assigned to the current site. Testing this will require some set up. I'll delineate the minimum setup you'll need for testing, but it may be helpful to use a logical, interconnected collection of known things (like family tree, org chart, etc.) to better understand the utility of this new feature.

- Create two new resource templates with the same properties, but only one template has alternate labels for those properties.
- Create a handful of new items that link to each other using the "Omeka resource" data type, some using one template you created, and the others using the other template. (This is where using a collection of known things may be helpful. The more complex and meaningful the linkages, the better.)
- Create a new site and, using the Resources interface, assign *just one* of the items you created to it, preferably the item with the most linkages.

Now go to the public show page for the one item assigned to the site. You should see every linked resource in the metadata block and the linked resources block. Now, in site settings, under the "Show" group you'll see a new "Exclude resources not in site" setting. Check it and submit. Go back to the public show page. You should not see any linked resources on the page (unless you linked the current item to itself).

Now do some experimentation. Assign more and more of your items to the site, checking each time that linkages appear after they're assigned. In the linked resources block, test the select menu. Make sure the page reloads as expected after selecting. Make sure the property labels of one template and the alternate labels of the other template are distinct in the select menu.

**Comment by katknow** [comment]
After the most recent pull, I'm getting this error across all my sites:

` Exception
The current theme is not active. Its current state is "invalid_omeka_version".

Details:

Exception: The current theme is not active. Its current state is "invalid_omeka_version". in /var/www/html/katknow/OmekaSTesting/application/src/Mvc/MvcListeners.php:330
Stack trace:
#0 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-eventmanager/src/EventManager.php(321): Omeka\Mvc\MvcListeners->preparePublicSite(Object(Laminas\Mvc\MvcEvent))
#1 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-eventmanager/src/EventManager.php(178): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent), Object(Closure))
#2 /var/www/html/katknow/OmekaSTesting/vendor/laminas/laminas-mvc/src/Application.php(310): Laminas\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Laminas\Mvc\MvcEvent))
#3 /var/www/html/katknow/OmekaSTesting/index.php(21): Laminas\Mvc\Application->run()
#4 {main}`

I tried pulling in the individual theme as well and it just says I'm already up to date. In system information it says I'm currently using version 4.0.0-alpha, but all themes currently are blocked out and say some variation of "This theme requires Omeka S ^3.0.0".

**Comment by jimsafley** [comment]
Yeah, I forgot to mention that you'll need to temporarily change the theme's Omeka version constraint. Open your current theme's `config/theme.ini` file and set `omeka_version_constraint = "^4.0.0"`.

**Comment by katknow** [comment]
This seems to be working as described.
