### ISSUE TITLE
Cozify browse default settings

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#1977]
It seems to me that we can comfortably move the browse default form selects to a single row:

![image](https://user-images.githubusercontent.com/298975/207453200-6ef1c46a-bcce-4014-a6fa-0a4e534f9abf.png)

I have a recollection we discussed this before so apologies if I've missed that and a possible reason 2 rows is necessary here.

**Comment by kimisgold** [comment]
Fixed in https://github.com/omeka/omeka-s/commit/3816261e3fc65bdee40a1410b58906139d35a743.
