### ISSUE TITLE
v4.0.0-rc - Unable to add a new user

### ISSUE THREAD

**Issue by ManOnDaMoon** [omeka/omeka-s#1978]
Hello,

I'm currently working on the v4 pre-version and I have an issue when trying to add users.

The form is limited to mail, name, role and active fields, and when submitting I get the following error:
_CSRF: Value is required and can't be empty_
<img width="400" alt="Capture d’écran 2022-12-20 à 15 15 08" src="https://user-images.githubusercontent.com/3284234/208692963-a2afd422-1318-444f-b337-0840712d2221.png">

Tried on an existing test instance as well as on a fresh install with the same result.

Thanks in advance and KR

Laurent

**Comment by zerocrates** [comment]
Thanks. This is something we introduced pretty close to the release, in fixing another issue. With the commit linked here, it shouldn't be a problem anymore.
