### ISSUE TITLE
Broken asset form helper on page layout editor

### ISSUE THREAD

**Issue by ivyrze** [omeka/omeka-s#2003]
I'm trying to use the [`Asset` form helper](https://github.com/omeka/omeka-s/blob/develop/application/src/Form/View/Helper/FormAsset.php) inside of a page block form but am running into a bug. When I click the desired asset from the picker sidebar, it wrongly opens the options sidebar.

I'm guessing this is a side effect from the system being used by the [`Asset` block form](https://github.com/omeka/omeka-s/blob/develop/application/view/common/asset-block-form.phtml), which I'm not using since I only want to support one attachment without options. The JavaScript from the page editor enabling that block is not narrowly scoped and creates this conflict with the [form helper functionality](https://github.com/omeka/omeka-s/blob/develop/application/asset/js/asset-form.js).

https://github.com/omeka/omeka-s/blob/99eb5688d0e64610f3475cbf052912f1a7f438ef/application/asset/js/site-page-edit.js#L413-L415

**Comment by zerocrates** [comment]
Hmm... yeah.

The asset-list is shared, so I think we'll have to introduce some state, maybe a class, to indicate that the asset sidebar was opened by the Asset block specifically.

**Comment by zerocrates** [comment]
It seems the code that causes this was basically vestigial anyway.

b1de725f7d6f514e21ce52499dfbd6c9f623e0a0 removes that code and should resolve this problem.

**Comment by ivyrze** [comment]
Fantastic, thank you for working this! I just gave the new commit a test and things seem to be working now.
