### ISSUE TITLE
Testing: Resource owner assignment

### ISSUE THREAD

**Issue by jimsafley** [omeka/omeka-s#2004]
In addressing #1984 we've made a change to the "Owner" dropdown in the "Advanced" tab of resources (items, media, item sets). Now, when a resource has no owner, the dropdown should include a "[No owner]" option, which prevents unwanted owner reassignment.

To test this you'll need to create a _temporary_ user, log in as that user, and create an item, a media, and an item set. Log out and log in as another administrator. Delete that temporary user, which should make those resources you just created owner-less. Edit each resource to see if the "[No owner]" option is present. Save the form with "[No owner]" selected. The resource should still be owner-less. Edit each resource again, but this time select another user. The resource should now have that user as its owner.

**Comment by allanaaa** [comment]
Item sets and media work well, but I am having an issue changing the item ownership from [no owner] to another user. It appears to work, but no change is reflected. 

1) Do we want media to change ownership automatically when the item they're attached to changes ownership? 

2) In the browsing columns, you don't see "[no owner]" in the column, it's just blank. Any way we can populate this?
![no-owner](https://user-images.githubusercontent.com/28012148/217878807-6c825220-7b18-40f5-9b40-57fcd191e0df.PNG)

3) Very nitpicky, but it's [No owner] uppercase in the dropdown menu on the Advanced tab, but [no owner] lowercase on the item view page. Can we pick one and stick with it?

**Comment by jimsafley** [comment]
>  I am having an issue changing the item ownership from [no owner] to another user

It's a strange one, but try disabling the Persistent Identifiers module. We believe there's a bug that duplicates the owner form element.

> Do we want media to change ownership automatically when the item they're attached to changes ownership?

That's a reasonable suggestion. I'm sure we thought of it before and decided to keep them separate. I forgot our reasoning, exactly. We'll consider it.

> In the browsing columns, you don't see "[no owner]" in the column, it's just blank. Any way we can populate this?

We can, for sure, but there would be knock-on effect of having to do the same for other null columns.

**Comment by allanaaa** [comment]
> It's a strange one, but try disabling the Persistent Identifiers module. We believe there's a bug that duplicates the owner form element.

Yep, that did it! Everything is working now.
