### ISSUE TITLE
API search query limit option is overridden by pagination

### ISSUE THREAD

**Issue by ManOnDaMoon** [omeka/omeka-s#2009]
Hello,

In the context of a site controller, with the following limited and paginated search query, I expected to get the first result of the 2nd page.
It actually ignores the `limit` query option, and returns the whole page.

```php
$query = [
            'site_id' => $site->id(),
            'limit' => 1,
            'per_page' => 10,
            'page' => 2,
            'sort_by' => 'modified',
            'sort_order' => 'desc',
        ];
$response = $this->api()->search('items', $query);
```
(see full example [here](https://github.com/ManOnDaMoon/omeka-s-module-Sitemaps/blob/c33e52211520f8e4239574783b16c94398a284d8/src/Controller/Site/SitemapsController.php#L99))

Is this the expected behavior here?

Thanks in advance and KR

Laurent Thomas

**Comment by jimsafley** [comment]
This is expected behavior. Setting the `page` parameter will ignore the `limit` and `offset` parameters, which are another way to paginate results. In your case, the `per_page` parameter is effectively the limit.

**Comment by ManOnDaMoon** [comment]
Fine, thanks for the explanation!
