### ISSUE TITLE
Check themes against updated core browse-preview

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#2011]
The fix to #1996 picked up something we missed when updating the core browse markup for 4.0: the browse-preview view was still using the old markup.

Now that it's updated, we need to do a pass over themes that use the core's browse-preview view to check that this hasn't broken the styling, and possibly look at removing any now-unused styles targeting the old markup.

Testing this needs core at current develop.

**Comment by zerocrates** [comment]
Themes using the default browse preview appear to be:

- Cozy
- Default
- The Daily

but correct me if I've missed one.

**Comment by kimisgold** [comment]
Everything looks good so far. I have to do a quick update to Cozy to have browse styles extend to browse preview, but that's nothing to do with your changes. I didn't catch any other themes relying on the default browse preview.
