### ISSUE TITLE
Omeka-S 4.0.0 fresh install error

### ISSUE THREAD

**Issue by tomvitale** [omeka/omeka-s#2012]
a new installation gives me the following errors on first startup on this system

Ubuntu 20.04.5 LTS
. Apache2  2.4.41-4ubuntu3.13
. PHP 7.4.3-4ubuntu2.17 (cli) (built: Jan 10 2023 15:37:44) ( NTS )
. Mysql  Ver 8.0.32-0ubuntu0.20.04.2 for Linux on x86_64 ((Ubuntu))

```
Warning: First argument of class_alias() must be a name of user defined class in /var/www/html/omeka-s/vendor/laminas/laminas-servicemanager/src/autoload.php on line 14

Warning: First argument of class_alias() must be a name of user defined class in /var/www/html/omeka-s/vendor/laminas/laminas-servicemanager/src/autoload.php on line 17

Warning: First argument of class_alias() must be a name of user defined class in /var/www/html/omeka-s/vendor/laminas/laminas-servicemanager/src/autoload.php on line 20

Fatal error: Could not check compatibility between Laminas\Mvc\Service\ModuleManagerFactory::__invoke(Interop\Container\ContainerInterface $container, $name, ?array $options = NULL) and Laminas\ServiceManager\Factory\FactoryInterface::__invoke(Psr\Container\ContainerInterface $container, $requestedName, ?array $options = NULL), because class Interop\Container\ContainerInterface is not available in /var/www/html/omeka-s/vendor/laminas/laminas-mvc/src/Service/ModuleManagerFactory.php on line 30
```

apache error.log :
```
[Wed Feb 15 10:16:03.174639 2023] [php7:warn] [pid 1817443] [client 192.168.1.116:63153] PHP Warning:  First argument of class_alias() must be a name of user defined class in /var/www/html/omeka-s/vendor/laminas/laminas-servicemanager/src/autoload.php on line 14

[Wed Feb 15 10:16:03.174679 2023] [php7:warn] [pid 1817443] [client 192.168.1.116:63153] PHP Warning:  First argument of class_alias() must be a name of user defined class in /var/www/html/omeka-s/vendor/laminas/laminas-servicemanager/src/autoload.php on line 17

[Wed Feb 15 10:16:03.174685 2023] [php7:warn] [pid 1817443] [client 192.168.1.116:63153] PHP Warning:  First argument of class_alias() must be a name of user defined class in /var/www/html/omeka-s/vendor/laminas/laminas-servicemanager/src/autoload.php on line 20

[Wed Feb 15 10:16:03.175597 2023] [php7:error] [pid 1817443] [client 192.168.1.116:63153] PHP Fatal error:  Could not check compatibility between Laminas\\Mvc\\Service\\ModuleManagerFactory::__invoke(Interop\\Container\\ContainerInterface $container, $name, ?array $options = NULL) and Laminas\\ServiceManager\\Factory\\FactoryInterface::__invoke(Psr\\Container\\ContainerInterface $container, $requestedName, ?array $options = NULL), because class Interop\\Container\\ContainerInterface is not available in /var/www/html/omeka-s/vendor/laminas/laminas-mvc/src/Service/ModuleManagerFactory.php on line 30
```

in the same system the Omeka-S 3.2.3 works perfectly

**Comment by zerocrates** [comment]
That's odd. It's almost like you're missing a dependency.

How'd you install: from a zip file, or using Git? If it was from zip the first thing I'd try is just getting a fresh copy of the zip, and re-unzipping/uploading. If some files were missing from the install, this could happen.

**Comment by tomvitale** [comment]
installed through the zip file downloaded today at
```
https://github.com/omeka/omeka-s/releases/download/v4.0.0/omeka-s-4.0.0.zip
```
and unzipped with command line
```
$ unzip omeka-s-4.0.0.zip
```
I thought about a missing dependency, but soon after I successfully installed the previous version in the same server

alternatively I installed the same zip file on another OS and it works correctly (tomorrow I'll try also with Ubuntu 22.04 lts)
```
Debian GNU/Linux 11 (bullseye)
apache2 2.4.54-1~deb11u1
PHP 7.4.33 (cli) (built: Nov  8 2022 11:40:37) ( NTS )
mariadb-server-10.5  1:10.5.18-0+deb11u1
```

**Comment by zerocrates** [comment]
Sorry, by "dependency" I meant the files that come with Omeka S itself, specifically in the "vendor" folder.

The fatal error is ultimately about this class/interface being missing: "Interop\Container\ContainerInterface", and it's one of the things included in the vendor folder. So I thought maybe you could be missing the file for that for some reason. Specifically the files in question would be in the folder vendor/psr/container/src .

Otherwise I don't have a good idea of what could be happening... maybe some bad caching on the PHP side (you could try restarting Apache, or PHP-FPM if that's what's being used, to see if that has an effect)? It feels more like an installation-specific or server-specific issue; we haven't seen it ourselves or seen it reported from anywhere else.

**Comment by zerocrates** [comment]
It doesn't seem like this is a bug on our end so I'm going to close this.
