### ISSUE TITLE
Query Form css is empty

### ISSUE THREAD

**Issue by fitnycdigitalinitiatives** [omeka/omeka-s#2015]
I noticed this file https://github.com/omeka/omeka-s/blob/develop/application/asset/css/query-form.css is referenced in the code but is empty, which gives a 404 error on editing a page. Happens in v.3.2.x and v4 it looks like.

Thanks,

Joseph

**Comment by zerocrates** [comment]
I don't think this would actually cause a 404 (typically a blank file won't do that), but we can probably just drop both the file and our loading of it since it's blank. I think this is just something we thought we might use for the Query element but we ended up not actually using.
