### ISSUE TITLE
Failed to import JSON-LD 1.1 vocabulary

### ISSUE THREAD

**Issue by regisrob** [omeka/omeka-s#2032]
Omeka S 4.0.1 fails to import the IIIF Presentation 3 vocabulary from its context file (JSON-LD 1.1): https://iiif.io/api/presentation/3/context.json

In the "Import vocabulary" form, I put:
- Namespace URI: `http://iiif.io/api/presentation/3#`
- Namespace prefix: `iiif_prezi`
- Vocabulary URL: `https://iiif.io/api/presentation/3/context.json`

Then Omeka S threw this error: `expected list of objects as value of '@context' -> '@version' node, got double`

**Comment by jimsafley** [comment]
The vocabulary import expects an [RDF vocabulary](https://www.w3.org/TR/rdf-schema/) (a collection of classes and properties used to classify and describe resources)., not a JSON-LD context. As far as I know, IIIF has no RDF vocabulary.

**Comment by regisrob** [comment]
I see, sorry for the misunderstanding. I am probably mislead by the fact that I remember importing IIIF Presentation 2 in a previous version of Omeka S. And I still have a vocabulary called "IIIF Presentation 2" (with a `sc` prefix) in my Omeka S instance, but I do not remember from which file it was imported initially... (probably an outdated Shared Canvas xml file ?)
