### ISSUE TITLE
Running Omeka S in project-dir returns different response header

### ISSUE THREAD

**Issue by parijke** [omeka/omeka-s#2048]
I don't know if this is intentional, but when running Omeka S in the project dir, the response header of the api is `application/ld+json`, but when in a basepath (in this case /data) the response header is `application/json`

See screenshots
![image](https://user-images.githubusercontent.com/7671998/234845780-9b9231a2-c3e3-4970-bfc5-f1fa3434b3b3.png)

![image](https://user-images.githubusercontent.com/7671998/234845940-4d62ca60-4a40-4383-bbfb-d7e3e7a2e1dd.png)

**Comment by jimsafley** [comment]
Am I right to assume that these are two different Omeka instances? If so, it's possible they are different versions. We introduced the application/json±ld content-type in a recent version (53a22005fd01a53b7672a18dc8c47afc7ed71c2f).

**Comment by parijke** [comment]
They are copies from the same base and both 4.0.1. so that could not be it?

**Comment by parijke** [comment]
Correction. The one that is giving ld+json is installed from a git clone of develop (which has the commit you mentioned) as the other is installed from the downloaded zip-file.

That could explain it.

**Comment by jimsafley** [comment]
Ah, yes, that's it. It's an unreleased fix to the content-type. Good eye.
