### ISSUE TITLE
How to update or create a property value of an item with a certain resource template

### ISSUE THREAD

**Issue by parijke** [omeka/omeka-s#2049]
We would like to update some meta data based on calculated values in a job. The documentation is unclear how to set or update a property on an item.

Can you describe/clarify how to do this in a Omeka way? I don't want to use SQL, but want to use the formal php API

**Comment by jimsafley** [comment]
Here's sample code to get you started:

```php
// Get the item representation.
$item = $apiManager->read('items', $itemId)->getContent();
// Convert the representation into an ingestable array.
$itemData = json_decode(json_encode($item), true);
// Modify property values as needed.
$itemData['dcterms:title'][0]['@value'] = 'bazbat';
// Update the item.
$apiManager->update('items', $itemId, $itemData);
```

What's important here is that you must pass all values, in their original order, to `update()` that were outputted from `read()`, unless you want them re-ordered or deleted.

**Comment by parijke** [comment]
@jimsafley I sure can update them now, thanks. One last hint: when the property is not set yet, it is not in the itemData.

Can you give me a hint how to add it then properly?

**Comment by jimsafley** [comment]
This is documented [here](https://omeka.org/s/docs/developer/api/rest_api_reference/#resource-values). Note the part about passing `auto` to `property_id`. That will make adding values far easier since you won't have to get property IDs separately.

**Comment by parijke** [comment]
Hi Jim, I already resolved hot to get the property id. I came up with this test. But when I merge this with the array from the read, the added property isn't in the database (using api->update).

What am I doing wrong? 

```
    private function createContentSizeArray($result) {
        return ['sdo:contentSize' => [
            ['type' => "numeric/integer",
            'property_id' => $result[0]->id(),
            'property_label' => $result[0]->label(),
            'is_public' => true,
            '@value' => 0,
            '@type' => 'http://www.w3.org/2001/XMLSchema#integer']
        ]];
    }
    ```

**Comment by jimsafley** [comment]
It looks like your data type is invalid. The value hydrator ignores invalid data types. Try using `numeric:integer` instead of `numeric/integer`. Also, you don't need to pass `property_label`, `@type`, or `is_public` (if the value is public).

**Comment by parijke** [comment]
Indeed I overlooked the slash instead if the colon. It is not presisted yet, but with a second read, the values are in the array now, so getting closer and closer :+1:
