### ISSUE TITLE
Can't update items with x media attached

### ISSUE THREAD

**Issue by olivierbicler** [omeka/omeka-s#2056]
Hi,

When we try to update items having "some" media attached, after 30s , we end up with a white blank screen, due to a maximum execution time exceeded. Number of attached media has a exponential impact of execution time.
5 media : 1.5s
20 media : 3.5s
50 media : 27.5s
60 media : 45s (I increased default maximum execution time for this one, obviously)
100 media : 191s
150 media : >300s

In all cases, we only added a character in title.
Interesting note : these times are only during the first update. Once it has been updated, subsequent updates (on the same item) are done in ~1s.

We first encountered this problem with Omeka 3.2.1, and remains with Omeka 4.0.1
For our tests, all of 30 modules have been deactivated.

As a side note, I logged sql queries (this example had 100 media attached)  :
```
2930 Query	UPDATE media SET position = 136 WHERE id = 512222
2930 Query	SELECT t0.id AS id_1, t0.type AS type_2, t0.lang AS lang_3, t0.`value` AS value_4, t0.uri AS uri_5, t0.is_public AS is_public_6, t0.resource_id AS resource_id_7, t0.property_id AS property_id_8, t0.value_resource_id AS value_resource_id_9, t0.value_annotation_id AS value_annotation_id_10 FROM `value` t0 WHERE (t0.is_public = 1 AND t0.resource_id = 512088) ORDER BY t0.id ASC
2930 Query	SELECT t0.id AS id_1, t0.type AS type_2, t0.lang AS lang_3, t0.`value` AS value_4, t0.uri AS uri_5, t0.is_public AS is_public_6, t0.resource_id AS resource_id_7, t0.property_id AS property_id_8, t0.value_resource_id AS value_resource_id_9, t0.value_annotation_id AS value_annotation_id_10 FROM `value` t0 WHERE (t0.is_public = 1 AND t0.resource_id = 512089) ORDER BY t0.id ASC
<52 similar occurrences of previous query on different resource_id>
2930 Query	DELETE FROM `reference_metadata` WHERE `resource_id` = '512222'
2930 Query	INSERT INTO `reference_metadata` (`resource_id`, `value_id`, `field`, `lang`, `is_public`, `text`) VALUES ('512222', '1012246', 'display_title', '', '1', 'page blanche non chiffrée')
2930 Query	INSERT INTO `reference_metadata` (`resource_id`, `value_id`, `field`, `lang`, `is_public`, `text`) VALUES ('512222', '1012246', 'dcterms:title', '', '1', 'page blanche non chiffrée')
```

These 58 queries seems repeated for each media, for a total of roughly 5800 queries.
On the other hand, the second update on the same item gives a total of 368 queries (including session-related queries, connection start, quit, etc.)

It seems we have some error in our data, but I can't see where.

Thanks for your help.

**Comment by zerocrates** [comment]
I think we've probably already caught this problem, quite recently: there's an issue that happens and causes repeated queries when a lot of media get saved in the same request.

The just-merged PR #2052 fixes a problem with fulltext search for media that causes a large growth in the number of calls and queries to update the saved fulltext index data. With 100 media, as in your example, calls to update fulltext for media would get called 5,050 times, a pretty close match to your numbers. At 150 it would be 11,325 calls.

Fulltext searching for media was added in version 3.2, so that matches your experience of when you first noticed the problem also.

**Comment by olivierbicler** [comment]
I installed the develop version, and indeed, the problem seems solved : an item with 800 media related has been updated in 5 seconds.

Many thanks !

**Comment by zerocrates** [comment]
Great. Thanks for reporting back on your experience with the change, that's very helpful information.
