### ISSUE TITLE
emptyValues() function for Resources?

### ISSUE THREAD

**Issue by patrickmj** [omeka/omeka-s#207]
For the connectors to other data sources (e.g., Fedora, DSpace), one use case is syncing from that source to Omeka S. In many cases, that'll call for clobbering all existing data from previous imports and updating with new data.

Instead of working through the update-delete via the API, would it make more sense to provide a blanket function that deletes all values for a resource with a direct DQL query?

Don't know if that more properly would be on the abstract resource entity or representation (or elsewhere). 

Seems like such a function would be way more efficient than the update-delete approach for the case of needing to clear out old data and replace it with new.

**Comment by zerocrates** [comment]
Having a separate function like this really breaks our committment to expose everything as part of the API, so I don't think we'll go that direction.

**Comment by zerocrates** [comment]
This should be resolved by the fix to #211.
