### ISSUE TITLE
Testing: 4.0.2

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#2070]
This is the `release-4.0` branch, the reported version should be 4.0.2-alpha.

More or less we're just talking a general runthrough rather than any particular features being tested as this is a bugfix release...

Note, this is an upgrade for 4.0.1, so testing should be on upgrade from that version, or on clean installs, not going from a current-develop version.

The removal of n3 from RDF import might merit a docs change, if that was specifically documented before.

Just for general information, and to get me a head start on release notes, the bugs fixed are:

- Batch editing options to clear property values and set value visibility sometimes did not work, depending on what other batch edit operations were used at the same time
- The lightgallery code was missing its license key
- Issues when displaying a very large number of tabs on admin pages
- Removed nonfunctioning n3 option for RDF import
- Misleading page display when user revokes own privileges from a site
- Issues with reporting of empty required fields on the resource add/edit pages
- Overbroad selection for assets on the site edit page
- Incorrect routing for URLs with "false" site slugs
- Property label still displayed even if no values were shown due to the locale filter being enabled on a site
- Miscellaneous translation string issues
- We unnecessarily checked the database version on each request to decide whether to use database-backed sessions
- Linked resources/subject values display didn't work properly for non-items
- Events for Doctrine entities did not always fire correctly
- Asset upload errors were silent
- Some advanced search fields were missing labels for accessibility
- Fulltext search for media caused an unnecessarily high number of queries when multiple media were saved at once
- Media public resource pages didn't have the media render block configured by default

**Comment by zerocrates** [comment]
Slight addition here, on latest pull there's a small database migration (if you've been using develop on the same database you probably won't get the prompt for it though).

**Comment by allanaaa** [comment]
> The removal of n3 from RDF import might merit a docs change, if that was specifically documented before.

✅

>     Batch editing options to clear property values and set value visibility sometimes did not work, depending on what other batch edit operations were used at the same time

Seems to work fine. 

>     The lightgallery code was missing its license key

What do you suggest to test this? I haven't noticed any lightbox issues myself.

>     Issues when displaying a very large number of tabs on admin pages

You mean tabs on item editing and that sort of thing? Like when Mapping and Extract Metadata and etc. are added? 

>     Misleading page display when user revokes own privileges from a site

Looks good when you downgrade by a step or two, or remove yourself when someone else is still assigned. 

However, when you remove the last user from a site, it appears to save but just reverts back to how it was just before. (Says it saved successfully.) We should probably have a "You cannot remove all users from a site" or "A site cannot have zero users" error message there.  

>     Issues with reporting of empty required fields on the resource add/edit pages

Looks good.

>     Overbroad selection for assets on the site edit page

Does this mean Site admin > Info tab > thumbnails? Or in themes? Or on page blocks? I don't know what "overbroad" means.

>     Incorrect routing for URLs with "false" site slugs

How would I test this?

**Comment by zerocrates** [comment]
> > The lightgallery code was missing its license key
>
> What do you suggest to test this? I haven't noticed any lightbox issues myself.

No testing to be done there.

> > Issues when displaying a very large number of tabs on admin pages
> 
> You mean tabs on item editing and that sort of thing? Like when Mapping and Extract Metadata and etc. are added?

Yes. It's just a minor style adjustment to the form tabs.

> > Overbroad selection for assets on the site edit page
>
> Does this mean Site admin > Info tab > thumbnails? Or in themes? Or on page blocks? I don't know what "overbroad" means.

The page block editor. It's an issue with how the JS for the asset block targeted some events used to make the asset selection and sidebar work. Won't really have an observable outcome on its own.

> > Incorrect routing for URLs with "false" site slugs
>
> How would I test this?

In particular this deals with a site slug that's just '0' (a zero), just that it's all still functional in that case

> > Misleading page display when user revokes own privileges from a site
>
> Looks good when you downgrade by a step or two, or remove yourself when someone else is still assigned.
>
> However, when you remove the last user from a site, it appears to save but just reverts back to how it was just before. (Says it saved successfully.) We should probably have a "You cannot remove all users from a site" or "A site cannot have zero users" error message there.

This is going to be a side effect of just how submitting no users works (probably). I'd treat it as a separate bug we can fix in a future release.

**Comment by allanaaa** [comment]
>     Property label still displayed even if no values were shown due to the locale filter being enabled on a site

This looks good. Should this locale filter also stop displaying the "used for resource title" and "used for resource description" fields on browse pages if those fields are not the right language? I suppose this would break a lot of stuff, but presumably it's where this setting is going. 

Another side question: When a site is in a language, should the admin bar at the top also translate? Seems like ... no. Should be the user's selected language (or the installation default) rather than the site language.

>     Linked resources/subject values display didn't work properly for non-items

Linked resources seems fine on item sets. I could do more if you think it needs it. 

>     Media public resource pages didn't have the media render block configured by default

Works on a new site. Why don't we use the lightbox gallery by default on both items and media?

**Comment by zerocrates** [comment]
> This looks good. Should this locale filter also stop displaying the "used for resource title" and "used for resource description" fields on browse pages if those fields are not the right language? I suppose this would break a lot of stuff, but presumably it's where this setting is going.

I think this already is how it works?

> Another side question: When a site is in a language, should the admin bar at the top also translate? Seems like ... no. Should be the user's selected language (or the installation default) rather than the site language.

We don't have a feature for this stuff to vary within the page. You could file it; no change on that front will go in on this version.

> Why don't we use the lightbox gallery by default on both items and media?

We covered this before: the lightbox gallery doesn't work for some media. We use embed because a media page is always one media so no need for all the "gallery" controls, and to guarantee we can display it properly, if it's iiif image, an oembed, etc.

**Comment by allanaaa** [comment]
> > This looks good. Should this locale filter also stop displaying the "used for resource title" and "used for resource description" fields on browse pages if those fields are not the right language? I suppose this would break a lot of stuff, but presumably it's where this setting is going.
> 
> I think this already is how it works?

Not reliably. It's working in one site and not in another. I'll try to chase it down and file another issue.

> 
> > Another side question: When a site is in a language, should the admin bar at the top also translate? Seems like ... no. Should be the user's selected language (or the installation default) rather than the site language.
> 
> We don't have a feature for this stuff to vary within the page. You could file it; no change on that front will go in on this version.
> 
Sounds good.

That's it, I think I'm done here! There's not too much to document, I will probably be done with the docs PR today or tomorrow.

**Comment by zerocrates** [comment]
> Not reliably. It's working in one site and not in another. I'll try to chase it down and file another issue.

I'd suspect a difference in the theme's code for the browse pages, if these sites are on different themes.

**Comment by allanaaa** [comment]
Oh, actually, the "empty properties based on language" problem still exists on the new Freedom theme, though it's fixed in all other themes. I can make an issue there.

<img width="1433" alt="Screenshot 2023-07-25 at 2 39 32 PM" src="https://github.com/omeka/omeka-s/assets/28012148/ba02b029-f592-4895-81fa-d3ffb2a468d7">

**Comment by zerocrates** [comment]
Yeah Sharon also ran into this. This is just an issue of Freedom's creation and the fix to the issue in the core kind of crossing paths with each other midflight.

**Comment by allanaaa** [comment]
> Yeah Sharon also ran into this. This is just an issue of Freedom's creation and the fix to the issue in the core kind of crossing paths with each other midflight.

Did Sharon report it already, or should I make an issue?

**Comment by zerocrates** [comment]
I don't think it's been reported on Freedom.

**Comment by zerocrates** [comment]
OK, I'm going to close this issue as complete.
