### ISSUE TITLE
Browse pages with queries do not respect site language settings predictably

### ISSUE THREAD

**Issue by allanaaa** [omeka/omeka-s#2089]
Re https://github.com/omeka-s-themes/thanksroy/issues/12#issuecomment-1652299291

When a browse query is set, it mostly does not use the correct locale filtering. This is on a site with locale filtering and custom browse properties set. It will display the correct language when available but fall back on the first value when not available, insteaad of displaying [No title] and an empty description, which is what's happening on the basic "Browse items" page.

A browse query with a resource template works, but a browse query with a class does not, and a browse query with a property value does not.

**Comment by zerocrates** [comment]
I'll look to see if there's something I've missed, but queries shouldn't really have any effect at all on the locale handling.

Can you give some representative links showing the problem?

**Comment by allanaaa** [comment]
Browse items (the way it's supposed to look): http://dev.omeka.org/amayer/amayer-s/omeka-s/s/my-omeka-s-site/item
Browse items with a resource template query (good): http://dev.omeka.org/amayer/amayer-s/omeka-s/s/my-omeka-s-site/item?resource_template_id%5B%5D=1&has_markers=&mapping_address=&mapping_radius=&mapping_radius_unit=km
Browse items with a class query (falling back on non-language-tagged values): http://dev.omeka.org/amayer/amayer-s/omeka-s/s/my-omeka-s-site/item?resource_class_id%5B%5D=33
Browse items with a property value query (ditto): http://dev.omeka.org/amayer/amayer-s/omeka-s/s/my-omeka-s-site/item?property%5B0%5D%5Bjoiner%5D=and&property%5B0%5D%5Bproperty%5D=12&property%5B0%5D%5Btype%5D=eq&property%5B0%5D%5Btext%5D=en&has_markers=&mapping_address=&mapping_radius=&mapping_radius_unit=km

Browse item sets (falling back on non-language-tagged values): http://dev.omeka.org/amayer/amayer-s/omeka-s/s/my-omeka-s-site/item-set
Browse item sets with a property value query (falling back on a non-language-tagged value in one class, correctly showing [No title] in another case, where the only title value is in another language): http://dev.omeka.org/amayer/amayer-s/omeka-s/s/my-omeka-s-site/item-set?property%5B0%5D%5Bjoiner%5D=and&property%5B0%5D%5Bproperty%5D=12&property%5B0%5D%5Btype%5D=eq&property%5B0%5D%5Btext%5D=en&has_markers=&mapping_address=&mapping_radius=&mapping_radius_unit=km

**Comment by allanaaa** [comment]
Oh I see. It is correctly falling back on non-language-tagged values as per the "Filter values" setting, but not as per your comment about when you have custom browse properties set. (https://github.com/omeka/omeka-s/issues/2087#issuecomment-1650436089)

So this is the way it *should* be, according to what I proposed, but not according to your statement of what it already does. :/

**Comment by zerocrates** [comment]
Non-tagged values always "match" for purposes of those rules.

**Comment by zerocrates** [comment]
So: I think judging by your description this isn't actually an issue, yes?

**Comment by allanaaa** [comment]
I guess so!
