### ISSUE TITLE
website deadlink

### ISSUE THREAD

**Issue by mquantin** [omeka/omeka-s#2104]
cause I don't know where to put this. 

On this page https://omeka.org/s/modules/ItemSetsTree/
documentation of module item set tree link is dead (https://omeka-s-module-itemsetstree.readthedocs.io/en/latest/)

the new link is https://biblibre.github.io/omeka-s-module-ItemSetsTree/fr/

**Comment by sharonmleon** [comment]
This is actually a page generated with in the module package, so the best place to file the issue is on the github page for the module itself: https://github.com/biblibre/omeka-s-module-ItemSetsTree
