### ISSUE TITLE
Can't minimize Lightbox in fullscreen when using Freedom Theme

### ISSUE THREAD

**Issue by joebauer** [omeka/omeka-s#2114]
This happens when using the Lightbox gallery in the item page and when you have the Freedom theme enabled. When viewing an item page on the site, if you click on the full-screen icon for the lightbox gallery, the toolbar for it goes to the top of the screen and is obscured by/hidden behind the navigation bar from the Freedom theme making it impossible to minimize the lightbox or access any of its features. 

We're using version 4.0.4 of Omeka S and version 1.0.1 of the Freedom theme. 

Thanks!

**Comment by mnhampl** [comment]
I think this is the same issue that's described here: https://github.com/omeka-s-themes/freedom/issues/6 Is there a way to connect these two issues?

**Comment by zerocrates** [comment]
The copy of this issue that's in the Freedom theme's repository is the better place for it, so I'll close this one, that's probably the best move here.
