### ISSUE TITLE
Omeka S 4.1 Release Candidate

### ISSUE THREAD

**Issue by coret** [omeka/omeka-s#2136]
The [omeka-s-4.1.0-rc.zip](https://github.com/omeka/omeka-s/releases/download/v4.1.0-rc/omeka-s-4.1.0-rc.zip) file does not have a **vendor** directory and the **themes** directory is empty. Is this on purpose / ok?

**Comment by coret** [comment]
fixed

**Comment by zerocrates** [comment]
We didn't change the release at all on our end. I'm guessing you might have downloaded Github's automatic zip of the source the first time? That wouldn't include vendor or the default theme.
