### ISSUE TITLE
How should visibility of media be handled?

### ISSUE THREAD

**Issue by kimisgold** [omeka/omeka-s#214]
While setting the default visibility of resources to 'public', a question about the visibility of media came up. The interface doesn't allow the user to toggle media's visibility at the moment. Should the user be able to set media visibility, how should it work in relation to associated items' visibility? Should media visibility be entirely independent, or should their visibility be conditional upon their associated items' visibility?

**Comment by jimsafley** [comment]
Here are the requirements as I see them. A user should be able to toggle media visibility, when adding it to an item and editing it. When an item is private its child media should *not* be visible. We need to discuss whether this means that a) all child media are automatically set to private, or b) they retain their visibility flags but are nevertheless invisible to people without permission. The first option is far, far easier.

**Comment by zerocrates** [comment]
I think it would be much better if the visibility of a Media just depended on both its own flag and its parent's flag, but I'd forgotten this is being handled with that Doctrine SQL filter, where it may not be possible to add in that join to make the parent's visibility even checkable.

**Comment by zerocrates** [comment]
It also just now occurs to me that with Media currently having their own totally separate permissions flag slash check, you hit the possibility where someone else with adequate permissions could go and add a media to an item you own, and you wouldn't be able to see it if they marked the media private (since you don't own it and it's not public). That seems like a possibility we don't want to allow.

**Comment by kalbers** [comment]
This is seemingly getting complicated, particularly with John's last point about shared resources.

Perhaps we should simplify it, and attached media should just take on the permissions of the item they are attached to? I can see where private media might be a nice feature, but it doesn't strike me as vital or even something that would be used very often.

**Comment by patrickmj** [comment]
In the case @zerocrates just described, would that media be visible to anyone except the person who added it? If it is only visible to the owner/person who added it, I'm not concerned ... yet.

**Comment by zerocrates** [comment]
I'm fairly significantly concerned if the owner of the item and the owner of the media are different.

*But*, I remembered today that we already just force Media to be owned by the owner of their containing Item, so that crazy scenario outlined above actually isn't possible.

**Comment by kalbers** [comment]
Yeah, I agree that would have been a major problem, but if ownership is transferred to the item owner, that skirts the issue. (It possibly raises another issue, but I'm happy to stick my head in the sand on that one.)

**Comment by patrickmj** [comment]
The scenario made me think of the use case of people wanting to make personal notes on an Item. E.g. teaching notes that would take the form of an HTML media on an item, that only that teacher would care about, even though the Item itself is available to all.

From the discussion, though, that sounds like something to punt to a module if it is asked for. Yes?
