### ISSUE TITLE
ListOfPages can break site edit with invalid data

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#2142]
A ListOfPages block with this `data` column:

    {"pagelist":"\"\""}

breaks the admin as it tries to `array_walk` over an empty string. Not quite certain how this situation arises that it's saved in that format in the first place, but there's protection against this on the display side that's missing on the admin side.

**Comment by matthewjmckinley** [comment]
Fixed by https://github.com/omeka/omeka-s/commit/13c9e646de4f3bd06c2cfd868f368a7995751183
