### ISSUE TITLE
Table of contents page block error

### ISSUE THREAD

**Issue by allanaaa** [omeka/omeka-s#2145]
In the docs, we say you can leave the field blank to show all child pages. But this produces an error in practice:

<img width="719" alt="Screenshot 2024-02-06 at 16 21 40" src="https://github.com/omeka/omeka-s/assets/28012148/4e7b2aad-1aba-40cf-bf80-4497fd75f5b7">
<img width="1120" alt="Screenshot 2024-02-06 at 16 21 49" src="https://github.com/omeka/omeka-s/assets/28012148/af713aae-112b-431f-99a7-eed9f087e278">

Do you want me to change the docs? Or can this be made to work?

**Comment by zerocrates** [comment]
Regardless it shouldn't be showing the warning. So we'll have to do something here.

**Comment by zerocrates** [comment]
In terms of the code for the block, it's got assumptions in various places that when nothing's set there, the value is just 1, and it's a number input with a minimum of 1. So I suspect the "leave it blank" feature has just never actually been a thing for this block.

**Comment by zerocrates** [comment]
So, I've fixed the notice (it's an error in some PHPs actually).

I didn't create a "show everything if depth is empty" feature so let's do a docs change there.
