### ISSUE TITLE
Sites: make it possible to query the API for slug(s), not IDs

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#215]
The basic Site pages all currently run off site ID, not slug. Obviously for the front-end we need to be able to query by slug instead, and for a page to be able to query by *two* slugs (the site slug and the page slug).

Ideally we would get the API to accept different information for "find," but other alternatives like trying to leverage the browse functionality could also work (though not optimally because of things like the pointless COUNT queries that would be run).

**Comment by jimsafley** [comment]
Take a look at this diff for my solution: https://gist.github.com/jimsafley/ca8c45ca199bf0972af0

On top of a few unrelated query optimizations, it allows requests to define an ID field, defaulting to "id". For example, from a controller:

```php
$response = $this->api()->read('sites', 'foo-bar', array('field' => 'slug'));
```

**Comment by zerocrates** [comment]
This looks like it should work for the site slugs.

The only thing mentioned in the description that this doesn't *quite* cover is the idea that for a page, we'd be looking for two slugs simultaneously, or at least two pieces of data: the site slug and the page slug. We can do two separate `read`s, but on that second one for the page itself we'd still need to be able to pass, at a mininum, the site ID and the page slug at the same time to get the right page.
