### ISSUE TITLE
Page block preview issues

### ISSUE THREAD

**Issue by allanaaa** [omeka/omeka-s#2157]
I have three blocks - one floated left, one right, and one default - in a normal flow page:

<img width="1522" alt="Screenshot 2024-03-04 at 11 04 12" src="https://github.com/omeka/omeka-s/assets/28012148/f38a690e-708d-443e-b649-3b04bdb7b21c">

The page layout preview isn't showing anything set to left or right (in the whole page):

<img width="1267" alt="Screenshot 2024-03-04 at 11 05 43" src="https://github.com/omeka/omeka-s/assets/28012148/836f2e39-b713-476e-9c80-cd378fcaf2f7">

I also wonder if the preview buttons can jump to the block in question, on long pages where you have to scroll. 

https://github.com/omeka/omeka-s/assets/28012148/9b0f954a-122f-4cc3-ae1b-20fbbdc83fc8

**Comment by jimsafley** [comment]
If anything, I think we should hide the preview feature when in the "Normal flow" layout. It was a late, almost accidental addition, an afterthought following the implementation of grid preview. Normal flow preview adds little value, given it's always a stack, except in this specific case where individual blocks are floated. We can't detect the floating behavior of blocks given float is a block configuration, not a block layout configuration.

**Comment by jimsafley** [comment]
Preview removed from normal flow in 99679147ea96d2e8c3fbab3cce6c4ab1a790bc0b
