### ISSUE TITLE
Page created/modified block

### ISSUE THREAD

**Issue by allanaaa** [omeka/omeka-s#2158]
The contents of the created/modified block sometimes overflow the container. Can we change that to text that will break and wrap? 

<img width="283" alt="Screenshot 2024-03-06 at 16 22 18" src="https://github.com/omeka/omeka-s/assets/28012148/72b80614-449d-4515-a772-fbb0518aba7c">

**Comment by kimisgold** [comment]
I got rid of a `max-content` style that was in there, but I'm feeling hesitant because I'm trying to remember why it was there in the first place. Could you check for any oddities across different layouts?

**Comment by allanaaa** [comment]
Yep, Center Row is doing something funky here. There's plenty of space for this to all be on one line, I don't know why there are breaks. 

<img width="494" alt="Screenshot 2024-03-07 at 16 10 29" src="https://github.com/omeka/omeka-s/assets/28012148/1d8dd2b3-2c94-46ed-8455-eac97b6a28f9">

**Comment by kimisgold** [comment]
There we go, that's what the `max-content` was trying to fix. I think setting the property and value spans to `display: inline` should do it.
