### ISSUE TITLE
Browse preview block

### ISSUE THREAD

**Issue by allanaaa** [omeka/omeka-s#2160]
In 4.1, the Browse Preview page block can be stuck in some pretty small spaces. The "grid" browse display (rather than list) should better fill that space. Specifically, it seems stuck in a 4-column layout, but should probably expand when possible, or maybe only do 3 or 2 columns depending on the width of the block. 

Center Row list and grid for comparison:
<img width="446" alt="Screenshot 2024-03-07 at 09 42 41" src="https://github.com/omeka/omeka-s/assets/28012148/3b56582e-0543-4b3b-82e3-eb51f0021ddb">
<img width="444" alt="Screenshot 2024-03-07 at 09 42 36" src="https://github.com/omeka/omeka-s/assets/28012148/c5a0b9ad-01fe-482a-93bb-9f6c39aac460">

Foundation:
<img width="890" alt="Screenshot 2024-03-07 at 09 47 15" src="https://github.com/omeka/omeka-s/assets/28012148/84ce32ea-2f7b-4610-8886-723c8ec83fbc">
<img width="888" alt="Screenshot 2024-03-07 at 09 47 21" src="https://github.com/omeka/omeka-s/assets/28012148/7a061387-5a63-4a9a-ad09-3e77e6ad965a">

**Comment by allanaaa** [comment]
You can get significant text overflow in Foundation with its larger fonts. Not sure if there's a way to counter that programatically other than just playing it safe. 

<img width="423" alt="Screenshot 2024-03-07 at 10 06 26" src="https://github.com/omeka/omeka-s/assets/28012148/1cc054e9-9e41-4e5e-9877-762d94466d4e">


<img width="428" alt="Screenshot 2024-03-07 at 10 05 22" src="https://github.com/omeka/omeka-s/assets/28012148/dbef6055-2623-4354-b56b-5cc8d30d470c">

**Comment by kimisgold** [comment]
Center Row and Foundation should now have updates that help with scaling for smaller numbers of items, as well as smaller device widths. They're ready for a look.

**Comment by allanaaa** [comment]
In Foundation, 2/3/4 look good, but 1 is still limited:

<img width="815" alt="Screenshot 2024-03-07 at 15 34 37" src="https://github.com/omeka/omeka-s/assets/28012148/84ad78e0-e8c4-49f5-a0da-5c6742160830">
<img width="787" alt="Screenshot 2024-03-07 at 15 34 53" src="https://github.com/omeka/omeka-s/assets/28012148/37129ab5-b9aa-411b-b118-ac6107d774c8">
<img width="788" alt="Screenshot 2024-03-07 at 15 35 09" src="https://github.com/omeka/omeka-s/assets/28012148/4a3341d4-06f0-4f81-93d6-740244e260d8">
<img width="791" alt="Screenshot 2024-03-07 at 15 35 24" src="https://github.com/omeka/omeka-s/assets/28012148/f612974e-fa09-48c9-84c7-0fca8c0ff205">

**Comment by kimisgold** [comment]
The missing style should be in now.

**Comment by allanaaa** [comment]
In Center Row, it looks good except if you have 5 entries the second row is centered, rather than in the grid?

<img width="757" alt="Screenshot 2024-03-07 at 15 38 11" src="https://github.com/omeka/omeka-s/assets/28012148/77ac45fa-e2ec-4522-9fac-692ee47a7e23">

I also noticed that the grid has left and right padding that the list version doesn't, but that's a minor issue. 

<img width="756" alt="Screenshot 2024-03-07 at 15 37 26" src="https://github.com/omeka/omeka-s/assets/28012148/20c26ecf-78ef-4da6-8ef5-16f5e95a2090">

**Comment by allanaaa** [comment]
Center Row is all in a grid now, thanks.

**Comment by allanaaa** [comment]
Foundation looks good at all numbers. There is still a tiiiiiiiny bit of overflow but it's pretty close. I would maybe bump down to 3 in a row first, but again, minor. 

<img width="564" alt="Screenshot 2024-03-07 at 16 16 35" src="https://github.com/omeka/omeka-s/assets/28012148/cf92f0cd-9b76-4480-8a73-9374da0eb853">

**Comment by allanaaa** [comment]
I think this is the worst it looks, in Inkwell:

<img width="570" alt="Screenshot 2024-03-07 at 16 19 32" src="https://github.com/omeka/omeka-s/assets/28012148/78897313-667a-4fa1-ab38-a83c77256386">

**Comment by kimisgold** [comment]
Foundation is now updated with some container queries to smooth out some of these awkward widths, ready for a look.
