### ISSUE TITLE
"CSRF: Invalid or missing CSRF token"

### ISSUE THREAD

**Issue by allanaaa** [omeka/omeka-s#2163]
I usually have a few admin-side tabs open. If they sit for longer than an hour or so, and then I try to make changes to a setting, I get error "CSRF: Invalid or missing CSRF token" when I save the page. This is happening a lot more in 4.1 than it did in earlier versions.

**Comment by zerocrates** [comment]
Default expiration time on those tokens is an hour, a setting that hasn't changed. My best guess here is just that the things you're looking at lately lead to more "left open" forms and chances to run into this.

Simplest action we can take here is to increase that default time higher than an hour.

**Comment by allanaaa** [comment]
Hrm. Maybe it wasn't working as intended before, and is now? 

As long as you've looked into it, I'm happy. It's up to you what that setting should be.

**Comment by zerocrates** [comment]
I think one big thing that could account for the difference is just that you've been doing a lot with site pages. Most of our things that are forms redirect you to the corresponding show page when you save your changes, but the site page admin edit doesn't have a corresponding show page, so you just go back to the form. So it's much easier to have that form in particular sitting open for a long time.
