### ISSUE TITLE
Browse items have white fade-out

### ISSUE THREAD

**Issue by allanaaa** [omeka/omeka-s#2164]
In 4.1, you can change the background colour of blocks, which means the "Fade to white" setting on some browse preview blocks should be updated to match the container colour. If possible. It's pretty minor, so if it's a complicated situation we can skip it. I don't think we truncate text anywhere except the browse preview blocks, but I'm not certain.

<img width="780" alt="Screenshot 2024-03-08 at 13 26 14" src="https://github.com/omeka/omeka-s/assets/28012148/45a77e60-6551-4e39-b31c-9bbb4767d6b5">

**Comment by kimisgold** [comment]
I'm not sure there's a way to grab that color value to apply it to the fade. We'd still run into this issue with a background image. I think I'm going to offer a theme configuration setting for truncating with an ellipsis instead of the fade. Does that seem like a reasonable alternative?

**Comment by allanaaa** [comment]
I wouldn't bother with a colour setting. It would be nice if text with fadeouts could inherit their containers' background colours, but it's not essential. Someday they'll introduce just setting the text opacity to 0....

**Comment by allanaaa** [comment]
Whoops. This is an option that appears in the theme settings, right? I just changed it for Default, but I don't see it in Cozy. Do you have to do each theme?

**Comment by kimisgold** [comment]
Yup, we have to do it for all themes that do it.  I believe it's just Cozy and Foundation that do it. The other themes don't seem to truncate descriptions. For those, I might apply the trailing ellipsis clipping only.

**Comment by kimisgold** [comment]
Cozy, Foundation, and Default themes now all have a theme setting to truncate with a fade, ellipsis, or show the full value.

**Comment by allanaaa** [comment]
Cozy shows the three setting options, but the fadeout no longer works - it just shows the full value. (Ellipsis works fine.)

<img width="794" alt="Screenshot 2024-03-13 at 18 54 12" src="https://github.com/omeka/omeka-s/assets/28012148/d5238f36-7b24-4c38-8843-8cb89645231b">


<img width="792" alt="Screenshot 2024-03-13 at 18 53 53" src="https://github.com/omeka/omeka-s/assets/28012148/6870f39c-8b50-4240-baa6-9a4036c1e2e6">

**Comment by kimisgold** [comment]
Default and Cozy should now be fixed.
