### ISSUE TITLE
User's item default settings don't work

### ISSUE THREAD

**Issue by allanaaa** [omeka/omeka-s#2166]
When a user has a default item template, item set(s), and site(s) for all their new items, the resource template seems to work (and automatically adds the associated class), but the default item set and default site don't automatically get set.

**Comment by allanaaa** [comment]
When a user has site defaults for items in their user settings, the item add tab is showing the right number of entries but they're all blank:

<img width="841" alt="Screenshot 2024-03-13 at 18 34 23" src="https://github.com/omeka/omeka-s/assets/28012148/b8b5fbe9-9f16-4f7f-97f8-40af8f475302">

If this setting is not intended to have any effect unless the user is also given a site-level permission, this seems pointless (at least to have the setting here, rather that in the site users tab).

**Comment by allanaaa** [comment]
When the item is saved and then edited, it changes to this:

<img width="846" alt="Screenshot 2024-03-13 at 18 39 44" src="https://github.com/omeka/omeka-s/assets/28012148/8d362744-9fde-4628-8444-569728c857ee">

**Comment by jimsafley** [comment]
The `fix-default-site-for-items` branch should fix this.

**Comment by allanaaa** [comment]
User settings are now reflected on new items. 

If the user goes to remove a site after saving the new item, they don't have the ability to do that. They can only determine the sites to add the item to at the point of creation, not in editing afterwards. Which is fine, I can just document that if you'd like. 

Item sets don't have that problem (the user can remove items from the default item sets, or add more, after creation). 

I realize these work differently by design, just wanted to put it out there in case some of this isn't intended.

**Comment by zerocrates** [comment]
Can you show a screenshot of what you're talking about with editing and not being able to remove?

In general, what they can do or not do is related to what permissions they have for the site. There are special carveouts to allow assignment to "default" sites even when the user doesn't have permission to add items to that site (so the "add all items to this site by default" setting for the site still works). I think that's what you're describing here but I'm not totally sure.

**Comment by allanaaa** [comment]
Yeah, that's what I was imagining. A user with no site-specific settings can still add items to their default sites - but then because they don't have site-specific settings they have no ability to remove the item after that point. 

User settings are basically everything (author level):
<img width="1035" alt="Screenshot 2024-04-01 at 14 48 08" src="https://github.com/omeka/omeka-s/assets/28012148/8ff01a84-b7fd-43c9-85b7-dc72c0a8c61a">

The item-add and -edit experience:

https://github.com/omeka/omeka-s/assets/28012148/30a449ec-a5f4-4dcb-8b99-3d91d34deec7

So yes, I guess we could change (or document) that the interface _appears_ like you're deleting a site from an item, and it _appears_ to save, although it won't take.

**Comment by zerocrates** [comment]
Hmmm, I think that's a bug.

**Comment by jimsafley** [comment]
The most recent commit should allow users who can edit an item (but do not have site-specific privileges) to un-assign a site from that item.

**Comment by allanaaa** [comment]
Perfect. A user at the lower levels can't choose which of their default sites get the item at item creation, and they can't edit that list after item creation. A user with permissions for one site can modify the item viz. that site only.
