### ISSUE TITLE
OEmbed block behaviour

### ISSUE THREAD

**Issue by allanaaa** [omeka/omeka-s#2169]
We've tried to fix the oEmbed block so that the width is constrained to our grid or page widths. 

In Cozy, the object is having its overflow cut off:

<img width="1343" alt="Screenshot 2024-03-19 at 13 37 34" src="https://github.com/omeka/omeka-s/assets/28012148/dfd5ca3b-69a3-4fc9-8b31-383a6dc07b1a">

In The Daily, it's not being constrained and is pushing the page width out:

<img width="1529" alt="Screenshot 2024-03-19 at 13 38 30" src="https://github.com/omeka/omeka-s/assets/28012148/74fa0bbd-18c5-491a-974a-72b2726a4391">

Same in Foundation and in Center Row:

<img width="1133" alt="Screenshot 2024-03-19 at 13 39 03" src="https://github.com/omeka/omeka-s/assets/28012148/58c6e13c-817e-4415-a44f-5609fd86dfc2">

In Freedom and everything else, we get a tiny oembed where the width is constrained correctly and the height is proportional to that. But in Papers the blocks are still loading as big as the original oembed before constraint:

<img width="1441" alt="Screenshot 2024-03-19 at 13 39 53" src="https://github.com/omeka/omeka-s/assets/28012148/3923fe58-9d3a-400d-a4bf-9f8b7834ef0b">

<img width="1150" alt="Screenshot 2024-03-19 at 13 40 13" src="https://github.com/omeka/omeka-s/assets/28012148/65d5a063-f0ea-47ba-bebe-f92f84df786d">

I think this needs to be handled more consistently in the core and not left up to the themes to garble the output.

**Comment by kimisgold** [comment]
We have a style for this in the core, where we specify that oembed iframes are set to `max-width: 100%`. Funny enough, Flickr's oembed generates an inline style for `max-width` that varies depending on the context, sometimes `none` or `100%`. I didn't look closely enough to figure out the logic behind how this embed chooses its max-width, but either way, it overrides our default. I've set the core style to `!important` for now, which should fix the inconsistency.

**Comment by allanaaa** [comment]
The Daily:

<img width="916" alt="Screenshot 2024-03-26 at 17 16 16" src="https://github.com/omeka/omeka-s/assets/28012148/e7cc627b-7f56-4457-aa3b-10d7d72a196f">

Center Row:
<img width="913" alt="Screenshot 2024-03-26 at 17 17 39" src="https://github.com/omeka/omeka-s/assets/28012148/2051ad52-7ce5-440a-bef4-1607a5ab6efd">

Papers:
<img width="904" alt="Screenshot 2024-03-26 at 17 17 25" src="https://github.com/omeka/omeka-s/assets/28012148/5001bcce-0d04-4d1c-8fa8-212c01f9a83d">

So, still inconsistent. But I'm not sure we're gonna solve this one.

**Comment by kimisgold** [comment]
Could you check these again, pulling in latest commits from themes and core? I'm seeing what you're seeing as a flicker that corrects into the expected sizing a moment later.

**Comment by allanaaa** [comment]
Yep, still inconsistent across themes. 
<img width="1607" alt="Screenshot 2024-04-09 at 13 28 49" src="https://github.com/omeka/omeka-s/assets/28012148/054e5a92-bc41-4d09-a096-cd20ea9960a1">
<img width="1323" alt="Screenshot 2024-04-09 at 13 29 03" src="https://github.com/omeka/omeka-s/assets/28012148/f3749ebf-0d71-4356-80d5-5f96bbefdf1e">
<img width="1332" alt="Screenshot 2024-04-09 at 13 29 14" src="https://github.com/omeka/omeka-s/assets/28012148/375a95d0-6e95-4269-9dd5-622255090013">

**Comment by kimisgold** [comment]
I'm looking at http://dev.omeka.org/amayer/amayer-s/omeka-s/s/my-omeka-s-site/page/my-grid-page, and I'm seeing a `max-width: 196px` on the Snow Beauty photo. Flickr's embed does funky calculations that make it hard to test in the browser only, but can we start with removing that constraint? Also what browsers are you using? 

I'm trying to replicate this using the same media on my local installation. I have a grid layout with a maximum of 3 columns, and a block group containing "Talk Talk" set to span 2 and "Snow Beauty" set to span 1 with a `max-width: 196px`. Across Firefox, Chrome, and Safari, I haven't been able to find an instance of that horizontal crop. I've only seen the tall container with the black background in Papers on Chrome.

<img width="1137" alt="image" src="https://github.com/omeka/omeka-s/assets/606764/d1eca5e2-0846-439b-9121-1b5d78c8fac6">

<img width="1139" alt="image" src="https://github.com/omeka/omeka-s/assets/606764/04ca1b02-60f5-48a7-84f4-2c8eef52754e">

<img width="1108" alt="image" src="https://github.com/omeka/omeka-s/assets/606764/b2b7dfcf-9ce4-4311-a1bc-cdf9bfde6191">

**Comment by allanaaa** [comment]
Whoops, didn't know I had stuck a constraint on there. Removed.

I've added a few extra oEmbed blocks lower on the page with different spans but no other settings.

**Comment by allanaaa** [comment]
Still getting the same thing on Papers vs others, Firefox on a Mac:

<img width="1186" alt="Screenshot 2024-04-10 at 10 49 35" src="https://github.com/omeka/omeka-s/assets/28012148/552d0bfa-c948-42ed-a1de-8e412942384b">

<img width="1537" alt="Screenshot 2024-04-10 at 10 49 03" src="https://github.com/omeka/omeka-s/assets/28012148/f0d19bed-244c-428a-b87e-1377e4802324">

**Comment by allanaaa** [comment]
Yeah, in Safari Papers in fine - just Firefox, and just Papers, is a problem.

**Comment by kimisgold** [comment]
Funny, I'm seeing in Safari but not Firefox. Either way, it's difficult to trace what's causing the issue due to the nature of iframes and how flickr's embed calculates its dimensions. This also seems a Papers-specific issue at this point, so I'm going to close this one and open one on the theme repo.
