### ISSUE TITLE
Media embed block horizontal vs. vertical

### ISSUE THREAD

**Issue by allanaaa** [omeka/omeka-s#2170]
I have two media embed blocks with a IIIF item displaying. One is set to "vertical" and sits in the page fine; the other is set to "horizontal" and is overflowing the page. I can't find an obvious CSS problem. 

<img width="1321" alt="Screenshot 2024-03-29 at 15 37 34" src="https://github.com/omeka/omeka-s/assets/28012148/3599770c-4641-40be-818e-d4cc057b4a7a">

**Comment by kimisgold** [comment]
I'm testing a fix for this. It is a CSS issue with IIIF containers set to take up as much horizontal space as possible, stemming from trying to have iiif media fill the width of grid space (https://github.com/omeka/omeka-s/commit/19205db1f87250490d3506b91033140b524beb9e and https://github.com/omeka/omeka-s/commit/3076bc246096a8c928522e01f2b6eb1d40895c24). 

Posting this for my own reference. This is what the IIIF containers were doing without that `100vw` style.

<img width="1183" alt="image" src="https://github.com/omeka/omeka-s/assets/606764/013ef2f9-1e3a-4388-bbbf-aef7fa0b8dbb">

**Comment by kimisgold** [comment]
Okay, a fix is in and ready for a look.
