### ISSUE TITLE
Feature request: Page Copy

### ISSUE THREAD

**Issue by joebauer** [omeka/omeka-s#2185]
Hi!
Our team would like to request a feature for copying or duplicating an existing page. 

For example, while creating a site - some pages may similar blocks and configurations, but just different content. We'd like to save time by making one page, copying that and then just adjusting the content. Currently we have to make a brand new blank page and then meticulously re-add and re-configure all the blocks to match the previous page. 

Thanks!

**Comment by Daniel-KM** [comment]
Note that this feature exists since a long time with the module [Internationalisation](https://github.com/Daniel-KM/Omeka-S-module-Internationalisation). You can even create a mirror page without copying block.

**Comment by allanaaa** [comment]
The module is now released: https://omeka.org/s/modules/CopyResources/
