### ISSUE TITLE
Long title in page blocks

### ISSUE THREAD

**Issue by allanaaa** [omeka/omeka-s#2191]
<img width="958" alt="Screenshot 2024-05-16 at 14 57 12" src="https://github.com/omeka/omeka-s/assets/28012148/4ff3eb32-6499-4276-a271-e910bab522c6">

Asset fienames in the Assets page block are running their configure and delete buttons off the screen.

Elsewhere, long item titles get wrapped - but that relies on spaces, which asset filenames often do not have.

<img width="668" alt="Screenshot 2024-05-16 at 14 59 05" src="https://github.com/omeka/omeka-s/assets/28012148/a8198355-6486-485c-90fa-a3b14921503a">

**Comment by kimisgold** [comment]
There's a fix in ready for a look.
