### ISSUE TITLE
Site admin setting named "Restrict browse to attached items" creates confusion

### ISSUE THREAD

**Issue by alexdryden** [omeka/omeka-s#2198]
The site admin setting "Restrict browse to attached items" sounds like it restricts browse to items that are attached to the site via the Resources page. But the name does not seem to suggest what the manual explains, "If checked, the Browse functions of your site will only show items which have been added to a page block." This explanation should be added to the drop down and the title should be updated to help avoid confusion. I propose "Restrict browse to items used in page blocks".

**Comment by zerocrates** [comment]
I think we'll just combine this with our previous discussion at #2033
