### ISSUE TITLE
AnyCloud Error

### ISSUE THREAD

**Issue by jlinsos** [omeka/omeka-s#2202]
Hi, I am getting this error when using AnyCloud with Azure storage. any ideas?

Fatal error : Could not check compatibility between AnyCloud\Service\File\Store\AzureFactory::getFilesystemAdapter(array $config): AnyCloud\Service\File\Store\FilesystemAdapter and AnyCloud\Service\File\Store\AbstractFlysystemFactory::getFilesystemAdapter(array $config): League\Flysystem\FilesystemAdapter, because class AnyCloud\Service\File\Store\FilesystemAdapter is not available in /var/www/html/modules/AnyCloud/src/Service/File/Store/AzureFactory.php on line 15

I am using the latest versions of everything

**Comment by sharonmleon** [comment]
This issue is best filed on the module's individual repository. You should be able to find that on the module's page in the Omeka module's directory.
