### ISSUE TITLE
4.1.1

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#2207]
A list of 4.1.1's changes/fixes, for everyone's review:

## Changes

- Custom thumbnails set on a primary media will also be used when getting a thumbnail for the parent item

## Fixed Bugs

- The "no sites" message never disappeared when adding the first site on the add/edit item page in 4.0.0
- Item sets were not sortable in the site resources section in 4.0.0
- Themes did not show new version notifications in 4.0.0
- Fulltext search automatic relevance sorting could improperly inherit the configured default sort order and sort least-relevant-first
- Value languages on the resource form were not validated as promptly as intended
- Large or oddly-sized asset titles or thumbnails could display oddly in the admin assets section
- A deprecation notice printed when using the lightbox gallery viewer together with Youtube media

## For Developers

- The ACL OwnsEntityAssertion now supports Doctrine proxies correctly
- `returnScalar` in the API now returns the correct total results count for paginated results

**Comment by zerocrates** [comment]
4.1.1 is on the `release-4.1` branch (though the same fixes will all be in latest develop also). To see the pre-fix behavior, check out the `v4.0.0` tag.

**Comment by allanaaa** [comment]
The site "view" button at the top of the screen is loading in the same tab, rather than opening a new tab. The one in the left sidebar is opening a new tab correctly, as is the one in the sites table. 

<img width="783" alt="Screenshot 2024-06-19 at 15 06 06" src="https://github.com/omeka/omeka-s/assets/28012148/4a52c255-90db-44fa-9b15-7d2c95d1c738">

**Comment by zerocrates** [comment]
I snuck the fix to the view link target in there.
