### ISSUE TITLE
Browse view toggle doesn't persist

### ISSUE THREAD

**Issue by allanaaa** [omeka/omeka-s#2213]
In themes where we offer the setting to publicly toggle between list view and grid view (Lively, Foundation, etc.) that view setting on the front-end does not persist if the user does anything to the page. 

If the page is set to grid by default, and I select list, then click through to page 2, it goes back to grid. 
If I change the sort method, it goes back to grid. If I change from "ascending" to "descending", it goes back to grid. 

Is there a way to maintain the user's selection at least until they navigate away from the browse?

**Comment by kimisgold** [comment]
Fixed and tested in #72.
