### ISSUE TITLE
migration of blocks type:"item showcase" to "media embed" crashes layout

### ISSUE THREAD

**Issue by tom-dea** [omeka/omeka-s#2219]
it looks like from version 4.0 to version 4.1 our layout was crashed, because we had item showcase blocks in use which seem to have been migrated to media embed blocks:

more precisely the page block "item showcase" is not available any more. instead the items seem to have transferred into a "media embed" block and to us it looks like this broke the displaying in the web view.

the alignment of the items now looks like a stair.

unfortunately your recommendations to adapt the media embed block to our needs did not work for us. we tried several different things - we tried all available settings, which took us several hours - to get the old view back as we had it in item-showcase.

currently the layout of our productive instances of the exhibitions is totally broken!

do you have any other solutions?
we already think about getting the old showcase block from a previous version of omeka!

we think that the media-embed block is not really an option for us, because we checked that block type before and came to the conclusion that it cannot deliver us the features we need. that's why we decided to use showcase and also made a lot of adaptions to it.

**Comment by kimisgold** [comment]
Sorry to hear you're experiencing difficulty with the migration. Can you provide any live examples of your use case, as well as describe the functionality you need specifically?

**Comment by zerocrates** [comment]
Also, it would help us to know what theme you're using, what version's being used, whether it's custom or customized, and so on.

4.1 basically added all the differences between the old "showcase" and "embed" blocks as options to the embed block and they're pre-selected when the migration happens, but it's possible for a specific theme to not include support for those options, which could lead to issues.

**Comment by walcherj** [comment]
Hello, 

I am in Tom's Team and try to provide the required info: 

- we know have version 4.1., which made the problematic change 
- we work with a customized theme
- functionalities within that theme with the showcase we had before version 4.1. and which are not available any more: the possibility to arrange the items horizontally, side by side; subheadings with fold-out function, which show a number of items
- as attachmet I am sending two screenshots, what the broken layout looks like: 
![Showcase issue_1](https://github.com/user-attachments/assets/8b894ad9-a9cc-4bb5-ae47-b8d4fea61b0c)
![Showcase issue_2](https://github.com/user-attachments/assets/9adfc549-c162-4d65-9e8e-bc3a78800092)

Many thanks in advance for your help 
Johanna

**Comment by walcherj** [comment]
I add another two screenshots of the desirable status before the new update: 

Item showcase fold out: 
![Item Showcase fold out](https://github.com/user-attachments/assets/6cbd0863-dab5-4533-b5da-f1499298746a)

Item showcase fold in: 
![Item Showcase fold in](https://github.com/user-attachments/assets/1b17ced8-3665-4e7d-8afc-94b4dc37e61f)

**Comment by kimisgold** [comment]
Thank you for the screenshots. Could you also show screenshots of what those blocks look on the admin side?

For your custom theme, are you including `css/page-blocks.css` in `page/show.phtml`? This provides some default styles for these blocks.

Your "item showcase fold out" screenshot is a layout we designed for in the new media embed block. This is a screenshot of the block within the "default theme".

<img width="1250" alt="image" src="https://github.com/user-attachments/assets/98c15e94-8e05-4768-8041-e733b9c81916">

This is what it looks like configured in the Omeka S page builder interface.

<img width="1093" alt="image" src="https://github.com/user-attachments/assets/ae08bfe5-2044-4fe0-aab8-bca69af7ec2e">

Can you talk more about the "fold out" option? I'm not sure that's an option we ever offered. If it's custom theme functionality that you need help adapting, it may be difficult for us to assist without having access to a live site or theme code to look at.

**Comment by walcherj** [comment]
Thank you so much for your detailed feedback, that helped us to find a solution. We managed to adapt the media embed accordingly, to have the dropdown and the horizontal alignment. The headlines, which should go in between the media embed blocks, we insert via an HTML-Block. I am sending an example attached. 
All the best an thanks again
Johanna 

![our solution](https://github.com/user-attachments/assets/b125b474-1c60-4dff-9421-beabb603a400)

**Comment by kimisgold** [comment]
Glad to hear it!
