### ISSUE TITLE
We need to be able to send emails

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#222]
For example, we need to be able to send "here's your new account" emails to new users.

**Comment by patrickmj** [comment]
This sorta breaks a flood dam of messaging in Omeka S. Do we want/need:

* Messaging Global Admin, either by email or internally?
* Messaging Site Admin, either by email or internally?
* Messaging Site members, either by email or internally (and by role?)?

I'm betting that these are round 2 issues, but as we aim for more technological interlinkiness, some of this messaging would be a great parallel features for the future. It'd be a helpful way to manage the kinds of conversations that come up in WP course sites, for example.  Could also be a module, I suspect.

**Comment by zerocrates** [comment]
I'd like to keep this basically laser-focused on the task of just sending emails from the system in a general sense, so looking into the ZF2 mail component(s) and seeing if/how we have to allow configuration of them.
