### ISSUE TITLE
User activations

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#223]
Connected to #222 

If we're sending account creation emails, we also need a publicly-accessible "activate your account" page that we can link to in those emails to allow people to choose passwords.

**Comment by zerocrates** [comment]
We also need this type of functionality for "forgot password?" support

**Comment by jimsafley** [comment]
Before I start on this issue we need to establish a user creation and activation workflow. Here are my thoughts:

An administrator adds a user, entering the name, email, and role. An inactive user account is created and an email is sent to the user containing a link to an activation page. Only when the new user navigates to this page and chooses a password will they be activated. Should the activation keys expire? Am I missing something?

At the very least we'll need an `isActive` flag on User entity and a UserActivation entity containing the user ID and activation key (and possibly a timestamp).

**Comment by zerocrates** [comment]
This sounds right. The only wrinkle I'd add is that you don't _technically_ need the active flag to do the initial activation workflow: a user is initially created with no password so they can't log in anyway. The active flag is probably a good idea regardless though, but you could split the "activate workflow" and "allow deactivation" parts if you wanted.

The activations should probably expire.
