### ISSUE TITLE
Custom Sort By does not persist

### ISSUE THREAD

**Issue by C-Norton** [omeka/omeka-s#2243]
When using the new custom sort by feature in omeka S 4.0.2, the sort by works as intended on the browse page. However, when another sort (say sort by title, ascending) is selected, and sort is clicked, the resultant page no longer has the custom sort by as an option. I do not see this addressed in the changelog for later versions, but I could be wrong here.

**Comment by zerocrates** [comment]
I can't reproduce this in 4.1... but I don't think we've done anything to change this behavior between these versions.

You're seeing this on a public view, the admin, or both? For a public view it's possible that you're using a theme (or a version of a theme) that doesn't use the 4.x sort selector and so wouldn't include your custom selection.

**Comment by C-Norton** [comment]
You're right that this is a theme issue. Upon further testing, It looks like foundation has not been updated yet for this feature to work.

**Comment by kimisgold** [comment]
@C-Norton As a heads up, [Foundation S v1.5.0](https://github.com/omeka-s-themes/foundation-s/releases/download/v1.5.0/theme-foundation-s-v1.5.0.zip) is newly released and should support custom sorting. If you find that for some reason it doesn't, please file an issue in its repo so we can address it in a bugfix.
