### ISSUE TITLE
Build Activate Account Placeholder Page

### ISSUE THREAD

**Issue by kalbers** [omeka/omeka-s#228]
Per #223 build out page with form, that can later be tied in when functional.

**Comment by zerocrates** [comment]
It probably makes the most sense for this (and the other one) to be new actions/views within the LoginController

**Comment by kalbers** [comment]
Currently in S and Omeka 2, we require the person inviting a new user to assign that user a username. It seems as though maybe a better approach would be to require only an email and a role, and allow users to fill in the remaining data on the signup page (similar to the installation page).

This potentially also could move us closer to simply having a registration page, which would allow users to sign up without a registration email.

Thoughts @sharonmleon @sheilabrennan @jimsafley @kimisgold @patrickmj ?

**Comment by patrickmj** [comment]
Seems to me like a registration email is essential. Maybe make the email the defaul username, and people can change it when they fill in the rest of teh data.

**Comment by sheilabrennan** [comment]
Email and role works for me.

**Comment by kimisgold** [comment]
Do we even necessarily need to require a username? Could users provide their email and password as a login, and then select a display name?

**Comment by jimsafley** [comment]
@kimisgold's question is interesting. I looked into it and found this on the information security StackExchange: http://security.stackexchange.com/questions/33269/email-instead-of-username

The top answer gives good reasons why an email address is a good username. Some lower-scored answers express reservations. Looking at them all, I suppose it's relatively safe to use emails as usernames, but I'm still not sure whether we should.

**Comment by kimisgold** [comment]
I'm fine with keeping usernames as well, but it does seem annoying for the admin to have to choose a username for a new account. If we keep usernames, I like the idea of generating a username (using email or some other means) that can be changed later.

**Comment by kalbers** [comment]
I think the idea of getting rid of usernames makes sense, after all of this. Just on simplifying the form alone, it seems worth it. Using emails also basically removes the possibility of duplicate usernames (which just removes and annoyance for users, but worth considering).

We can keep display names (currently Name) for other uses, eg the link to the user page, name as it appears for a resource owner, etc.
