### ISSUE TITLE
New link URI field has scrollbar

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#233]
![scrollbar](https://cloud.githubusercontent.com/assets/298975/8162439/31a02d02-134b-11e5-9071-a0c741c6e877.png)

**Comment by jimsafley** [comment]
Regardless whether the label has a scrollbar, the field should remain a textarea. I'm not too concerned about the database column size of 255 characters, but we should assume that authority lists contain labels with newlines.
