### ISSUE TITLE
How should non-admin users interact with other users?

### ISSUE THREAD

**Issue by kalbers** [omeka/omeka-s#236]
Currently only admins can view other user show pages. However, there are links to these pages in different areas of the site, eg, the Owner column on item-sets browse. This now results in a 403 page for non-admin users.

Do we want those links to point to queries of resources owned by those users, rather than the user show page? Or do we want to rework the permissions a bit so that the user show page is available to any user with a role? The latter would potentially allow the user show page to contain more content, such as resources owned, etc.

**Comment by patrickmj** [comment]
I'd say that info about such owners should be pretty widely visible. It seems like we're in a mode of encouraging interactions withing the institution running S, and so having at least contact info so people can talk about item sets and jobs could be important. Plus, if the column says 'owner' and has a link, I'd absolutely expect to go to info about the owner, not other resources owned by that owner.

In module land, this will also be important, as I've been putting in a 'comments' field about the purpose of an import job. Being able to know who imported what, and why, seems pretty useful.

**Comment by zerocrates** [comment]
Decisions:

1. Allow read/show access for users
2. Allow browse access for users
3. Defer decision about limiting info on show/browse (e.g., email)
