### ISSUE TITLE
Sites UI completion

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#241]
Take the existing barebones Sites pages and apply the existing styles and/or wireframe styles as appropriate.

In particular:
- the Pages tab of the Site edit UI

**Comment by kimisgold** [comment]
Added some basic browse styles for the page list in https://github.com/omeka/omeka-s/commit/dfd277871729f4e0e2e0fd28de99f276b9ba8c43. Not sure about the placement of the add page button, but I figure that might be better addressed once we have more robust versions of these views. Is there anything else in Sites you think needs attention at the moment?

**Comment by zerocrates** [comment]
There'll be some other stuff shortly, but at this very moment there's some more that we need there, like including the slugs for the pages in the page list.
