### ISSUE TITLE
Add HTMLPurifier

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#242]
We need at least opt-in (by the admin) support for enabling HTML Purifier for HTML inputs like the Media and Site blocks.

* Update Composer stuff to pull in htmlpurifier
* Hook it up to the HTML media type
* Add setting for activating/deactivating the purifier
* Consider the possibility of having the purifier be a Service, or otherwise be easily reusable wherever HTML might be used

**Comment by patrickmj** [comment]
I'm guessing start with the default configuration for atts and elements first, and worry about admin settings for that later?

**Comment by zerocrates** [comment]
Yes, I'd say that's the best course.

The defaults are pretty reasonable anyhow

**Comment by patrickmj** [comment]
current htmlpurifier branch 00917 just uses the class directly. not sure what's gained or lost by making it a service (or filter) or not.

**Comment by zerocrates** [comment]
the main benefit would be centralizing where settings are applied

even ignoring potential settings for elements/attributes, the "is the purifier enabled" setting could be such an example
