### ISSUE TITLE
duplication of title and description

### ISSUE THREAD

**Issue by alyssafahringer** [omeka/omeka-s#244]
When adding an item using a newly-created resource template, the title and description fields are duplicated. 
![screen shot 2015-06-23 at 1 07 33 pm](https://cloud.githubusercontent.com/assets/8807816/8313020/2ea1f504-19ae-11e5-9816-14990e506bb5.png)
![screen shot 2015-06-23 at 1 47 03 pm](https://cloud.githubusercontent.com/assets/8807816/8313049/5ba79c8e-19ae-11e5-82cd-de576614706d.png)

**Comment by zerocrates** [comment]
I _think_ this is the same as a bug that Kim's already working on and may have fixed, but I'll check on that.

**Comment by mebrett** [comment]
Just pulled the latest commits to the dev.omeka install. Still having problems?

**Comment by alyssafahringer** [comment]
Yes it's still duplicating those fields.

**Comment by zerocrates** [comment]
It seems from viewing Megan reproducing this problem that this was just an artifact of the dev site not being up to date, and then client-side caching after that (the problem went away after refreshing the edit page).
