### ISSUE TITLE
ZF2.5 and PHP version requirement

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#245]
Our Composer dep on Zend Framework has been updated to 2.5. With that comes a bump in their minimum PHP requirement:

> Finally, we have a significant bump in our minimum supported PHP version starting with 2.5.0: we now require PHP 5.5+. PHP 5.3 is no longer receiving even security updates at this time, and PHP 5.4 support ends on 14 September 2015 — just over 3 months from now. We encourage our users on versions prior to 5.5 to migrate immediately; the migration from 5.4 to 5.5 or 5.6 is trivial, and you'll get substantial performance benefits in addition to new features.

**Comment by zerocrates** [comment]
To be clear, this means that as of right now the minimum version of PHP required to run S is 5.5.

We can pin the ZF dependency back to the 2.4 series and keep our previous PHP 5.4 dependency as Zend claims to be doing "long-term support" for 2.4... but starting off with an older version of our major dependency isn't exactly getting off on the right foot. Additionally, the reason Zend is making this move is that, as quoted above, PHP is ending their support for 5.4 in just a few months.

We may need to re-refer to the shared hosting support matrix document we'd put together to see how this affects things

cc @omeka/team-omeka

**Comment by zerocrates** [comment]
The hosting data spreadsheet is here https://docs.google.com/spreadsheets/d/1nrm1t5zdhuKNkfcWjlZEOezk-tI6kzi6qurh8oFK9mg/edit?usp=sharing

**Comment by jimsafley** [comment]
If we move on this, let's look into whether we want to take advantage of some [new features](http://php.net/manual/en/migration55.new-features.php) in 5.5.
