### ISSUE TITLE
Version number should be visible in the interface

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#250]
This will make it easier to know what version people are using, and becomes more important as other people may be using/testing S.

**Comment by jimsafley** [comment]
Use the Status service to get the installed version:

```php
$version = $serviceLocator->get('Omeka\Status')->getInstalledVersion();
```

**Comment by zerocrates** [comment]
`Omeka\Module::VERSION` is also a way to go that doesn't require access to the service locator.

**Comment by jimsafley** [comment]
There is a distinction between *installed* version and *code* version, but I suppose that distinction is hidden from users during updates.

**Comment by zerocrates** [comment]
FYI we should have this done by, lets say, Monday, so that it will be there in the version we package on Tuesday.
