### ISSUE TITLE
Minimal layout can't handle h1s

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#261]
A h1 on a minimal layout page tries to style itself as if it's on a regular admin page.

**Comment by zerocrates** [comment]
We may eventually want to actually separate the "minimal" styles from the normal ones. This kind of conflict seems inevitable with the complexity of the regular styles

**Comment by kimisgold** [comment]
Yup, agreed.

**Comment by zerocrates** [comment]
As a particular example: that h1 looks nice enough now, but it's significantly smaller than the h2. There's no point in fooling with it further at this point, but just a concrete example of something small already happening
