### ISSUE TITLE
Display media types more clearly

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#264]
Right now we cram the media type into "Source." We have the adapters define "nice" labels for each type already, so we should probably use those, and they also probably make sense to appear on the browse or at least the sidebar.

**Comment by kalbers** [comment]
Right now we don't put much in the sidebar aside from explicitly entered metadata (this is true on items as well). It might make sense to separate that out, and think about what exactly the sidebar should contain for both items and media.
