### ISSUE TITLE
The minimal views should have headings

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#265]
They're currently just the forms with no headings

* installer
* login
* forgot password
* create password

**Comment by jimsafley** [comment]
Same with login/login, login/forgot-password, and login/create-password.

**Comment by zerocrates** [comment]
An h1 added to the installer view looks totally different from one added to the others so i think we'll temporarily punt this until we have the styling settled

**Comment by zerocrates** [comment]
actually that's probably just an artifact of something unrelated
