### ISSUE TITLE
Should browse details in sidebar show more information

### ISSUE THREAD

**Issue by kalbers** [omeka/omeka-s#267]
Per #264, should the sidebar on browse pages show more than just the title and explicitly entered metadata? eg, type for media or items

**Comment by kalbers** [comment]
Was there any consensus about what should additionally be added in?

**Comment by jimsafley** [comment]
There was no consensus. Do you have specific ideas for specific sidebars?

**Comment by kalbers** [comment]
eg, for the media one, it would include date added, visibility, type, etc. Potentially it could include owner and what item it belongs to, if we decide we want to drop those as table headers on the browse page.

Essentially, of whatever displayValues() doesn't handle, should we include for resources? I'd probably argue that we probably shouldn't even use displayValues() at all.

**Comment by kalbers** [comment]
So I pushed up a branch sidebar-details, which shows the media sidebar as an example of the kind of additional data we could put there, and how we might move stuff around on the browse page. It's probably worth having people weigh in a little more before going any further with this, though.

**Comment by patrickmj** [comment]
Just as a wording thing as we work on that for translations, maybe not use "Part of Item" to avoid confusion with the dcterms:isPartOf property and make clear that that's not how the media and the item are related.
