### ISSUE TITLE
Warn users before navigating away from unsaved changes

### ISSUE THREAD

**Issue by kalbers** [omeka/omeka-s#269]

**Comment by jimsafley** [comment]
Something like this in form views should work:

```js
jQuery(document).ready(function ($) {
    var isDirty = false;
    $(':input').change(function() {
        isDirty = true;
    });
    $(window).on('beforeunload', function() {
        if (isDirty) {
            return "It appears you've made changes to the form.";
        }
    });
});
```

This only works when input, textarea, select, and button elements change, so we'll need to include some way to flag "dirty" when other elements change (e.g. when adding and removing elements). If `isDirty` is a global variable other functions could set the flag during state changes.

**Comment by jimsafley** [comment]
And obviously the above script will need a way to allow form submission without firing the `isDrity` alert.

**Comment by zerocrates** [comment]
Another possible strategy is to serialize the form on page load and then serialize it again on beforeunload and compare the two for equality.
