### ISSUE TITLE
Translate and proofread all text

### ISSUE THREAD

**Issue by jimsafley** [omeka/omeka-s#270]
*All* text needs to be translated using the `$this->translate()` controller plugin, the `$this->translate()` view helper, or the `MvcTranslator` service directly. This is also a good opportunity to check the text for accuracy and consistency.

**Comment by kalbers** [comment]
Per accuracy and consistency, I mentioned to John the other day that there doesn't seem to be (though I could be wrong) a consistent use of $escape. It's often used in conjunction with translation, so it might make sense to tie that in as well.

**Comment by zerocrates** [comment]
The major problem you'll encounter in some places is $escape being used *instead* of $this->translate. Usually you only need one or the other on a particular piece of data.

* $escape() or $this->escapeHtml() is for escaping data that comes from the user (so, things that get pulled from the request/query string/URL, or things in the database that we originally got from the user, things like that)
* $this->translate() should get used for literal strings that are going to end up getting shown to the user (mostly labels, headings, explanatory text, and also things like aria-label, title, and alt attributes)

Where you've got text that combines those two things, like a sentence that includes dynamic data in it, then you want to combine those two with sprintf:

```php
sprintf($this->translate('Sentence with some %s in it'), $escape($data))
```

For strings that have more than one dynamic piece of data in them you need to use a slightly different format:

```php
sprintf($this->translate('Sentence with some %1$s and some more %2$s in it'), $escape($data), $escape($data2))
```

**Comment by jimsafley** [comment]
Shouldn't we consider translations to be user data?

```php
$escape($this->translate('Sentence with some %s in it'), $data);
```

**Comment by zerocrates** [comment]
So, you can do the escaping around the whole thing if you want, and if the string you're trying to translate doesn't have HTML in it, but no, I wouldn't consider translations to be user data.

At a certain level they come from users, the translators, but they're essentially trusted as far as we're concerned here. We can set Transifex up to reject/warn when there's HTML stuff in a translation and there wasn't in the original.

The only reason I'd escape a translation result is for convenience, if there'd otherwise have to be several escape calls.

**Comment by jimsafley** [comment]
The best way to tell if text is being translated is to set up a debug translation:

https://gist.github.com/jimsafley/b60736062e30a1840c89

Replace `{locale}` with any string and set that string in local.config.php under `translator.locale`.

**Comment by kalbers** [comment]
These lines require manual listing of source strings:

All Vocab, Class, and Proptery labels, specifically vocabs that come with Omeka.

https://github.com/omeka/omeka-s/blob/develop/application/view/omeka/admin/item/show.phtml#L24

https://github.com/omeka/omeka-s/blob/develop/application/view/omeka/admin/item-set/show.phtml#L34

https://github.com/omeka/omeka-s/blob/develop/application/view/omeka/admin/job/browse.phtml#L45
https://github.com/omeka/omeka-s/blob/develop/application/view/omeka/admin/job/browse.phtml#L46

https://github.com/omeka/omeka-s/blob/develop/application/view/omeka/admin/job/show-details.phtml#L19
https://github.com/omeka/omeka-s/blob/develop/application/view/omeka/admin/job/show-details.phtml#L31

https://github.com/omeka/omeka-s/blob/develop/application/view/omeka/admin/media/show.phtml#L19

https://github.com/omeka/omeka-s/blob/develop/application/view/omeka/admin/module/browse.phtml#L129

property/show-details.phtml (multiple)

resource-class/show-details.phtml (multiple)

https://github.com/omeka/omeka-s/blob/develop/application/view/omeka/admin/resource-template/browse.phtml#L32
https://github.com/omeka/omeka-s/blob/develop/application/view/omeka/admin/resource-template/browse.phtml#L57

https://github.com/omeka/omeka-s/blob/develop/application/view/omeka/admin/resource-template/form.phtml#L19
https://github.com/omeka/omeka-s/blob/develop/application/view/omeka/admin/resource-template/form.phtml#L22
https://github.com/omeka/omeka-s/blob/develop/application/view/omeka/admin/resource-template/form.phtml#L24

https://github.com/omeka/omeka-s/blob/develop/application/view/omeka/admin/resource-template/show-details.phtml#L5
https://github.com/omeka/omeka-s/blob/develop/application/view/omeka/admin/resource-template/show-details.phtml#L9

https://github.com/omeka/omeka-s/blob/develop/application/view/omeka/admin/resource-template/show-property-row.phtml#L10

https://github.com/omeka/omeka-s/blob/develop/application/view/omeka/admin/resource-template/show.phtml#L18

https://github.com/omeka/omeka-s/blob/develop/application/view/omeka/admin/resource-template/show.phtml#L35

https://github.com/omeka/omeka-s/blob/develop/application/view/omeka/admin/user/browse.phtml#L56

https://github.com/omeka/omeka-s/blob/develop/application/view/omeka/admin/user/edit-keys.phtml#L26

https://github.com/omeka/omeka-s/blob/develop/application/view/omeka/admin/vocabulary/browse.phtml#L34
https://github.com/omeka/omeka-s/blob/develop/application/view/omeka/admin/vocabulary/browse.phtml#L62

https://github.com/omeka/omeka-s/blob/develop/application/view/omeka/admin/vocabulary/classes.phtml#L7
https://github.com/omeka/omeka-s/blob/develop/application/view/omeka/admin/vocabulary/classes.phtml#L9
https://github.com/omeka/omeka-s/blob/develop/application/view/omeka/admin/vocabulary/classes.phtml#L30
https://github.com/omeka/omeka-s/blob/develop/application/view/omeka/admin/vocabulary/classes.phtml#L41

https://github.com/omeka/omeka-s/blob/develop/application/view/omeka/admin/vocabulary/properties.phtml#L7
https://github.com/omeka/omeka-s/blob/develop/application/view/omeka/admin/vocabulary/properties.phtml#L9
https://github.com/omeka/omeka-s/blob/develop/application/view/omeka/admin/vocabulary/properties.phtml#L30
https://github.com/omeka/omeka-s/blob/develop/application/view/omeka/admin/vocabulary/properties.phtml#L41

vocaubalary/show-details.phtml (multiple)

**Comment by zerocrates** [comment]
Some problems left over here, at least some escapes that should be translates, e.g. https://github.com/omeka/omeka-s/blob/develop/application/view/omeka/admin/item/edit.phtml#L7

**Comment by kalbers** [comment]
Don't forget that Settings is not being translated in the main navigation.

**Comment by zerocrates** [comment]
The Settings thing will be solved if we ever translate that string somewhere else, it's just a matter of getting it picked up into the template

We could also probably make a pretty trivial script to pull the labels out of the nav config and include them in the translation template for us. There shouldn't be any need to manually add translation calls to those labels just for the purpose of picking them up for xgettext
