### ISSUE TITLE
Write activation/forgot-password emails

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#272]

**Comment by sharonmleon** [comment]
See what you think of these @jimsafley:

Subject: Omeka S User Activation

Greetings!

A user has been created for you on [linked to main URL].

Your username is: <strong>[email address]</strong>.

Click this link to set a password and begin using Omeka S:
	[Authorization URL]

Your activation link will <strong>expire in [duration]<strong>. If you have not completed the user activation process by time the link expires, you will need to request another activation email from your site administrator.

Learn more about using [Omeka S -- link to documentation?].

_____________________________
Subject: Reset your Omeka S password

Greetings, [username]!

It seems you have forgotten your password for [linked to main URL].

To reset your password, click this link:
	[Reset link]

Your reset link will expire in <strong>[duration]</strong>.

Learn more about using [Omeka S -- link to documentation?]

**Comment by jimsafley** [comment]
done via https://github.com/omeka/omeka-s/compare/fd48ed63d9f5...2eb53f961119
