### ISSUE TITLE
Site permissions: ACL/assertion

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#276]
Write an ACL assertion(s) that we can use to make actual granted permissions depend on what the SitePermissions settings are for a given site. This probably ends up just using the "getPermissions()" or similar method on the Site entity to get the child permissions entities assigned to it.

**Comment by zerocrates** [comment]
Blocks #240

**Comment by jimsafley** [comment]
I'm going to need a better idea what the admin, attach, and edit permissions mean before I implement the ACL assertion.

**Comment by zerocrates** [comment]
"admin" is control over the administrative stuff for the site, like its slug/title, and probably the ability to grant permissions to other people, too

"edit" is just the ability to edit the site content, the pages and so on

"attach" is the most nebulous currently. This was meant to go along with the idea of explicitly assigning items to sites before actually using the items, so attach would be the ability to add to that list of items. It's not totally clear to me that this one still makes sense, or that we're really going to be doing the explicit assignment like that still.
