### ISSUE TITLE
Make language input more obvious

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#279]
This is a hard tightrope to walk because we've wanted to minimize its size because it's just designed to be ignored by many users.

> I wasn't sure what the input box next to to the keyboard was. Really didn't appear to do anything that I could discern.

**Comment by kimisgold** [comment]
I was thinking of using an abbreviated placeholder string like LANG, which we could make translatable so groups can choose how they'd want to represent that, and then also a link to a new window with a list of accepted language codes.

**Comment by zerocrates** [comment]
I think we'll handle the "list of codes" issue separately, probably with a suggester of some type, whether that's from a huge list of all lang codes or something more limited.

**Comment by patrickmj** [comment]
My fantasy suggester would let people type a language, and return limited list of codes that match the language description. E.g. type "Portug" and get back something like this in a select or some other chooser.


* Portugues - Brazil (pt-BR)
* Portugues - Portugal (pt-PT)


Kinda like how Omeka 2 Locale shows codes, but via an autosuggest. Then we just store the code, and filter the display to show both the stored code, and the human-readable version.

How much of a fantasy is that?

**Comment by zerocrates** [comment]
Part of the problem is that the list of possible languages is _really_ big. It remains to be seen how well trying to suggest from that will work.

There's also the issue of matching to the language name, whether that should be the English name, the name of that language in itself, or the name of the language in the current locale (we may not be able to get that easily, to some degree ZF1 provided those names itself and it doesn't anymore, not sure what we can get out of ext/intl)

**Comment by zerocrates** [comment]
Here's one example of a list http://www.iana.org/assignments/language-subtag-registry/language-subtag-registry

That includes codes for languages, scripts, variants, and regions. Another problem is that there's, as far as I'm aware, no simple registry we can work with for which regions "normally" go with which languages.

I'd be tempted to only support completion for languages themselves, and leave it up to the user to go forward if they want to add additional subtags.

The only other reasonable option i can come up with is administrators having the ability to define what the language choices are.

**Comment by patrickmj** [comment]
So, a pretty big fantasy of mine, then. 

I don't see this as needing to be hugely generalized. Either site-by-site admins defining language choices, or the global admin defining them, will make more sense. I doubt the situation of wanting to have content in, say, Spanish, Mandarin, Japanese, Swahili, English, Hrvatski, العربية, русский, etc. (you get the point) in one site.

Upshot I see is at some level (global admin or site admin) limiting the language options in a settings page?

**Comment by zerocrates** [comment]
It can't be site-by-site admins, that's the familiar "global pool" problem.

**Comment by patrickmj** [comment]
How so? I'm thinking of site-by-site admins just having different language selection. For the same, shared global pool item, could one site have a language selector limited to, e.g., 4 western languages, and another site, looking at the same item, and a language selector limited to, e.g. 5 asian languages. 

Upshot I have in mind is keeping the language selector site-by-site, but all that value/language data still gets stored on the same global pool item. So, in the above scenario, single item could get value/language pairs from 9 different languages, from 2 different sites, the 2 different sites just having different configurations for a language selector.

That is, what stops language selector configuration from being site-specific? And the value/language pairs are just shared on the item?

**Comment by patrickmj** [comment]
Under this conception, HTML Media should also be flagged in the same way by language.

**Comment by zerocrates** [comment]
What does "another site looking at the same item" mean? What site are you "from" when you're editing an item?

**Comment by patrickmj** [comment]
ah. ok. sorry. I guess I still haven't completely absorbed how sites and items are going to work in practice
