### ISSUE TITLE
Review our browse table headings for consistency and suitability

### ISSUE THREAD

**Issue by jimsafley** [omeka/omeka-s#284]
Related to #270. We are limited by horizontal space, which forces us to omit columns that would be helpful. For count columns, users may experience slowdown at large numbers, so we should consider moving counts to the sidebar and replacing with something else (else wait until it becomes a problem). For those resources that are owned, we should probably always include an owner column, given the shared nature of the database.

For our convenience, here's a table of all browse table headings:

Resource | Column 1 | Column 2 | Column 3 | Column 4
--- | --- | --- | --- | ---
Items | Title | Class | Date Created
Item Sets | Title | Items | Owner
Media | Title | Item | Owner
Vocabularies | Label | Prefix | Classes | Properties
Resource Templates | Label | Class | Items
Users | Email | Role | Date Created
Modules | Module | Status
Jobs | ID | Status | Status | Owner
Sites | Title | Owner

**Comment by kalbers** [comment]
People should also reference #267 with regards to this, and see if there is information (eg owner) that is more suited to the sidebar than the table.

**Comment by sharonmleon** [comment]
@sheilabrennan Can we review this for discussion on Monday July 27?

**Comment by sharonmleon** [comment]
Suggestions:

Resource | Column 1 | Column 2 | Column 3 | Column 4
--- | --- | --- | --- | ---
Items | Title | Class | Owner | Date Created
Item Sets | Title | Items | Owner | Date Created
Media | Title | Item | Owner | Date Created
Vocabularies | Label | Prefix | Classes | Properties
Resource Templates | Label | Description | Class | Items
Users | Email | Role | Date Created
Modules | Module | Status
Jobs | ID | Status | Owner | Date Begun
Sites | Title | Owner | Date Created

**Comment by sheilabrennan** [comment]
I'd like to see Visibility on quick and detailed view.

**Comment by sharonmleon** [comment]
Description for Resource Template -- that doesn't exist now, and maybe it shouldn't but we need to signal to users that they should create rich titles if that is all they have to identify the template.

**Comment by kalbers** [comment]
In instances where the sidebar won't offer any details, should we take away the button? eg Jobs.

**Comment by kalbers** [comment]
Some notes from while I addressed this issue:

Might not make sense to put a date started under a job status. If the status reads "Stopped" a date would seem to indicate when it stopped, not when it started.

On Modules it might make sense to make the title cell much longer than the status cell, as those are the only two cells

Still some work for Sites. We can't return the list of sites for a user right now, and we can't get when a site was created.

There are visibility icons on items/browse for review.

**Comment by kimisgold** [comment]
We also should look at the resource/show sidebars and decide how much consistency we want with the sidebars on their respective browse views. Here's the current content for the show view sidebars.

Resource | Sidebar
--- | --- 
Items | Square thumbnail, Item Sets, Date Created, Owner, Visibility, Media
Item Sets | Date Created, Owner, Visibility, Link to Items
Media | Date Created, Part of Item, Visibility, Type, Source, MIME Type, File Derivatives

**Comment by kimisgold** [comment]
For future reference, the hierarchy of sidebar values: https://docs.google.com/spreadsheets/d/1GCY1OWGzPv_ZXtUFGufaAU11bYaGlSsFmg0sVteGq2I/edit?pli=1
