### ISSUE TITLE
Action Icons on modules page went a bit crazy

### ISSUE THREAD

**Issue by patrickmj** [omeka/omeka-s#299]
Best described in pictures.

Chrome:
![omekasmoduleschrome](https://cloud.githubusercontent.com/assets/153262/8652000/210bedd6-294a-11e5-843a-fb66a1951a7f.png)

Firefox:

![omekasmodulesff](https://cloud.githubusercontent.com/assets/153262/8652011/292edec4-294a-11e5-964c-0aa7856c3d12.png)

**Comment by kimisgold** [comment]
Which view is this?

**Comment by zerocrates** [comment]
It's the modules browse
