### ISSUE TITLE
Allow RDF vocab importer to import just properties, just classes, or both

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#303]
(in response to feedback)

The list of classes we end up getting after importing the vocabularies is cluttered up with a lot of what's basically junk, particularly from Dublin Core. If we could direct the importer to only consider classes or properties from a specific vocab, we could exclude unhelpful classes or properties when they're unwanted.

**Comment by jimsafley** [comment]
I would rather allow users to select from a list of properties and classes. By limiting this selection process to all-or-none, they'll likely lose useful vocabulary members. For example, while Dublin Core has "Agent Class" and "Linguistic System" classes, it also has the arguably more relevant "Location" and "Physical Resource" classes.

**Comment by patrickmj** [comment]
I'd vote for keeping everything in there. If we say that we're following and incorporating existing standards, it seems iffy for us to effectively put an asterisk on that that says "except for what we've decided is cruft in the standards". For people who want to use the full standards as they exist, it would lead to surprises to discover gaps.
