### ISSUE TITLE
ValueRepresentation's toString should always escape

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#306]
Right now the ValueRepresentation produces properly escaped output for URI and Resource values, but not for literals. Literals should probably get escaped too, so values can be handled consistently in the views.

**Comment by zerocrates** [comment]
Note, we'd probably have to change the internals of things like displayTitle and displayDescription, since our usages of those assume that we have to escape them, so we'd get double-escaping if we just changed ValueRepresentation and nothing else.

**Comment by jimsafley** [comment]
fixed in https://github.com/omeka/omeka-s/compare/ae4a8a4...f95a022aa5a5
