### ISSUE TITLE
Can't submit multiple new HTML media

### ISSUE THREAD

**Issue by patrickmj** [omeka/omeka-s#312]
Trying to add two new HTML media to an item gives:

Fatal error: Cannot set directive after finalization invoked on line 23 in file /var/www/omekas/application/src/Service/HtmlPurifier.php in /var/www/omekas/vendor/ezyang/htmlpurifier/library/HTMLPurifier/Config.php on line 892

**Comment by zerocrates** [comment]
Yeah, that looks pretty simple, the HtmlPurifier service should probably just be holding onto the "real" purifier it creates so it only has to instantiate it once, rather than trying to create a new one every time.

**Comment by patrickmj** [comment]
in the factory, or in the service itself?

**Comment by zerocrates** [comment]
Well, you can handle it in either the service or the factory or in both. The factory is already only going to run once to create your HtmlPurifier service. Any calls to get that service later will just return the HtmlPurifier that got created the first time.

So, you can do the config-type stuff directly in the factory, you can have it as a method of the HtmlPurifier service that you call from the factory, or you can do it as you're doing it now but just change the way `purify` works so it doesn't always try to re-create the purifier.
