### ISSUE TITLE
Display Job logs

### ISSUE THREAD

**Issue by jimsafley** [omeka/omeka-s#316]
Users need a way to view Job logs.

**Comment by patrickmj** [comment]
I'm good with working on this, but I don't think it is likely that I'll get to it by the July 31 milestone. All good to add it to the next cycle.

**Comment by jimsafley** [comment]
Ok, I understand. I'll prefer it it was done this week so I'll go ahead and do it.

**Comment by patrickmj** [comment]
That sounds like it might be a thing to save for planning?
