### ISSUE TITLE
How much metadata/LoD guidance should we give in interfaces?

### ISSUE THREAD

**Issue by patrickmj** [omeka/omeka-s#325]
It seemed to me like the list of OWL properties and classes imported on the vocabulary import page was a little long (and possibly misleading), and might be better as part of the documentation.

But elsewhere, I'm wondering about putting some of that data in an additional column on properties to give additional guidance, which could be followed or ignored in data entry.

For example, if we stored and displayed somewhere whether something is an `owl:DatatypeProperty` vs an `owl:ObjectProperty` would give guidance about whether expected value types would be texts vs resources or uris.

We wouldn't want to try to enforce that. But as an informational thing for people using Omeka to teach high-level metadata concepts, having that reference information available within Omeka S might be a handy thing.

**Comment by zerocrates** [comment]
Just a note that doing this would require a change to the database/entity model for properties/classes.

**Comment by zerocrates** [comment]
Verdict: remove the specific LOD names from the hint text for the uploader, create a page or section in manual to explain those same things instead.
