### ISSUE TITLE
Do media inputs need a header?

### ISSUE THREAD

**Issue by patrickmj** [omeka/omeka-s#330]
If someone is adding multiple media types, it seems like a more prominent header for each one might make the screen more readable, in addition to the existing labels

![media](https://cloud.githubusercontent.com/assets/153262/9151677/4994d6e8-3dd9-11e5-9195-4a8e119fc5ff.png)

**Comment by kimisgold** [comment]
Hmm, I might need a little more context. What kind of headings and groupings were you thinking? Also, what browser are you using in that screenshot? There's some weird excessive top margin/padding going on.

**Comment by patrickmj** [comment]
The top margin/padding is probably influencing me here. Screenshot is from FF. That padding/margin make it look like a heading would belong there. What I'm seeing is the different inputs that don't say at the top what kind of Media they are, even though it can be discerned from what's there. 

I'm thinking of the same headings at the top of each input form as are in the dropdown for selecting the Media type. The YouTube option might make an even better example -- select YouTube media type, and you get info to enter, but it doesn't say it is YouTube. If you have an OEmbed and a YouTube type both chosen, it would leave the form ambiguous. 

Similar to the top margin/padding thing, in Chrome it looks better. In Chrome, too, the "Paste from Word" button doesn't get bumped onto a new line like it does in FF.

**Comment by kimisgold** [comment]
![screen shot 2015-08-10 at 4 44 36 pm](https://cloud.githubusercontent.com/assets/606764/9183899/edd0ecb8-3f7f-11e5-96dd-e8eb20c81cfe.png)

So here's a look at the media fields with headings, and I'm finding that beyond Youtube, the headings feel repetitive. As you said, the media types can mostly be discerned by the context provided by the inputs—I lean towards trusting the user to grasp the interface quickly sans headings. Headings would also add more vertical space, and I'm not sure the tradeoff would be worth it.

**Comment by patrickmj** [comment]
I'm on the fence. I see the repetiveness. I also kinda like the headings as a general idea. It's a little less work for me to orient to what's happening on the screen. More impressions will be helpful, I think.

**Comment by jimsafley** [comment]
I like the headings. The page appears more organized. There's some comfort in seeing the media type that I just selected added to the (potentially long) form as a heading.

**Comment by zerocrates** [comment]
I also like the headings (keep in mind, as well, that the visibility and trash icons would likely move into those header rows). To some degree the repetitiveness would/could be solved by modifying the field labels (there'd be no need for the oEmbed URL field to say "oEmbed").

Potentially this also opens the door to allowing media forms that don't use the standard form field styling within: an example would be the HTML type where we've had concerns over horizontal spacing. With an HTML heading, the editor seemingly could be expanded to occupy the entire form area underneath, with no additional visible label as there is now.

**Comment by mebrett** [comment]
The headings might also help with accessibility.
