### ISSUE TITLE
Subdomains and domain mapping

### ISSUE THREAD

**Issue by patrickmj** [omeka/omeka-s#331]
Beyond the site slugs, people will likely want to have either or both of subdomains for each site in an Omeka S installation, and the ability to map their own domain names onto a site in an installation.

**Comment by zerocrates** [comment]
My recollection is that we'd previously said this wouldn't be in any initial release.

**Comment by losterhout** [comment]
Bumping this. I want to use Omeka S with a consortium and would love to be able to get subdomains and domain mapping similar to WP multisite. I can set up a subdomain in my host but there doesn't seem to be root to point it to as the Omeka S site folder is empty.

**Comment by bradspry** [comment]
:thumbsup: :thumbsup:

**Comment by jimsafley** [comment]
We don't currently plan on addressing this issue. Feel free to reopen and elaborate should you want further discussion.
