### ISSUE TITLE
Add current item/item set number range and total to pagination in the browse header

### ISSUE THREAD

**Issue by sharonmleon** [omeka/omeka-s#333]
In addition to just the page numbers and ranges on the top of the browse pages, can we have a total item count and an indication of where the user is as a range within that total?

 The page numbers don't feel like enough orientation.

This seems to effect both the items browse and the item sets browse layouts.

![firefoxscreensnapz004](https://cloud.githubusercontent.com/assets/741480/9212812/503a8be0-405a-11e5-91cb-4c3da4a059df.png)

**Comment by jimsafley** [comment]
Adding `'offset' => $paginator->getOffset()` to the pagination view helper's partial variables and using the code below somewhere in `common/pagination.phtml` should work:

```php
$from = $offset + 1;
$to = ($currentPage < $pageCount) ? $offset + $perPage : $totalCount;
echo sprintf('viewing %s–%s of %s', $from, $to, $totalCount);
```
