### ISSUE TITLE
Translate dynamic strings

### ISSUE THREAD

**Issue by kalbers** [omeka/omeka-s#336]
These lines require manual listing of source strings:

All Vocab, Class, and Proptery labels, specifically vocabs that come with Omeka.

https://github.com/omeka/omeka-s/blob/develop/application/view/omeka/admin/item/show.phtml#L24

https://github.com/omeka/omeka-s/blob/develop/application/view/omeka/admin/item-set/show.phtml#L34

https://github.com/omeka/omeka-s/blob/develop/application/view/omeka/admin/job/browse.phtml#L45
https://github.com/omeka/omeka-s/blob/develop/application/view/omeka/admin/job/browse.phtml#L46

https://github.com/omeka/omeka-s/blob/develop/application/view/omeka/admin/job/show-details.phtml#L19
https://github.com/omeka/omeka-s/blob/develop/application/view/omeka/admin/job/show-details.phtml#L31

https://github.com/omeka/omeka-s/blob/develop/application/view/omeka/admin/media/show.phtml#L19

https://github.com/omeka/omeka-s/blob/develop/application/view/omeka/admin/module/browse.phtml#L129

property/show-details.phtml (multiple)

resource-class/show-details.phtml (multiple)

https://github.com/omeka/omeka-s/blob/develop/application/view/omeka/admin/resource-template/browse.phtml#L32
https://github.com/omeka/omeka-s/blob/develop/application/view/omeka/admin/resource-template/browse.phtml#L57

https://github.com/omeka/omeka-s/blob/develop/application/view/omeka/admin/resource-template/form.phtml#L19
https://github.com/omeka/omeka-s/blob/develop/application/view/omeka/admin/resource-template/form.phtml#L22
https://github.com/omeka/omeka-s/blob/develop/application/view/omeka/admin/resource-template/form.phtml#L24

https://github.com/omeka/omeka-s/blob/develop/application/view/omeka/admin/resource-template/show-details.phtml#L5
https://github.com/omeka/omeka-s/blob/develop/application/view/omeka/admin/resource-template/show-details.phtml#L9

https://github.com/omeka/omeka-s/blob/develop/application/view/omeka/admin/resource-template/show-property-row.phtml#L10

https://github.com/omeka/omeka-s/blob/develop/application/view/omeka/admin/resource-template/show.phtml#L18

https://github.com/omeka/omeka-s/blob/develop/application/view/omeka/admin/resource-template/show.phtml#L35

https://github.com/omeka/omeka-s/blob/develop/application/view/omeka/admin/user/browse.phtml#L56

https://github.com/omeka/omeka-s/blob/develop/application/view/omeka/admin/user/edit-keys.phtml#L26

https://github.com/omeka/omeka-s/blob/develop/application/view/omeka/admin/vocabulary/browse.phtml#L34
https://github.com/omeka/omeka-s/blob/develop/application/view/omeka/admin/vocabulary/browse.phtml#L62

https://github.com/omeka/omeka-s/blob/develop/application/view/omeka/admin/vocabulary/classes.phtml#L7
https://github.com/omeka/omeka-s/blob/develop/application/view/omeka/admin/vocabulary/classes.phtml#L9
https://github.com/omeka/omeka-s/blob/develop/application/view/omeka/admin/vocabulary/classes.phtml#L30
https://github.com/omeka/omeka-s/blob/develop/application/view/omeka/admin/vocabulary/classes.phtml#L41

https://github.com/omeka/omeka-s/blob/develop/application/view/omeka/admin/vocabulary/properties.phtml#L7
https://github.com/omeka/omeka-s/blob/develop/application/view/omeka/admin/vocabulary/properties.phtml#L9
https://github.com/omeka/omeka-s/blob/develop/application/view/omeka/admin/vocabulary/properties.phtml#L30
https://github.com/omeka/omeka-s/blob/develop/application/view/omeka/admin/vocabulary/properties.phtml#L41

vocaubalary/show-details.phtml (multiple)

**Comment by jimsafley** [comment]
fixed in 8bd636463eddacbd022ca525ddea70fd79561b43
