### ISSUE TITLE
Sites: consider browse strategies

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#337]
The "browse block" as previously conceived may not be the best option for adding browse functionality to Sites. We should look into the problems raised by the browse block and consider whether those can be solved in the same framework (using a block) or whether it makes more sense to shift to another strategy for browsing (for example, having a static route/page for browsing within the items attached to the Site).

Among the problems are: pagination (what do we do when more than one browse block is on a single page?) and having the browse block be in a certain sense simply a reimplementation of the regular browse page.

**Comment by zerocrates** [comment]
Possible option: browse preview with link to real browse page

**Comment by sharonmleon** [comment]
@kimisgold Thoughts on this? Seems like pagination is a usability nightmare.

**Comment by jimsafley** [comment]
I added a "Browse Preview" layout that displays the first 10 items of a user-defined browse and links out to the site browse page. I plan to make the number of preview items customizable.
