### ISSUE TITLE
Should sites have their own pool of items?

### ISSUE THREAD

**Issue by jimsafley** [omeka/omeka-s#340]
There are at least two approaches to adding items to sites: one where site builders attach items to pages directly from the global item pool, and the other where they attach items from a "curated" item pool, i.e. items pre-selected for use in the site.

The first option removes one step from item assignment, but could complicate item selection due to the large number of unrelated items. The second adds a (possibly arduous) pre-selection step to item assignment, but could add clarity to the site building process.

To be clear, in the second option, all items remain in the global pool, but are also in a second, "curated" pool.

Blocks #337 because I need to know where to derive the list of "attached" items.

@patrickmj @zerocrates @kimisgold @kalbers @sharonmleon @sheilabrennan

**Comment by patrickmj** [comment]
Seems like option 1 makes more sense. For the curating step of option 2, people can just use item sets. That'd alleviate the complication in the first option. If a site builder wanted to curate items for use in their site, they can just say "Choose from Item Sets X, Y, Z" They'd have made those item sets same as they would have attached items to a site as in option 2.

I think that would make more sense for one of the use cases -- building different sites from the same collection of items, e.g. a class that runs every year, building sites from the same or very similar items

**Comment by zerocrates** [comment]
The context here is that we have some little pieces in the code and database that's intended for Option 2, as a result of long-ago early-stage conversations and decisions about the data model.

I'm also in favor of Option 1 just because it removes a step that otherwise would annoyingly get in the way.

**Comment by jimsafley** [comment]
Sites will not have a separate pool of items. @patrickmj's answer above explains why.
