### ISSUE TITLE
Should items have shared/not shared flag?

### ISSUE THREAD

**Issue by kalbers** [omeka/omeka-s#341]
The USDA ARS people indicated they hoped that items could be marked both Public/Private for use in the general pool, but also that items could be marked as Shared/Not Shared between site users; eg, we all share an install of Omeka S, with a pool of items, but I am able to have items which are public, and able to be added to my sites, but not available for other users on their own sites.

I think we might have discussed this a bit before, but I thought I'd mention it since we haven't gotten much back from our user base yet. Just one group's perspective (and a portion of that group's), but something to consider.

I bring it up now, as it seems like it could impact #340.

**Comment by patrickmj** [comment]
Not sure what exactly the permissions options are right now, but this sounds a little like group permissions ala server permissions. That is, an owner of an Item marks it public or private. But owner also can add it to a group. Thus, the _group_ could see it to add it to a site (that'd mean a group-site correlation somewhere in the data model).

Or, we stick with what I think we've been aiming for -- Items are generally visible, or they're not.

This is a good nuance to address in the context of #340. I'm still won over to option 1 in that issue. In general, we'll have to decide how much we support this kind of siloing.

**Comment by jimsafley** [comment]
We discussed the idea of shareable resources early in development and concluded that a) the interaction between shareability and visibility is technically problematic, and, less importantly, b) it contradicts the spirit of collaboration and openness we're trying to nurture in Omeka S.

Though I understand the impulse to not share things, I question the logic behind making them public and non-shareable, given that anyone could reconstitute a public item and use it in another site anyway.
