### ISSUE TITLE
Sites need a user interface for building navigation

### ISSUE THREAD

**Issue by jimsafley** [omeka/omeka-s#350]
Navigation can contain links to a home page, browse pages, or site pages. All pages can have child pages. A drag and drop tree structure could possibly work here, as long as the final data structure follows this general syntax:

```json
[
  {
    "type": "home"
  },
  {
    "type": "browse",
  },
  {
    "type": "page",
    "id": 1,
    "pages": [
      {
        "type": "page",
        "id": 2,
        "pages": [
          {
            "type": "page",
            "id": 3
          }
        ]
      }
    ]
  }
]
```

**Comment by jimsafley** [comment]
One hitch is that a site must have at least one page for the navigation to work. This is due to `NavigationAbstractServiceFactory` not accepting an empty navigation configuration. We either have to mandate at least one page (such as a home page) or possibly write our own abstract service factory that does not have this restriction.

**Comment by zerocrates** [comment]
Seems that we can just have our layer that normally filters the navigation just return a fake array with a pre-baked link to "Home" that just links to the site's URI, without actually mandating a minimum number of pages or changing the factory.

**Comment by jimsafley** [comment]
Since we store navigation data as a multidimensional array, we must have three recursive functions to handle conversions between formats:

* jsTree to o:navigation, in `SiteAdmin/IndexController`
* o:navigation to jsTree, in `SiteAdmin/IndexController`
* o:navigation to ZF2 navigation, in `MvcListeners`

We will need to propagate any changes to the o:navigation format to all of these functions, so we're probably better off keeping them all in one place, even sharing the recursion somehow. Maybe a NavigationFormat service? What do you think @zerocrates?

**Comment by zerocrates** [comment]
Yes, it definitely makes sense to have things together for decoding/encoding to the storage format for the nav data.

This could probably just be a class rather than a Service though... I don't see any likelihood of it needing to be replaced or configured.

**Comment by jimsafley** [comment]
Notes for instructions on how to use the navigation tree:

>  Use the sidebar to add pages to the navigation, delete a selected page, and deselect a selected page. Add a page to the navigation root by deselecting any selected page and adding as usual. Add a page under a page by selecting the parent page and adding the child page as usual. Drag-and-drop to move a page and its child pages to another place.

We probably need to put something like this on the page.

**Comment by zerocrates** [comment]
Does "delete" in this context mean "remove from the navigation"? If so, I think we want to scrupulously avoid the word "delete."

Having to have a button for deselecting seems pretty non-optimal as well.

**Comment by zerocrates** [comment]
Additionally things would probably be a little less confusing if the stuff in the sidebar disappeared or greyed out or something like that when it was already in the navigation.

**Comment by zerocrates** [comment]
Ah sorry, I'd missed that clicking them again actually lets you add the same page multiple times. That should probably be illegal.

**Comment by jimsafley** [comment]
@zerocrates @kimisgold @kalbers 

The first run of the navigation builder UI (see the "navigation" branch) stimulated good conversation and raised some red flags. Overwhelmed by ideas I want to back up and gather some minimum requirements in writing, here on this issue.

Let's start from the beginning, not focusing on the "navigation" branch. Generally we need a way for users to build a navigation tree using existing pages. How should users do this? What controls should we offer? What restrictions should we place? What should the interface look like? I'm not familiar with navigation building in our Exhibit Builder, but that may be a good jumping-off point.

Again, I'm asking for _minimum requirements_ for the navigation builder UI. Thanks.

**Comment by zerocrates** [comment]
Here's a short description of what we have in the Exhibit Builder:

The pages that exist are shown in a nested tree and can be nested and reordered through drag-and-drop. They can be deleted from within the tree by clicking an "X," but that deletes the *page* itself. There is no way to have a page exist in the site but be absent from the "navigation." There is no facility to add custom navigation entries. The tree is also where the links to edit each page appear.

**Comment by zerocrates** [comment]
By contrast, here's what Classic has for "Navigation:"

* The pages that are added by the core and plugins are presented in a drag-and-drop sortable tree (largely the same as the EB tree in terms of how the d-n-d works).
* A separate pair of text inputs below the tree allows users to add a custom entry given a label and URL.
* Pages that come from plugins and the core cannot be deleted from the navigation, while custom pages can be deleted.
* Any page can be "deactivated" with a checkbox, keeping it in the navigation interface while making it not visible in the output (this is the only way to remove the core/plugin-added pages from the output nav).
* Entries in the tree can be expanded by clicking on them, revealing text inputs for editing the label (and, in the case of custom pages, the URL).

This is probably, in my view, closer to the set of things we need for site navigation than what Exhibit Builder had.

**Comment by jimsafley** [comment]
It seems that, by looking at the feature lists posted by @zerocrates above, the Omeka S navigation builder will need to be a hybrid of the Exhibit Builder navigation _and_ theme navigation. An OS site will have _many_ pages, like an O2 exhibit but largely unlike O2 theme navigation. An OS site will have custom pages, like O2 theme navigation.

Of the features in O2 theme navigation, which a) make sense in an O2 site context, and b) meet the _minimum_ requirements for a navigation builder?

**Comment by jimsafley** [comment]
Up now on the "navigation" branch is a simple two-tree strategy. You can move pages from the sidebar to the navigation tree and back to the sidebar. Everything there can be themed and optimized.

**Comment by zerocrates** [comment]
I think the "classic navigation" is very close to what we need in terms of features:

* the tree (hierarchy is non-negotiable, I think)
* drag and drop (can't really think of another reasonable way to have people make the tree)
* preset pages (the pages of the site, as well as the "special" pages for browse, at least)
* custom pages

There are a few features that aren't strictly necessary like the ability to change all the labels, but once you have custom pages you need some label entry anyway.

**Comment by kalbers** [comment]
Sorry, jumping in late here, but just to confirm, is this in reference to top-level nav only?

**Comment by jimsafley** [comment]
Not sure what you mean by "top-level" navigation. This is in reference to the navigation shown to the public when viewing a site.

**Comment by kalbers** [comment]
Most sites have several areas of navigation. Top level navigation. Sub-navigation on browse pages, exhibit pages, footer navigation, etc.

In other words, there will be a need to build multiple menus at the very least, but I wasn't sure if we were only focused on the top-level right now.

**Comment by zerocrates** [comment]
Let's say this is about building the hierarchy. There's unlikely to be any further UI areas for configuring navigation, but that doesn't mean that you couldn't have a dichotomy between top-level nav and side nav (like the nav across the top could show only the first level of things in the configured navigation, and a sidebar could show the pages underneath the current one, stuff like that).

**Comment by jimsafley** [comment]
I may be wrong, but I think there's no distinction between "top-level" and "exhibit pages" navigation in Omeka S.

**Comment by kalbers** [comment]
Just so I understand, it seems like we're leaning toward something like Wordpress, where you can create as many navigation menus as you want, and return them in your themes in different places?

**Comment by zerocrates** [comment]
No, I don't think so.

I meant that you'd have just one navigation (this is where I called it "hierarchy"), but the theme could potentially show different parts of that in different places.

The current model allows for only one navigation hierarchy to be stored.

**Comment by kalbers** [comment]
Hmm, that sounds a little confusing to me, but I guess so long as you can break out parts of it, it should be fine. I'm having a little trouble picturing it, but I guess so long as pages can be repeated in different parts of the hierarchy, that should work.

**Comment by zerocrates** [comment]
> so long as pages can be repeated in different parts of the hierarchy, that should work

I'm having trouble understanding what you're looking for here. Whether or not the pages can be repeated is one of the outstanding questions for the UI (I'm not in favor of allowing it). What would you use that ability to do?

**Comment by kalbers** [comment]
You have a header and footer nav. You want header nav to have Foo, Bar, Baz. You want footer nav to have Baz, Bat.

**Comment by zerocrates** [comment]
A feature currently not provided by either the "main" navigation or either of our plugins that provide navigation, Exhibit Builder and Simple Pages.

Do we care about this? (This is a serious question, it is an important factor if we do.)

**Comment by kalbers** [comment]
I don't really care that much, since I assume we can build them out int he theme manually. But if we are widgetizing most of everything else, it might make sense to build in some widgets for the navigation as well.

**Comment by zerocrates** [comment]
Okay.

A solid understanding of what we want this to actually do is pretty vital for doing most or all of the UI work on it, so we need to get some clarity on the scope here.

**Comment by patrickmj** [comment]
I'm not sure we can assume the ability to build things out in the theme manually will be as common as it is for an O2 instance, since in many cases people won't have direct access to the server.

**Comment by zerocrates** [comment]
Rather than just call for opinions I'll state my own here: I think it's fine to only have one "navigation" hierarchy you can configure. As with any system that does things like this for you, you take the good with the bad, meaning you can't have it do absolutely everything you might want to.

I'm finding it pretty hard to believe that "same footer nav as header nav" is really a dealbreaker.

**Comment by kalbers** [comment]
Probably not a dealbreaker, but being able to have a different header and footer nav feels like a fairly basic feature to me.

This gets me thinking about the headers and footers in general. Are we going to handle the header and footer content in the themes, as it currently is, or will it be independent. It might make sense to not even have a central navigation point, but instead, opportunities in to include navigation in different places; eg, instead of controlling the navigation in one spot, and the header content in the theme, the header content can be set independent of the theme, and part of setting the content includes setting the navigation.

Sorry if this significantly muddies the water, but seems worth thinking through.

**Comment by jimsafley** [comment]
I agree that it's fine to have one navigation hierarchy. One way to alleviate @kalbers' concern is to provide an optional HTML editor to enter customized footer navigation. I also think repeatable pages is fine, though I understand how this could be confusing to the end user if the navigation is arranged carelessly.

**Comment by sheilabrennan** [comment]
I like @jimsafley's suggestion, because it seems to appease everyone. I think keeping one navigation hierarchy is a good call, while also offering users the ability to control footer text/nav.

**Comment by jimsafley** [comment]
On the `navigation` branch we've settled on a strategy to add pages to the navigation, but there's more work to be done:

* Determine whether we want to allow custom labels for "preset" pages (the pages of the site, home browse). We'll definitely need custom labels for browse pages since they could link to different searches.
* Determine whether we even need "special" preset pages (home, browse), since this feature can easily be done using "custom" pages. I'm leaning toward removing "special" pages in favor of "custom" pages.
* Add an interface to add "custom" pages (given a label and URL). Given space limitations in the sidebar, we may want to include this interface directly under the navigation tree.
* If we decide to include them, add an interface to display and add "special" preset pages (home, browse). We could include these in the sidebar, above the pages of the site.

Thoughts, @zerocrates, @kalbers, @kimisgold?

**Comment by zerocrates** [comment]
On the preset pages: here's an area where we have to think about plugin integration a little bit as well, in this case for Contribution. Contribution has to end up on the public side somehow, and I believe in our prior discussions we've indicated that people will want that embeddable within a site so it will carry the same theme. That could be tough to accomplish without the "special" pages

**Comment by kalbers** [comment]
1) I'd say we definitely need custom labels for any page.

2) I think we could probably make them custom pages that just come preloaded? That way if people don't want to build them out, they are there, but they can customize them as desired.

**Comment by kimisgold** [comment]
I would want to allow custom labels for preset pages, especially after seeing large variance in what users want to call the 'browse' view in Omeka 2. I don't have many immediate thoughts on layout and placement, but I'll be able to provide informed opinions once I get more hands-on with the interface.

**Comment by jimsafley** [comment]
We have a good idea of requirements now. Closing but continuing development on #378, #379, #383
