### ISSUE TITLE
Private status for sites

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#355]
We need a public/private flag to make sites viewable/published or not. If not public, users will have to pass a permissions check to see the site.

**Comment by zerocrates** [comment]
Question: does an "unpublished" site need to be hidden from other logged-in users? The "published" or "public" flag could affect only what non-logged-in users can see, or it could apply to everybody. The difference between those two is very significant for how it needs to get implemented and the terminology we use.

@omeka/team-omeka

**Comment by patrickmj** [comment]
Before I write a too-long response, am I following right that there is no distinction of being logged in to one particular _site_ and being logged-in to the entire Omeka S installation? That seems like the situation and question, but want to make sure.

**Comment by jimsafley** [comment]
You're correct, there is no distinction.

**Comment by patrickmj** [comment]
Thanks, @jimsafley 

I'd call it an absolute imperative that an 'unpublished' site can be hidden from other logged-in users.

Take the case of an OS installation at a university. One prof wants to use it to stand up a site about a potentially controversial topic -- one that they don't want public -- especially one that could make public access to their students' work uncomfortable or even risk backlash and intimidation. (topics like sexuality, religion, gender relations, sports, immigration....it's a long list). They'll need to do their work in a closed, private, safe environment. If any other logged in user could see that work, that would easily be a deal-breaker for using Omeka S. (To my understanding, the items permissions we've talked about handle that case. Is that right?)

More basically, the alternative -- where an 'unpublished' site could be visible to other logged in users -- sounds like the equivalent of us having a universal login to all Omeka 2 sites: if you can log in to one O2 site, you can log in and see the private content of any. That doesn't sound good.

**Comment by sheilabrennan** [comment]
It makes sense to me that a private/unpublished site is only visible to those with permissions associated with that site.

**Comment by jimsafley** [comment]
@patrickmj's comment above convinced me that we should stick to a strict "public/private" approach to site visibility. It will greatly complicate implementation but I foresee that our users will rebel against a simple, unprotected "published/unpublished" approach

**Comment by kalbers** [comment]
So, would an unpublished site be only available to the site owner? Or are users going to be able to be added to, ie given permission to view, a site?

**Comment by zerocrates** [comment]
Take a look at #366, Ken. The current vision there is that there'd be a level or permission you can give to specific users that would let them view the site even when it was private.

**Comment by zerocrates** [comment]
As for "greatly complicated implementation"... could be. The sort of "standard" permissions stuff of "it's private or you own it" for normal users is not difficult and we already have a model for doing that with the search query event.

The per-user permissions definitely add a wrinkle, but it would be an easy query if the rule/model was that just anybody who's in the permission table for a site gets view permissions (so setting that up as the absolute minimum grantable permission). Otherwise, thinking back at #366 and our options there, the query would also be easy with separate-column permissions as the model currently stands as you could just check for the `view` column.
