### ISSUE TITLE
Sites: integration/polish of the stub block layout interface

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#357]
The initial version of the admin interface for adding blocks doesn't pay attention to styling -- it needs to be integrated into the existing admin theme.

**Comment by kimisgold** [comment]
Here are the changes I've made thus far: 

* Use 'flat' theme for CKEditor to better match the rest of the Omeka interface
* Provide full-width handle for sorting blocks
* Mark up 'browse preview' to use 'field' markup (including 'field-meta' and 'inputs' divs)
* Add a class indicating layout of each block

Is there anything that I missed and/or needs more attention?

**Comment by jimsafley** [comment]
Looks good. I think block headers on page edit would make organizing the page a bit easier.

**Comment by jimsafley** [comment]
Also, when adding a block below the fold the page should probably scroll down.

**Comment by patrickmj** [comment]
Joys of Firefox: adding an HTML block, it gets pushed way far to the right, almost completely invisible under the sidebar:


![screenshot from 2015-09-14 14 34 47](https://cloud.githubusercontent.com/assets/153262/9858337/1ecd2adc-5aee-11e5-8776-ccdb3c9cda4b.png)

**Comment by kimisgold** [comment]
Seems like everything in this thread's been addressed. Open new issues for further refinements.
