### ISSUE TITLE
Allow modules to filter/hook onto value display

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#364]
In its simplest form, this would entail an event or trigger in ValueRepresentation::asHtml.

**Comment by zerocrates** [comment]
This will be necessary for MetadataBrowse

**Comment by patrickmj** [comment]
Do we want/need to establish patterns for the parameters (e.g., objects passed besides the event target (if any), and naming conventions for keys) passed along to events for doing filtering, or is that premature for this issue?
