### ISSUE TITLE
Rework site user-by-user permissions

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#366]
Especially now that we've decided to nix the separate "attach" step of using items in a Site, it's probably time to pivot from the original permissions levels we specified when initially envisioning the model to ones that more accurately fit the workflow we actually have.

That almost certainly means bidding adieu to "attach", and potentially adding a level that just gives out read permission. We'd need to decide at this point too if we're satisfied with "admin" and "edit" as the two other levels, and whether or not we want to keep the concept that these are all independent permissions or to rework them as basically roles: `admin` > `edit` > `view` > joe schmo.

**Comment by patrickmj** [comment]
On the question of whether or not we want to keep independent permissions, I strongly lean toward yes. We get a lot of requests about different permissions configuration. While we'll never accommodate all the variations people want, building in more degrees of freedom at this stage sounds like the best move early on.

That might imply, though, some idea of how to assign such permissions (I'm assuming that's an admin thing).

**Comment by zerocrates** [comment]
> That might imply, though, some idea of how to assign such permissions (I'm assuming that's an admin thing).

I don't catch your meaning here.

**Comment by patrickmj** [comment]
I might be missing a basic thing, but I'm thinking of who decides who is admin, who is editor, who is Joe Schmo kinds of questions.

For example: I assume admins can make other admins. But could an editor make other editors?

**Comment by zerocrates** [comment]
All that stuff has (sort of) been looked at already, the answer being that only the owner and any "admin"-having users can change the permissions grants at all.

**Comment by zerocrates** [comment]
My concern with the permissions levels we're likely to end up with: something around the ballpark of admin, edit, and view, maybe with some different names or another level in there, is that they don't have any really reasonable way to actually work as independent units in a very sensible way.

For example, what does it mean to have "admin" but not "edit" permissions, or to have any of them and not have "view"? They're not really additive in a way that makes sense to me for mix-and-match, which means we either need to make some nonintuitive  or nonsensical permissions choices possible or we need to make some of the choices meaningless (like, right now, having 'admin' in actuality implies the lower permissions in the way the checks are actually written, so once you click 'admin' the other boxes are irrelevant), making the interface pretty confusing.

**Comment by patrickmj** [comment]
yeah...here there be Drupal checkbox dragons.

If the permissions-assignment question is done, then the hierarchy of roles seems right to me, even though I don't think we've had a strong stance against allowing nonsense heretofore.

**Comment by jimsafley** [comment]
For clarity, here's how I see a hierarchy of roles working:

* **view**: read-only privileges to the site when the site is non-public;
* **edit**: all the privileges of **view**; create, update, and delete the site's pages and blocks;
* **admin**: all the privileges of **edit**; update the site; assign the site's user permissions (note that this role cannot create or delete the site).

We currently don't have administrative show templates for site and site-page, so for the **view** role we need to either a) create these templates or b) limit viewing of non-public sites to the front-end.

As for the data model, we should probably consolodate the separate `SitePermission` fields into one `role` field.

**Comment by zerocrates** [comment]
Yes, basically if those are the 3 permissions we go with, there's not much point that i see in doing them as independent permissions rather than as "roles" because each naturally contains the lower ones.

Now, it's still possible to have them *stored* as independent permissions as they are now while making the interface not expose those possiblities... but the only point in keeping it that way would be if *something* was going to actually use the independent checkbox-style permissions granting. Right now I can't see anything we've thought of that would actually work that way.

**Comment by zerocrates** [comment]
Oh and a side note, this really interacts with the "published vs. public" discussion about Site permissions: the `view` permission here only really makes sense if the Site visibility flag is "private," that is, hidden from other auth'd users.

**Comment by zerocrates** [comment]
We'll be doing this with "roles"
