### ISSUE TITLE
Cannot add site because no dropdown for theme

### ISSUE THREAD

**Issue by mebrett** [omeka/omeka-s#367]
On the install on dev (which is on branch master, just updated), I can't currently add a site. There is a dropdown field for theme but the dropdown is empty; I can't successfully add a site until I select a theme. 
![screen shot 2015-09-11 at 12 15 34 pm](https://cloud.githubusercontent.com/assets/2314070/9819990/0a3f037c-587f-11e5-8177-03dd7e829051.png)

**Comment by zerocrates** [comment]
This happens when there's no theme.

It would be fixed by the inclusion of a default theme, so #356.

**Comment by kimisgold** [comment]
There should be a default theme now. (fdc0d0354f0355aeb53dbb9bfa6b5a2300f9e9b8)
