### ISSUE TITLE
Ingesters for locally-stored files should be separate from full "media types"

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#369]
The concern is this: a plugin adds a new media type for ingesting files and storing them locally (say this is BulkFileUpload). When the plugin is deactivated or uninstalled, we won't recognize that media type anymore, and won't be able to show it.

Instead, it should be possible for these types of ingesters to be added as simply that: ingesters, while allowing the resulting files to be always stored as a single "file" or "local file" type.

**Comment by jimsafley** [comment]
![20150921_142551-1](https://cloud.githubusercontent.com/assets/141955/10001154/5ec216ea-606e-11e5-877c-e18c198eda33.jpg)
