### ISSUE TITLE
Error with login page

### ISSUE THREAD

**Issue by patrickmj** [omeka/omeka-s#372]
Pulled latest this morning (b8429097fa534ea53125c3916ad7358208499dcd) got:

<b>Fatal error</b>:  Uncaught exception 'Zend\View\Exception\RuntimeException' with message 'Zend\View\Renderer\PhpRenderer::render: Unable to render template &quot;layout/minimal&quot;; resolver could not resolve to a file' in /var/www/omekas/vendor/zendframework/zend-view/src/Renderer/PhpRenderer.php:493
Stack trace:
#0 /var/www/omekas/vendor/zendframework/zend-view/src/View.php(205): Zend\View\Renderer\PhpRenderer-&gt;render(Object(Zend\View\Model\ViewModel))
#1 /var/www/omekas/vendor/zendframework/zend-mvc/src/View/Http/DefaultRenderingStrategy.php(103): Zend\View\View-&gt;render(Object(Zend\View\Model\ViewModel))
#2 [internal function]: Zend\Mvc\View\Http\DefaultRenderingStrategy-&gt;render(Object(Zend\Mvc\MvcEvent))
#3 /var/www/omekas/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#4 /var/www/omekas/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager-&gt;triggerListeners('render.error', Object(Zend\Mvc\MvcEvent), Array)
#5 /var/www/om in <b>/var/www/omekas/vendor/zendframework/zend-view/src/Renderer/PhpRenderer.php</b> on line <b>493</b><br />

**Comment by patrickmj** [comment]
Update. actually looks like it's a problem on login page

**Comment by zerocrates** [comment]
@jimsafley I assume this is just a result of the view moving stuff from the end of last week. I wasn't sure whether you were planning to have the "minimal" layout exist in the shared views or whether you were just going to rework the views like login to use the regular layout/layout fallback in the shared views, so I just assigned it to you.
