### ISSUE TITLE
Apply autocomplete interface to navigation sidebar

### ISSUE THREAD

**Issue by kimisgold** [omeka/omeka-s#380]
The list of site pages can easily get long and unwieldy, so the autocomplete would help users more quickly find and add pages to the navigation tree.

**Comment by zerocrates** [comment]
So I'm clear, we're talking more like an optional "filter" that would narrow down the sidebar's listing rather than really an autocomplete, correct?

**Comment by kimisgold** [comment]
Yes, basically what we have in in the property selector.
