### ISSUE TITLE
Error deleting items that are in a block on a site

### ISSUE THREAD

**Issue by patrickmj** [omeka/omeka-s#382]
While mucking about with Omeka 2 Importer and deleting items, when I tried to delete ones that are part of a site I got this. Not sure if we've decided how to handle the situation when an item is part of a site, and someone tries to delete the item. I remember talk of stern warnings, but not sure where it stands now.

There was an error.

exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`omekaSdev`.`site_block_attachment`, CONSTRAINT `FK_236473FE126F525E` FOREIGN KEY (`item_id`) REFERENCES `item` (`id`))' in /websites/omekadev/home/www/omeka-s/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91
Stack trace:
#0 /websites/omekadev/home/www/omeka-s/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(91): PDOStatement->execute(Array)
#1 /websites/omekadev/home/www/omeka-s/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(989): Doctrine\DBAL\Driver\PDOStatement->execute(Array)
#2 /websites/omekadev/home/www/omeka-s/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(595): Doctrine\DBAL\Connection->executeUpdate('DELETE FROM res...', Array, Array)
#3 /websites/omekadev/home/www/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/JoinedSubclassPersister.php(285): Doctrine\DBAL\Connection->delete('resource', Array)
#4 /websites/omekadev/home/www/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(1098): Doctrine\ORM\Persisters\Entity\JoinedSubclassPersister->delete(Object(Omeka\Entity\Item))
#5 /websites/omekadev/home/www/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(406): Doctrine\ORM\UnitOfWork->executeDeletions(Object(Doctrine\ORM\Mapping\ClassMetadata))
#6 /websites/omekadev/home/www/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(356): Doctrine\ORM\UnitOfWork->commit(NULL)
#7 /websites/omekadev/home/www/omeka-s/application/src/Api/Adapter/AbstractEntityAdapter.php(360): Doctrine\ORM\EntityManager->flush()
#8 /websites/omekadev/home/www/omeka-s/application/src/Api/Manager.php(207): Omeka\Api\Adapter\AbstractEntityAdapter->delete(Object(Omeka\Api\Request))
#9 /websites/omekadev/home/www/omeka-s/application/src/Api/Manager.php(123): Omeka\Api\Manager->execute(Object(Omeka\Api\Request))
#10 /websites/omekadev/home/www/omeka-s/application/src/Mvc/Controller/Plugin/Api.php(125): Omeka\Api\Manager->delete('items', '3221', Array)
#11 /websites/omekadev/home/www/omeka-s/application/src/Controller/Admin/ItemController.php(79): Omeka\Mvc\Controller\Plugin\Api->delete('items', '3221')
#12 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(82): Omeka\Controller\Admin\ItemController->deleteAction()
#13 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#14 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#15 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#16 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(118): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#17 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-mvc/src/DispatchListener.php(93): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#18 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#19 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#20 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#21 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-mvc/src/Application.php(314): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#22 /websites/omekadev/home/www/omeka-s/index.php(16): Zend\Mvc\Application->run()
#23 {main}

Next exception 'Doctrine\DBAL\Driver\PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`omekaSdev`.`site_block_attachment`, CONSTRAINT `FK_236473FE126F525E` FOREIGN KEY (`item_id`) REFERENCES `item` (`id`))' in /websites/omekadev/home/www/omeka-s/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93
Stack trace:
#0 /websites/omekadev/home/www/omeka-s/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(989): Doctrine\DBAL\Driver\PDOStatement->execute(Array)
#1 /websites/omekadev/home/www/omeka-s/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(595): Doctrine\DBAL\Connection->executeUpdate('DELETE FROM res...', Array, Array)
#2 /websites/omekadev/home/www/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/JoinedSubclassPersister.php(285): Doctrine\DBAL\Connection->delete('resource', Array)
#3 /websites/omekadev/home/www/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(1098): Doctrine\ORM\Persisters\Entity\JoinedSubclassPersister->delete(Object(Omeka\Entity\Item))
#4 /websites/omekadev/home/www/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(406): Doctrine\ORM\UnitOfWork->executeDeletions(Object(Doctrine\ORM\Mapping\ClassMetadata))
#5 /websites/omekadev/home/www/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(356): Doctrine\ORM\UnitOfWork->commit(NULL)
#6 /websites/omekadev/home/www/omeka-s/application/src/Api/Adapter/AbstractEntityAdapter.php(360): Doctrine\ORM\EntityManager->flush()
#7 /websites/omekadev/home/www/omeka-s/application/src/Api/Manager.php(207): Omeka\Api\Adapter\AbstractEntityAdapter->delete(Object(Omeka\Api\Request))
#8 /websites/omekadev/home/www/omeka-s/application/src/Api/Manager.php(123): Omeka\Api\Manager->execute(Object(Omeka\Api\Request))
#9 /websites/omekadev/home/www/omeka-s/application/src/Mvc/Controller/Plugin/Api.php(125): Omeka\Api\Manager->delete('items', '3221', Array)
#10 /websites/omekadev/home/www/omeka-s/application/src/Controller/Admin/ItemController.php(79): Omeka\Mvc\Controller\Plugin\Api->delete('items', '3221')
#11 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(82): Omeka\Controller\Admin\ItemController->deleteAction()
#12 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#13 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#14 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#15 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(118): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#16 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-mvc/src/DispatchListener.php(93): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#17 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#18 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#19 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#20 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-mvc/src/Application.php(314): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#21 /websites/omekadev/home/www/omeka-s/index.php(16): Zend\Mvc\Application->run()
#22 {main}

Next exception 'Doctrine\DBAL\Exception\ForeignKeyConstraintViolationException' with message 'An exception occurred while executing 'DELETE FROM resource WHERE id = ?' with params [3221]:

SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`omekaSdev`.`site_block_attachment`, CONSTRAINT `FK_236473FE126F525E` FOREIGN KEY (`item_id`) REFERENCES `item` (`id`))' in /websites/omekadev/home/www/omeka-s/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:60
Stack trace:
#0 /websites/omekadev/home/www/omeka-s/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(116): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException))
#1 /websites/omekadev/home/www/omeka-s/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(996): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'DELETE FROM res...', Array)
#2 /websites/omekadev/home/www/omeka-s/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(595): Doctrine\DBAL\Connection->executeUpdate('DELETE FROM res...', Array, Array)
#3 /websites/omekadev/home/www/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/JoinedSubclassPersister.php(285): Doctrine\DBAL\Connection->delete('resource', Array)
#4 /websites/omekadev/home/www/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(1098): Doctrine\ORM\Persisters\Entity\JoinedSubclassPersister->delete(Object(Omeka\Entity\Item))
#5 /websites/omekadev/home/www/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(406): Doctrine\ORM\UnitOfWork->executeDeletions(Object(Doctrine\ORM\Mapping\ClassMetadata))
#6 /websites/omekadev/home/www/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(356): Doctrine\ORM\UnitOfWork->commit(NULL)
#7 /websites/omekadev/home/www/omeka-s/application/src/Api/Adapter/AbstractEntityAdapter.php(360): Doctrine\ORM\EntityManager->flush()
#8 /websites/omekadev/home/www/omeka-s/application/src/Api/Manager.php(207): Omeka\Api\Adapter\AbstractEntityAdapter->delete(Object(Omeka\Api\Request))
#9 /websites/omekadev/home/www/omeka-s/application/src/Api/Manager.php(123): Omeka\Api\Manager->execute(Object(Omeka\Api\Request))
#10 /websites/omekadev/home/www/omeka-s/application/src/Mvc/Controller/Plugin/Api.php(125): Omeka\Api\Manager->delete('items', '3221', Array)
#11 /websites/omekadev/home/www/omeka-s/application/src/Controller/Admin/ItemController.php(79): Omeka\Mvc\Controller\Plugin\Api->delete('items', '3221')
#12 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(82): Omeka\Controller\Admin\ItemController->deleteAction()
#13 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#14 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#15 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#16 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(118): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#17 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-mvc/src/DispatchListener.php(93): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#18 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#19 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#20 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#21 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-mvc/src/Application.php(314): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#22 /websites/omekadev/home/www/omeka-s/index.php(16): Zend\Mvc\Application->run()
#23 {main}

**Comment by zerocrates** [comment]
We should probably be doing a DB-level cascade delete there. For media we could SET NULL, but the item is required, so without it the attachment can't exist

**Comment by zerocrates** [comment]
This doesn't preclude us from showing a warning, but we need the cascade setup to be able to delete the item anyway after the warning (unless we want to force users to delete all the attachments before they can get rid of the item, which I think we don't).
