### ISSUE TITLE
In FF, modules list and omeka s version conflict

### ISSUE THREAD

**Issue by patrickmj** [omeka/omeka-s#385]
Fine in Chrome, but in FF the version info draws on top of the modules list.
![modulesvsversionfight](https://cloud.githubusercontent.com/assets/153262/10103663/27321768-6373-11e5-86c4-867698645c53.png)

**Comment by zerocrates** [comment]
By "modules list" you mean the main admin nav, right?

**Comment by patrickmj** [comment]
@zerocrates yep.
