### ISSUE TITLE
Fix search filters display to account for resource-based value filters

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#387]
This is the "res" and "nres" filters.

A bare minimum implementation would just show the ID of the resource being searched for, but it could also go further to look up the resource represented by that ID so we can show the title (but, you'd need to account for when somebody searches for a nonexistent or hidden resource).

**Comment by kimisgold** [comment]
From within the view helper, I need a way to pull the name of the searched linked resource, and that's not possible within the current build.

**Comment by zerocrates** [comment]
To clarify, this is because only the resource ID gets passed in. This is actually sufficient to uniquely return a single resource since they share their ID space, but there's no API endpoint for reading a resource based only on its ID (that is, without specifying that it's an Item or Item Set or Media that you're looking for).

**Comment by zerocrates** [comment]
@jimsafley the only way I can think of for fixing this is making a "resources" API resource that lets you `read` only. Not sure we want to bother, but I suppose I could see some use to it...
