### ISSUE TITLE
Decide about how to do developer documentation, and do it.

### ISSUE THREAD

**Issue by patrickmj** [omeka/omeka-s#393]
This has been lingering. Last addressed, there was a sense that it was premature to work on this. I think that time is passed.

Things to address, even if they might change:
* Style (CSS, classes, etc.)
* Patterns to use (in controllers, views, jobs, more)
* building config files
* Stay with readthedocs, or something different? Coordinate here with user docs.
* other ?

**Comment by zerocrates** [comment]
I do still think this is premature, but we can try to make some decisions about things like platform now or soon, I suppose.

**Comment by patrickmj** [comment]
Is the concern about knowing that things will change by the time we get to a non-alpha release? If so, I'd say that points us to some versioning of the documentation, marked by the release it applies to, and should be part of considering the platform.

**Comment by zerocrates** [comment]
It's not so much that there will be change, which is definitely true, but yes any platform we choose *has* to be able to deal with versioning. My concern is more that dev documentation this early is basically wasted effort if it changes, since nobody will be around to read it.

**Comment by patrickmj** [comment]
I see two possible audiences for documentation at this stage:

1. The people who look at it early. As we get ready to do another announcement of a release, some documentation about how to build off it will also be helpful for explaining the guts of it. Since we're doing a release end of this period, I'm not sure we need docs that quickly, but after the next two, I think it'd be a helpful companion.

2. Us (well, mostly me, but really us). I'm keeping a running list of things to remember to do, how to do them, and patterns to follow for modules, surprises I encounter, CSS goodness, etc. (For example, the style stuff for config page and sidebars Kim and I addressed for MetadataBrowse). Getting that knowledge in a common place sounds like a good reference point for our own development.

This could be summed up as 'eating our own documentation dogfood'. :dog2:

**Comment by zerocrates** [comment]
we need a date for this

**Comment by patrickmj** [comment]
I hear Angelina Jolie is newly available. I'll ask her.

**Comment by patrickmj** [comment]
@zerocrates @jimsafley @kimisgold @kalbers @mebrett Does Monday Oct. 3  afternoon, 1ish, work to talk about dev documentation and come to some conclusions?

**Comment by kimisgold** [comment]
Works for me.

**Comment by zerocrates** [comment]
👍

**Comment by zerocrates** [comment]
Calling this closed for the "decision" component.
