### ISSUE TITLE
Do we need to allow modules to add admin only views?

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#394]
To my understanding, only the views-admin directory gets the "only loaded on the admin" treatment. Should we be handling this in config so plugins can have an admin-only views directory too?

**Comment by patrickmj** [comment]
So...is there a different mechanism for a module to have an admin-only view?

**Comment by zerocrates** [comment]
There's no way to currently do that other than using an event to manually do it in the same way the core adds the views-admin folder.

**Comment by patrickmj** [comment]
I definitely think that modules need _some_ way to restrict access to some views and operations. If that's based on roles or views or whatever. Admin-only views seem to make the most sense, maintaining the public/admin dichotomy that's pretty well-entrenched.

**Comment by zerocrates** [comment]
So I've looked back over this and it does indeed appear that the solitary item that's actually changed by using the view-admin vs. view-shared directory is layout/layout.phtml. In other words the view switching could be replaced by instead just switching what the layout view is (a layout-admin.phtml for example).

Otherwise yes it does make it harder for views from the admin to be used in the public or vice-versa, but I'm not sure that's really particularly valuable.
