### ISSUE TITLE
Stub public theme: grey border stops partway down the page on longer pages

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#399]
Seen on Chrome.

Appears to be caused by or related to the `height: 100%` style on the `html` element.

**Comment by kimisgold** [comment]
Can you provide a screenshot?

**Comment by zerocrates** [comment]
![bleeding](https://cloud.githubusercontent.com/assets/298975/10291329/401bd866-6b77-11e5-8609-906643dd4c6c.png)
