### ISSUE TITLE
Provide file derivative options for item images attached to site pages

### ISSUE THREAD

**Issue by kimisgold** [omeka/omeka-s#406]
Right now, images for items attached to a site default to the square thumbnail. The site page editor should include a way to select a preferred filed derivative.

**Comment by zerocrates** [comment]
One that came up recently with Exhibit Builder: caption position

**Comment by jimsafley** [comment]
Attachment thumbnail type (and most other) configuration should be block-level, not attachment-level.

**Comment by jimsafley** [comment]
Blocked by #436, even though this feature is block-level
