### ISSUE TITLE
Scale tables down for mobile widths

### ISSUE THREAD

**Issue by kimisgold** [omeka/omeka-s#410]
What is the best way to view the tables used throughout Omeka's interface on a mobile device? <a href="http://exisweb.net/responsive-table-plugins-and-patterns">This list has a good summary of the various approaches and tools available for responsive tables.</a>

**Comment by kimisgold** [comment]
@sharonmleon, @sheilabrennan, @mebrett: For those testing the mobile tables, please provide feedback on this issue. You'll want to checkout the <a href="https://github.com/omeka/omeka-s/tree/mobile-tables">mobile-tables</a> branch and look at item, item sets, or media's browse views.

**Comment by mebrett** [comment]
The stacked layout (where each thing has all its info before you see the next thing) is amazing. Much easier to read on the small screens. 
It does look like it's doing something funky on the item/item set view, but that might be a different aspect of the layouts.

**Comment by kimisgold** [comment]
> It does look like it's doing something funky on the item/item set view, but that might be a different aspect of the layouts.

Could you clarify, possibly with a screenshot? What is the item/item set view and what is it doing?

**Comment by mebrett** [comment]
The screen is trying to share a media preview with the item information: 
![screen shot 2015-10-15 at 1 05 28 pm](https://cloud.githubusercontent.com/assets/2314070/10521623/e1606aa6-733e-11e5-8f99-04226b2f9579.png)

**Comment by kimisgold** [comment]
Ah, this is an issue specific to the tables on the 'browse' views, so sidebars and the 'show' view will be addressed as a separate task.

**Comment by mebrett** [comment]
Ok, thanks.

**Comment by alyssafahringer** [comment]
When looking at the browse view of vocabularies, the arrows next to properties are overlapping with the word
![screen shot 2015-10-15 at 13 29 12](https://cloud.githubusercontent.com/assets/8807816/10522016/d56a17a4-7340-11e5-8ac4-9e87bcdc2ee8.png)

**Comment by kimisgold** [comment]
@alyssafahringer It looks like the mobile-tables branch isn't currently checked out on the dev install. If the correct branch is checked out, inspecting the `<table>` should show `class="tablesaw"`.

**Comment by kimisgold** [comment]
For anyone who still wants to look at what the mobile tables look like, the dev install currently has the mobile-tables checked out. Some of the feedback I'm looking for includes the readability of the resource blocks (rows in the full view), UI elements I haven't accounted for outside of 'sorting' options, and thoughts on the markup required to make this work.

Regarding the markup, it basically requires <a href="https://github.com/omeka/omeka-s/blob/mobile-tables/application/view-admin/omeka/admin/item/browse.phtml#L23">a class and attribute on the table</a>, as well as <a href="https://github.com/omeka/omeka-s/blob/mobile-tables/application/view-admin/omeka/admin/item/browse.phtml#L28">mobile-specific table headings</a> so that the sorting links don't get duplicated for every resource block. I'm using the <a href="https://github.com/filamentgroup/tablesaw">tablesaw plugin</a>.

(@zerocrates, @jimsafley, @sheilabrennan, @sharonmleon, @patrickmj, @mebrett, @kalbers, @alyssafahringer)
