### ISSUE TITLE
Sites: plan set of basic blocks

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#419]
In particular, we're missing additional configurations of blocks with Item attachments, and ones that have side-by-side text and attachments.

**Comment by kalbers** [comment]
Minimum-keep what we have

Gallery
	-with lightbox? Make plugin? Make a configuration w/in gallery block?

Lightbox with gallery

File with text
	-left or right

Text only

Item embed pages
	-eg users want guided tour of items, but no additional narratives. Essentially prints the normal items/show but with customizable pagination

Navigation blocks?
	-eg, something like DPLA with their exhibits->portals to sections?

Can we have a block of a saved query? Possible solution for leveraging stuff like d3.

Other improvements

Multi-column?
	-can be done with css
	-possible configuration on all blocks

Want to be able to choose, link to file[size], file show page, item show page.

**Comment by zerocrates** [comment]
Kim's also pushed the idea of foregrounding a slider or carousel rather than a thumbnail gallery

**Comment by zerocrates** [comment]
Saved query blocks are totally possible, at a minimum with the "paste in a query string" strategy used by the browse preview block.

**Comment by zerocrates** [comment]
Not sure what item embed pages really means in the context of a block, since you're mentioning pagination and stuff like that

**Comment by kalbers** [comment]
@kimisgold Per the gallery layout-do you have thoughts on whether we should present an option for a slider and/or lightbox? Do you have any jquery plugins or the like in mind? This will likely impact what the html ultimately looks like...

**Comment by kalbers** [comment]
@kimisgold Possible slider: https://github.com/bqworks/slider-pro
