### ISSUE TITLE
Error when logging in

### ISSUE THREAD

**Issue by mebrett** [omeka/omeka-s#421]
On the latest commit, when someone logs in they get an error screen displaying the following message:

There was an error.

exception 'Zend\Mvc\Router\Exception\InvalidArgumentException' with message 'Missing parameter "controller"' in /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-mvc/src/Router/Http/Segment.php:298
Stack trace:
#0 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-mvc/src/Router/Http/Segment.php(409): Zend\Mvc\Router\Http\Segment->buildPath(Array, Array, false, false, Array)
#1 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-mvc/src/Router/Http/TreeRouteStack.php(330): Zend\Mvc\Router\Http\Segment->assemble(Array, Array)
#2 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-mvc/src/Router/Http/Part.php(210): Zend\Mvc\Router\Http\TreeRouteStack->assemble(Array, Array)
#3 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-mvc/src/Router/Http/TreeRouteStack.php(351): Zend\Mvc\Router\Http\Part->assemble(Array, Array)
#4 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-mvc/src/Controller/Plugin/Url.php(99): Zend\Mvc\Router\Http\TreeRouteStack->assemble(Array, Array)
#5 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-mvc/src/Controller/Plugin/Redirect.php(48): Zend\Mvc\Controller\Plugin\Url->fromRoute('admin/default', Array, Array, false)
#6 /websites/omekadev/home/www/omeka-s/application/src/Controller/LoginController.php(40): Zend\Mvc\Controller\Plugin\Redirect->toRoute('admin/default')
#7 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(82): Omeka\Controller\LoginController->loginAction()
#8 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#9 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#10 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#11 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(118): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#12 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-mvc/src/DispatchListener.php(93): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#13 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#14 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#15 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#16 /websites/omekadev/home/www/omeka-s/vendor/zendframework/zend-mvc/src/Application.php(314): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#17 /websites/omekadev/home/www/omeka-s/index.php(16): Zend\Mvc\Application->run()
#18 {main}

Note that the login is successful, but the only way to know that is to refresh the page or try to navigate to the install again.

**Comment by zerocrates** [comment]
What's the URL in the URL bar when you're seeing this error message?

**Comment by mebrett** [comment]
http://dev.omeka.org/omeka-s/login
