### ISSUE TITLE
Make advanced search form sticky

### ISSUE THREAD

**Issue by jimsafley** [omeka/omeka-s#428]
This is specifically for the site/edit item pool panel, which does not save a previously saved query after submission. Making the form "sticky" will solve this.

**Comment by zerocrates** [comment]
Omeka 2's advanced search form is "sticky" normally.

Handling this by passing the array of params to the code that renders the form

**Comment by jimsafley** [comment]
Fixed in 0e15c5de98275440fe7192d583853f461c89a906
