### ISSUE TITLE
Sites: Separate pages interface from site edit?

### ISSUE THREAD

**Issue by jimsafley** [omeka/omeka-s#434]
The "Pages" panel seems out of place in site edit. Adding and editing pages takes the user to another page so any changes to the "Item Pool", "Navigation", "User Permissions" panels are lost.

Instead, we could integrate some linkage to page browse on the site browse page, perhaps in a "Pages" column containing the page count, where the count is linked to the site's page browse. (We do something like this on the vocabulary browse page with class and property counts.) This may be insufficient exposure for something as important as page browse/add/edit, but I think the "Pages" panel should move from site edit.

**Comment by zerocrates** [comment]
I think this would be a step backward, that you'll get a lot of people going to "edit" the site and finding they have to back out and enter a different way to edit what they want. Obviously that's something you can document around but it strikes me as a negative anyway.
