### ISSUE TITLE
Sites: How do we determine a public home page?

### ISSUE THREAD

**Issue by jimsafley** [omeka/omeka-s#435]
Currently the default home page (e.g. `omeka-s/s/my-site`) redirects to the first site page added. Instead it should redirect to either a) whatever is linked first in navigation, or b) the first site page in navigation.

A disadvantage of a) is that the first link may go off-site (in the case of a URL link). A disadvantage of b) is that the first site page may not be the preferred home page.

**Comment by zerocrates** [comment]
I suppose we could also have an explicit selector for "homepage."

I definitely don't think, in any case, that we should allow external links to be the home page.
