### ISSUE TITLE
Move admin-only templates out of view-shared/common

### ISSUE THREAD

**Issue by jimsafley** [omeka/omeka-s#438]
Templates in `view-shared/common` should conceivably be used by public sites. The crossed-out templates don't seem to fit in the public context:

* advanced-search.phtml
* ~~form-element.phtml~~
* ~~item-set-selector.phtml~~
* linked-resources.phtml
* pagination.phtml
* ~~property-selector.phtml~~
* ~~resource-fields.phtml~~
* ~~resource-form-templates.phtml~~
* ~~resource-select-sidebar.phtml~~
* resource-values.phtml
* search-filters.phtml
* site-page-pagination.phtml
* sort-link.phtml

**Comment by zerocrates** [comment]
For some of these we might need to think about the possibility of a Contribution-type plugin and whether "hiding" these views could complicate that.
