### ISSUE TITLE
Browser cannot validate a required form control when hidden

### ISSUE THREAD

**Issue by jimsafley** [omeka/omeka-s#442]
For example, in the site edit page, remove the URL slug on the "Admin" panel, switch to another panel and save. You should see the following error in your browser's console: `An invalid form control with name='o:slug' is not focusable.` (This message may be particular to Google Chrome.)

We either need to disable the browser's native validation checks when we tab away from the panel, somehow detect a validation error before it attempt to focus on the control and handle it differently, or (most likely) remove the "required" attributes from the controls, instead depending on server-side validation.

See http://stackoverflow.com/questions/22148080/an-invalid-form-control-with-name-is-not-focusable

**Comment by zerocrates** [comment]
Yes, we have this on any form with the tabs that also uses any native validation (it's usually just the `required` attribute).

**Comment by zerocrates** [comment]
On the other hand we don't want to just disable the validation, it's there for a reason.
