### ISSUE TITLE
Add styles for invalid inputs

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#443]
We use the HTML5 form validation stuff in a few places, and it would probably be helpful to use its hook into CSS to provide at least some subtle styling in the case of invalid elements (this is the `:invalid` pseudoclass).

For that matter, we may want some kind of styling for `:required` elements too, whether it's the asterisk or something else. "required" is basically the only validation we're using right now, and it probably pays to make it somewhat obvious when stuff's being required.

**Comment by kimisgold** [comment]
Could you provide a use case for where I can find an element with  `:invalid`?

**Comment by zerocrates** [comment]
Trying to submit a form with a required field left blank is probably the easiest route

**Comment by zerocrates** [comment]
You should be able to style `:required` in the CSS directly without having to add the class with Javascript (doing it that way also causes problems with dynamically added content)

**Comment by kimisgold** [comment]
So I can only style `:required` inputs without using pseudo-selectors. If we want something nice like that asterisk I'm currently using, it can't be done without creating some kind of wrapper. I can simulate it using a background image, but that seems non-ideal.
