### ISSUE TITLE
Untranslatable strings in globals.js

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#444]
globals.js directly embeds a few strings that define things like title and aria-label attributes. Since our translation happens entirely in PHP, this makes those strings untranslatable

Examples include the "Search" text in the placeholder of the search bar, the "make public" and "make private" labels, and the "Expand" and "Collapse" labels.

**Comment by jimsafley** [comment]
For reference, here are the strings that need attention:

### global.js
\<p\>Something went wrong\</p\>
Make private
Make public
Expand
Collapse
You have unsaved changes.

### item-manage-item-sets.js
Undo remove item set

### resource-form.js
Close icon set
Open icon set
[Untitled]
Failed loading resource template from API

### resource-template-form.js
Undo remove property

### site-navigation.js
\<p\>There are no available pages.\</p\>

**Comment by zerocrates** [comment]
"You have unsaved changes" at least is basically worthless to translate: the browsers don't show the message anymore. Not sure if we can return true or false or whatever there instead.
