### ISSUE TITLE
Sites: views break if all pages are deleted, but still in the navigation

### ISSUE THREAD

**Issue by kimisgold** [omeka/omeka-s#447]
Fatal errors appear when, after adding pages to a navigation, the user deletes all pages from the site via the pages tab in the site edit form. The errors look like this:

```
Notice: Undefined offset: 35 in /omeka-s/application/src/Site/Navigation/Link/Page.php on line 60

Fatal error: Call to a member function id() on a non-object in /omeka-s/application/src/Site/Navigation/Link/Page.php on line 64
```

**Comment by zerocrates** [comment]
This appears to happen whenever a page that appears in the navigation gets deleted.

**Comment by jimsafley** [comment]
I see two options, both involve listening to the `ENTITY_REMOVE_POST` event after a page is deleted and finding the page node in the navigation array: remove the node altogether, including all child nodes;
or change the node to the "fallback" type, preserving the child nodes.

**Comment by jimsafley** [comment]
Actually, we have no way to declare a "fallback" link type. It only exists when we ask for an unknown type. So we'll need to change that (and hope there's little or no unforeseen consequences), or simply remove the node altogether.
