### ISSUE TITLE
Attach primary media to block attachments by default?

### ISSUE THREAD

**Issue by jimsafley** [omeka/omeka-s#450]
We don't currently attach a media to an attachment by default. Instead, users must attach the media themselves. Should we attach primary media to attachments by default?

I'll frame this another way: what does it mean when media *is not* attached to an attachment? Should we not render the media in the attachment sidebar, the block form, the public view? Do we fall back to the primary media? In any case, if a media is deleted or made private, we need to account for an attachment without attached media.

@zerocrates

**Comment by zerocrates** [comment]
What Exhibit Builder does is this: it automatically "attaches" the first file when you attach an item (i.e., the first file is preselected).

When there is no selected file for an attachment (either through deletion of the previously selected file or an upgrade from a previous version or whatever), the code falls back to returning the first file for the item, if it exists. That applies on both the front and back sides, so if an attachment didn't have a selected file it can "magically" get one through this fallback by simply saving the page.

**Comment by jimsafley** [comment]
Yes, primary media is default. Fixed in 04c5642f50b871e24b5307b7c8e384be9f89b4e5
