### ISSUE TITLE
Style/include item sets to public theme

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#453]
* Item sets show needs styling generally
* Item sets should be linked off of show pages for the sets an item is in
* Item set show should probably contain info/links for the items it contains, or directly contain a browse page, or something like that

**Comment by kimisgold** [comment]
For the `item-set/show` view, we're experimenting with combining it with the `item/browse` view. Now when you go to view an item set, it will show the item set metadata in a left column and an `item/browse` view filtered to items within the set on the right. 

We need some eyes on this, so whoever can look at it should check out the `public-item-set-show` branch to test. 

@mebrett @sheilabrennan @sharonmleon @jimsafley @kalbers @patrickmj

**Comment by jimsafley** [comment]
The layout makes sense to me. Ultimately will the item sets be limited to those configured in the site's item pool?

**Comment by zerocrates** [comment]
Obviously right now there's no limitation. It feels a little odd to me to have the Item Set selection from the Item Pool do double duty in some sense by also limiting the visible sets, but that's more of a gut feeling and people might actually assume that's how it works.

Part of the issue with limiting sets is that we'd have to go down the road of removing them from the listing of sets on an Item's show page if it belongs to sets that aren't in the pool, and then you still have the problem that an Item Set could appear as related metadata (we have the same problem for items, which is why they're not actually limited on the show page, i.e. the pool only affects browsing, not showing).

**Comment by mebrett** [comment]
Depending on how robust people make the metadata for their item sets, the width of the sidebar might be an issue, but hopefully no one is going to be writing paragraphs in Item Set descriptions. 

I like the "text fades to indicate more information" on the items display itself, although it's doing it for descriptions of a single line which actually makes them hard to read. (see http://dev.omeka.org/omeka-s/s/apples/item-set/1166 item Baker St. flat)

**Comment by patrickmj** [comment]
I'm a little more concerned than @mebrett about the possibility of long text in metadata like description -- I can see it as a real possibility if people use Item Sets as a key part of how they build and organize a site, in which case the information people want to give could get much more lengthy. I think that'd be a rare case, but possible. The idiom here seems to be that the Item Set information is subordinate to the list of items in it -- again, probably the usual case, but not always. Maybe that'd just be a matter of different theme designs when we get there.

Putting that quibble aside, I think this works very well, and addresses the most common complaints about O2's Collection pages.

**Comment by mebrett** [comment]
I think having multiple theme options - one with lots of space for ItemSet data and one like what is there now - makes sense.

**Comment by patrickmj** [comment]
Just to clarify, I wasn't thinking of different options within one theme, but when we get to building multiple themes have them handle the item sets page differently

**Comment by kimisgold** [comment]
I've adjusted the column ratios for this theme. Is it any better?

**Comment by sheilabrennan** [comment]
@kimisgold in some ways I like how the item-set description looks on the /show page better in the mobile format than I do in desktop. For the desktop (using Chrome for Windows 8, but looks the same in FFX for PC) version, there is a lot open white space to the left that the metadata column still looks squished. If different themes can handle this style differently, I can live with it.
![item-set-show-desktop](https://cloud.githubusercontent.com/assets/741484/11599888/621c145e-9a97-11e5-8b48-2a960ca391f1.jpg)
![item-set-show-mobile](https://cloud.githubusercontent.com/assets/741484/11599893/6461d456-9a97-11e5-9253-9fd2e0c6b9b2.jpg)

**Comment by kimisgold** [comment]
@sheilabrennan What is the desktop resolution for the first screencap? The max container width for the page is at 1120px, and I'm wondering if you have an oddly wide display.

**Comment by sheilabrennan** [comment]
I do have a wide screen, that is for sure. 1900x1080

**Comment by kimisgold** [comment]
@sheilabrennan: I've increased the maximum container width, so try looking at the item sets now.

**Comment by sheilabrennan** [comment]
You are gold! Looks much better on my giant and smaller re-sized screen. @kimisgold
