### ISSUE TITLE
Tables on browse pages invisible in FF

### ISSUE THREAD

**Issue by patrickmj** [omeka/omeka-s#473]
The tables on `items`, `item-sets`, `modules`, and probably others are invisible in FF 42.

Appears as expected in Chromium

**Comment by patrickmj** [comment]
Correction: the `<nav>` element appears to just be pushing everything way down the page

**Comment by zerocrates** [comment]
Confirmed on Win FF 42 (wasn't happening on an older version).

It looks like Firefox isn't letting us use the space taken up by the right padding on the body, while older FF and Chrome don't seem to care about that padding.

**Comment by zerocrates** [comment]
My guess is that this is a result of them fixing this bug https://bugzilla.mozilla.org/show_bug.cgi?id=478834

**Comment by zerocrates** [comment]
The basic change (to the CSS not the SASS) that looks like it's the best path and seems to fix Firefox without breaking anything else is this:

```diff
diff --git a/application/asset/css/style.css b/application/asset/css/style.css
index 60c2c4f..5abe82c 100755
--- a/application/asset/css/style.css
+++ b/application/asset/css/style.css
@@ -479,7 +479,7 @@ th {
     font-family: "Source Sans Pro", sans-serif;
     font-size: 16px;
     line-height: 24px;
-    padding: 0 1.04167%;
+    padding-left: 1.04167%;
   }

   /* @group ----- Tables ----- */
@@ -923,12 +923,12 @@ th {

   div[role="main"] > h1:first-of-type {
     background-color: #fff;
-    width: 79.58333%;
     font-size: 24px;
     position: fixed;
     padding: 0 30% 0 1.04167%;
     z-index: 3;
     top: 1.5em;
+    left: 20.83334%;
     height: 2em;
     right: 0;
     margin-bottom: 0;
@@ -981,7 +981,7 @@ th {
     position: absolute;
     top: 0;
     left: calc(18.75% + 1.04167%);
-    right: -1.04167%;
+    right: 0;
     bottom: 0;
     background: #fff;
   }
@@ -1193,7 +1193,7 @@ th {
   /* @end */
   /* @group ----- Wrappers ----- */
   div[role="main"] {
-    width: 81.25%;
+    width: 80.20833%;
     margin-left: 19.79167%;
     padding: 6em 1.04167% 1.5em;
     background-color: #fff;
@@ -2680,7 +2680,7 @@ th {
   }

   body.sidebar-open #content {
-    width: 56.25%;
+    width: 55.72916%;
   }

   .sidebar .meta-group {
```

Basically it just removes the body's right padding and alters the other containers sizes to account for it so they actually fit correctly.

**Comment by zerocrates** [comment]
I'm really not familiar with how Susy "should" work but the above looks correct to me.

@kimisgold: please look over and decide if you want to merge or handle this differently

**Comment by kimisgold** [comment]
The sass and susy look good to me. Go ahead and merge it.
