### ISSUE TITLE
Allow themers to override site page block markup 

### ISSUE THREAD

**Issue by kimisgold** [omeka/omeka-s#476]
Currently, the markup for site page blocks exist outside of the shared views folder, so themers are unable to override block markup. The 'item-list' block in particular could see many variations in use: users may want to show the item media name, link the item media to the item or media show, change the heading levels, etc.

**Comment by zerocrates** [comment]
The simplest solution here is almost certainly using partials at some level since they give us themeability for free.

Exhibit Builder mandates partials for its layouts. It may be worth considering doing that here, at least for the public rendering.
