### ISSUE TITLE
Sites: Style "file with text" site block

### ISSUE THREAD

**Issue by kimisgold** [omeka/omeka-s#480]
This is a subtask of #475. Files should be viewed using both 'left' and 'right' alignments, with all 3 image sizes: square thumbnail, medium, and large, and with both a single item and multiple items.

**Comment by mebrett** [comment]
The list of items associated with the text extends beyond the block, running down the page to the left or right of any blocks below it. (see image)
![screen shot 2015-12-16 at 2 28 09 pm](https://cloud.githubusercontent.com/assets/2314070/11851576/544c96b4-a401-11e5-8265-cb1575373d9b.png)

**Comment by kimisgold** [comment]
@mebrett Should now be fixed in f72e951, and the dev install is up-to-date. Hopefully all content is clearing properly and associated items and text are grouped as expected.

**Comment by mebrett** [comment]
That fixed it. Everything is clearing and grouping as expected.

**Comment by sheilabrennan** [comment]
this block is doing what I'm expecting, with different thumb sizes and bits of text.
