### ISSUE TITLE
Sites: Style "navigation" site block

### ISSUE THREAD

**Issue by kimisgold** [omeka/omeka-s#481]
This is a subtask of #475. The navigation block should present itself as a subnavigation on a site page, usually as a first block.

**Comment by kimisgold** [comment]
The navigation block is pretty straightforward, though it's only been styled with the use case of it being the first block on the page. If you can provide some logic for the placement of navigation lower on the page, it could be a useful consideration.

@sheilabrennan @mebrett @kalbers @sharonmleon

**Comment by sheilabrennan** [comment]
I can see a good case for placing a nav block at the bottom of page, particularly when pages are used for longer text and file blocks, in an exhibit, ie.

**Comment by zerocrates** [comment]
I think there's definitely some simple scenarios where it won't be first, like a landing page for the site that starts with a description and/or image and has the nav tree following.

**Comment by kalbers** [comment]
Isn't the point of it being a block that the users can place it where they want? Obviously themes will have to make some accounting for it, especially if they want it in the sidebar, but as far as top or bottom goes, that strikes me as a user defined decision.

**Comment by kimisgold** [comment]
It's a question of understanding expectations. For example, does it make sense for the navigation to go at the bottom right on top of the "previous/next page" navigation? If the navigation is to go in a sidebar, what does it mean for that navigation block to be in the middle of the page, i.e does it float left in the middle of content or should it always stay at the top?

I'm not opposed to accommodating different scenarios but I do want a good sense of the different ways people plan on using the navigation block before I style for those uses.

**Comment by kalbers** [comment]
It seems to me that the block styles should be limited to the content within the block itself, not the block in relation to the rest of the page; eg, we might provide a general style for the navigation list content, but not anything regarding it's position on the page.

**Comment by kimisgold** [comment]
There are so many ways the navigation block could be presented that I'm not sure regarding the best way to style the navigation content, especially when so many of the styling decisions do take into account the navigation's position on the page. Some examples:

![screen shot 2015-12-11 at 2 53 00 pm](https://cloud.githubusercontent.com/assets/606764/11754378/e7ea0286-a018-11e5-8a81-7d7c9714325a.png)

![screen shot 2015-12-11 at 2 55 23 pm](https://cloud.githubusercontent.com/assets/606764/11754356/b359d6e0-a018-11e5-8112-edf9959285e3.png)
![screen shot 2015-12-11 at 2 56 54 pm](https://cloud.githubusercontent.com/assets/606764/11754354/b359662e-a018-11e5-9128-76877db27a5e.png)
![screen shot 2015-12-11 at 2 58 20 pm](https://cloud.githubusercontent.com/assets/606764/11754357/b35ca5f0-a018-11e5-8612-4cd713d04b06.png)
![screen shot 2015-12-11 at 3 00 28 pm](https://cloud.githubusercontent.com/assets/606764/11754355/b35adb6c-a018-11e5-9952-2b1ebfde3b49.png)

So I'm asking:

* Should all of these cases be taken into account in the theming?
* If not, which versions do you believe will see the most use?
* If so, how many options should be built into the block? (Horizontal full-width, vertical full-height left, vertical floating right, etc.)

**Comment by kimisgold** [comment]
The approach to page subnavigation has split into two approaches: subnavigation as page content (the navigation block) and as a fixed element in the view. 

As a fixed element, the default theme has a horizontal subnav at the top of the page if the page has children. If the page is a child, it also has breadcrumbs above the title. When discussing the navigation block with @zerocrates, we agreed that themes shouldn't be held accountable for every possible layout configuration: the default theme shouldn't have to provide styles for navigation as a sidebar, a horizontal bar, floating box, etc. Multiple themes with different navigation presentation approaches should cover that.

The navigation block is currently a list of subpages that float left within the content, so that text wraps around it. Now that child page navigation is part of the view, we should maybe reconsider the contents of the navigation block to avoid redundancy. What would users want from navigation as page content? I was thinking that instead of returning subpage, the block should be a customizable list of links, both internal and external. It could be used to show "related pages" (examples: <a href="https://cloud.githubusercontent.com/assets/606764/11879066/2c660010-a4c7-11e5-9c9d-e22d20b5414e.png">1</a>, <a href="https://cloud.githubusercontent.com/assets/606764/11879065/2c6559c6-a4c7-11e5-94dd-4a9e125f0cf4.png">2</a>). So at the moment, I need some input on 1) use cases for the navigation block and 2) block options we need to include.

**Comment by mebrett** [comment]
Will there be any way in which the navigation block will override/take the place of the basic site navigation? If that top-level nav is pretty much always showing, I think that having the fellow child pages (or related pages) makes sense.

Thinking about use cases: if someone was using an S site for a class, each student might have a page? Or their own series of pages, with their name/information as the top page.

**Comment by kimisgold** [comment]
I don't believe so. Adding a navigation block on every page to take the place of the basic site navigation seems cumbersome, and the user would be better off choosing a different theme. The navigation block should be content that doesn't necessarily appear on every page, and also may appear in the middle of the page content.

**Comment by sheilabrennan** [comment]
In thinking about how users might be using this block, I do think that @kimisgold first option from above--a customizable list of links--could be useful. 

The way it works now, only pulling child pages, is much less useful if the theme will or can allow for those child pages to be shown.

**Comment by kimisgold** [comment]
Conclusions from navigation discussion:

* The 'navigation' block should be renamed, something along the lines of 'table of contents'.
* The block would show children of the current page with the number of levels defined by a 'depth' block option.
* The block would render as a full-width list.
* Inclusion of the block on the page would turn off the page's default single-level subnavigation to reduce redundancy.

**Comment by kimisgold** [comment]
The 'table of contents' block reflects the above requested changes. In particular, testers should look at the 'depth' option on the admin side, and that the correct page trees are being rendered on the public side. @mebrett @sheilabrennan

**Comment by mebrett** [comment]
If the depth is left null, it displays all levels (which makes sense to me). Putting in a number larger than the actual depth of page trees does not break it, and the page trees are being properly rendered, no matter how ridiculous I make them.

**Comment by sheilabrennan** [comment]
@kimisgold Everything worked for me, in that the correct number of levels displayed when I selected that number. And, I can see now how this can better represent the introduction to a larger piece since you can add an image and a summary to go along with your table of contents. 

This exercise does emphasize to me how fixing the navigation requires a lot of back and forth from the Pages section to the Settings->Navigation. Also, @mebrett one thing to note in the documentation is that the Navigation Labels are not the Page titles/names. I changed my page titles and then wondered why they weren't reflected in the navigation block, and it was because I also needed to change the label for each page in the Navigation section.
