### ISSUE TITLE
Sites: Style "browse preview" site block

### ISSUE THREAD

**Issue by kimisgold** [omeka/omeka-s#482]
This is a subtask of #475. The 'browse preview' site block should follow the presentation of items on a 'browse' view and link to a full browse view.

**Comment by kimisgold** [comment]
This block is ready for testing. Things to look out for:

* On the admin side, you can provide a heading for the browse preview as well as customize the link to the browsed items.

* On the public side, this block consists of the heading, the item list with thumbnail, item name, and short description, and a link to a full browse. Is there anything else it needs?

@sheilabrennan @mebrett @kalbers @sharonmleon

**Comment by sheilabrennan** [comment]
When adding an item list and adding an attachment,  I'm confused by the top button (in the Attachment right side bar) that says "Select Item" but then closes the Attachment sidebar and doesn't add the item. It appears as if the only way to attach, the Apply Changes button at the bottom of hte sidebar. Is that how it works now or is that a bug? I find that top Select Item button deceiving if it isn't helping me to add the item. 
![item-block-add](https://cloud.githubusercontent.com/assets/741484/11688400/665dd89c-9e5a-11e5-90ac-a7a64da8aae7.jpg)

**Comment by zerocrates** [comment]
This comment doesn't go with this issue

**Comment by sheilabrennan** [comment]
#475 ?

**Comment by kimisgold** [comment]
#475 and all its sub-issues are about public-facing styles. This question probably warrants its own issue or comments on #454.

**Comment by sheilabrennan** [comment]
@kimisgold Seems like all of the elements are here. 

My one comment is that the link to the view the other items in the set at the bottom of that block is not a heading and so the link gets a little lost on the page. 

Is it possible to give that a heading, maybe an h4, like the item titles listed above?

**Comment by kimisgold** [comment]
There should be an option to set a heading in the block.

**Comment by sheilabrennan** [comment]
I didn't see it in the block itself. In the theme?

![browse-preview](https://cloud.githubusercontent.com/assets/741484/12099989/0fd71344-b2fa-11e5-92d5-cd88bab1dd01.jpg)

**Comment by kimisgold** [comment]
The 'Preview Title' is the heading setting for the browse preview block, so I suspect I'm misunderstanding you somehow.

**Comment by kimisgold** [comment]
@sheilabrennan I've at least restyled the 'view all' link to be more visible. It should be updated on the dev install.

**Comment by sheilabrennan** [comment]
Thanks, I see it, and it is more visible with the box. 

Might be helpful for @mebrett or @sharonmleon to look on their monitors, http://dev.omeka.org/omeka-s/s/test5/page/SnoopyChild to see about the amount of contrast to make sure it's readable on different monitors.

**Comment by mebrett** [comment]
The box does make it more visible, and more obviously a button. There is enough contrast to be readable on both my laptop, external monitor, and phone screen.
