### ISSUE TITLE
Sites: Style "item list" site block

### ISSUE THREAD

**Issue by kimisgold** [omeka/omeka-s#483]
This is a subtask of #475. Currently, the understanding of how the "item list" block differs from the "file with text" is that the item list has no text wrapping and uses the full width of the content area.

**Comment by sheilabrennan** [comment]
This works as expected for me. 

The only thing we will want to note in the documentation is that the list is horizontal and not vertical.

**Comment by zerocrates** [comment]
I think the best course is probably picking a new name that doesn't contain the word "list."

**Comment by kimisgold** [comment]
How about "item showcase"?
