### ISSUE TITLE
Decide where on sites we want to trigger events

### ISSUE THREAD

**Issue by patrickmj** [omeka/omeka-s#490]
Thinking of the Sharing module, this comes down to what's shareable, but the more general question of triggering events is also there. Site pages? Page blocks? Individual items in the item list block? Other?

**Comment by patrickmj** [comment]
not sure how much we'll care about this, but Facebook API recommends putting their snippet right after the body tag https://developers.facebook.com/docs/javascript/quickstart/v2.5, and it doesn't look like we have a trigger that'll do that

**Comment by zerocrates** [comment]
So, "top" and "bottom" of every page are easy enough for us to do... anything else becomes a little problematic at least under our current system.

**Comment by patrickmj** [comment]
So far the FB code doesn't seem to care, so I'm not worried. Some other placement issues might come up, like whether 'bottom' means before or after navigation
