### ISSUE TITLE
Consider a link back to admin sites browse more prominently on site show page

### ISSUE THREAD

**Issue by patrickmj** [omeka/omeka-s#493]
I can get there if I expand the general settings, then click sites again, but that seems like an unnecessary click when I'm bouncing around managing sites.

**Comment by zerocrates** [comment]
While this issue explicitly mentioned "site show," I'm not sure that was the intent, versus having the "back to sites" link available *throughout* the admin interface for a site.

**Comment by kimisgold** [comment]
Okay, so how do we feel about the presentation of the "back to sites" that's currently on the show page? If it's good, I can apply it to the rest of the site admin views.

Alternatively, we could eliminate the extra click by keeping the global navigation open by default.
