### ISSUE TITLE
Sites: Not really clear what distinguishes "General" from "Settings"

### ISSUE THREAD

**Issue by patrickmj** [omeka/omeka-s#494]
It's clear when you know the code and db structures, but to a user I don't think it's clear. Maybe how the Site Settings Form works enforces the distinction at the interface level, but if they can be reconciled I think it'll make a lot more sense -- there's nothing about "General" or "Settings" that suggests a difference to me at the interface level.

It'd be super-nice to have a tab for "Module Settings" in what's now in "General" that modules could stuff into. The existing setting for restricting browsing makes as much sense to me under the "Navigation" tabs.

That'd mix up the forms in complicated ways, but if it isn't prohibitively complicated I think it's worth looking at.

**Comment by zerocrates** [comment]
Does the newly-split nature of the site admin form alleviate this to some degree?

Naming-wise "General" could become "Basic" now or something like that

**Comment by patrickmj** [comment]
I think so. putting in the name change from "General" to "Basic" (or even "Basic setup"? ) makes it more clear to me.

**Comment by zerocrates** [comment]
Go wtih "Site Info" for the name here
