### ISSUE TITLE
Test unsaved-changes branch

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#495]
We need to look at the "unsaved changes" warning across as many of the forms as we can find.

The branch is `unsaved-changes`

It should:
- Not warn if no changes are made
- Not warn if the form is actually submitted (through enter or clicking the button)
- Warn if there are changes and the user tries to leave the page any other way.

**Comment by kimisgold** [comment]
Scenarios where the warning doesn't fire when expected:

* `page/edit`: Marking blocks for deletion.
* `site/s/[site-name]/index` (general site settings)
  * making changes to text inputs in the 'item pool' tab
  * making any changes on the 'navigation' tab
* `[resource]/search`: making changes to text inputs

**Comment by zerocrates** [comment]
A clarification: the warning only applies to forms where data will be saved, so the search pages are intentionally excluded from its scope.

**Comment by mebrett** [comment]
Everything I could think to enter in a form was saved. The only thing that I did not get a warning was when I edited a site's navigation and then clicked away from the general options for that site.

**Comment by zerocrates** [comment]
Confirmed no-fire on:
* block (but not attachment) deletion
* item pool edits to "complex" fields (simpler ones like the item sets selection or the class do actually work)
* navigation

Not a bug:
* search forms
