### ISSUE TITLE
Sites: Adding new users to a site with existing users removes one of those users

### ISSUE THREAD

**Issue by kimisgold** [omeka/omeka-s#499]
When working in the site user permissions tab, I noticed odd behavior on saving. The site I was working with had a pool of existing users. I'd add a new user to the site and submit the form. On refresh and navigating back to the permissions tab, I'd see one of the previously existing users missing from the list. 

I also tested with adding multiple users to a list of existing users, and every time only one existing user disappears. Add any number of users to a site unassociated with any users saves all new users properly.

**Comment by zerocrates** [comment]
Confirmed.

**Comment by zerocrates** [comment]
This looks like it's an off-by-one error with the Javascript used for that form
