### ISSUE TITLE
Cannot add resource to block after search

### ISSUE THREAD

**Issue by mebrett** [omeka/omeka-s#500]
On branch master. 

If I page through the available resources, I can easily add a resource to the list. However, if I search for a resource, I can't get them to attach.

I search for something I know is there, it comes up in the search results, but when I click on the resource, instead of saying "apply changes" the button says "select resource". Clicking "select resource" just takes me back to my search results. 

![screen shot 2016-01-14 at 2 54 27 pm](https://cloud.githubusercontent.com/assets/2314070/12335803/fcaf2518-bace-11e5-80dd-c6bedeea8bae.png)

**Comment by zerocrates** [comment]
Is this happening for any block, or just that one?

**Comment by mebrett** [comment]
Also happens on File with Text
