### ISSUE TITLE
Resource forms: Sidebar resource selector search button submits the main form

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#502]
The search button is an `<input type="submit">` and its located within the form so clicking it submits the form.

The same problem doesn't appear to occur within the sites, probably because the sidebar is located outside the form there.

**Comment by kimisgold** [comment]
The current setup groups the sidebars within fieldsets as an easy way to ensure that they appear only when the fieldset/section is active. We would need to figure out a way for the navigation tabs to target sidebars outside the form alongside their respective fieldsets.

**Comment by zerocrates** [comment]
This button doesn't actually submit a form when it's pressed so we should be able to just make it a `<button type="button">`
