### ISSUE TITLE
Editing an item does not preserve the resource template's suggested class

### ISSUE THREAD

**Issue by jimsafley** [omeka/omeka-s#509]
Add a resource template, set a suggested class, and save. Add an item and switch to that resource template; the class automatically changes, as expected. Save the item and edit the same item and you'll see the class is now unset. This is a bug. The class should be preserved on subsequent edits of that item.

**Comment by zerocrates** [comment]
Can't reproduce.

**Comment by jimsafley** [comment]
My repo is up to date (origin/develop) with no modifications and no modules installed. I can reproduce with any variation of a resource template (with and without alternates/types).
