### ISSUE TITLE
Validation on site settings for a multi_checkbox

### ISSUE THREAD

**Issue by patrickmj** [omeka/omeka-s#515]
In the site settings page, a single checkbox is all good. But a multicheckbox won't allow nothing to be set.

So, this validates fine

![sharingok](https://cloud.githubusercontent.com/assets/153262/12868863/74f9361e-ccde-11e5-98a2-a93c089f0dcd.png)

But this fails validation

![nosharingforyou](https://cloud.githubusercontent.com/assets/153262/12868867/7fbb81c4-ccde-11e5-98f5-f9bcdb0e7b42.png)

Related to this on Sharing https://github.com/omeka-s-modules/Sharing/commit/88373bbd05249b9af618404ec52e94f39d209a7b

Default seems to be that data is required. That can be changed in the module, so question is what the default validation should do.

**Comment by zerocrates** [comment]
We don't really control the default validation here either, it's actually being specified by the Checkbox element (parent of the MultiCheckbox).

As a default it makes no sense, but that's how it just is for some reason. It's an [ancient](http://framework.zend.com/issues/browse/ZF2-571) bug that [never got fixed](https://github.com/zendframework/zf2/issues/2596).

**Comment by patrickmj** [comment]
shouldn't be a problem. thanks.
