### ISSUE TITLE
Job show page

### ISSUE THREAD

**Issue by jimsafley** [omeka/omeka-s#517]
Right now we're shoehorning all information about jobs into the job browse page. In an effort to make the relationship between an import (or other long-running process) and it's corresponding job more intuitive, we should provide a direct link to individual jobs. This page should contain all data provided in the show-details sidebar, and should probably just render the args data on page rather than via a link.

This way modules that run jobs can provide a direct link to the corresponding job for better troubleshooting and status updates.

**Comment by kalbers** [comment]
We don't seem to need the sidebar anymore if there's a show page, however, I do believe we let you stop the job from the sidebar while it's in progress. Do we want to keep the sidebar just for that, or should we find another place to stop the job; eg the home page, or next to the status on browse?

**Comment by jimsafley** [comment]
Any controls that affect a job should go on the show page.

**Comment by kalbers** [comment]
New branch up. Needs styles for the button to stop the job on the show.phtml page @kimisgold 

https://github.com/omeka/omeka-s/tree/jobs-show-page
