### ISSUE TITLE
Navigation (Question)

### ISSUE THREAD

**Issue by LaceyWilson** [omeka/omeka-s#532]
Will there be any way to have an option to decide where navigation will show? Currently it defaults as showing in the top navigation and on the parent page. This can cause the top navigation to stretch down to half the page (as was the case in my situation). Since pages are not visible currently unless they are in the navigation, I think users would find it helpful if they had these options for each page: show in top navigation, show on parent page, show in top navigation and parent page.
![screen shot 2016-02-24 at 10 34 24 am](https://cloud.githubusercontent.com/assets/16085891/13290680/c330e040-dae2-11e5-881b-9b562bb20b50.png)
![screen shot 2016-02-24 at 10 34 49 am](https://cloud.githubusercontent.com/assets/16085891/13290684/c552e7f6-dae2-11e5-98cd-b67d25941078.png)

**Comment by zerocrates** [comment]
A different workaround is now available to deal with this problem: you can now set the maximum number of levels to show up top for a site in the "Theme" section of the site edit.

Here, setting that to 2 should avoid the crazy-big dropdown.

**Comment by zerocrates** [comment]
I'm going to close this because we have what I think is an okay solution to the problem shown in the screenshot, even though we don't have the features suggested for pages.
