### ISSUE TITLE
Delete buttons on browse views but not on edit views

### ISSUE THREAD

**Issue by kimisgold** [omeka/omeka-s#541]
There are a number of sections where delete options appear on the browse view but not individual edit views:

* Vocabularies
* Users
* Media

Delete buttons should go on the edit views for consistency.

**Comment by zerocrates** [comment]
For anything we're currently letting you delete one at a time on its browse we should have the same option on the edit page, I think.

**Comment by kimisgold** [comment]
"User" is a fun one: should the delete button appear on ever "tab"?

**Comment by zerocrates** [comment]
Let's treat the user page part of this as part of #307.
