### ISSUE TITLE
Look into using the Form element factory builtin stuff

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#542]
We're doing a lot of form creation and injection stuff ourselves right now, and it results in some annoying overhead when making any form, as you have to get and inject the ServiceLocator to do so.

ZF has a factory for "elements" (and a Form/Fieldset is an "element") that purports to handle a lot of this for us. We might be able to cut down on the boilerplate as well as remove some of our custom code.

**Comment by jimsafley** [comment]
WIP in https://github.com/omeka/omeka-s/compare/form-enhancements
