### ISSUE TITLE
De-accentuate slug inputs for sites and pages

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#544]
Now that the slug inputs are optional, it would be nice if they were more obviously so. They don't have the asterisk anymore, but I think someone's natural tendency will be to fill it in anyway.

I've already moved things so the titles come first on the appropriate forms. What else can we do to make the slug input seem less important or mandatory?

**Comment by kimisgold** [comment]
It's hard to de-emphasize the slug field further when there are only two fields on the "add page" view. The title field also currently has an asterisk where the slug field does not. We could add a field comment to further explain that a slug will be generated if the text input is left empty, but that currently feels excessive.
