### ISSUE TITLE
Default theme: Public views need search functionality

### ISSUE THREAD

**Issue by kimisgold** [omeka/omeka-s#551]
The public views lack any means of searching through the site's items.

**Comment by kimisgold** [comment]
We have a simple search for items, but we also probably need an advanced search for items in the item pool, and site-wide search for things like pages and item sets.

**Comment by kimisgold** [comment]
Basic item search on public views is ready for review on branch `public-item-search`.

(@zerocrates, @mebrett)

**Comment by mebrett** [comment]
Search works accurately. I wasn't expecting the search criteria to display below the search box (`Property contains value(s) "John"`).
