### ISSUE TITLE
Modules need a reserved namespace prefix

### ISSUE THREAD

**Issue by jimsafley** [omeka/omeka-s#558]
To prevent namespace conflicts between native resource data and associated module data, we need to  reserve a namespace prefix for use only by modules. This means that when importing a vocabulary, any namespace prefix that begins with, say, "o-module-" should be rejected.

This will give modules a reserved namespace prefix *prefix* to unambiguously identify their data in JSON-LD, while not conflicting with other vocabulary namespaces. For example, for the Mapping module:

```jsonld
{
    "@context": {
        "mapping": "http://example.com/mapping-vocab/",
        "o-module-mapping": "http://schema.org/"
    },
    "mapping:latitude": [
         "39.36827914916014"
    ],
    "mapping:longitude": [
         "-105.809326171875"
    ],
    "o-module-mapping:geo": [
        {
            "@type": "o-module-mapping:GeoCoordinates",
            "o-module-mapping:latitude": "39.36827914916014",
            "o-module-mapping:longitude": "-105.809326171875"
        }
    ]
}
```

**Comment by patrickmj** [comment]
The FedoraConnector module optionally imports a couple vocabs right into Omeka S. It assumes that the vocab URI does the differentiating. Should this change in FedoraConnector? Or should it be more generally handled? It looks a little like a new datatype, but not sure?

**Comment by jimsafley** [comment]
If you can manage to integrate your module's data into Omeka's native data structures, that's preferable. So what you're doing is completely fine. This issue is for modules that need to store data differently but use the resource's JSON-LD for interchange. For instance, the Mapping module stores geographical data in a separate table and uses the item's JSON-LD to pass from server to client and back again.

**Comment by patrickmj** [comment]
ah, got it. thanks
