### ISSUE TITLE
Stop passing the service locator to events

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#568]
Pretty much all events we fire pass along the param `'services'` with the ServiceLocator. But, pretty much anywhere that has access to the SharedEventManager to actually attach to those events probably is either a) in a Module class, where you already have the service locator, or b) in something that's a Service itself (like our MvcListeners or ExceptionListener classes), so it can just factory-inject its dependencies.

Not doing this will cut down on the number of things that currently have to hold references to the ServiceLocator just for the purpose of firing an event.

See #554 
ping @jimsafley

**Comment by zerocrates** [comment]
In a nonexhaustive search of the codebase, I haven't actually found any listener that's actually using the `'services'` param.

**Comment by jimsafley** [comment]
Not to mention the amount of text we can take our of event docs. I'm all for getting rid of the services param.

**Comment by jimsafley** [comment]
Removed references to the service locator from [docs](https://github.com/omeka/omeka-s/wiki/Events-%28Server%29)
