### ISSUE TITLE
update-db-data yells about session stuff

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#580]
It's trying to save a session, and... it probably shouldn't.

**Comment by jimsafley** [comment]
Here's one fix:

https://gist.github.com/jimsafley/324b67047719fab34d53f01da890ff61

Though we'd like to figure out why it's even writing anything to the session in the first place. It's probably from another little piece which asks about the current user and that's what gets the auth trying to use a session.

**Comment by zerocrates** [comment]
The delegators change for view helpers may have fixed this (by making the ACL and therefore the current user a more lazy dependency).

@jimsafley can you confirm?

**Comment by jimsafley** [comment]
Confirmed
