### ISSUE TITLE
Media upload needs to return file size limit error

### ISSUE THREAD

**Issue by kimisgold** [omeka/omeka-s#586]
When uploading a file above PHP's size limit, the view flashes the vague and unhelpful "There was an error during validation". Omeka Classic shows the file size limit, and that should continue in S.

**Comment by zerocrates** [comment]
We can trivially show the limit, but having a more intelligent error message when you exceed post_max_size may be more difficult.

**Comment by zerocrates** [comment]
Needs more investigation as to how it fails now; could be deleting everything in existing resource when this error happens.

**Comment by zerocrates** [comment]
The current faliure mode _doesn't_ in fact delete everything: because the CSRF token goes missing when this happens, we treat it as an invalid submission and don't do anything.
