### ISSUE TITLE
Should ResourceSelect be EntitySelect?

### ISSUE THREAD

**Issue by patrickmj** [omeka/omeka-s#587]
The `ResourceSelect` class works great for my need in CSVImport to produce a select in the form for assigning an owner to all the items imported. :+1: 

However, `User`s are not strictly speaking `Resource`s, which makes that usage a little odd :-1: 

So, is it worth renaming that class to suggest it is appropriate for entities more generally, or is there something I'm missing that calls for it to be Resource-specific?

**Comment by zerocrates** [comment]
It's talking about resources in the API context (since it uses the API to do its thing).

Users are an API resource.

The naming conflict here is perennially annoying, though.

**Comment by patrickmj** [comment]
ah, wondered if there was naming ambiguity going on. I'll continue rocking on, then.

**Comment by zerocrates** [comment]
If somebody can come up with some synonym for API resource or Resource the entity, I'd love to remove the overloading of that term. The problem is that it's pretty much the standard term in both the RDF and REST/API worlds.

**Comment by patrickmj** [comment]
I suspect that any effort to clarify with a renaming will only muddy the waters more. Things like `ApiResource` or `RdfResource` seem at first glance to make sense, but I can easily see them producing more confusion, which would lead to further non-clarification like `OmekaApiResource`. Seems like a nuance that we'll just have to deal with, and know how to talk about.
