### ISSUE TITLE
View Log not clickable in FF

### ISSUE THREAD

**Issue by patrickmj** [omeka/omeka-s#593]
Latest pull (81d72) in FF happily fixes the alignment of the args for the job info, but View Log isn't clickable. Looks like an overlap with the footer in FF?

![noclickyonlog](https://cloud.githubusercontent.com/assets/153262/14497101/a8ed1e86-0163-11e6-9451-4065a5b5e08c.png)

**Comment by zerocrates** [comment]
Does that persist after a refresh/cache clear? I can't reproduce.

**Comment by patrickmj** [comment]
ah. nope, refreshing made it all good. my bad. nothing to see here.

**Comment by zerocrates** [comment]
OK, cool. Removing that overlap was one of the earlier fixes, so I guess you just had a cached version of the stylesheet.
