### ISSUE TITLE
Can't scroll horizontally to read error messages

### ISSUE THREAD

**Issue by patrickmj** [omeka/omeka-s#604]
An error message runs off to the right of the screen, but no horizontal scrollbar is there to let me scroll through to read all of it (at least not without copy-pasting it into something else). Both FF and Chromium

![noscrollforyou](https://cloud.githubusercontent.com/assets/153262/14612086/76b176d4-0563-11e6-8d45-d990e138a6ba.png)

**Comment by zerocrates** [comment]
Where is this happening? Frontend, backend, etc.

It's just a theme issue.

**Comment by patrickmj** [comment]
backend
