### ISSUE TITLE
The API representation of item_sets don’t provide the list of items ?

### ISSUE THREAD

**Issue by jeau** [omeka/omeka-s#615]
The Omeka-s API provides a representation of item_sets without the list of items it contains or link to the list of these items (that gives Omeka API to represent collections)

**Comment by zerocrates** [comment]
Due to scaling concerns we don't want to include the items themselves in this response, as that would hugely increase its size.

We should probably link to the contained items, though. That would be just the `/items` API resource with an appropriate `?item_set_id=` appended.

**Comment by jeau** [comment]
I agree with you.
This is the solution that was chosen for Omeka classic for collections, it seems.
