### ISSUE TITLE
Doctrine proxies are not generated for entities in Omeka S modules

### ISSUE THREAD

**Issue by jajm** [omeka/omeka-s#619]
The `data/doctrine-proxies` directory contains Doctrine proxies for all Omeka S entities, but it is not updated when modules are installed/enabled.
It means that when a module declare two entities with a relation between them, and we try to load one entity, Doctrine will fail to open the proxy file for the other entity.
This can be fixed by running `vendor/bin/doctrine orm:generate-proxies` but I think this should be automated.
I tried adding this code to Module::install

```php
$em = $serviceLocator->get('Omeka\EntityManager');
$metadatas = $em->getMetadataFactory()->getAllMetadata();
$destPath = $em->getConfiguration()->getProxyDir();
$destPath = realpath($destPath);
$em->getProxyFactory()->generateProxyClasses($metadatas, $destPath);
```

but it generates proxies for all modules except this one.

**Comment by zerocrates** [comment]
We've known about this for a while, we've just managed to not run into any scenarios where the module proxies were needed yet.

I'd really prefer not to have to have the proxy dir be writable, and not to turn on Doctrine's autogeneration either. We had some early ideas of how to let the modules ship their own pregenerated proxies as the core does (basically by using/abusing Doctrine's support for autoloading the proxies), and we'll just have to really look into it now that it's a concrete problem for someone.

**Comment by jajm** [comment]
If it helps, the module for which I need that is https://github.com/biblibre/omeka-s-module-Search (https://github.com/biblibre/omeka-s-module-Solr is also needed to trigger the error)

**Comment by zerocrates** [comment]
Thanks, that could be helpful

**Comment by zerocrates** [comment]
I'm not totally sure what I need to do to trigger the error between your modules (plus, I don't have Solr or the extension installed).

I do have a WIP branch of my solution to this problem up: the branch name is proxy-autoloading. Basically, it adds an extra config key: `[entity_manager][proxy_paths]`. You put that in your config, pointing it to a folder in your module that holds the proxies for that module's entities.

Right now there's no tooling backing this up, so you have to do the regular proxy generation process and then move the files for your module into its proxies folder. But, having done that you can just check them in and ship them with the plugin, and users shouldn't have to do anything to have it work.

Try it out and let me know what you think.

**Comment by jajm** [comment]
As you said, it would be great to have a more automatic way of generating proxies for modules. But the important thing is that module's users don't have to login to the server after installing it.
I just tested your WIP branch and it works well.
But I looked quickly at the code and I worry about this particular line:
```php
$emConfig->setAutoGenerateProxyClasses(-1);
```
`-1` seems to be an invalid (or undocumented at least) value for this attribute. Won't that be a problem ?

**Comment by zerocrates** [comment]
There's the hacky part, for sure. I have an issue open on Doctrine asking for an explicit way to do this (remove the explicit `require` calls and instead rely on autoloading) but I wouldn't hold my breath. I've checked pretty thoroughly and this doesn't cause any problems _now_, but of course the main concern is that they make changes that will break the hack in the future.

If push comes to shove we can fork the relevant Doctrine component to allow what we want, but I'd hope to avoid that.

I'll at least mark this more clearly as a hack.

**Comment by zerocrates** [comment]
I'm going to move forward with this solution, but with an eye out for potential problems (or better options).

We'll have to tackle the issue of making it easier for the modules to actually generate the files, too. My recollection is that the ProxyGenerator has some built-in functionality for filtering which proxies get generated, so that should hopefully not be too much of an issue.
