### ISSUE TITLE
Media not attaching on site page blocks

### ISSUE THREAD

**Issue by mebrett** [omeka/omeka-s#625]
On branch develop, up to date.

When I go to add attachments to either Media or Item with Metadata blocks, I can go through the steps (select an item, select media and/or add caption) but it doesn't stick - the media does not actually attach. If I save and either go back to editing or go to view the item, there's nothing there.

I'm using the shared install, if you want to try it for yourself.

**Comment by zerocrates** [comment]
Dupe of #623, I think

**Comment by mebrett** [comment]
Yup. Sorry.
