### ISSUE TITLE
Look into allowing URL generation in JS

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#648]
Currently to make any URLs we need to use a url() helper, even if we're just dealing with a static string.

We could get the installation base path once and set that to the JS, so we could then just use a js function to create valid URLs from strings.

This would simplify a few use cases, in particular in forms where we want to have an attribute that represents the path to an API endpoint or some AJAX action to load from. On the other hand, it would require using strings instead of using the routing system like we normally do for URLs, so it may not be worth it to create another different way to do URLs.

**Comment by patrickmj** [comment]
I'd be fully in favor of a consistent pattern in JS for url construction. Modules need this a lot, and in that context I usually don't much care about the routing system vs strings. Right now I'm doing ad-hoc injecting a base url into the javascript, then building up the rest of the url from there as needed, which seems non-pretty at best.

**Comment by zerocrates** [comment]
It's possible to do this without JS and with the `base` element instead, but I'd rather not deal with the undesirable side effects for thinks like anchor links.

**Comment by zerocrates** [comment]
We've kicked the can down the road on this one for more than long enough.

Barring a compelling use case this is a wontfix.
