### ISSUE TITLE
Link label translations applied on public side, not on admin

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#649]
Zend\Navigation's helpers automatically translate link labels, but we control what's given to jsTree for the admin interface and we aren't translating there. This is sometimes masked because we set the initial label when creating a new link to the text from the dropdown, which _is_ translated.

**Comment by jimsafley** [comment]
@zerocrates  How do I get `// @translate` to work?

**Comment by zerocrates** [comment]
`@translate` only marks the string to be picked up and added to the translation template. That's working fine here. It depends on there being some indirect call to the actual translator somewhere (it's just that that somewhere is not right where the literal string is defined).

The labels just need to be getting passed through the translator somewhere on the admin. It can (and should) be just one call that's in some generic place that gets it called for every nav link, though.
