### ISSUE TITLE
Translate non-view strings

### ISSUE THREAD

**Issue by jimsafley** [omeka/omeka-s#655]
Outside of views, most translatable strings get passed into:

- `Omeka\Mvc\Controller\Plugin\Messenger::add()`
- `Omeka\Stdlib\ErrorStore::addError()`
- `Exception\*::__construct()`

We could compose the messenger plugin and error store using factories and inject the translator that way. I'm not sure the best way to translate exception messages.

**Comment by jimsafley** [comment]
Change messenger so it can take variables in last argument. Add translation for messenger at the time it prints. Take away all message translation calls in controllers.

Do not translate within the error store. Rather it needs a way to store template variables alongside their strings. Hold off on this one. Maybe have a message object to store the message and the template variables.

We could extend base `Exception` overwriting `__toString()` to return a translated string. But hold off on this for now.

**Comment by jimsafley** [comment]
Possibly not worth the effort, but here's how we'd bundle a message and it's args into one object and make the translator service act accordingly: https://gist.github.com/jimsafley/f255249a4a7dbdbf67cf1c7b626dabe7

**Comment by jimsafley** [comment]
@zerocrates Where do we stand on this? We still need some strategy to translate ErrorStore and Exception messages (JS strings are covered in #444).

**Comment by zerocrates** [comment]
So we only really have two possible strategies for pretty much any translation: direct and indirect.

For ErrorStore we basically control the whole thing, so indirect wouldn't be terribly difficult I think, though it'd require using either a pattern or an object like we've talked about before to include the args alongside the message template.

The same _sort of_ applies for Exceptions with the difference that we're somewhat constrained by the actual underlying internals of Exceptions. Relevantly, that the message has to be a string (so we can't just cram in some "message with args" object there). We _could_ have all our exceptions derive from a base exception we write that provides for storage for interpolated args, but that causes some issues if we're actually using the base exception types anywhere.
