### ISSUE TITLE
Remove usages of getServiceLocator from controllers

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#666]
See also #554, these don't implement that interface but the usages of the method are also deprecated.

**Comment by jimsafley** [comment]
@zerocrates I looked through all the controllers and have some ideas about how to remove the service locator dependencies. I still need to address the dependencies in the existing controller plugins, but I'm saving that for later. How does this approach look to you?

### Controller Factories

Some controllers use services that aren't (or shouldn't be) widely used. Create factories for the following controllers, injecting the listed dependencies:

- Admin/ModuleController.php
  - Omeka\ModuleManager
  - ViewRenderer
- Admin/UserController.php
  - Omeka\EntityManager
- LoginController.php
  - Omeka\EntityManager
  - Omeka\AuthenticationService
- Admin/JobController.php
  - Omeka\JobDispatcher
- Admin/SystemInfoController.php
  - Omeka\Connection
- Admin/VocabularyController.php
  - Omeka\RdfImporter
- ApiController.php
  - Omeka\Paginator
  - Omeka\Logger
- InstallController.php
  - Omeka\Installer
- MigrateController.php
  - Omeka\MigrationManager

### Controller Plugins

Some services are (or could be) widely used by controllers. Create the following controller plugins (currently used by the listed controllers)

- UserIsAllowed; Omeka\Acl; like the view helper
  - Admin/UserController.php
- Settings; Omeka\Settings; like the view helper
  - IndexController.php
  - MigrateController.php
- Status; Omeka\Status
  - InstallController.php
  - MigrateController.php
- SiteSettings; Omeka\SiteSettings
  - Site/ItemController.php
  - SiteAdmin/IndexController.php
- ViewHelperManager; ViewHelperManager
  - Site/PageController.php
  - SiteAdmin/PageController.php

**Comment by jimsafley** [comment]
### Controller Plugin Factories

Create factories for existing controller plugins, injecting the listed dependencies: 

- Api
  - Omeka\ApiManager
- Paginator
  - ViewHelperManager
- Translate
  - MvcTranslator
