### ISSUE TITLE
Consider combining the "value" and "property" advanced search options

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#668]
We currently have two very similar rows on our search: one that gives you a dropdown of search types and lets you search all values of a resource, and another that has the same options, but additionally lets you pick a specific property to search on.

We could add an "[All Properties]" choice to the property drop-down and thereby combine those two query types into one. This would allow us to consolidate both the api-side query code and the UI for searching, turning "Search all properties" and "Search specific property" into a single "Search by value".

We could also probably combine the "Search resources" into this as well by adding additional match types. This would basically turn the input here into the same thing as the old "advanced" input from Classic.

**Comment by mebrett** [comment]
Adding the All Properties option and making it default makes sense to me

**Comment by zerocrates** [comment]
People can look at the "merge-value-search" branch to see how this would work.

In addition to removing that section of the search UI, it removes a pretty significant amount of code.
