### ISSUE TITLE
We need "URL" advanced search options

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#671]
The reorganization of the values means that the default searches will only search against URL value labels, not the urls themselves.

There are search types already for internal resources by ID. We just need to add them for URL as well.

**Comment by zerocrates** [comment]
There's a "question" component to this issue: how do we want to handle URLs in the search?

The two main options are:
- Add query types specifically for looking for URLs. This is the easiest option: it's directly analogous to what we've already got for the search. You'd have to explicitly choose to do this kind of search.
- Change the existing text-based queries to search on both the text and URL fields simultaneously. This isn't really significantly more difficult, but does involve making changes to the existing search implementation. In this alternative, you don't explicitly choose to do a URL or text search; instead all searches look for results in both value text and value URLs.

The first alternative is likely somewhat more performant as it only works on a single column, but this may not be particularly significant. The second would return behavior to what it was before we made our recent changes that moved where URLs were stored.

**Comment by sharonmleon** [comment]
I'm tempted to suggest that we go with the simplest option for the user, which seems to be the second one. But, I'm interested in whether others can think of a scenario where users would specifically want to search for URLs and not text.

**Comment by patrickmj** [comment]
Hard to tell...if a user is used to thinking about the distinction, however it is visually presented, I can see them wanting to make the distinction. They'd be the minority, I suspect, but would appreciate the distinction, much like people who appreciate booleans in searches, or using Classic's advanced search as opposed to the simple search.
