### ISSUE TITLE
Use interoperable typehints where appropriate

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#677]
Some Zend components specifically implement more generic interfaces, but in many cases we're hinting and writing against the Zend-specific interface.

One place in particular I'm thinking of is the logger: there's a log PSR and Zend has support for it, writing our code to depend only on that interface will make it possible to have basically drop-in support for other loggers if we or somebody ever wants to switch.

The ServiceManager interfaces also now extend an interoperable Container interface, but part of that is a change that's really more fleshed out in ZF3 so it may be something better handled there.

In general, where Zend's providing us tools to reduce direct coupling to their implementation, it's a good idea to use them.

**Comment by jimsafley** [comment]
Is there a way we could make these changes without perusing the entire codebase -- some sort of automated typehint detection?

**Comment by jimsafley** [comment]
One caveat: Zend's `FactoryInterface::createService()` typehints on ServiceLocatorInterface, so our service factories won't be able to use `Interop\Container\ContainerInterface` out of the box.

**Comment by jimsafley** [comment]
```
$ find . -type f -print0 | xargs -0 sed -i 's/use Zend\\ServiceManager\\ServiceLocatorInterface;/use Interop\\Container\\ContainerInterface;/g'
$ find . -type f -print0 | xargs -0 sed -i 's/ServiceLocatorInterface/ContainerInterface/g'
```

**Comment by zerocrates** [comment]
They don't switch to using the interop Container hint until the zf3 version, I think. They're _compatible_ with both in a fashion in the version we have, but it's a little odd.
