### ISSUE TITLE
Figure out language input guidance

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#681]
The language field is just a free-text input. Minimally we want some kind of validation to stop people from writing in "English" when we're taking BCP 47 codes.

**Comment by jimsafley** [comment]
One course we can take is the use of client-side regex to match against whatever the user inputs into that field. A visual cue indicating a poorly-formed tag would, I think, greatly reduce the use of illegal tags. We could supplement this with a feature that autosuggests a popular subset of tags. All of this would be on the client-side.

Should we prevent form submission when there are poorly-formed language tags on the page? Should we perform similar validation server-side? If we don't, resources added by the API would not be held to the same scrutiny (which I don't think is a bad thing, tbh).

**Comment by jimsafley** [comment]
It's worth noting that "English" is a valid language tag when matched against the [most inclusive regular expression I could find](http://stackoverflow.com/a/7036171). If we're not going to have strict validation for tags, I could match the code against a less inclusive pattern, like the [ones found here](http://stackoverflow.com/questions/3962543/how-can-i-validate-a-culture-code-with-a-regular-expression).
