### ISSUE TITLE
Form elements that are named by array do not stick when the form does not validate

### ISSUE THREAD

**Issue by jimsafley** [omeka/omeka-s#685]
To reproduce this, go to the "Add Item" page and set a "Resource Template" and an "Upload" media, but do not choose a file. The form correctly invalidates as "File was not uploaded" but the resource template element was lost during the reload.

I think ZF2's Form component doesn't recognize that the POST's

```
[
  'o:resource_template' => [
    'o:id' => {value}
  ]
]
```

is the same as `name="o:resource_template[o:id]"` and doesn't set the value. This also may prevent validations and filters from working.

**Comment by zerocrates** [comment]
That's not super surprising... I think the only way to get it to do multiple levels like that is to use Fieldsets (that's just off the top of my head and could be wrong though)

**Comment by zerocrates** [comment]
The other ways around it are: make "flattened" element names and alter the structure into what the API needs in the controller, or alter the API to accept a scalar in place of a single-element array (we've done this _somewhere_ but I don't remember where).

**Comment by zerocrates** [comment]
Maybe also investigate the hydration/extraction functionality built into Zend\Form, it may offer a nicer way to do this.

**Comment by jimsafley** [comment]
Moving this to #802
