### ISSUE TITLE
Consider an abstract ControllerFactory class that standardizes injecting services

### ISSUE THREAD

**Issue by patrickmj** [omeka/omeka-s#692]
In updating various modules, I'm finding some repetitions that might suggest an abstraction for injecting services. I've ended up with a lot of constructors that have a param for each service the Controller needs.

It might make sense to have an abstraction with a `setServices(array $services)` (or something like it) that has a `serviceName => service` array that could be called from a ControllerFactory, just to standardize the practice and make it easier to anticipate what's happening. The abstract factory would set properties based on the key=>value.

I see this as similar to how Omeka 2 hooks have just one array of `args` to look through.

The most common services should probably get their own plugins, like for Logger and JobDispatcher. For additional ones, like CSV using `Omeka\MediaIngesterManager`, I think it'll be easier to understand what the module is doing if additional services come in one array.

Seems like this would also call for the plugins being updated to deal with duplication, where the plugin adds a service, and the suggested `setServices` function adds the same. Not sure how weird that could get.

UPDATE: 
Might be that I'm really talking about something on the Controller class

**Comment by zerocrates** [comment]
Agreed on the commonly-used services getting plugins.

Not so sure on what setting them by array really brings to the table, though.

**Comment by patrickmj** [comment]
Just brings predictability to the table. Instead of chasing through the signatures of the various construct functions, which could vary widely and haphazardly, one place to stuff in the services injected could lead to easier inspection. It'd be a standardization of knowing where to look for what's going on.

**Comment by zerocrates** [comment]
Feel free to elaborate on the benefits you're thinking of with that approach, but I'm not in favor of it as of now.

The constructors for the controllers should pretty much all be the same: just passing and setting services. On the off-chance the constructor's doing something else you could always look at the factory side instead. Switching to an array I think would actually make things worse: with a constructor you can typehint the arguments so the dependencies will appear as `use` statements and will be guaranteed by the runtime to be of the expected type, and you lose that if you just pass an array.
