### ISSUE TITLE
Only certain roles can create site pages

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#698]
Lower-level users require the "editor" or higher permission on a site to work on the pages, but their role is currently relevant for deciding even with that permission if they're allowed to create pages rather than just edit them.

If we want such a distinction, it should be a different site-specific permission level, not an interaction between those levels and the global roles.

**Comment by jimsafley** [comment]
Is one possibility to allow all privileges to all site resources to all roles, but perform parallel permission checks based on site role and ownership assertions?

**Comment by zerocrates** [comment]
That's pretty much how the permissions are already granted for everything in Sites *except* creating new pages.
