### ISSUE TITLE
Delete legacy GitHub issues

### ISSUE THREAD

**Issue by jimsafley** [omeka/omeka-s#70]
The issues were created before our move to JIRA. There is no value in retaining them. They are obsolete, inaccurate, and clutter up the closed issues filter. It is currently [not possible to delete issues](https://github.com/isaacs/github/issues/253), but we can a) remove all content from them, or b) delete and re-make the repository from a clone.

**Comment by jimsafley** [comment]
Here's a demonstration of how we can delete legacy issues: the [omeka-s- repository](https://github.com/omeka/omeka-s-). Note the issues are gone and I've retained the wiki. We do lose the 12 stars, 3 forks, and traffic metrics, but those shouldn't matter at this pre-alpha stage.

**Comment by zerocrates** [comment]
My preference is for us to just leave the old dumb issues there as they are and move on.
