### ISSUE TITLE
Migrate view layout broken by "minimal" change

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#700]
The migrate page was one of the few using the minimal layout, and now when you go to migrate, you see a "logged out" version of the regular admin layout.

Something in the routing must be causing us to treat migrate as an "admin" route so we're loading the wrong layout.

**Comment by jimsafley** [comment]
In `MigrateController:indexAction()` I get the following matched route:

```

Zend\Mvc\Router\Http\RouteMatch Object
(
    [length:protected] => 8
    [params:protected] => Array
        (
            [controller] => Omeka\Controller\Migrate
            [action] => index
        )

    [matchedRouteName:protected] => migrate
)
```

Nothing seems out of place here. It's identical to the maintenance one, which loads the correct layout. Even after moving the view from `/view-admin/omeka/migrate` to `/view-shared/omeka/migrate` it doesn't work. I'm stumped.
