### ISSUE TITLE
Clicking on link to number of items in a site's pool loses context

### ISSUE THREAD

**Issue by patrickmj** [omeka/omeka-s#704]
On a site's item pool page, we have a handy link to all the items in that site's pool, like

```
 There are currently 3974 items in this site’s pool.
```

with a link on the number.

Clicking that goes to an items browse page, filtered by site id: `/item?site_id=1`

But from that page I lose all the site context, like being able to click to the public page or click back directly to the site's edit page. I'd like to not lose that context to click to relevant site info.

**Comment by zerocrates** [comment]
I think of the list of results there as an Item browse page like any other, such that it wouldn't be appropriate to have it exist "under" the Site's admin section.

I'm open to arguments to the contrary. We could also have that link open in a new tab/window as a different kind of solution.

**Comment by patrickmj** [comment]
Agreed that 'under' Site's admin section isn't best solution. The dissonance comes when I'm starting with a site, and to get to know it I click on the link from the item count. Then, I don't have an easy way back to what I was interested in -- I basically have to start again from sites browse. 

Since the site id is already in the URL, that sorta gives me the context if I know how to read the URL. Maybe something analogous to how classic reads search params and exposes them. Just something that more prominently signals 'these are filtered by site X' And then find a place for a link back to site X edit, and site X public view.
