### ISSUE TITLE
Decide on beta-priority issues

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#722]

**Comment by jimsafley** [comment]
Beta-priority issues:

#177
#307
#336
#393
#394
#438
#444
#445
#472
#490
#516
#550
#580
#615
#647
#648
#655 
#663
#669
#679
#681
#719
#720
#721
#722

**Comment by zerocrates** [comment]
See https://github.com/omeka/omeka-s/labels/beta
