### ISSUE TITLE
Child page nav hiding under main nav on public view of parent page

### ISSUE THREAD

**Issue by mebrett** [omeka/omeka-s#723]
This seems to be a new issue since the change to Page Title being a block, but the issue persists whether or not the block is present. 

On parent-level pages, the sub-nav options for child pages are displaying half under the main nav (see images):

![screen shot 2016-08-29 at 2 34 35 pm](https://cloud.githubusercontent.com/assets/2314070/18062802/5a95d066-6df6-11e6-9bf4-fb0761bd315e.png)

![screen shot 2016-08-29 at 2 34 59 pm](https://cloud.githubusercontent.com/assets/2314070/18062803/5b9d8292-6df6-11e6-9c9b-58498b1bc21f.png)

**Comment by kimisgold** [comment]
Fixed in https://github.com/omeka-s-themes/default/commit/c7a02f4a435ce52e942e6c9ef808130dd05838d4. The themes are now in their own separate repositories, so we can start filing default theme issues in https://github.com/omeka-s-themes/default/.
