### ISSUE TITLE
Site assertions should derive site entity from more ACL resources

### ISSUE THREAD

**Issue by jimsafley** [omeka/omeka-s#730]
The `HasSitePermissionAssertion` and `SiteIsPublicAssertion` ACL assertions derive the `Site` entity from the passed ACL resource, but it only does this for the `SitePage` entity. There should be a way instruct the assertions how to derive the `Site` entity from other site-related entities—either by the use of an event (more flexible) or by a `getSite()` convention on related entities (easier).

**Comment by zerocrates** [comment]
I'm fine with the duck-typed `getSite` approach.
