### ISSUE TITLE
Attention to permissions

### ISSUE THREAD

**Issue by jimsafley** [omeka/omeka-s#732]
Now that we have a better handle of things, it's time we give more attention to permissions. A couple of things immediately stick out: it's strange to me that editors and reviewers can't see private items; ~~reviewers can see the add/edit resource template pages but don't have permission to actually add/edit.~~

**Comment by jimsafley** [comment]
One important feature of the Collecting module is item review, where, essentially, a user bulk-edits the visibility of private items. The way permissions are set up currently, the only roles that can do this are global and site admins, since they are the only roles that can view or edit private items. The module would work better if some lower roles could also view and edit private items.

**Comment by jimsafley** [comment]
Realistically, the best way to determine whether our permissions make sense is for people to use the software while logged in as different roles. Do we account for this during testing? @sheilabrennan  @mebrett

**Comment by sheilabrennan** [comment]
Yes, we should be doing that for something like this. 
 @mebrett
