### ISSUE TITLE
HTML inputs can't be required

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#734]
The inline editor breaks when the textarea is required.

**Comment by zerocrates** [comment]
The simplest solution is to return to the "regular" editor if we want to have a required editor: ckeditor handles the `required` attribute in this case but seems to ignore it for the inline editor.

The other main pretty simple alternative is to just not have Media inputs be required, instead ignoring them when they're left empty.

Otherwise, we'd have to gin something up where we remove the required attribute on the textarea and set up some javascript of our own to prevent submission when the editor is empty. This feels like a bug in ckeditor so there might be some possibility of resolution there, but I'm not sure of the chances.

**Comment by zerocrates** [comment]
ticket filed with ckeditor: https://dev.ckeditor.com/ticket/14862

**Comment by jimsafley** [comment]
A WIP in the html-require branch: https://github.com/omeka/omeka-s/compare/html-require

Changed the HTML media to use the new Ckeditor form element. The normal editor renders as expected, but the browser does not flag an empty textarea as required during submission. Normally ckeditor does this check internally but somehow this implementation doesn't work.

**Comment by jimsafley** [comment]
CKEditor documents a `required` event that should fire when a textarea marked as required is empty during form submission: http://docs.ckeditor.com/#!/api/CKEDITOR.editor-event-required

I've attached a listener directly to the editor when the editor is created, and even during the general-purpose `instanceReady` event, but it's never called. I'm not sure what to do.

**Comment by jimsafley** [comment]
By moving to the normal editor we fix the superficial problem. Moved the underlying problem to #767
