### ISSUE TITLE
Option to turn off attachment resource title in site blocks

### ISSUE THREAD

**Issue by kimisgold** [omeka/omeka-s#741]
There are use cases when a block like media or item showcase uses multiple file attachments from the same item. This results in a block where the item title is repeated redundantly under the images.

For example, I was rebuilding this page from an Omeka Classic project: http://physical-electrical-digital.nyufasedtech.com/exhibits/show/teleologies-of-the-american-co/gabilliet. Here is the 4 image block rebuilt in Omeka S.

<img width="1132" alt="screen shot 2016-09-15 at 10 45 35 am" src="https://cloud.githubusercontent.com/assets/606764/18554265/a01a1bd6-7b31-11e6-98d1-cce062a633eb.png">

**Comment by zerocrates** [comment]
Could we have options for item title, file title, no title?

**Comment by zerocrates** [comment]
Or rather, one setting with those as the choices

**Comment by kimisgold** [comment]
That sounds good to me. Maybe also an option to caption the whole block?

**Comment by zerocrates** [comment]
Caption the whole block meaning what?

**Comment by kimisgold** [comment]
Providing a caption for a gallery of items, like in this example, where the user created a workaround by using an HTML block to describe the group of covers: http://physical-electrical-digital.nyufasedtech.com/exhibits/show/teleologies-of-the-american-co/introduction.
