### ISSUE TITLE
Sane-ify File Manager

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#752]
It combines
- stuff used when adding new files (taking File objects)
  - you need it if you want to get the extension for a file, for example
  - it also holds the actual FileStore, so the actual storage passes through it, as does something like calculating the path where something should be stored
  - it also does some storage and calculation on regular filenames like stripping off the extension (this stuff should probably be taken out as it's actually a relic from when the extension was stored crammed into the filename)
- stuff used when acting on a stored file for Media (taking Media objects)
- stuff that acts on the thumbnails (sometimes taking a File and sometimes Media, and sometimes just holding the array of existing thumbnail types)
- plus common-ish code for downloading a file using the HTTP client (this doesn't use either the File or Media objects)

Beyond just being a sort of confusing mishmash, the result now is that something like asset uploading needs to use the FileManager to do something like get the extension of the uploaded file, but _can't_ use it to actually store the uploaded asset (because the Manager doesn't have any facility for uploading that's not basically specific to Media).

**Comment by zerocrates** [comment]
Some of this should clearly just be separated into more focused classes/services, I think.

**Comment by zerocrates** [comment]
So, I think there's a few ways to see the issues I have with the current manager, and ways to improve the situation.

The different concerns laid out in the issue summary is still a pretty good listing, and that's quite possibly a good basis for separating things. It's quite possible that the endgame doesn't have a File Manager at all.

downloadFile should almost certainly be separated from the rest as it really doesn't interact with the rest of the class at all: it doesn't use a File object, doesn't use anything passed to the class, and is the only thing that uses the HttpClient or the Logger. It's also of more obvious general applicability other places.

validateFile is a minor pain point for the Asset API, as it needs to do effectively the same validation but needs to have a different, more restrictive set of extensions/types. The Asset adapter is a good place to look for the basic problem that motivated this issue: it actually needs the Manager, more or less just to get a File object (another capability that's pretty much separate from anything else, as it just needs the tempDir config setting, and nothing else in the class uses it), but then has to reimplement things like validation and handling an uploaded file within the API.

The validation feels like something where we should have a class that has the behavior and a factory that reads the config data for the mime/extension settings out and injects the results. That way something like Asset can use the behavior by just manually instantiating the class with the mimes/extensions it wants.

The uploading stuff that's currently separated between Asset and the Upload ingester should probably be shared in some component, possibly one that gives back a File object at the end, though just a bare path would work too. We have other places where we take uploaded files as well that could potentially use this, though they're not in the API so that basically explains that difference.

The Asset adapter does use the Manager for one other thing, and that's to just get the FileStore. The pattern of having a _different_ service just hold onto the Store and talk to it for various reasons might make sense, but again it feels like something that should be separate. We may just want to have components go get at the FileStore directly though. The constellation of methods that act on Media are perhaps the oddest part of this class. Note that when AssetRepresentation wants to get the URL of a stored asset, it gets the Manager... just to get the Store and talk to it directly, as the stuff in the Manager for doing this only works for Media. This will only become a more obvious weird area as Asset gets other stuff it needs, like deletion, where it would again go straight to the Store to do its work.

My general idea is that the process can start by carving off stuff that makes the most sense separately, or in another place (i.e., Media stuff in the MediaRepresentation or adapter or events), and then what's left may be something that's more obviously cohesive.

**Comment by jimsafley** [comment]
Fixed in 997ad56fd138b3d9dec45dfb091c79dceda213dd
