### ISSUE TITLE
Remove use of inputFilters throughout codebase, including modules?

### ISSUE THREAD

**Issue by patrickmj** [omeka/omeka-s#753]
The use of inputFilter to do things like setting required fields seems to create quite a lot of surprising failures, especially with modules adding to forms. We might need to systemically move away from that pattern, and instead work by extending Zend Elements to provide a consistent interface, even if that means forcing devs to add on some unintuitive code (we can document that, and maybe even find ways to ease that small pain-point)

**Comment by zerocrates** [comment]
What exactly are all the surprising failures we're talking about here? I've seen a couple related issues but it's not super clear to me what the scope is.

**Comment by patrickmj** [comment]
Made the changes about extending classed to the test stuff for Sharing adding to global settings. Can't seem to get around the same problems of data being stripped out. Worth more investigation and seeking options, but so far the use of `inputFilter()` on the forms is the consistent sticking point. It's become clear that the pattern Jim's used of extended elements is more likely to work, so a switch of patterns seems in order.

Sharing branch filter-fix. Core branch global-admin-event. Trying to add/update a textarea setting from global admin page.

Might be just the browser re-filling in text, but there's definitely something hard to predict going on. I'm still digging around.

**Comment by zerocrates** [comment]
Everything about input filters is frustratingly awful

**Comment by zerocrates** [comment]
Thank goodness we don't really use them for much of anything. That should make whatever needs to be done a little easier.

**Comment by patrickmj** [comment]
Might be a modules thing, but I hit them a lot, especially in the context of figuring out the appropriate events.
