### ISSUE TITLE
PUT vs PATCH confusion in the API

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#76]
We've talked about this before, but the API generally behaves more like how you'd expect a PATCH to work: things that are simply omitted from a PUT request don't get changed.

In certain places this behavior causes us actual trouble already. For an example, Item Sets on the Item form had a problem last week where you couldn't delete all the sets. The reason was, removing them all would mean no item sets at all got submitted with the form, so the API treated that as a request that wasn't talking about item sets so they should be left alone.

Right now that's fixed with a one-off that forces the ItemController to add an empty `o:item_set` array to the API request if no sets were sent, but that strategy will get old fast.

Simple option(s) I think could work for easily enabling a PUT/PATCH dichotomy:

* right now we're generally setting up our logic for "skipping" a key with `array_key_exists`. We could instead use a method on the abstract adapter that takes the request and a key to check, if the request is a PATCH, then it does an array_key_exists and will give you a bool result on whether that key is there so you know to skip it. If the request is a PUT, it will just always return `true`.
* the other option is similar: have each adapter define somewhere a list of all the top-level keys it pays attention to. On a PATCH, process things as normally done now. On a PUT, array_merge an array with  all the top-level keys but `null` for the value, so every key is specified and `array_key_exists` will return true so nothing will be skipped over.

There are almost certainly places in the API where we're sloppy so doing either of these will require fixing several individual adapters.

**Comment by jimsafley** [comment]
I agree. We've avoided this issue for too long. Our conflation of PUT and PATCH has led to confusing and brittle hydration patterns. I like your second option. Since we accept a particular JSON-LD syntax I can see how it could help us document that syntax.
