### ISSUE TITLE
Item 'add new media' URL option error on non image links

### ISSUE THREAD

**Issue by mebrett** [omeka/omeka-s#772]
When editing or adding an item, on the Media tab.

I can add a URL media if the url ends with an image extension (so https://upload.wikimedia.org/wikipedia/commons/4/40/Q2_Title_page_Merry_Wives_of_Windsor.jpg works)

However, other web urls (https://en.wikipedia.org/wiki/The_Merry_Wives_of_Windsor) do not work, and instead result in the error `Cannot store files with the resolved extension ""`

In the past I've been able to add media which was a link to somewhere else (to an IMDB or Wikipedia entry). If that was a bug, I just need to know so I can make it clear that the url needs to be a file, not a webpage.

**Comment by zerocrates** [comment]
This looks like a bug: the media type is being detected as "application/x-gzip" meaning basically "unknown gzip-compressed data", when it should be "text/html." Some errors in media type detection are to be expected, but this particular one probably means that ZF's not decoding gzipped or compressed responses correctly.

**Comment by zerocrates** [comment]
This should fix the problem sort of: you'll still get an error, but it will be that by default neither "html" nor "text/html" the media type are in the allowed lists. Adding them should allow you to ingest the file.

**Comment by mebrett** [comment]
I just pulled from develop to the shared install, and I'm getting a different error.

Trying to add https://en.wikipedia.org/wiki/As_You_Like_It as a URL media for http://dev.omeka.org/omeka-s/admin/item/18264 

Error: Error ingesting "/wiki/As_You_Like_It". Cannot store files with the media type "text/html".
Error ingesting "/wiki/As_You_Like_It". Cannot store files with the resolved extension "html".

**Comment by mebrett** [comment]
That did fix it. Thank you.
