### ISSUE TITLE
Nail down Omeka vocabulary IRI

### ISSUE THREAD

**Issue by jimsafley** [omeka/omeka-s#775]
Defined in `Module::OMEKA_VOCABULARY_IRI`, we must nail down our vocab IRI *before* we release beta. It's currently `http://omeka.org/s/vocabs/o#`.

**Comment by zerocrates** [comment]
We should actually define the vocabulary and what's in it at some point as well.

**Comment by jimsafley** [comment]
It appears that we will be using `http://omeka.org/s/` for the website, so we can stick with`http://omeka.org/s/vocabs/o#`.
