### ISSUE TITLE
Omeka S needs themes

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#78]
Regardless of what happens with the rest of the public side and sites stuff, we need themes.

At a basic level this means we need some setup of our own or leveraging built-in ZF configuration for switching out the layout being used, and/or the paths loaded on the view template stack.

**Comment by jimsafley** [comment]
On `MvcEvent::EVENT_ROUTE` or `MvcEvent::EVENT_DISPATCH` detect "site" route, add the configured theme's path to `template_path_stack` and (possibly?) the layout to `view_route_layouts`.
