### ISSUE TITLE
Enforcement of module structure and .ini structure

### ISSUE THREAD

**Issue by patrickmj** [omeka/omeka-s#793]
The initial docs from the wiki describe the `config/module.ini` file as being required, and some of the components of that file being required. 

However, there doesn't seem to be any enforced checks to throw errors or warnings or whatnot if module.ini isn't present, or if the currently described requirements are not met.

Do we want to enforce those things, for the beta or aspirational for the final release? Either way, what should the documentation for beta say about them?

**Comment by zerocrates** [comment]
There are already enforced checks for the presence of the module.ini, and that it must contain name and version keys.

**Comment by patrickmj** [comment]
I'm seeing something different. I deleted the module.ini from STest, and here's what I see on modules page

![stestmodule](https://cloud.githubusercontent.com/assets/153262/19831996/6e4e613e-9de6-11e6-87ca-16a75dedcfef.png)

**Comment by patrickmj** [comment]
Before deleting the file, I'd uninstalled STest

**Comment by zerocrates** [comment]
Notice that you can't activate, deactivate, or install it. It will also be coming up in the Error dropdown selection on the page. If the module had been installed, it'd be automatically deactivated.

At some point this page appears to have been edited so it doesn't display the status of the module, which would make the fact that STest is in an error state more obvious.

**Comment by patrickmj** [comment]
So, accurate to say that it's enforced, but not a lot of information being displayed?

**Comment by zerocrates** [comment]
Yes, I think that's an accurate portrayal of the situation.

**Comment by patrickmj** [comment]
I don't see this as necessarily a thing for the beta release, just something that raised an eyebrow as I was looking at ways to break my modules and document what's in the module.ini.
