### ISSUE TITLE
Clean up module.ini in all modules

### ISSUE THREAD

**Issue by jimsafley** [omeka/omeka-s#794]
Creating issue here since the config/module.ini files in most modules need attention. I notice that many INI files need `description` and `author_link = "http://rrchnm.org/"`. We also need somewhere to link for `module_link`.

**Comment by zerocrates** [comment]
Setting the minimum omeka version is something we're not really doing anywhere and should be doing in all the modules.

**Comment by jimsafley** [comment]
@patrickmj For the Omeka2Importer, Sharing, CSVImport, MetadataBrowse, FedoraConnector, and DspaceConnector modules I'm not going to touch the `version`, but do you have objections if I set `omeka_version_constraint` to 1.0.0-beta?

**Comment by patrickmj** [comment]
no objections at all. We've already said that the November releases will all be 1.0.0-beta, so I've no objection to bumping those while you're in there.

**Comment by jimsafley** [comment]
I'm done with everything except `module_link`. Ideally each module will have a page on http://omeka.org/s/ with links to download link and documentation. Right now we only link to Github releases pages. @zerocrates @kimisgold, are module pages planned or in the works?
