### ISSUE TITLE
Duplicate-seeming properties in some vocabularies

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#795]
In bibo: there are two "status" and two "presented at" properties: both are actually different properties where one of the pair looks to have a mis-copied label, bibo:degree and bibo:presents. An updated bibo OWL RDF file from their github fixes the degree label but still has the double "presented at." I've filed a pull request to fix the latter. https://github.com/structureddynamics/Bibliographic-Ontology-BIBO

FOAF has this problem for "account" (both foaf:account and foaf:holdsAccount) and "Given name" (both foaf:givenname and foaf:givenName). I hold much less hope that we'd be able to get actual changes to the FOAF source to disambiguate those, especially in the givenName case. FOAF also has, as we've seen, many other inconsistencies in its labels. I don't know if we have any ideas for fixing them, and we've discussed them before, but we might want to try to come up with something.

**Comment by patrickmj** [comment]
I'd actually be okay with us just making the changes we want for our own needs. After all, there's no reason we couldn't write our own vocab to assert different labels. Not that we should, but the effect in the database would be the same.

**Comment by sharonmleon** [comment]
Interesting. I was using foaf:givenName and I figured that there was
something that I wasn't getting about why there were two.

**Comment by zerocrates** [comment]
The only problem with just changing them is keeping up with changes to the
sources. Now they're unchanged so we can just drop in new ones if they're
updated (e.g. to get the updated bibo that fixes the degree label). Once we
change those we need to remember to merge or otherwise reapply our variants
to keep the "fixes."

Another option could be to have separate files or something similar that
just store our changes vs. the source, so they wouldn't be clobbered by
updates.

**Comment by patrickmj** [comment]
Very true. But in practical terms I don't think we'll see a lot of changes for either BIBO or FOAF to worry about, unless they accept our pull requests, which we'll know about.

I'm still on the BIBO email list (though I don't often keep up with the convo). I could float a question there, both BIBO-specific and the general feeling about other vocabs.

**Comment by zerocrates** [comment]
The PR on BIBO was merged, so regardless we should probably grab an updated copy of it.

**Comment by jimsafley** [comment]
We should use a vocabulary as it's defined in the most recent version of its schema, mistakes and all. We should not attempt to update a vocabulary without first speaking with the schema's custodian and receiving a *published* update. Otherwise we risk our vocabulary irrevocably getting out of sync with the formal definition.

When migrating a vocabulary it's safe for us to add new members (classes and properties) and update existing labels and comments. To avoid data loss and general breakage, we should never delete existing members or update existing local names. I believe we can automate this process.

**Comment by zerocrates** [comment]
This issue was just for the "question," and doesn't provide anything really that #840 doesn't, so I'm closing it (but with this comment connecting the two).
