### ISSUE TITLE
link and .error are same color

### ISSUE THREAD

**Issue by jimsafley** [omeka/omeka-s#798]
Both `link` and `.error` are `$red` in SCSS. This is confusing when the link needs to be marked as an error, since there is no visible change.

**Comment by kimisgold** [comment]
Could you provide a use case I can experiment with?

**Comment by jimsafley** [comment]
There's no use case anymore. I noticed that errors and links were the same color while working on module UI. The module no longer has an link marked as an error.

**Comment by kimisgold** [comment]
How would you recommend I proceed?

**Comment by jimsafley** [comment]
Make link and .error not identical.

**Comment by kimisgold** [comment]
The way I understand it, error appears as a flash message with a pink background, distinguishing it from a link. I get the issue if a link appears within an error, and my thought would be to underline the link within the error message. Am I understanding this issue correctly, and does that sound like a good solution?

**Comment by jimsafley** [comment]
Yes, that sounds like a good solution.
