### ISSUE TITLE
More flexibility about what the API manager does

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#809]
A decent amount of the trouble encountered doing more "interesting" or intensive with the API is that it's pretty rigid in what it does and what it allows you to change. Ultimately for most things the core of what it does is find entities and hydrate them, but it generally mandates that it returns Representations, not Entities (and not References either), and that it flushes at every step.

Mostly this makes sense for the normal flow of things: we want to use the Representations generally, and we need the flush to occur so new data like the IDs of newly created records will exist so the Representation can be created. In jobs and bulk processing and a few other places, this doesn't work though: we need the Entity so we can detach it, or so we can do things that aren't in the API, or we want to reduce the number of expensive flush() calls.

I think it makes sense to try to let the API accomodate some of these other use cases. The API could

- return stuff other than Representations (like References instead, or even Entities)
- detach the entities that it returns
- just hydrate, not flush, leaving the API consumer the duty of flushing (or not)

None of these are desirable in the normal case, but we have current needs for all of these things and currently we're either doing hacks to make it happen or we're not using the API at all (or we build in a backdoor to get Entity access from the Representation, as in the case of Users).

**Comment by jimsafley** [comment]
Some possible issues with the changes currently in #861:

First, we are no longer validating API response content. I wonder if we should by checking against the three "responseContent" request options. (Or something more flexible but complicated.)

R elatedly, listeners to `api.*.post` and `api.execute.post `can no longer rely that the passed response contains objects that implement `RepresentationInterface`. They must check the "responseContent" request option to know. To guarantee a return type, it may be in our best interests to transform `Api\ResourceInterface` content to `Api\Representation\RepresentationInterface` within `finialize()`.

**Comment by jimsafley** [comment]
To resolve the above concerns, adapters must now set `Api\ResourceInterface` objects to the resource content. The manager will transform the API resources (respecting the the "responseContent" request option) in `finalize()` _after_ triggering the `post` events.

**Comment by jimsafley** [comment]
Above concerns resolved here 8d0ba562cf4d5abbcb2bcbce81e28d2a7c9160e7

**Comment by jimsafley** [comment]
Resolved in #856 and #861
