### ISSUE TITLE
Modules and themes: root-level [info] section in INI files

### ISSUE THREAD

**Issue by jimsafley** [omeka/omeka-s#813]
In the interest of consistency between projects and compatibility with the addon page builder (under development) we probably need to put root-level INI configuration under an `[info]` section. Classic already requires this, but S does not. Without this section, the page builder prepends the section to the INI file, under the assumption that root-level config is always at the top. I don't think it's a good idea for us to assume this, given the file could contain other sections at the top. So unless we enforce a convention of always putting root-level config at the top, we need an `[info]` (or some other) section.

**Comment by jimsafley** [comment]
This is a problem largely because Python's native configuration file parser, [ConfigParser](https://docs.python.org/2/library/configparser.html), does not recognize INI files without at least one section. If this isn't worth the trouble of changing every addon INI file in S, I'll have to parse the file another way.

**Comment by jimsafley** [comment]
Still, I do think it's generally best practice to use a "default" section for otherwise root-level configuration.

**Comment by zerocrates** [comment]
`[info]` is such a terrible section name.

Having one in the S inis is fine, even named `[info]`.

**Comment by jimsafley** [comment]
a3d505f makes the `[info]` header optional. Eventually (probably before the next release) we'll need to make `[info]` required so the addon page builder will function.

**Comment by jimsafley** [comment]
As of now, all modules and theme INIs have the `[info]` header in their respective default branches.
