### ISSUE TITLE
Testing: new theme-selection interface

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#814]
On develop.

The interface is accessible in two places:
- when creating a new site, there's a Theme tab
- on an existing site, there's a Theme entry in the left nav (the Theme dropdown on the Site Info page is gone)
  - theme settings are also available from within this page

There's not a great deal going on here, but just a basic runthrough of those two locations to spot any possible issues and confirm it's working and is an improvement over the dropdown.

**Comment by mebrett** [comment]
@alyssafahringer @jannellelegg

**Comment by mebrett** [comment]
Worked for me on Chrome, Safari, and Firefox

**Comment by alyssafahringer** [comment]
I second @mebrett's comment. I also played around with the theme settings and that worked out as well. I prefer this interface to the dropdown menu.

**Comment by jannellelegg** [comment]
Third - worked well for me on existing and new sites. It's easier to navigate/makes more sense.

**Comment by zerocrates** [comment]
Sounds good!
