### ISSUE TITLE
Alternative to ResourceReference::getRepresentation ?

### ISSUE THREAD

**Issue by jajm** [omeka/omeka-s#815]
#807 removed `ResourceReference::getRepresentation`.
What is the proper way now to get the resource representation from a `ResourceReference` ?

`$resourceName` is not public so we can't do `$api->read($ref->resourceName, $ref->id())`.

I think that a public method `resourceName()` may be helpful here.

**Comment by zerocrates** [comment]
You're probably right that `resourceName()` is appropriate to have given the changes to ResourceReference. It's designed to no longer make it very easy to get a representation from a reference, but it's not supposed to be this difficult either.

**Comment by jajm** [comment]
> It's designed to no longer make it very easy to get a representation from a reference

Maybe if I explain my use case it'll be more clear why I need this.
I use Solr for the public search and I need to index items as soon as they are created/updated, so I listen to the `api.*.post` events. Everything works fine for creation and update, because I get an `ItemRepresentation` object. But this is not the case when items are created by `batchCreate()`, I get a list of `ResourceReference`. And I still need the representation object to get all the properties (among other things).
