### ISSUE TITLE
Configuration for Mail and S3

### ISSUE THREAD

**Issue by boredland** [omeka/omeka-s#827]
With Omeka-S getting more stable I'd like to ask: how does one configure S3-Storage and mailservers with it? Currently there seems to be sendmail configured by default. I'd like to change that for me.

**Comment by zerocrates** [comment]
There's no implementation of S3 storage built in at the moment, but there is a system in place for a pluggable storage layer, the FileStore. The `[file_manager][store]` key of merged config allows for configuration of which storage layer is used. A module could therefore provide an S3 storage option easily.

As for mail, look at the `mail` key of application/config/module.config.php. Like anything in this file, these are defaults that are overridable in the local configuration (config/local.config.php). In particular the `transport` key under `mail` lets you select the mail transport and any options it requires. As you say, the default is sendmail, but anything pre-provided by Zend or added by a module can be chosen here (so for example you could set it up to use [SMTP instead](https://framework.zend.com/manual/2.4/en/modules/zend.mail.smtp.options.html)).

**Comment by boredland** [comment]
Hi! Since there has been no development on this: is anybody else interested in a s3 module?

**Comment by boredland** [comment]
I'd suggest we reopen this. I know at least one person that would post a bounty on bountysource for this.

**Comment by rexsavior** [comment]
Yes, this seems like a valuable feature. As it is available in Omeka Classic I was expecting to find a similar feature in Omeka S and was disappointed to find it missing. A generic cloud-based file storage module might go further, adding support for Azure and Google (in addition to S3).
