### ISSUE TITLE
403 Error on install

### ISSUE THREAD

**Issue by cwhits** [omeka/omeka-s#831]
Without adding `Options +SymLinksIfOwnerMatch` I get a 403 error after install. Adding `Options +SymLinksIfOwnerMatch` to my Apache conf for omeka-s fixes it. Omeka-S was installed by cloning the git repo at commit 1b46701.

The log entry is 
```
[Fri Feb 10 10:06:07.657411 2017] [rewrite:error] [pid 26801] [client x.x.x.x:57340] AH00670: Options FollowSymLinks and SymLinksIfOwnerMatch are both off, so the RewriteRule directive is also forbidden due to its similar ability to circumvent directory restrictions : /web_apps/omeka-s/
```

**Comment by zerocrates** [comment]
I don't think we can easily (or feasibly) change our core RewriteRule to not trigger this, so it may be a documentation solution. We probably don't want to go down the road of trying to set Options in the shipped .htaccess either.

**Comment by cwhits** [comment]
Does this not trigger on other installs or in your tests? Is there something with my Apache setup that is causing this to happen that is out of the ordinary?

**Comment by zerocrates** [comment]
I don't think we've seen this error from any testing or any user reports up until now. My guess would be that your Apache configuration is just a little more restricted in terms of the Options it sets than the usual cases we see.

**Comment by cwhits** [comment]
Then feel free to ignore me 😄

**Comment by zerocrates** [comment]
It's good to have the report anyway: I'm sure we'll see this again at some point.
