### ISSUE TITLE
Decision not to have usernames

### ISSUE THREAD

**Issue by TimHollies** [omeka/omeka-s#833]
I've developed a simple module which allows users to login with LDAP credentials (https://github.com/digihum/omeka-s-ldap). We use LDAP to manage all of our Omeka classic instance accounts at my institution - so having a plugin for Omeka-S is essential for us to be able to migrate.  

However, there is a fundamental difference between Omeka Classic and Omeka S which makes it very difficult to integrate with 3rd party authentication systems - the lack of usernames. Omeka S only has display names and emails.

The solutions to this problem seem to be either to do a nasty hack in authentication modules (such as the current behavior of using the string before the @ as the username in my LDAP module), make each authentication module replace almost the entire Omeka S authentication system to include a username field, or patch Omeka S to include usernames.

What was behind the decision to remove usernames in Omeka S? And would you be open to accepting a pull request that puts them back?

**Comment by zerocrates** [comment]
I believe the rationale was just to simplify and/or shorten the various forms dealing with users. We already had a requirement to have their email to send messages, and the email already uniquely identifies users, so the separate username was seen as redundant. Other services using email directly as the login have also become more common in the time between Classic and S.

LDAP is an interesting case though. I'd be amenable to making or accepting changes that make LDAP work better, but I'd prefer not to have to reintroduce usernames. Storing an LDAP username for each user shouldn't be a big problem as this could just be a table added by the module that references S's user table.

**Comment by TimHollies** [comment]
Okay, that make sense. 

Adding in a table to store usernames that has a foreign key link to the users table is easy enough. Setting the usernames is slightly more tricky.. Is there a way to add additional fields into the user form without making the module replace `UserController` and `UserForm`? I'll also have to replace `LoginForm` to allow non-email input when the module is being used. 

Replacing that many classes makes me uneasy. It could potentially be avoided with the introduction of a number of events into the `UserController` and `LoginController` classes. 

I think I could make it work if the following events were added:
- login.form
- user.form
- user.add
- user.edit
- user.show

Similar events are already in place for views and the site_settings form. What do you think?

**Comment by TimHollies** [comment]
Actually - it may be possible with the existing `entity.*` events and `form.add_elements`.

**Comment by zerocrates** [comment]
@TimHollies Did you end up figuring out if you had the events you needed/wanted?
