### ISSUE TITLE
500 errors on subdomain install

### ISSUE THREAD

**Issue by ManOnDaMoon** [omeka/omeka-s#834]
I've encountered the following issue while installing Omeka-S on a subdomain of my main site.

I was unable to install Omeka-S at URL `omekas.mysite.com` as the `omekas.mysite.com/install` URL threw a 500 error.

I figured out that the absolute URL `mysite.com/path/to/omekas` was working correctly.
I was able to install Omeka-S this way. The default front page then worked correctly from the subdomain view. Admin panel access, and I guess access to all rewritten URLs, still threw a 500 error.

I made the following change to the default .htaccess file to solve the issue: on line 23 I added a slash before `index.php`
Original line:
`RewriteRule ^(.*)$ %{ENV:BASE}index.php [NC,L]`
Modified line:
`RewriteRule ^(.*)$ %{ENV:BASE}/index.php [NC,L]`

This change solved my issue. I've not found any similar report, so I'm submitting in case this could be relevant.

**Comment by zerocrates** [comment]
Hmm, interesting.

We haven't heard any reports like this so far, so we'll see if we get any more or what turns up. The idea behind the rule used in S is to avoid having to tweak RewriteBase as was so often necessary for users of Classic. Perhaps there's a minor change we can make that avoids this problem.

**Comment by zerocrates** [comment]
I pushed an update (the commit above) that aligns our rewrite rule here with the Zend Framework upstream. It's similar but not exactly the same to the change you did yourself.

Let us know if the updated .htaccess also works for you.

**Comment by ManOnDaMoon** [comment]
Thanks zerocrates. I confirm that the updated .htaccess from your commit works fine on my subdomain install.

**Comment by zerocrates** [comment]
OK, good. Then I'll close this as it should be fixed now.
