### ISSUE TITLE
Proposal: Docker-Build for easy exchange of Beta-Installs

### ISSUE THREAD

**Issue by boredland** [omeka/omeka-s#838]
I created one. It works with socket-share, external files and and an external database.ini, so one can just replace his docker-install by a new one without loosing database-entries or files. And without git-fiddeling. It downloads all available themes and modules. I hope this is useful for somebody.

https://hub.docker.com/r/boredland/omeka-s-docker/

**Comment by patrickmj** [comment]
@boredland I've copied this announcement to a [new category on our forums for community contributions](https://forum.omeka.org/t/docker-build-for-omeka-s/4079) for greater exposure.
