### ISSUE TITLE
Resource form: switching back to no template deletes all values

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#84]
If you choose a template on the resource form, then go back to the empty "Select Template" option on the select box, all the contents of the values part of the form get deleted.

What's *supposed* to happen is that the labels just get switched back to the regular ones; none of the values or properties should get removed.

**Comment by patrickmj** [comment]
so, I'm not seeing this bug (though I am seeing that the labels and descriptions aren't changing at all). Someone else making changes that might touch on this?

**Comment by zerocrates** [comment]
it temporarily looks like that select isn't doing anything at all, i'll see what's up

**Comment by zerocrates** [comment]
Actually never mind, I can still reproduce the same problem.
