### ISSUE TITLE
Add site broken

### ISSUE THREAD

**Issue by patrickmj** [omeka/omeka-s#850]
On develop ( 96175e8 ), the add site page breaks, with nothing in the log.

![addsite](https://cloud.githubusercontent.com/assets/153262/23512050/4b59759e-ff2d-11e6-889a-26a1e0eb302c.png)

**Comment by kimisgold** [comment]
Mine breaks right at 9212f8fa1f9ffc35ef1cfd8fa8481c00f00b3f7f with the following errors:

```
Notice: Undefined variable: currentTheme in /Users/kim/Sites/omeka-s/application/view-admin/omeka/site-admin/index/theme-selector.phtml on line 7

Fatal error: Call to a member function getId() on null in /Users/kim/Sites/omeka-s/application/view-admin/omeka/site-admin/index/theme-selector.phtml on line 7
```

**Comment by zerocrates** [comment]
It's in all likelihood a bug related to the recent changes to the Theme interface and events
