### ISSUE TITLE
Some user roles can't change theme image options

### ISSUE THREAD

**Issue by kernsb** [omeka/omeka-s#857]
I am seeing an issue where if a user has a role lower than Site Administrator, they are unable to make changes to image items in the theme options (logo, etc.) - even if they are set as an Admin for that particular site. When attempting to select an image, the right pane opens and states "Something went wrong". Any text or selection values can be changed without issue.

**Comment by zerocrates** [comment]
Thanks for the report.

This is an ACL problem one way or the other in all likelihood.

**Comment by zerocrates** [comment]
Can you clarify for me: what version of Omeka S are you using?

**Comment by kernsb** [comment]
My installation is currently at 1.0.0-beta2.

Brandon Kerns
