### ISSUE TITLE
Test resource template export and import

### ISSUE THREAD

**Issue by jimsafley** [omeka/omeka-s#860]
Resource templates are now shareable in the `import-template` branch. I need you to test the export on all different variations of a resource template; such as with and without a suggested class, with and without properties from all different vocabularies, pepper in some alternate labels and comments, data types, and requires. I suggest that you use the CustomVocab and ValueSuggest modules to add custom data types. I'll need you to be comprehensive about the variations here. You'll find the export button on the RT show page.

The best way to test the export is to import each exported file you created above and see if everything carries over. (The _absolute_ best way to test the export/import if to import a RT into another Omeka installation that has different vocabularies.) Import is a two-step process, one to upload the file, and another to review the import. Things should be self-explanatory, so make note if you see something that doesn't make sense (or breaks, obviously). You'll find the import button on the RT browse page.

**Comment by mebrett** [comment]
Testing included: Custom Vocab, Vocab Suggest, requiring fields, alternate labels, alternate comments, and various data types. Everything imported as needed, with expected exceptions (if a module is not installed, or a custom vocab doesn't exist on the import side you can't assign it).

When importing a template with CV or VS options, they were not auto-selected but the dropdown to choose the kind of data did show up to enable me to re-select them. I appreciated that the Review Import page tells you which vocab was assigned in the original template, as it makes it easier to re-select the correct one.

![screen shot 2017-03-22 at 11 55 18 am](https://cloud.githubusercontent.com/assets/2314070/24207183/a879ca66-0ef6-11e7-96a6-7d999f7fb418.png)


One feature which would be nice to have is that the exported file have the name of the resource template - all the of files were simply "resource_template_export.json" which led to a little confusion if I exported more than one at a time.

**Comment by jimsafley** [comment]
The review page doesn't auto-select non-default data types because there's no way to tell if the imported data type is identical to an installed one with the same name. This is why it forces the user to make the selection.

Good idea re. the file name. I'll look into it.

**Comment by mebrett** [comment]
I'm fine with the review page not auto-selecting. I appreciate that it does display what *was* used, so that you don't have to hunt it down, but can instead just reference the exact row as you select from the drop down.

Thanks re: file name.
