### ISSUE TITLE
Create sandbox

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#863]

**Comment by mebrett** [comment]
Either update the slug/name of the DPLA sandbox or create a fresh install which is kept up to date.

**Comment by patrickmj** [comment]
Big question will be how to give people access. We can create a bunch of users, but how do we make those credentials public?

**Comment by sharonmleon** [comment]
In the past, we've had one user and password that we make publicly available with the link to the site, and then we've had a cron job that goes through every night and deletes everything that has been created that day. (At least, I think that's how it worked.)

**Comment by mebrett** [comment]
Do we want to update the [current slug of the DPLA sandbox](http://dev.omeka.org/dplafest-omeka-s/) or create an entirely new one?

**Comment by patrickmj** [comment]
It'll probably work to just rename the directory. I'll try. Hopefully I'll be able to empty the database if that works.

**Comment by patrickmj** [comment]
I suspect we'll need to ask @zerocrates and/or @rsanc77 for a script and cron job to empty the database automatically.

**Comment by patrickmj** [comment]
Switching the directory name looked fine, but updating to master killed everything (it was going from 0.7.0-alpha up to current)

**Comment by zerocrates** [comment]
"killed everything" is less than descriptive.

**Comment by patrickmj** [comment]
"killed everything" == white screen, nothing in logs.

Guessing that there's things to double-check about where files moved from 0.7.0-alpha, and do the new gulp stuff.

**Comment by zerocrates** [comment]
Well certainly you'd need to do `gulp deps` to run Composer, or run composer manually

**Comment by patrickmj** [comment]
A sandbox is now available at http://dev.omeka.org/s-sandbox/admin

Master of plugins and themes are there, but . . . 

Still needed:
- [ ] Sandbox account credentials
- [ ] Page showing those credentials with a link from somewhere on a public/ity page
- [ ] Cron job and script to clear out data and files periodically 

Part of the above might be branding, and the last one is coding/server stuff, so pinging @zerocrates @mebrett @sharonmleon and @rsanc77

**Comment by patrickmj** [comment]
Basic, empty sandbox is now up on master branch of omeka-s at http://dev.omeka.org/omeka-s-sandbox/

Sadly, somehow during the upgrade all the files were deleted -- a mystery. Means that we'll need to decide what new content to put up, and what modules and themes. I'm guessing we want two or three global admin accounts available?

**Comment by mebrett** [comment]
I believe some of the sandbox content may come from the Fellows, which means we need to make sure the CSV and Omeka2 Importers are installed and working.

**Comment by patrickmj** [comment]
Those are in. I'm keeping everything on the master branch (where available). The user you (@mebrett) had is still there. Looks like you and me were the only users in there.

**Comment by patrickmj** [comment]
See https://github.com/omeka-s-modules/CSVImport/issues/72 in CSVImport about owners. This might also need attention in other importers.

**Comment by patrickmj** [comment]
@rsanc77  ran the test of the cron job resetting data, and it seemed to work as expected.

So, the next steps look like:

- [ ] finalize content
- [ ] finalize modules / themes available
- [ ] make sure everything is on a master branch we're happy with
- [ ] write up whatever blog post or advertising we will use

"Finalize" is actually an overly strong word. We can easily do a new database dump and clone of the files -- the reset script will just use the new data. We'll certainly also have new master branches of everything that we can update as we go along.

I'm guessing we run the reset every 2 days, at midnight our time? (whatever the schedule, we should just put that in the info about the sandbox)

**Comment by patrickmj** [comment]
I'm thinking of asking Roberto to make the cron job run Mon, Wed, Fri, Sun rather than daily. The idea is to let people explore, then have a chance to sleep on it and revisit what they've done. Any thoughts on this @mebrett @sharonmleon @sheilabrennan ?

**Comment by sharonmleon** [comment]
I think that's fine. I'd just like to get this launched.
