### ISSUE TITLE
Keep metadata when an error occurs with an uploading

### ISSUE THREAD

**Issue by Daniel-KM** [omeka/omeka-s#866]
Hi,

When we create a new item with metadata and files to upload, if there is an error for the upload (even a simple empty upload field), the form is returned empty and metadata are lost.

Sincerely,

Daniel Berthereau
Infodoc & Knowledge management

**Comment by zerocrates** [comment]
This sounds like #802, but we may also have some things to improve to reduce the impact regardless.

The upload input should be required on the client side so that this doesn't let the form be submitted with the error in the first place.

**Comment by zerocrates** [comment]
That commit's not responsive to the actual problem here but it should make it arise less often.

**Comment by Daniel-KM** [comment]
The only issue now is when the file is bigger than the limit size. The same issue occurs for the url of the iiif image.

**Comment by jimsafley** [comment]
Moving this to #802
