### ISSUE TITLE
Modified dates not being stored for Resources

### ISSUE THREAD

**Issue by patrickmj** [omeka/omeka-s#867]
Both 'manually' and via Omeka2Import, updating an Item doesn't store the modified date. To check, just update an existing Item and look in the database for that resource. `modified` is `NULL`

**Comment by zerocrates** [comment]
2 reasons:

1. we're not setting modified date on persist, that's an easy fix
2. Doctrine doesn't trigger the "update" event unless the actual row itself is updated, so edits to values and things like that don't count as an update and don't set the modified date for the Resource.

**Comment by zerocrates** [comment]
Moving these updates into the API may be the simpler course of action... I doubt that getting Doctrine to trigger the update event we want whenever any of the associated records are updated is easy.

The downside is that this will miss out on any updates that circumvent the API, but we really don't have any of those that deal with the Resource entities at the moment, as we've put all their interesting functionality at the API level.
