### ISSUE TITLE
Long class names on vocab list get oddly broken

### ISSUE THREAD

**Issue by patrickmj** [omeka/omeka-s#875]
If a class name is longish, the display in the list of classes breaks the name oddly

![classeswrap](https://cloud.githubusercontent.com/assets/153262/24874615/47dbb406-1df3-11e7-96f2-aed939decfc2.png)
[pizzaOntology.txt](https://github.com/omeka/omeka-s/files/910939/pizzaOntology.txt)

**Comment by zerocrates** [comment]
We're sort of screwed with these things without spaces, unless we want to reorient things completely or have an ellipsis cutoff.

**Comment by patrickmj** [comment]
The Fedora vocab is a pretty egregious offender this way. The labels and properties don't have spaces, and they can push the Items column off the page.

![fedoraproperties](https://cloud.githubusercontent.com/assets/153262/24882640/c4b6682e-1e0f-11e7-9c72-bc696b32579e.png)
