### ISSUE TITLE
Fix UI for bulk editing

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#880]
With a specific eye to:

- checkbox column size
- auto-select/deselect all checkboxes
- general look at the actual edit form

**Comment by zerocrates** [comment]
Issues:

- batch delete all too easy
- batch deletes should show count of items
- batch edit non-all should show count of items
- edit or delete all should possibly show active filters

**Comment by jimsafley** [comment]
@mebrett I made some changes that should make it harder to do bad things. Check it out and re-test.

**Comment by mebrett** [comment]
The bold red text and item count are a great help for cluing in the user that Everything Will Go.
