### ISSUE TITLE
Add UI/option for presenting "links to this" resources on public view

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#886]
It's in the admin, not currently in the public.

**Comment by sharonmleon** [comment]
I know Jim made a commit that made the linked resources visible, but it's only working with the default theme. Will it require theme updates?

**Comment by jimsafley** [comment]
Yes, I suppose it will. I'll work with @kimisgold to incorporate the section in all themes.

**Comment by jimsafley** [comment]
All themes should include linked resources now.

**Comment by kimisgold** [comment]
@sharonmleon We talked about how the table of linked resources includes a lot of repetitive information, namely the resource values already listed earlier in the view. Do we even need to include these rows? When I mentioned this to @zerocrates, he suggested leaving them out by default and providing some kind of option to include them.

**Comment by zerocrates** [comment]
It might be easiest to just walk through `$item->objectValues()` (I believe that's the right one) directly rather than use the helper here at all.
