### ISSUE TITLE
Should YouTube (or other?) media be playable on the item page?

### ISSUE THREAD

**Issue by patrickmj** [omeka/omeka-s#893]
Only noticed this while building stuff for the sandbox. On an item page, where the item has YouTube media, it doesn't play until you click through to the media page.

I would have expected to be able to play the media on the item page, e.g. http://dev.omeka.org/omeka-s-sandbox/s/media-examples/item/251

**Comment by zerocrates** [comment]
Site setting?

**Comment by zerocrates** [comment]
Site setting.

#921
