### ISSUE TITLE
Testing: batch edit and batch delete

### ISSUE THREAD

**Issue by jimsafley** [omeka/omeka-s#896]
Batch edit and batch delete are now up on the develop branch, accessible via the item browse page. There are four batch actions that need testing:

- Edit selected: edit only the items that are selected on the page
- Edit all: edit all the items returned by a search (default is all items)
- Delete selected: delete only the items that are selected on the page
- Delete all: delete all the items returned by a search (default is all items)

When batch editing make sure every item you selected was affected by your changes. Make sure the batch edit interface works as expected, including the add and remove buttons. Test every possible change, including [No change] and [Unset...] options. Test the "batch all" actions by performing several advanced searches and fulltext searches and confirming that only the resulting items were affected by your changes. Also, make sure the batch delete actions prompt you to confirm before running the process.

**Comment by mebrett** [comment]
Confirming expected behavior:
- Conduct search
- Page through search results
- On page 3 of results, select "Delete all" from dropdown. Confirm prompt.

All search results, not just ones on page, are deleted.

**Comment by jimsafley** [comment]
Yes, that's expected. The "batch all" actions operate on all items of the current result, regardless of what page you're on.

**Comment by mebrett** [comment]
Thanks - I thought so but wanted to be sure (will need to make that clear in the documentation)

**Comment by mebrett** [comment]
Found another small bug - in an effort to delete only some of my search results I used the "all these checkboxes" master checkbox... but then I don't get the option to Delete Selected (or edit). Same behavior if browsing all items (not just on search results)

<img width="1025" alt="screen shot 2017-04-27 at 4 14 20 pm" src="https://cloud.githubusercontent.com/assets/2314070/25502503/cfdb19a4-2b64-11e7-8a74-fbfc10b63657.png">

**Comment by jimsafley** [comment]
@kimisgold This is related to the JS you wrote. It seems checking "select-all" does not automatically trigger the change event that enables the "batch selected" actions.

**Comment by kimisgold** [comment]
@mebrett The batch selected actions should now take into account that select all checkbox.

**Comment by mebrett** [comment]
@kimisgold That fixed it, thank you

**Comment by mebrett** [comment]
The confirm delete message is the same whether you're doing selected or all. These *need* to be different to reinforce which choice the user has made.

Delete selected:
![screen shot 2017-05-01 at 12 21 33 pm](https://cloud.githubusercontent.com/assets/2314070/25585490/c59b73ce-2e68-11e7-9b0e-7e626a720544.png)

Delete all:
![screen shot 2017-05-01 at 12 21 44 pm](https://cloud.githubusercontent.com/assets/2314070/25585491/c69c122e-2e68-11e7-8a3a-595d8524d327.png)

**Comment by mebrett** [comment]
We had five people using bulk edit at once yesterday, and other than discovering that it's entirely too easy to accidentally delete all, there were no problems
