### ISSUE TITLE
Figure out multilanguage sites

### ISSUE THREAD

**Issue by patrickmj** [omeka/omeka-s#898]
We have a way to tag language for values, but don't yet have a system for using them, other than the signal about what language a value has set. Seems like some way to 1) set a language, or languages to display and 2) filter based on that setting might be in order. Alternatively, people have suggested a way to have multiple sites that use different languages (which sounds like a site setting). Either of those approaches sound like having the theme be able to know what language(s) to display and filter values accordingly.

One feature we know people want is on-the-fly language switching, without being logged in and without changing browser setting. However, a system that _can_ work with browser settings also makes sense for the filtering.

See convo on the forums https://forum.omeka.org/t/internationalized-omeka-s/3154

**Comment by elrossco22** [comment]
one to follow @stephenwf @euanfergusson

**Comment by patrickmj** [comment]
If I remember right from our conversation, it sounded like we'd look at the approach you need for your deadline and go from there?

**Comment by Daniel-KM** [comment]
An example of Omeka S project in multilanguage (French, English, Turkish), where the language code is the site: http://ifeaistanbul.net/omeka-s/.

**Comment by patrickmj** [comment]
@Daniel-KM Interesting. Is this items with metadata in the three languages, then the theme decides which to display? Or is it distinct items for each language?

**Comment by euanfergusson** [comment]
looks like 3 omeka sites, where the site slug is also set to the language code?

**Comment by Daniel-KM** [comment]
They are the same items. Each metadata is translated in three language and the user choose the main language, that is related to the interface, then it displays only the good language for metadata.

**Comment by zerocrates** [comment]
One option I've been thinking about is to have a language setting in the site settings, which would go along well with a pattern of having a site-per-language type setup.

**Comment by euanfergusson** [comment]
its an interesting approach and may work for some, but isnt multilingual , its multisite

**Comment by zerocrates** [comment]
Well I'd say it's a bit of both, but no need to quibble over the wording.

Having this (choosing language for a site in its settings) wouldn't preclude other ways of dealing with multilingual content (like separating values from different languages and allowing users to interactively select the content/UI language they want). Where "multisite" and "multilingual" start to cross over though, is in "site" content: static pages and so on. as those aren't stored in parallel or language-tagged like resource values are. That's where tying the default language support to a site starts to make a good deal of sense.

**Comment by patrickmj** [comment]
Yes, the two different approaches will appealing to different projects as different design choices. Both, though, need the theme work to figure out what to display, so that might be a common system to think through.

**Comment by euanfergusson** [comment]
@zerocrates that could prove problematic re static pages, ideally we dont want to build multiple pages. Perhaps adding something to the pages db table (or other means to identify a page language) is the first step we need to take.

**Comment by patrickmj** [comment]
Interesting -- while we have the language tag for metadata values, it doesn't look like there's a good way to tag all of the aspects of display. That would go beyond site_pages down to site_page_blocks, and continue over to media attached to items (e.g., HTML media). That could lead into a pretty heavy lift.

**Comment by hajoki** [comment]
Hello, I confirm http://ifeaistanbul.net/omeka-s/ is a multisite approach. 
How are things going about the general approach Omeka S want to adopt for multilingual sites?
Good luck everyone!

**Comment by euanfergusson** [comment]
@hajoki , we have started developing a module for it. Not sure what is happening re this from Omeka's end.

**Comment by patrickmj** [comment]
Thanks @hajoki and @euanfergusson ! It's good to see what people building sites want and need, per the above discussion. Debates are continuing here at RRCHNM about what will be most helpful. Links to code -- both themes and modules -- for us to look in-depth at the approaches will be helpful to us.

**Comment by euanfergusson** [comment]
will keep you in the loop

**Comment by euanfergusson** [comment]
@patrickmj @zerocrates - has any of the discussions so far focused on how pages an or interaction with the api will be handled ?

**Comment by hajoki** [comment]
Sure, I uploaded the theme I use: https://github.com/hajoki/istanbul

**Comment by patrickmj** [comment]
@euanfergusson not a lot on those fronts, though I suspect that API considerations will just pass along all data available with the language codes where they exist.

**Comment by euanfergusson** [comment]
@patrickmj @zerocrates 

quick request for the multilingual elements. Can we include the name of the language in the mo/po files. Looking at the Omeka files , the word "Deutsch" doesnt appear in the file anyway - meaning we need to manually translate the actual name of the Language

**Comment by zerocrates** [comment]
The trick there is that for our translation platform, everything needs to be translating from the same English strings, so unless we want to have an ever-growing translation in each language of the name of every other language, we can't easily accomplish this (unless we cheat and make a "fake" source string which each language translates as its own name).

However, we have the same problem solved in Classic by just using an external source for the language strings. In Classic we have to use Zend's Locale component which is based on ICU data. The equivalent in S would be using PHP's `intl` support, so something like http://php.net/manual/en/locale.getdisplayname.php I'd imagine.

**Comment by euanfergusson** [comment]
@patrickmj @zerocrates - shall look into that 

Can we also get a en_GB translation set up at transfix ? (need to deal with your countries obsession with 'z' and inability to spell colour ;) )

**Comment by hajoki** [comment]
Hello everyone,
Can we have a bit of visibility about what is going on about Omeka S' way of dealing with multilanguage sites? @euanfergusson, do you have any idea of when your module could be ready?

At the moment, even with a multisite approach, I cannot have a clean multilanguage site because:
- the strings enclosed in <?php echo $this->translate(); ?> display invariably in English
- tags in all languages display all together.

Can we open the Transifex project to start translating the strings in translate()?
As for tags, I know @Daniel-KM is waiting to see the coming choices of Omeka S team to make changes in Folksonomy.

Thanks for your work and news!

**Comment by Daniel-KM** [comment]
On this subject: in fact, any content or module content may have a language (tags, comments, etc.). And the visitor should be able to switch from one language for the interface or for the metadata, independantly. 

So it is rather a theme related question, but the value of the language may be saved as a specific value, or as a value managed widely in all Omeka.

**Comment by zerocrates** [comment]
The Transifex project for S is already open: https://www.transifex.com/omeka/omeka-s/

**Comment by hajoki** [comment]
Thank you for the link, I requested the creation of Turkish and French and asked to join the team but I still cannot access to any translation, is there something I miss?

**Comment by zerocrates** [comment]
I'll see if there's something we need to fix over on the Transifex side, but at least some translations have been coming through

**Comment by zerocrates** [comment]
Let's try this: there are older preexisting "teams" for "French" and "Turkish (Turkey)". Can you try asking to join those instead?

**Comment by hajoki** [comment]
Of course I would love that, but I cannot find the access... 
When going there https://www.transifex.com/omeka/omeka-s/, signing in, in the long list of languages first there was no French nor Turkish, that's why I tried "Request the language". 
Now there are appearing but I could not enter in them, that's why I tried "Join the team"
but I did not change anything yet, do I miss something about the functioning of the site?

**Comment by zerocrates** [comment]
@hajoki I've manually added you to those two teams

**Comment by hajoki** [comment]
Perfect, now I can enter!

**Comment by margari** [comment]
@Daniel-KM hello, I am trying to check out your installation (http://ifeaistanbul.net/omeka-s/ ), but it seems that is not working at the moment... or maybe it has another url?
I would like to have multilanguage sites and themes for my Omeka. Could you help me please?
Thank you :-)

**Comment by hajoki** [comment]
Hello @margari, yes sorry the installation has moved to http://archivis.ifea-istanbul.net
This installation uses 3 sites, one site per language, to present the same items and item sets, but also check out the new features of Omeka S (language parameter for a site, etc.) to see what suits you needs best. Feel free to write in Omeka forum to receive help from the community.

**Comment by margari** [comment]
Thank you so much!!

**Comment by jogogo2** [comment]
Hi, I want to create a multilingual site with Omeka S (Catalan, Spanish and English), with the ability of switch among languages easily.
@euanfergusson , will you realease your module when ready freely in order to be used by others? (like me), can you explain more in detail how it works?
I really will apreciate your help.
Thanks.

**Comment by garcicar** [comment]
Hello, there is any progress in the multilingual functionality? For now, we have added the language ISO code to the properties, so we have each property duplicated 3 times (for every language). @euanfergusson finally did yo create the module?

Many thanks,

**Comment by zerocrates** [comment]
The major development here is that there's a new options for sites to select and display only values tagged with the site's configured language.
