### ISSUE TITLE
Select properties to include in the browse preview block

### ISSUE THREAD

**Issue by sharonmleon** [omeka/omeka-s#906]
Can we offer the ability to set which properties are included in a browse unit? Right now it's Title and Description, but with the amount of flexibility offered by the LOD vocabs, it would be nice to be able to select what gets included.

**Comment by zerocrates** [comment]
Uh, this could probably be selected with options for the block, like choosing the heading property and the body property(s) or something like that? Is that what you're looking to be able to do?

**Comment by sharonmleon** [comment]
Yes. Thank you.

**Comment by jimsafley** [comment]
The [browse-preview-select-properties](https://github.com/omeka/omeka-s/compare/browse-preview-select-properties) introduces configurable heading and body properties for the browse preview block. I wonder if we should move `BrowsePreview::getProperty()` to `AbstractBlockLayout` so other block layout classes can utilize it.

**Comment by zerocrates** [comment]
The remaining question I had about this was whether the title/description setting should actually live on the Site, so it could affect the actual browse page itself. It adds a valuable consistency between the preview block and the actual browse, but it also means you can't have different settings for these different places within the same site.

As for the block itself as-is, I'm not sure about the usage of displayTitle and displayDescription as the defaults. This means you'll have a fallback to the "real" title/description before "Untitled." Is that confusing?

As for getProperty, can we reorient things to just eliminate it? It seems like all the block needs to know is the term string, so can that just be what comes from the selector in the first place? Seems unnecessarily circuitous to select out and store the property ID in the block just so we can go back to the database with that to get the term string, to then go back to the database with _that_ to actually look up the property to display (as the value helper will do). I suppose this is just a limitation of propertySelect but it should be a fairly trivial change (just a matter of how to expose that choice).

**Comment by jimsafley** [comment]
> whether the title/description setting should actually live on the Site, so it could affect the actual browse page itself. 

Yes, consistency between the blocks and the browse page is the desired behavior here. I'll move the fields to the Site settings.

> I'm not sure about the usage of displayTitle and displayDescription as the defaults

You're right. The heading/body should only reflect the configured properties and not fall back to title/description (unless they are configured as title/description, of course).

> As for getProperty, can we reorient things to just eliminate it?

I'll look into it.
