### ISSUE TITLE
Confusing CSRF error message when upload item is too large

### ISSUE THREAD

**Issue by crism** [omeka/omeka-s#907]
If a user tries to upload media that exceeds some limit (I believe the limit set in `php.ini`), the upload page displays “CSRF: Value is required and can't be empty,” which only serves to confuse the user.

**Comment by zerocrates** [comment]
The reason this happens is that when you go over the post_max_size, PHP just drops all the data out of the request entirely. We see this as you missing the CSRF token on the page and so we throw that error.

PHP doesn't really tell us in a useful way that you've gone over the limit, but we may be able to detect this in some other way.

**Comment by crism** [comment]
In `ItemController::addAction()`, the form data is populated with `$this->params()->fromPost()`. However, since PHP has already rejected the post at a lower level, that comes back empty. Validation then fails on the first required field.

(There is a warning to the user on the Media upload form, but it’s hidden by default.)

**Comment by crism** [comment]
Ah, @zerocrates—crossed signals. `(-:` My first preference would be to see if we can detect that PHP has rejected the post as too large—but if not, give a more meaningful message when a post comes in apparently with no data, with a diagnostic suggestion.

**Comment by crism** [comment]
This fix inexplicably[*] causes user account creation to fail:
```
[Thu May 18 11:46:15.597082 2017] [:error] PHP Notice:  Undefined index: user-information in .../omeka-s-dev/application/src/Controller/Admin/UserController.php on line 45, referer: .../omeka-s/admin/user/add
[Thu May 18 11:46:15.597135 2017] [:error] PHP Catchable fatal error:  Argument 2 passed to Omeka\\Api\\Manager::create() must be of the type array, null given, called in .../omeka-s-dev/application/src/Mvc/Controller/Plugin/Api.php on line 94 and defined in .../omeka-s-dev/application/src/Api/Manager.php on line 71, referer: .../omeka-s/admin/user/add
```
I’m looking into it…

[*] Nothing is inexplicable, but I sure don’t understand this yet.

**Comment by zerocrates** [comment]
My preference for fixing this would be to move to a higher layer to detect the issue, somewhere like a MVC controller/dispatch event listener, where we can just check if the current request is a POST with no data submitted, then do something like throw an exception if so (optionally checking to see if there's a request length, as I believe that remains intact even after PHP trashes the post data).

As for why your solution is failing: it's probably the call to `getInputFilter()`. Zend's form code does some... interesting (terrible) things when you do things like getting the input filter at not the exact time they expect you to, and it tends to cause somewhat baffling breakage. We've had to move things around more than once to ensure that nothing with the filters happens until after all elements have been created.

Anyway, I maintain it's probably better not to have the solution live in the Form at all, so the solution can apply equally to API requests among other reasons.

**Comment by crism** [comment]
All right… I’ll withdraw this PR, but leave #907 open. We’ll just have to educate our users about what CSRF means to them, in the meanwhile.

**Comment by zerocrates** [comment]
Something else I've mulled over is adding some JS to prevent form submission when a file is over-size. That should be easier to accomplish without messing around in the internals and allow for a nice relevant message immediately.

It won't cover every situation that can cause this, but it'd probably catch 80% or so.

**Comment by crism** [comment]
There’d still be edge cases; with post and file size limits of 16 MB, a 15.99 MB file plus the other form submission items might push the entire POST payload over the limit, so the server-side check remains necessary. The JavaScript helper would definitely save some time in the case of really large uploads, though; PHP doesn’t close the connection, it just stops paying attention.

**Comment by jajm** [comment]
Hi,

https://github.com/omeka/omeka-s/commit/f12adb0ba9182018b8bbd941681215f8f72005ff is making some of my tests fail with the following error

    Undefined index: CONTENT_LENGTH

Couldn't it be replaced with `$request->getHeader('Content-Length', 0)` ?

**Comment by jajm** [comment]
Thanks for the fix!
