### ISSUE TITLE
Misleading CSRF error when trying to delete an item

### ISSUE THREAD

**Issue by crism** [omeka/omeka-s#910]
From the item editing page, if a user selects the Delete button, and does not have sufficient privileges to do so, they are asked to confirm the decision to delete, but then come back to the item list with a message, “CSRF: Value is required and can't be empty.”

**Comment by zerocrates** [comment]
Hmmm, that's an interesting one for sure... I suppose we're just not rendering the appropriate pieces of the delete form.

**Comment by zerocrates** [comment]
So this is when a user clicks the Delete button in an edit page but they don't have delete privileges?

These are Reviewer users? Or some custom role?

**Comment by zerocrates** [comment]
Similar to your other issue, if this is truly a privs issue, we should just not be showing the Delete button at all.

**Comment by crism** [comment]
Agreed the button should not be shown. In this case, the item was created by a System Administrator, and an Editor is trying to delete it. (To my surprise, the Editor can _edit_ it, but not delete it.)

**Comment by zerocrates** [comment]
Hmm, something's not right there.... by default permissions, Editors should be able to edit _and_ delete any item.

**Comment by zerocrates** [comment]
You're sure it's not a Reviewer? They _do_ have the permissions you're talking about (edit, but not delete).

**Comment by zerocrates** [comment]
There are some areas where the UI is improperly showing deletion options when the user doesn't have that privilege, but in my testing, trying to do these always results in a standard 403 error, not a CSRF one.

**Comment by crism** [comment]
I can confirm that I made this resource (an Item with an associated PDF Media) as a Systems Administrator, and I’m now looking at it from a separate Editor account.

As the Editor, I can edit the item, and when I select the Delete button, I get a confirmation request; upon confirming deletion, I still get the CSRF error. The same thing happens using the trash can icon in the Items list; confirmation now appears (since #909 is fixed), but confirming deletion causes the CSRF error.

**Comment by zerocrates** [comment]
This CSRF error is something different... the privilege checks in these places are correctly represented in the UI now, so as far as the ACL is concerned, your Editor does indeed have permission to delete that item.

Something else is causing the CSRF problem, and I'm not sure what. I can't reproduce it at this time.

**Comment by crism** [comment]
Oh, weird—it looks like the `delete` request was cached; the network monitor shows a 302 Found response. That’s… odd.

**Comment by crism** [comment]
```
130.126.152.146 - - [09/May/2017:14:10:44 -0500] "POST .../omeka-s/admin/item/1/delete HTTP/1.1" 302 - ".../omeka-s/admin/item" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:53.0) Gecko/20100101 Firefox/53.0"
```
A `delete` request should really never return a 302, IMO.

**Comment by zerocrates** [comment]
The Found issue could be related, though. Can you check your .htaccess file? Older versions of S have a rule in there that redirects with a 302, while the current version uses 307. Really there shouldn't be any redirecting happening here but this rings a bell.

**Comment by crism** [comment]
That could be it… this installation has been around since at least 1.0.0-beta2, and the `.htaccess` may be a legacy. Switching to the distribution version… but no, still a 302 and the CSRF error.

**Comment by crism** [comment]
I still suspect a problem with `$form->setData()` and `$form->isValid()`—the `ItemController::deleteAction()` assesses the form and sets messages before calling `$this->redirect()`, which is presumably the source of the 302 response. The CSRF error would be consistent with `setData()` getting no information. However, the necessary stuff is there, and unlike with #907, there’s no error message indicating PHP dropped the POST data on the ground… I’ll keep investigating.

**Comment by crism** [comment]
The `postData()` definitely comes through, but `isValid()` comes back false.

**Comment by zerocrates** [comment]
That's consistent with what you're seeing, that the CSRF check is failing, as it's the only thing being checked there. So there's somehow a mismatch between the stored CSRF token and what's being submitted with the form... The particularly puzzling aspect is that it's only for this user. The CSRF code operates the same way for all users, and applies equally to administrators as it does any other role.

**Comment by crism** [comment]
Ah-hah… thank you for highlighting a bad assumption. I was testing privilege problems when I ran across this, but it actually applies to the System Administrator user who first created the Item, too.

**Comment by zerocrates** [comment]
Ah, well that is a useful piece of information for sure... but still puzzling.

**Comment by zerocrates** [comment]
So let's just check: are you able to do other things that require a POST, like creating a new item?

**Comment by crism** [comment]
Yes. As System Administrator, I just created a trivial item with no media. I then went to the Items list and tried to delete it with the trash can icon; I got the confirmation firm, but then the CSRF error, and the item is still present.

**Comment by zerocrates** [comment]
Does changing browsers (or devices) have any effect?

**Comment by crism** [comment]
Yes, Chromium and Firefox for Linux, and Firefox for Windows, all have the same problem. It definitely appears to be something on the server side—the POST is properly-formed (as far as I can tell), but something goes wrong…

This is not a 100% clean install from scratch, as [noted above](#issuecomment-300280581). I’ll try a fresh checkout and see if it does the same thing. This is PHP 5.6.30, running on RedHat 7.3, if that makes a difference…

**Comment by crism** [comment]
A completely clean install works. I’m closing the issue.

While installing the clean version from git, I noted that I had never run `npm` in my dev test site, when switching from packaged installs to git-based. Initializing `npm` in the dev site doesn’t fix this problem, but it’s possible that things have already gotten in some kind of weird unrecoverable state as a result.

**Comment by crism** [comment]
Just to confirm: using my clean install as the basis, migrating files and database credentials from the dev site, a clean delete now works fine.

**Comment by zerocrates** [comment]
This is a somewhat unsatisfying conclusion to the issue, but it's good to hear that you've gotten past it.

**Comment by KihOshk** [comment]
Hey all,

I'm playing with a fresh copy of the newest version of O-S on CentOS 7 / PHP 7.0.23 / 5.5.56-MariaDB 

I'm unable to delete users and items; both result in "CSRF: Value is required and can't be empty" errors. 

The only unusual step I took in setting up the new instance was to change the first-user's email address while finalizing its properties. I've also tried creating new Global Administrator accounts under different emails (obviously) in hopes of their being able to remove items/users...same issues.

On a frustrating side-note, application.log and sql.log files aren't logging anything although I have set:
**SetEnv APPLICATION_ENV "development"**
...in **.htaccess**.

In any case, here're Apache access-log examples...no pertinent errors in the error-log though:

192.168.10.1 - - [03/Oct/2017:15:41:50 -0400] "GET /admin/user/2/delete-confirm HTTP/1.1" 200 784 "http://library.microsopht.com/admin/user" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36"
192.168.10.1 - - [03/Oct/2017:15:41:51 -0400] "POST /admin/user/2/delete HTTP/1.1" 302 - "http://library.microsopht.com/admin/user" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36"
192.168.10.1 - - [03/Oct/2017:15:41:51 -0400] "GET /admin/user HTTP/1.1" 200 11331 "http://library.microsopht.com/admin/user" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36"

192.168.10.1 - - [03/Oct/2017:15:54:49 -0400] "GET /admin/item/3/delete-confirm HTTP/1.1" 200 1040 "http://library.microsopht.com/admin/item" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36"
192.168.10.1 - - [03/Oct/2017:15:54:50 -0400] "POST /admin/item/3/delete HTTP/1.1" 302 - "http://library.microsopht.com/admin/item" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36"
192.168.10.1 - - [03/Oct/2017:15:54:50 -0400] "GET /admin/item HTTP/1.1" 200 19206 "http://library.microsopht.com/admin/item" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36"

Any insight would be appreciated; I'm hoping I can avoid setting up a new instance to correct the issue. I'm anxious to start doing some meaningful work with Omeka S. I'm pretty impressed only after about 20-minutes of playing around with it; it'll really improve management of multiple sites I'm managing. 

Thanks!

**Comment by patrickmj** [comment]
Could you tell exactly which version of Omeka S you are trying? That is, is it something you grabbed from GitHub, or from the packaged up release. The version number will be at the bottom of the admin pages.

**Comment by KihOshk** [comment]
Hey @patrickmj 

Here's my system-info. I'll set up an admin-account on it if you send me an email and want to poke around; it's publicly accessible.


```
Omeka S
--
1.0.0-beta4

7.0.23
apache2handler
128M
8M
2M
Yes
apache2handler, bz2, calendar, Core, ctype, curl, date, exif, fileinfo, filter, ftp, gettext, gmp, hash, iconv, json, libxml, mysqli, odbc, openssl, pcre, PDO, pdo_mysql, PDO_ODBC, pdo_sqlite, Phar, Reflection, session, shmop, SimpleXML, sockets, SPL, sqlite3, standard, tokenizer, xml, Zend OPcache, zip, zlib

5.5.56-MariaDB
5.5.56-MariaDB
 

Linux 3.10.0-693.2.2.el7.x86_64 x86_64

```

**Comment by patrickmj** [comment]
Thanks. I wasn't immediately able to recreate the issue on my dev environment, and there have been a lot of changes since beta4 that aren't in packaged releases -- they're just in the development code. Hopefully, it'll turn out that this is solved in later code, but I'll check around.

**Comment by KihOshk** [comment]
Much appreciated!

**Comment by patrickmj** [comment]
There's also all the preceding discussion to check through, to see if it's the same thing or something different. I reopened just to remind us to look into this mystery.

**Comment by zerocrates** [comment]
Yes, I believe this is an issue that was fixed just after the beta4 release: #957

**Comment by KihOshk** [comment]
Thanks for the feedback. Can you recommend a method to circumvent this protection until beta5 is released?

**Comment by KihOshk** [comment]
For my assessment purposes, I disabled the CSRF check by changing the form-element type from 'csrf' to 'hidden' in **/application/src/Form/Initializer/Csrf.php** . 

```
//          'type' => 'csrf',
            'type' => 'hidden',
```

Of course, I assume the risk, but if anyone can give me a reason NOT to do this until the next release, please let me know. There are no mission-critical assets on my isolated instance.

**Comment by crism** [comment]
@KihOshk, I had seen this reappear, too, but was still trying to track it down… thanks for confirming that I wasn’t going nuts. `(-:` @zerocrates, thanks for the fix. Looking forward to deploying it.

**Comment by KihOshk** [comment]
Hey all, 

Just to confirm that RC1 has resolved my CSRF issues.

Thanks!

**Comment by crism** [comment]
@zerocrates, @KihOshk, I also saw this come back, and also saw that RC1 seemed to resolve it. I don’t want to close this since someone else re-opened it, but I’m comfortable with it being closed.

**Comment by zerocrates** [comment]
With the consensus being that it's fixed, I'll go ahead and close it.

Thanks for the feedback, everyone.
