### ISSUE TITLE
Reimporting an existing vocabulary?

### ISSUE THREAD

**Issue by mattmcgrattan** [omeka/omeka-s#912]
Is there a process for reimporting an existing vocabulary? Was this fixed in a recent commit?

Or is it still the case that the vocab needs to be deleted and then reimported? With the concomitant effect on the Items/Item Sets that use that vocab?

Thanks!

Matt

**Comment by jimsafley** [comment]
Updating vocabularies was added in #848. In the admin interface edit the vocabulary and select a file using "Update vocabulary".
