### ISSUE TITLE
Installation screen/wizard

### ISSUE THREAD

**Issue by elrossco22** [omeka/omeka-s#914]
Perhaps more of a nice to have than a feature, Can you confirm if there is plans for a web installation screen/wizard on the future roadmap. A good example of this would be Wordpress ( [http://cdn2.wpbeginner.com/wp-content/uploads/2016/01/wpinstall-dbsettings.png] (http://cdn2.wpbeginner.com/wp-content/uploads/2016/01/wpinstall-dbsettings.png))

This would alleviate the need for users to have to manually edit config files to get a basic Omeka-S instance up and running

**Comment by zerocrates** [comment]
There aren't any current plans for this.

In general. we like to avoid the server having to have write access outside the file upload directory, as would be required for us to write the configuration file.
