### ISSUE TITLE
Symlinked directories show wrong error

### ISSUE THREAD

**Issue by stephenwf** [omeka/omeka-s#918]
When the call is made to check `is_dir` and the directory is a symbolic link this returns false.
https://github.com/omeka/omeka-s/blob/master/application/data/scripts/update-db-data-module.php#L26

However the issue is more likely around the permissions on the symlink itself. It would be useful for this error to be better relayed to users. I've not tested, but `is_link()` and `is_readable()` together might avoid false positives on symlinked modules.

**Comment by zerocrates** [comment]
Permissions on the symlink itself are almost never relevant...

I'm thinking we can just use `realpath` here to dereference any possible link.

**Comment by zerocrates** [comment]
`realpath` shouldn't do much to help since `is_dir` should already work on a link...

Without more detail about the permissions situation that causes the error in the first place I don't think we can do much about this. I don't even have a system that allows me to set symlink permissions.
