### ISSUE TITLE
Long titles smoosh the action icons in Items list

### ISSUE THREAD

**Issue by patrickmj** [omeka/omeka-s#919]
Looks like something that got introduced with the big style upgrades on the admin side:
![longtitles](https://cloud.githubusercontent.com/assets/153262/26010104/9190aa0e-3719-11e7-8a8f-7e5f02e76bef.png)

**Comment by kimisgold** [comment]
@patrickmj Should be fixed in 234afa9. Could you pull and see if it works for you?

**Comment by patrickmj** [comment]
Yes, but want to confirm that the intent was to make the three action appear on two rows instead of just one like it was before.

**Comment by zerocrates** [comment]
@patrickmj updated screenshot?

**Comment by kimisgold** [comment]
![screen shot 2017-05-12 at 5 42 59 pm](https://cloud.githubusercontent.com/assets/606764/26018017/89f24764-373a-11e7-9ffe-82f76754ded1.png)

This is how I intend for the browse tables to look. If they don't look like this on your installation, let me know because something has gone wrong.

**Comment by patrickmj** [comment]
Related to the bump to two lines for the title?

![longtitle2](https://cloud.githubusercontent.com/assets/153262/26018130/16658b7a-373b-11e7-99c3-ae6eee7fe95e.png)

**Comment by patrickmj** [comment]
Zoom level also a factor -- here it is zoomed out to 80%

![longtitles3](https://cloud.githubusercontent.com/assets/153262/26018216/7ff78c0a-373b-11e7-866c-ce419134f653.png)

**Comment by patrickmj** [comment]
A couple 3 liners, if it helps

![threeliners](https://cloud.githubusercontent.com/assets/153262/26018664/3a3f91e6-373e-11e7-8ce4-5decf3637553.png)

**Comment by patrickmj** [comment]
Same happens on Item Sets page

![itemsets](https://cloud.githubusercontent.com/assets/153262/26066103/dd4a2dd4-3963-11e7-8b56-31f222d13aa3.png)

**Comment by kimisgold** [comment]
@patrickmj Can you empty your cache/hard refresh and let me know if you're still seeing action icons on multiple lines? I'm having trouble reproducing what's in your screenshots.

**Comment by patrickmj** [comment]
@kimisgold yep, cleared cache, hard refresh. No change. Both FF and Chrome

**Comment by patrickmj** [comment]
huh. looks like Metadata Browse is the culprit

**Comment by zerocrates** [comment]
Regardless, it might be better to use flexbox's styling here rather than min-width...

`flex-shrink: 0` on the actions ul will stop flexbox from compressing it onto 2 lines like this, basically making the min-width whatever's appropriate for how many actions are there

Similarly, instead of an auto margin, we could have `flex-grow: 1` on the title (or on the actions ul itself, if we also add text-align right).
