### ISSUE TITLE
User-friendly select boxes

### ISSUE THREAD

**Issue by jimsafley** [omeka/omeka-s#920]
Some of our select boxes are, or have the potential to be, long and unwieldy. For example, the "Resource Template" and "Class" selects on the item form can become quite large. Anticipating user requests, we should look into comboboxes, where a user can easily filter the available options, much like our sidebar selectors.

There's a WIP using the popular [Chosen](https://harvesthq.github.io/chosen/) JS library on the [chosen-select-boxes](https://github.com/omeka/omeka-s/tree/chosen-select-boxes) branch.

**Comment by jimsafley** [comment]
Chosen uses its own styling that we'll need to modify to fit in better with ours. These changes remove some of the more glaring differences:

```diff
diff --git a/application/asset/vendor/chosen-js/chosen.css b/application/asset/vendor/chosen-js/chosen.css
index 2b7bb92..e267f8a 100644
--- a/application/asset/vendor/chosen-js/chosen.css
+++ b/application/asset/vendor/chosen-js/chosen.css
@@ -15,7 +15,7 @@ This file is generated by `grunt build`, do not edit it by hand.
   position: relative;
   display: inline-block;
   vertical-align: middle;
-  font-size: 13px;
+  font-size: 16px;
   -webkit-user-select: none;
      -moz-user-select: none;
       -ms-user-select: none;
@@ -68,11 +68,9 @@ This file is generated by `grunt build`, do not edit it by hand.
   display: block;
   overflow: hidden;
   padding: 0 0 0 8px;
-  height: 25px;
+  height: 27px;
   border: 1px solid #aaa;
-  border-radius: 5px;
   background-color: #fff;
-  background: linear-gradient(#fff 20%, #f6f6f6 50%, #eee 52%, #f4f4f4 100%);
   background-clip: padding-box;
   box-shadow: 0 0 3px #fff inset, 0 1px 1px rgba(0, 0, 0, 0.1);
   color: #444;
```

**Comment by zerocrates** [comment]
We'd probably want to do any tweaks to this in our own CSS, rather than editing theirs.

**Comment by jimsafley** [comment]
@kimisgold Would you mind looking at this on the [chosen-select-boxes](https://github.com/omeka/omeka-s/tree/chosen-select-boxes) branch? We want your opinion on a) the general approach to more user-friendly select boxes, b) whether [Chosen](https://harvesthq.github.io/chosen/) is a good choice, and c) if so, the best way to style the selects created by Chosen.

**Comment by kimisgold** [comment]
I think this looks great. It's keyboard accessible, the autocomplete makes selection faster, and I had no problem overriding the default styles with our own (daec3be).
