### ISSUE TITLE
Release updated beta

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#923]

**Comment by patrickmj** [comment]
For #863 , I figure that we should just put it on the beta4 release when it is finalized and master is updated?

**Comment by zerocrates** [comment]
Yes, that's probably best.

**Comment by zerocrates** [comment]
So I take it then that you're on master now, so the beta3 release? This will cause (and is causing) problems with the themes that are on newer commits, as those are written against the develop version. (For example things like the advanced search and javascript are busted).

**Comment by patrickmj** [comment]
yep and yep. Everything is on master -- core, themes, and modules (except default theme, which doesn't have a master branch). So, when themes and modules work against core master, that'll be the time to fire up the sandbox.
