### ISSUE TITLE
Quick Add: Clicking outside the checkbox should select the resource's checkbox when quick-add is active

### ISSUE THREAD

**Issue by jimsafley** [omeka/omeka-s#924]
Right now clicking outside the checkbox a) does nothing, or b) opens the options sidebar for that individual resource.

**Comment by kimisgold** [comment]
@mebrett This needs to be tested in two places: the editors for items and pages. Test that the quick add works for both creating multiple resource values for an item as well as adding multiple resource attachments to a page block. Click on both the checkboxes as well the item/resource titles and confirm that they work identically when in quick add mode.

**Comment by mebrett** [comment]
Is there a specific branch for this or is it on develop?

**Comment by zerocrates** [comment]
develop

**Comment by mebrett** [comment]
Both work identically and check when clicking on checkbox and title. It doesn't work when clicking on the thumbnail/thumbnail placeholder, which I sort of would like but isn't necessary.

**Comment by kimisgold** [comment]
@mebrett Images should work now.

**Comment by mebrett** [comment]
Images work smoothly on item edit.

When adding resources to a site page block, clicking on the image opens the item details - I think to give you the option to pick from multiple files if it's there? - but closing that view with an X takes you back to the quick select and the resource is marked as checked. So it works, just with a bit of a detour.

Attached image shows what opens when you click on image for a resource in site page edits:
<img width="310" alt="screen shot 2017-06-02 at 3 21 34 pm" src="https://cloud.githubusercontent.com/assets/2314070/26741477/85b05e52-47a7-11e7-9a88-c6fba4a8d43b.png">

**Comment by zerocrates** [comment]
pretty sure that's a bug, not intended

**Comment by zerocrates** [comment]
@kimisgold yeah, the previous commit you did for this issue seems problematic: minimally it's not respecting the `showDetails` flag (you'll see that the "main" link for the item's text does do so).

Might be a better move to just wrap a single link around both the image and the text?
