### ISSUE TITLE
Double-check file deletion

### ISSUE THREAD

**Issue by patrickmj** [omeka/omeka-s#927]
I just did a batch delete of all my items, but when I look at the files folder I still see lots of files and derivatives. Can anyone confirm this? It might just be something weird with all the import/delete cycles I've been doing.

**Comment by jimsafley** [comment]
I can't reproduce this. I batch-deleted all and all my originals and derivatives were removed.

**Comment by patrickmj** [comment]
likely oddities in my various imports, then.
