### ISSUE TITLE
Removing filters for a site's pool is a bit confusing

### ISSUE THREAD

**Issue by patrickmj** [omeka/omeka-s#929]
There might be more variations on this, but what I noticed was around item sets. (see also #928)

When there are multiple item sets chosen and I want to remove them, I see the handy trashcan icon and click it to remove things. However, once I get down to a single remaining item set, the trashcan is no longer there, and I don't really know what to do. 

It turns out that for that last one, I have to choose "Select item set" from the remaining dropdown to finally clear out that data, then save that, but that's far from intuitive.

**Comment by zerocrates** [comment]
The same thing happens with the advanced property search, and it's a little worse there since there are multiple options in each row.
