### ISSUE TITLE
Awkward UI for Item with metadata when no resources available

### ISSUE THREAD

**Issue by patrickmj** [omeka/omeka-s#930]
If I've managed to have no resources available for a site, when I try to add a page using Item with metadata the list gives a curious "1 of 0" list of pages.

![oneofzero](https://cloud.githubusercontent.com/assets/153262/26269732/aa1b5780-3cc4-11e7-911c-ef2915eefe9c.png)

Maybe if there are no resources available, that sidebar could offer suggestions for what might be going wrong, directing them to the site's resources page?

**Comment by kimisgold** [comment]
@patrickmj If no resources are available, no pagination should appear and the sidebar should tell you no resources found.
