### ISSUE TITLE
Think about file extension replacement policy

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#934]
Current behavior is to _only_ accept extensions from the list we source from Apache. If we know the mimetype of the file but the extension is either missing or not in the list of extensions we know for that type, we replace it with the first one that we _do_ know about.

This can lead to some strange results... Many types of files will be detected as "text/plain" because the detector can't tell they're of some more specific type, like .csv. Our extension list "knows" .csv, but only for "text/csv," a more specific type we aren't likely to detect. The result is, we throw out the .csv extension we got and replace it with .txt.

Besides just being confusing and possibly breaking things that try to key off the extension (as file renderers can do), this becomes _really_ confusing when combined with the extension whitelist. As a result of us tossing the original extension, we sometimes allow files we'd otherwise reject (the .csv example being one of them; it gets accepted as a .txt).

**Comment by jimsafley** [comment]
I can't think of any obvious downsides to there being a mimetype/extension mismatch, can you? I think our original decision was tentative and, so it appears, overly-cautious, so I don't see a downside to retaining extensions.

**Comment by zerocrates** [comment]
The only thing I can come up with as a major benefit would be where the incoming file has no extension but it might "look" like it does by virtue of having a dot somewhere in the name... with the current system we don't have to figure out that difference as we'll see it as an unrecognized extension and replace it... though this would mangle the filename so maybe it's not really worth keeping around.

**Comment by jimsafley** [comment]
Fixed in 0cca91f
