### ISSUE TITLE
Consider deduplicating some mimetypes

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#935]
Our mimetype handling for detection and rendering purposes isn't all that different from Classic: pretty much we just take whatever we're given from the mime type detector as-is. Due to many different possible pattern lists being installed on different systems and changes in which is the "standard" type, we have many mappings for the "same" types.

For example we have both `audio/ogg` and `audio/x-ogg` mapped, both `audio/aac` and `audio/x-aac`, and many others like this. MP3 possibilities include `audio/mpeg` (the general standard), `audio/x-mpeg`, `audio/mp3`, `audio/x-mp3`, `audio/mpeg3`, `audio/x-mpeg-3`, `audio/x-mpegaudio`.

It works to just add a bunch of extra mappings for these, but then those extra versions also need to be replicated in the mime type whitelist, making that yet more daunting of a list by default than it has to be. It also means that a plugin/module trying to override the way these files are displayed needs to account for all the many variations on the types that are possible that we account for. The extension guessing lookup is also affected, as the list there generally only includes the standard types.

It may be a better idea to just apply a filter to the mime type we get from the detector, essentially defining some aliases so that all these nonstandard options we currently account for just get replaced with their one standardized version.

**Comment by jimsafley** [comment]
Fixed via #940
