### ISSUE TITLE
Uploading assets a bit confusing

### ISSUE THREAD

**Issue by patrickmj** [omeka/omeka-s#936]
Copied from https://github.com/omeka-s-themes/centerrow/issues/14

The wording of the heading and buttons leads me astray when adding an asset to use for a theme logo. The "Upload" in the sidebar heading makes me immediately want to like on the "Upload" button, missing the needed intermediate step of choosing the file (I expect clicking the "Upload" button would open the modal for choosing the file).

It's worse in FF than in Chrome. FF's file upload button says "Browse", while Chrome's says "Choose File". Dunno what Safari or IE say.

I think the verbal echo of "Upload" encourages missing that intermediate step.

[Side note -- when no assets have been uploaded, the same "1 of 0" in the page list that we've seen elsewhere is present.]

**Comment by kimisgold** [comment]
@patrickmj The upload button now only appears once a file has been selected. Does that mitigate the confusion?

**Comment by patrickmj** [comment]
Yes, I think so.
