### ISSUE TITLE
Add a mechanism to remove theme assets

### ISSUE THREAD

**Issue by patrickmj** [omeka/omeka-s#937]
Once an asset for theme (e.g., a logo option) has been uploaded, there doesn't seem to be a way to delete it from the list of available assets. While complications of permissions and usage across different sites and themes gets tricky, we might want to sort out whether there's a good way to remove or otherwise manage theme assets.

Otherwise, I'm now stuck with party parrot in my installation.

![evilparrot](https://cloud.githubusercontent.com/assets/153262/26514146/fbebd106-423d-11e7-953b-8c052de3e3c9.png)

**Comment by patrickmj** [comment]
Need to figure out what to do when someone attempts to delete a theme asset that is in use somewhere:

* How can I check that?
* How to respond? Probably remove the option to delete

**Comment by zerocrates** [comment]
We don't generally deal with this case otherwise, so I'm tempted to say just allow it regardless. There's also a little problem that you can't reliably tell when an asset's in use: the theme controls those settings and it need not be "logo"
