### ISSUE TITLE
Should empty search do anything?

### ISSUE THREAD

**Issue by patrickmj** [omeka/omeka-s#942]
When I've not entered anything into search, but click the magnifying glass anyway, it performs a search for `search=`, an empty search text, which returns what looks like everything in the pool for that site.

It's ambiguous what that should do. On one hand, it makes sense that clicking the icon will just run the search. On another hand, if I'm just exploring and wondering what exactly the magnifying glass icon does, it's a moment of figuring out that it's an empty search, and it's a little weird to do an empty search.

**Comment by pols12** [comment]
There is no external consistency:
* Google, Yahoo, DuckDuckGo: does nothing.
* AFP.com, BBC.com: does an empty search (no result).
* WordPress: does a whole search (returns all items).
* Drupal: does an empty search (no result), can display browsable categories.
* Joomla: does an empty search (no result).

Omeka S has the same behavior than Wordpress. In my humble opinion, I think it is the best way to process empty searches.

**Comment by patrickmj** [comment]
@zerocrates @sharonmleon @pols12 have we landed on keeping this the way it is, and close the issue?

**Comment by Daniel-KM** [comment]
If there is a doodle, I vote to return all items.

**Comment by zerocrates** [comment]
I think let's keep the empty search the way it is, so all results.

The stuff about accessibility of the advanced search on the themes may merit a separate issue... I think having it tied to an empty search is pretty undiscoverable.
