### ISSUE TITLE
Cannot edit media values

### ISSUE THREAD

**Issue by patrickmj** [omeka/omeka-s#944]
I uploaded a file for media, and gave it a title. When I go to edit that media to delete the title, the title still sticks. That's both deleting the text from the input, and clicking the trash icon.

UPDATE: that's when there's only one property. If there are more than one property, the trash icon works as expected.

**Comment by zerocrates** [comment]
Looks like a regression causing us to do nothing if no values are submitted. The logic there got changed quite a bit so it's not super surprising.

**Comment by patrickmj** [comment]
Yeah, I figured it was related to those changes
