### ISSUE TITLE
Improve link between media and items

### ISSUE THREAD

**Issue by pols12** [omeka/omeka-s#949]
I think media should be semantically linked to items with a customizable RDF property.

Otherwise, the resource template should include a way to specify media like one for properties. Indeed, it could be useful to require a medium for a resource and to set a label for the medium.

**Comment by jimsafley** [comment]
These are worthwhile discussions, and something we're thinking about.

> I think media should be semantically linked to items with a customizable RDF property.

One idea we have is to add "Media" to the "Omeka resource" data type ("Item" and "Item set" are already included), but the sidebar select _only_ displays media that is assigned to the item and ingested. This would use our current workflow and would allow more than one property relationship between an item and its media. Omeka would reflect the semantic link in the values list as well as in the JSON-LD serialization of the item

Another idea is to provide a property select for each media in the "Media" tab of the item add/edit page. When a user assigns a property to a media, Omeka would reflect this semantic link in the the item's "Linked resources" tab as well as in the JSON-LD serialization of the item. This would require new functionality and workflow.

Do you have any other ideas about interface?

> Otherwise, the resource template should include a way to specify media like one for properties. Indeed, it could be useful to require a medium for a resource and to set a label for the medium.

This is a good idea, though tough to implement. We'll consider it.

**Comment by pols12** [comment]
Adding "Media" to "Omeka ressource" data type seems to be a good implementation, in my humble opinion. But I think the select panel should propose to ingest new media (such as for theme assets).

In this case, it would be nice if resource templates would be able to precise the resource type (between "Item", "Item Set" and "Media"), when "Resource" would be chosen as data type.

**Comment by jimsafley** [comment]
> In this case, it would be nice if resource templates would be able to precise the resource type (between "Item", "Item Set" and "Media"), when "Resource" would be chosen as data type.

This is a work in progress in #970.
