### ISSUE TITLE
Resource form: no indication of the specific type of an Omeka Resource value

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#95]
The Resource values let you pick Item or Item Set, but a selected Item and selected Set look identical when editing (or viewing for that matter, but that's probably less important).

This may be a matter of adding text saying what kind of resource is being pointed to, or even just finally picking different icons for Item and Set and using those to distinguish, or some combination.

**Comment by kimisgold** [comment]
I'm stuck for the time being. When I access the selected resource's value object, it only contains the id, dcterms:title, url, and value resource id. It doesn't currently look like there's a way to pull out whether the resource is an item or item set.

**Comment by zerocrates** [comment]
`value_resource_name` should now be available in the resource value objects on the form.
