### ISSUE TITLE
Readme should mention reinstalling file database.ini instead local.config.php

### ISSUE THREAD

**Issue by pprw** [omeka/omeka-s#950]
The Readme.md says to backup and reinstall the file `/config/local.config.php` when updating to a new version of Omeka S  (see below).

It seems the important file to reinstall is rather `/config/database.ini`.

The documentation should probably be modified accordingly.     

> 
> Updating from released zip file
> 
>     Download the latest release from the release page
>     Make a copy of your /config/local.config.php file.
>     Make a copy of your /modules and /themes directories.
>     Make a copy of your /files directory.
>     Remove all Omeka S files, and replace them with the files from the updated zip file.
>     Replace your original /config/local.config.php file, and the /modules, /themes, and /files directories that you copied.
>     In your web browser, go to your site and run any migrations that are needed.
>

**Comment by zerocrates** [comment]
Yeah, you're right, that's out of date.

What we should be saying there is to backup and restore the whole "config" folder.
