### ISSUE TITLE
Add numerical comparisons query type

### ISSUE THREAD

**Issue by pols12** [omeka/omeka-s#952]
Currently, we can look for books published in 1905.

Being able to looking for books published before 1905 or after 1905 would be very useful.

Full date and time values should be in [format](https://www.w3.org/TR/NOTE-datetime) which is recommanded by [dcterms:date](http://dublincore.org/documents/dcmi-terms/#terms-date).

It is maybe necessary to distinguish numerical values from date and time values.

**Comment by zerocrates** [comment]
So, you're looking for query types like "less than," "greater than," "between"?

Numeric support can be a little tricky without additional table support, so more of a module thing, but adding the queries themselves shouldn't be, and they'd work as long as you're using any format that will lexicographically sort correctly, like the ISO 8601 you mention.

**Comment by pols12** [comment]
Yeah, I would like to look for items for which a value is "less than" or "greater than" a given constant (or "between" 2 given constants).

Since PHP DateTime objects support comparison operators, I thought the query could try to consider a non-integer value as one.

**Comment by zerocrates** [comment]
It's easy to do comparisons on the PHP side, but they're not really helpful here. Pretty much anything in the search needs to happen on the MySQL side of things, otherwise we'd have to pull all the data out of MySQL first just to do the comparison, and that's not going to work with even a pretty small site.

**Comment by pols12** [comment]
My bad, you’re right.

So the user should precise if the data contains numbers or dates when they want to compare values. And MySQL would cast values to correct type before compare them. It could be possible adding 0 to string for numbers, and using STR_TO_DATE() for dates.

**Comment by pols12** [comment]
I’ve created [this patch](https://gist.github.com/pols12/30925969103c5c87bcd3a340e7e5aeb1). It’s not a really proper way, but an easy way which seems to work well. Do you think it could be integrated?

**Comment by jimsafley** [comment]
This is currently possible using the Numeric Data Types [module](https://omeka.org/s/modules/NumericDataTypes/).
