### ISSUE TITLE
How can I turn off the Omeka-s "Stack trace" (on error 404 pages)?

### ISSUE THREAD

**Issue by clarkewd** [omeka/omeka-s#958]
Hello,

I'd like to disable the "Stack trace" that shows up - for example on error 404 pages ( when a site is not published / public )

![screen region 2017-06-22 at 12 17 59](https://user-images.githubusercontent.com/156377/27444611-e16d304c-5744-11e7-8bd2-ace0d6aefdec.png)

I'm using Omeka-S and have the `.htaccess` file setup with:

    SetEnv APPLICATION_ENV "production"

I checked and this value is present and readable via PHP ( checked the `$_SERVER` ) array.

I also tried changing the `application/config/module.config.php` file to set `'display_exceptions' => false` as the Zend documentation (`vendor/zendframework/zend-view/doc/book/quick-start.md`) mentions:

	// Additionally, we'll tell it that we want to display an exception
	// stack trace; you'll likely want to disable this by default.
	'display_exceptions' => true,
	'exception_template' => 'error/index',

Neither of these methods worked. How can I disable the stack trace?

**Comment by zerocrates** [comment]
I'll check back on it, but I believe the situation is that we just haven't made the 404/403 pages pay attention to the development/production environment switch.

We'll fix it.
