### ISSUE TITLE
nginx configuration

### ISSUE THREAD

**Issue by stephenwf** [omeka/omeka-s#961]
Just wanted to ask before opening a PR to your README.md or docs. We've found that the `.htaccess` fix for trailing slashes is sometimes required, but there is no detail about running on nginx.

We've had this issue and found simply adding:
```nginx
rewrite ^/(.*)/$ /$1 permanent;
```
to nginx configuration in your server block. 

Is this something you want added to your documentation?

**Comment by patrickmj** [comment]
@stephenwf Catching up on lots of things today. Yes, a PR sounds great to me. Many thanks.
