### ISSUE TITLE
Should items be visible between sites?

### ISSUE THREAD

**Issue by clarkewd** [omeka/omeka-s#962]
We have setup omeka-s and so far have two sites. We have granted access to one user who is a "site administrator" for just one site - but she can see items that have been uploaded to the other site as well. Is this a bug or intended behavior?

**Comment by mebrett** [comment]
Site Administrators have robust privileges for content - the main thing they *can't* do is activate or configure modules. See https://github.com/omeka/omeka-s-enduser/blob/develop/users.md#roles-and-permissions

**Comment by clarkewd** [comment]
A colleague and I experimented with changing her roles in OmekaS - from site administrator to editor / reviewer. That worked to only give her access to the one site. However, she could still access the items uploaded to the other / all sites.

It seems that when we upload items they are part of the network, rather than just a part of a discrete site. Is there a way to change this?

**Comment by sharonmleon** [comment]
All items are visible to all users. Encouraging sharing and reuse is one of the core principles of the platform. 

Edit and delete controls are restricted for permission levels below Editor.

**Comment by clarkewd** [comment]
I see. Our group is helping different faculty members use it for separate projects - so for us it would be nice ( and easier for the Faculty members ) if there were a way to filter the items / isolate them to be used on each project. Do you think this might ever be implemented?

**Comment by mebrett** [comment]
You could make an [item set](https://github.com/omeka/omeka-s-enduser/blob/develop/content/item-sets.md) for each project.
