### ISSUE TITLE
Default site without redirection to /s/[slug]/

### ISSUE THREAD

**Issue by o1da** [omeka/omeka-s#967]
Is there a way (probably .htaccess?) to have only one site within Omeka-S installation with nice URL (without `/s/[slug]/` in it )? 
I understand that it is necessary for more sites within one Omeka-S installation. But it would be nice to have default site served on the "naked domain" without a redirection to `/s/[slug]/` if I have only one site.

**Comment by kimisgold** [comment]
This seems to be a duplicate question of #870. Hopefully the conversation there is helpful.
