### ISSUE TITLE
User settings

### ISSUE THREAD

**Issue by jimsafley** [omeka/omeka-s#973]
There will likely be a need to store settings specific to individual users. Settings may include a default resource template (#168) and a default interface language. This would be functionally identical to site settings.

**Comment by zerocrates** [comment]
We're still missing here:

- a frontend
- any actual settings

The two Jim mentioned in the issue itself seem reasonable or are something we've already talked about. Time zone could be another that would make sense, but hour-level differences are usually not interesting enough to our users. There's some other potential settings that have been bandied about at least briefly, mostly to do with the admin interface (things like sizes of thumbnails, etc.)

There's also potential for having modules hook into this as well of course, in particular for modules that just modify the display of things (like Metadata Browse, although it may already have a complex enough settings story).

**Comment by Daniel-KM** [comment]
Besides, what are the best practices to save user settings for a module (see https://github.com/omeka-s-modules/CSVImport/pull/96)

There seems to be at least six possibilities (for the position of the settings and its name):
- Internally in the module
- in the module config of the module, somewhere
- in the module config, as `[csv_import][user_settings]`
- in the module config, as `[user_settings][csv_import]`
- in the module config, without subarray, as `[user_settings]['csv_import_multivalue_separator`]
- in the module config, without subarray, as `[user_settings]['multivalue_separator`]

The question is the same for module settings and site settings.
