### ISSUE TITLE
Add more Resource data types

### ISSUE THREAD

**Issue by jimsafley** [omeka/omeka-s#975]
Right now the "Resource" data type form will always render "Item" and "Item set" buttons, and conditionally the "Media" button. Instead we should offer separate "Resource: All", "Resource: Item", "Resource: Item set", and "Resource: Media" data types.

**Comment by tomcrane** [comment]
Are you considering the ability to specify a constraint on a Resource data type field when defining it in a resource template? For example, I can define a field `dcterms:creator` and specify that its data type is `Resource`, but I would also like to limit the range to items of class `foaf:Person`. 

I'm finding that the editorial user experience of selecting a Resource value suffers when there are many items to choose from.

The range could even be given a default class from any range specified in imported vocabulary.

**Comment by jimsafley** [comment]
@tomcrane We're looking into the possibility. We've previously nixed the idea of custom data type options due to the unpredictability of results when the data type changes. Its complexity and brittleness makes the feature impracticable. Nevertheless, I think it's possible to do what you say given that the Resource data type is within our control, and we'll be working to make it happen.

**Comment by tomcrane** [comment]
Thanks @jimsafley. Even a quick way of filtering the resource picker list by class would greatly improve the user experience - "I only want to see people".
