### ISSUE TITLE
Determine/finalize site block features/options

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#976]
Requires discussion as to what features are seen as required or missing from the current set of options for site building (also involves some of the existing search customization issues).

**Comment by zerocrates** [comment]
@sharonmleon we'll need to run back through this to actually make some decisions about it in the near future

**Comment by kimisgold** [comment]
Here a few ideas for page building features we don't currently support:

* full width bleed images
* slider image gallery
* floatable pull quotes

I'm sure some of these can be handled within themes, but I thought I'd throw these out there to see if there's anything that would benefit from being supported by core.

**Comment by patrickmj** [comment]
Since @alyssafahringer also built sites in the sandbox, if you're around, thoughts about helpful features for page-building will also be helpful.

**Comment by sheilabrennan** [comment]
@kimisgold my inclination is to not add any more page building features at this time. 
The one I think would be most sought after would be the slider image gallery, but really would be fine with that coming in another release.
