### ISSUE TITLE
Add "in Site pool" filter to advanced search form

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s#981]
We've got all the plumbing for showing the items for some site, it's just that you have to go into the Site to do it. We could present this on the advanced search page directly as well.

**Comment by jimsafley** [comment]
A WIP in the [in-site-pool-filter](https://github.com/omeka/omeka-s/tree/in-site-pool-filter) branch.

**Comment by zerocrates** [comment]
We've got site selection in one other place already (the settings page, for choosing a "default" site). I don't believe we do user grouping there, and I'm not sure we need to here. I suppose it could be useful, but at any rate it seems to me that those two places should share their implementation of the select.

**Comment by jimsafley** [comment]
I think user grouping is appropriate given a large number of sites which may have identical titles. It's the same logic we used when we grouped item sets by user. I'll use the new site select in global settings.
