### ISSUE TITLE
Standardize class descriptions

### ISSUE THREAD

**Issue by patrickmj** [omeka/omeka-s#983]
Sometimes the docblock describing a class is within the class declaration, and sometimes it is outside. Compare https://github.com/omeka/omeka-s/blob/develop/application/src/View/Helper/Api.php and https://github.com/omeka/omeka-s/blob/develop/application/src/View/Helper/BlockShowTitleSelect.php

In the first, the description of what it does is outside the class, and the second, it is inside.

Don't know what we'll do with auto-generating documentation, but this seems like a possible problem brewing?

**Comment by patrickmj** [comment]
Might just be inconsistency of what has documentation, the class itself or the method within the class.

**Comment by pols12** [comment]
I think both should be documented (we can’t guess if a class is callable if only __invoke() is documented). Maybe using `@method` or `@see` targeting __invoke() method in class doc.

For example, Zend just precise what the helper does in class doc, and how to call an instance in __invoke() doc:
```
/**
 * Helper for doing something.
 */
class MyHelper extends AbstractHelper
{
     /**
     * Returns a thing.
     *
     * $var may be a var
     *
     * @param  string|null $foo   The string
     * @param  string|null $var   The var
     * @return Thing
     */
    public function __invoke($foo, $var = "")
    {
```
