### ISSUE TITLE
Url of the Omeka S vocabulary

### ISSUE THREAD

**Issue by Daniel-KM** [omeka/omeka-s#991]
The vocabulary "http://omeka.org/s/vocabs/o#" is redirected to a wrong url. Is it planned to display the whole vocab? And for modules?

**Comment by zerocrates** [comment]
That's definitely an interesting redirect it's doing now...

**Comment by jimsafley** [comment]
We're pretty sure that URL will not change. It will resolve to a [serialization of the vocabulary](https://github.com/omeka/omeka-s-vocab) by the time the software comes out of beta.

Modules need a little more discussion. We've settled on `http://omeka.org/s/vocabs/module/<module-name>#` for internally developed modules. We're not sure yet whether to share this namespace with third party modules. Nevertheless, I see no problem with module developers using their own namespace.

**Comment by Daniel-KM** [comment]
I keep this thread in mind to reopen it when Omeka S will be released.
