### ISSUE TITLE
Media value and media attachment sidebars open different views

### ISSUE THREAD

**Issue by kimisgold** [omeka/omeka-s#995]
On the item/edit view, clicking on the 'media' value button opens a 'Select media' sidebar with a limited list of media. On the site-page/edit view, the media block's 'Add attachment' button opens a 'Select item' sidebar with a list of items containing selectable media. What is the logic behind these two buttons behaving differently?

**Comment by zerocrates** [comment]
Media values in item/edit are limited to the media currently assigned to the item, while attachments are: 1. valid for the whole set of media on any item in the pool and 2. attachments need not select media at all, but can be just the item (i.e., Mapping).

**Comment by kimisgold** [comment]
That makes sense, thanks.
