### ISSUE TITLE
Should URI values have a validation check that they are dereferencable?

### ISSUE THREAD

**Issue by patrickmj** [omeka/omeka-s#997]
This amounts to how [cool we want our URIs](https://www.w3.org/TR/cooluris/) to be. Currently, any URI can be added happily. The intent _seems_ to be that people enter a dereferencable URI, but there's no check or validation on that. 
Do we want to try to enforce, or at least warn, about whether a URI is dereferencable? Or, keep it as it is and just let people enter anything? (technically speaking, a purist might still say that an isbn number counts as a URI, but I don't think we want to go down that road).

**Comment by jimsafley** [comment]
I'd rather not have to check if all URIs resolve every time a resource is added or edited. The overhead could be prohibitive. This looks more like a problem that a data cleansing module could solve, to the extent that it's a problem at all.
