### ISSUE TITLE
Figure out auto-generated documentation

### ISSUE THREAD

**Issue by patrickmj** [omeka/omeka-s#998]
We should figure out if/how we're doing autogenerated documentation. PhpDocumenter seems the most straightforward way to go, but we'd need to figure out a bit of templating for how we want it to look. It also produces quite a list of complaints/errors in our documentation (over 3000). Most of those we can likely not worry about, but it might point us to things we want to prioritize in improving our in-code documentation.

**Comment by zerocrates** [comment]
Take a look at https://github.com/ApiGen/ApiGen as a possible alternative

**Comment by patrickmj** [comment]
apigen 4.1 breaks thusly: https://github.com/ApiGen/ApiGen/issues/774
the latest chokes thinking there's an array constant

PhpDoc gives lots of noisy errors and notices. Some of which are internally helpful, but a bit much for our public docs

**Comment by patrickmj** [comment]
After work and tweeking, ApiGen runs through, but takes more than 14 hours. Next question is where it goes.
